/* ============================================================
   batch23_welcome_join.js  —  Vendra v4, Batch 23 (welcome + join)
   Drop in project root (C:\Users\kvngs\VENDRA), then run:
       node batch23_welcome_join.js
   ------------------------------------------------------------
   Migrates TWO pages to the v4 look:
     - app/welcome/page.tsx   (returning-user chooser)
     - app/join/page.tsx      (Web3 + Circle login/onboarding)
   Keeps ALL logic: welcome redirect; join's full Circle flow
   (send-otp / verify-otp / login / create-wallet / send),
   sessionStorage persistence, resend timer, copy, balance fetch,
   RainbowKit ConnectButton, all redirects.
   Reuses ob-* inputs (Batch 18) + v4btn + v4spinner.
   Appends "V4 WELCOME + JOIN STYLES" (idempotent). Backs up both.
   ============================================================ */
const fs = require('fs');
const path = require('path');
const root = process.cwd();
const welcomePath = path.join(root, 'app', 'welcome', 'page.tsx');
const joinPath = path.join(root, 'app', 'join', 'page.tsx');
const cssPath = path.join(root, 'app', 'globals.css');
for (const [p, label] of [[welcomePath, 'app/welcome/page.tsx'], [joinPath, 'app/join/page.tsx'], [cssPath, 'app/globals.css']]) {
  if (!fs.existsSync(p)) { console.error('\n  x  ' + label + ' not found. Run from project root.\n'); process.exit(1); }
}
if (!fs.readFileSync(cssPath, 'utf8').includes('V4 ONBOARDING STYLES')) {
  console.warn('  !  Warning: ob-* styles not found. Run node batch18_onboarding.js first, or form fields will be unstyled.');
}

const WELCOME = [
"'use client';",
"import Nav from '../Nav';",
"import Link from 'next/link';",
"import { useAccount } from 'wagmi';",
"import { useRouter } from 'next/navigation';",
"import { useEffect } from 'react';",
"",
"export default function Welcome() {",
"  const { isConnected } = useAccount();",
"  const router = useRouter();",
"  useEffect(() => { if (!isConnected) router.push('/join'); }, [isConnected, router]);",
"",
"  return (",
"    <main className='v4home wc-main'>",
"      <Nav theme='v4' />",
"      <div className='amb'><div className='amb-glow' /><div className='amb-grid' /><div className='amb-line' /></div>",
"      <div className='wc-in'>",
"        <div className='vbadge'><span className='vbadge-dot' /><span className='vbadge-txt'>Welcome back \u00b7 Arc Testnet</span></div>",
"        <h1 className='wc-h1'>What would you <span className='v4amber'>like to do?</span></h1>",
"        <p className='wc-sub'>You have both a buyer and seller profile. Your storefront and order history are ready whenever you are.</p>",
"        <div className='wc-opts'>",
"          <Link href='/profile' style={{ textDecoration: 'none', color: 'inherit' }}>",
"            <div className='wc-opt'><div className='wc-opt-ic'>\uD83C\uDFEA</div><div className='wc-opt-h'>Manage my store</div><div className='wc-opt-p'>Add products, view sales, edit your storefront or launch a new store on Arc Testnet.</div></div>",
"          </Link>",
"          <Link href='/marketplace' style={{ textDecoration: 'none', color: 'inherit' }}>",
"            <div className='wc-opt'><div className='wc-opt-ic'>\uD83D\uDECD\uFE0F</div><div className='wc-opt-h'>Keep shopping</div><div className='wc-opt-p'>Browse stores, discover new products and pay instantly in USDC on Arc.</div></div>",
"          </Link>",
"        </div>",
"        <div className='vor' style={{ maxWidth: 480, margin: '0 auto 20px' }}><div className='vor-line' /><span className='vor-txt'>or</span><div className='vor-line' /></div>",
"        <Link href='/marketplace' className='wc-explore'>Explore marketplace \u2192</Link>",
"      </div>",
"    </main>",
"  );",
"}",
""
].join("\n");

const JOIN = [
"'use client';",
"import Nav from '../Nav';",
"import { useAccount } from 'wagmi';",
"import { ConnectButton } from '@rainbow-me/rainbowkit';",
"import { useEffect, useState } from 'react';",
"import { useRouter } from 'next/navigation';",
"import Link from 'next/link';",
"",
"type CircleStep = 'email'|'otp'|'checking'|'found'|'notfound'|'creating'|'done';",
"const STORAGE_KEY = 'vendra_circle_wallet';",
"",
"export default function Join() {",
"  const { isConnected } = useAccount();",
"  const router = useRouter();",
"  const [step, setStep] = useState<CircleStep>('email');",
"  const [email, setEmail] = useState('');",
"  const [otp, setOtp] = useState('');",
"  const [circleWallet, setCircleWallet] = useState<{address:string;walletId:string;email:string}|null>(null);",
"  const [balance, setBalance] = useState('0');",
"  const [copied, setCopied] = useState(false);",
"  const [error, setError] = useState('');",
"  const [loading, setLoading] = useState(false);",
"  const [sendForm, setSendForm] = useState({ to: '', amount: '' });",
"  const [sending, setSending] = useState(false);",
"  const [sendResult, setSendResult] = useState('');",
"  const [mode, setMode] = useState<'options'|'circle'>('options');",
"  const [resendTimer, setResendTimer] = useState(0);",
"",
"  useEffect(() => { if (isConnected) router.push('/onboarding'); }, [isConnected, router]);",
"  useEffect(() => { try { const saved = sessionStorage.getItem(STORAGE_KEY); if (saved) { const w = JSON.parse(saved); setCircleWallet(w); fetchBalance(w.walletId); setMode('circle'); setStep('found'); } } catch {} }, []);",
"  useEffect(() => { if (resendTimer > 0) { const t = setTimeout(() => setResendTimer(resendTimer - 1), 1000); return () => clearTimeout(t); } }, [resendTimer]);",
"",
"  const saveWallet = (w: any) => { setCircleWallet(w); try { sessionStorage.setItem(STORAGE_KEY, JSON.stringify(w)); } catch {} };",
"  const logout = () => { setCircleWallet(null); try { sessionStorage.removeItem(STORAGE_KEY); } catch {} setMode('options'); setStep('email'); setEmail(''); };",
"  const fetchBalance = async (walletId: string) => { try { const res = await fetch('/api/circle/balance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ walletId }) }); const data = await res.json(); setBalance(data.balance || '0'); } catch {} };",
"  const handleCopy = () => { if (!circleWallet) return; navigator.clipboard.writeText(circleWallet.address); setCopied(true); setTimeout(() => setCopied(false), 2000); };",
"",
"  const handleSendOtp = async () => {",
"    if (!email) { setError('Enter your email'); return; }",
"    setLoading(true); setError('');",
"    try {",
"      const res = await fetch('/api/circle/send-otp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      setStep('otp'); setResendTimer(60);",
"    } catch (e:any) { setError(e.message || 'Failed to send code'); }",
"    finally { setLoading(false); }",
"  };",
"",
"  const handleVerifyOtp = async () => {",
"    if (!otp || otp.length !== 6) { setError('Enter the 6-digit code'); return; }",
"    setLoading(true); setError(''); setStep('checking');",
"    try {",
"      const verifyRes = await fetch('/api/circle/verify-otp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, otp }) });",
"      const verifyData = await verifyRes.json();",
"      if (verifyData.error) throw new Error(verifyData.error);",
"      const res = await fetch('/api/circle/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      if (data.found) { const w = { address: data.address, walletId: data.walletId, email }; saveWallet(w); await fetchBalance(data.walletId); setStep('found'); }",
"      else { setStep('notfound'); }",
"    } catch (e:any) { setError(e.message || 'Verification failed'); setStep('otp'); }",
"    finally { setLoading(false); }",
"  };",
"",
"  const handleCreate = async () => {",
"    setStep('creating'); setError('');",
"    try {",
"      const res = await fetch('/api/circle/create-wallet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      const w = { address: data.address, walletId: data.walletId, email }; saveWallet(w); await fetchBalance(data.walletId); setStep('done');",
"    } catch (e:any) { setError(e.message || 'Failed'); setStep('notfound'); }",
"  };",
"",
"  const handleSend = async () => {",
"    if (!sendForm.to || !sendForm.amount || !circleWallet) return;",
"    setSending(true); setSendResult(''); setError('');",
"    try {",
"      const res = await fetch('/api/circle/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ walletId: circleWallet.walletId, walletAddress: circleWallet.address, toAddress: sendForm.to, amount: sendForm.amount }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      setSendResult('Sent! TX: ' + (data.txId || '').slice(0,20) + '...');",
"    } catch (e:any) { setError(e.message || 'Send failed'); }",
"    finally { setSending(false); }",
"  };",
"",
"  return (",
"    <main className='v4home jn-main'>",
"      <Nav theme='v4' />",
"      <div className='amb'><div className='amb-glow' /><div className='amb-grid' /></div>",
"      <div className='jn-in'>",
"        <div className='jn-head'>",
"          <div className='vbadge'><span className='vbadge-dot' /><span className='vbadge-txt'>Arc Testnet \u00b7 Powered by USDC</span></div>",
"          <h1 className='jn-h1'>Join <span className='v4amber'>Vendra</span></h1>",
"          <p className='jn-sub'>Connect a Web3 wallet or log in with Circle \u2014 no crypto experience needed.</p>",
"        </div>",
"        {mode === 'options' && (",
"          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>",
"            <div className='jn-card'>",
"              <div className='jn-card-l'>\uD83E\uDD8A Web3 wallet</div>",
"              <div className='jn-card-p'>MetaMask, Coinbase, WalletConnect or any EVM wallet.</div>",
"              <div className='jn-connect'><ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} /></div>",
"            </div>",
"            <div className='vor'><div className='vor-line' /><span className='vor-txt'>or</span><div className='vor-line' /></div>",
"            <div className='jn-card'>",
"              <div className='jn-card-l'>\u2B55 Circle wallet</div>",
"              <div className='jn-card-p'>No crypto experience needed. Verify your email and access your USDC wallet instantly.</div>",
"              <button onClick={() => setMode('circle')} className='v4btn v4btn-ink' style={{ width: '100%', justifyContent: 'center' }}>Log in with Circle wallet \u2192</button>",
"            </div>",
"            <div style={{ textAlign: 'center', marginTop: 8 }}><Link href='/marketplace' className='jn-browse'>Browse without connecting \u2192</Link></div>",
"          </div>",
"        )}",
"        {mode === 'circle' && (",
"          <div className='jn-circle'>",
"            <div className='jn-circle-top'>",
"              <div>",
"                <div className='jn-circle-l'>Circle \u00b7 USDC Wallet</div>",
"                <div className='jn-circle-h'>",
"                  {step === 'email' && 'Log in with Circle'}",
"                  {step === 'otp' && 'Enter your code'}",
"                  {step === 'checking' && 'Verifying\u2026'}",
"                  {step === 'notfound' && 'Create wallet'}",
"                  {step === 'creating' && 'Creating wallet\u2026'}",
"                  {(step === 'found' || step === 'done') && 'Welcome back \u2713'}",
"                </div>",
"              </div>",
"              {(step === 'found' || step === 'done') && <button onClick={logout} className='jn-logout'>Log out</button>}",
"            </div>",
"            {step === 'email' && (<>",
"              <p className='jn-p'>Enter your email. We\u2019ll send a 6-digit verification code to confirm it\u2019s you.</p>",
"              <div className='ob-field'><label className='ob-label'>Email address</label><input className='ob-input' type='email' placeholder='you@example.com' value={email} onChange={e => setEmail(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSendOtp()} autoFocus /></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              <button onClick={handleSendOtp} disabled={loading} className='v4btn v4btn-amber jn-cta'>{loading ? 'Sending code\u2026' : 'Send verification code \u2192'}</button>",
"              <button onClick={() => setMode('options')} className='jn-link-btn' style={{ width: '100%' }}>\u2190 Back to options</button>",
"            </>)}",
"            {step === 'otp' && (<>",
"              <p className='jn-p'>We sent a code to <strong>{email}</strong>. Check your inbox.</p>",
"              <div style={{ fontSize: 11, color: 'var(--v4-tx40)', marginBottom: 18 }}>Code expires in 10 minutes. Check spam if not received.</div>",
"              <div className='ob-field'><label className='ob-label'>6-digit code</label><input className='ob-input jn-otp-input' type='text' inputMode='numeric' maxLength={6} placeholder='000000' value={otp} onChange={e => setOtp(e.target.value.replace(/\\D/g, ''))} onKeyDown={e => e.key === 'Enter' && handleVerifyOtp()} autoFocus /></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              <button onClick={handleVerifyOtp} disabled={loading || otp.length !== 6} className='v4btn v4btn-amber jn-cta'>{loading ? 'Verifying\u2026' : 'Verify & continue \u2192'}</button>",
"              <div className='jn-link-row'>",
"                <button onClick={() => { setStep('email'); setOtp(''); setError(''); }} className='jn-link-btn'>\u2190 Change email</button>",
"                <button onClick={resendTimer === 0 ? handleSendOtp : undefined} disabled={resendTimer > 0} className='jn-link-btn' style={resendTimer === 0 ? { color: 'var(--v4-aDeep)' } : undefined}>{resendTimer > 0 ? `Resend in ${resendTimer}s` : 'Resend code'}</button>",
"              </div>",
"            </>)}",
"            {step === 'checking' && <div className='jn-spin'><div className='v4spinner' style={{ margin: '0 auto' }} /><div className='jn-spin-p'>Verifying your identity\u2026</div></div>}",
"            {step === 'notfound' && (<>",
"              <div style={{ border: '1px solid var(--v4-line)', borderRadius: 10, padding: 14, marginBottom: 18, background: 'var(--v4-paper2)' }}><div style={{ fontSize: 12.5, color: 'var(--v4-tx60)', lineHeight: 1.7 }}>No wallet found for <strong>{email}</strong>. Create one?</div></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              <button onClick={handleCreate} className='v4btn v4btn-amber jn-cta'>Create new Circle wallet \u2192</button>",
"              <button onClick={() => setStep('email')} className='jn-link-btn' style={{ width: '100%' }}>\u2190 Try a different email</button>",
"            </>)}",
"            {step === 'creating' && <div className='jn-spin'><div className='v4spinner' style={{ margin: '0 auto' }} /><div className='jn-spin-p'>Creating your wallet on Arc Testnet\u2026</div></div>}",
"            {(step === 'found' || step === 'done') && circleWallet && (<>",
"              <div className='jn-wallet'>",
"                <div className='jn-wallet-l'>Circle wallet \u00b7 Arc Testnet</div>",
"                <div className='jn-addr-row'><div className='jn-addr'>{circleWallet.address}</div><button onClick={handleCopy} className={'jn-copy' + (copied ? ' done' : '')}>{copied ? '\u2713 Copied' : 'Copy'}</button></div>",
"                <div className='jn-bal-row'>",
"                  <div><div className='jn-wallet-l' style={{ marginBottom: 2 }}>USDC balance</div><div className='jn-bal'>${balance}</div></div>",
"                  <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ fontSize: 10, padding: '8px 12px' }}>Get USDC \u2197</a>",
"                </div>",
"              </div>",
"              <div className='ob-field'><label className='ob-label'>Send to address</label><input className='ob-input' placeholder='0x...' value={sendForm.to} onChange={e => setSendForm({ ...sendForm, to: e.target.value })} /></div>",
"              <div className='ob-field'><label className='ob-label'>Amount (USDC)</label><input className='ob-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e => setSendForm({ ...sendForm, amount: e.target.value })} /></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              {sendResult && <div className='jn-ok'>{sendResult}</div>}",
"              <button onClick={handleSend} disabled={sending} className='v4btn v4btn-amber jn-cta'>{sending ? 'Sending\u2026' : 'Send USDC on Arc \u2192'}</button>",
"              <div className='jn-btn-row'>",
"                <a href={`https://testnet.arcscan.app/address/${circleWallet.address}`} target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost jn-sm' style={{ flex: 1 }}>Arc Explorer \u2197</a>",
"                <Link href='/marketplace' className='v4btn v4btn-amber jn-sm' style={{ flex: 1 }}>Explore marketplace \u2192</Link>",
"              </div>",
"            </>)}",
"          </div>",
"        )}",
"      </div>",
"    </main>",
"  );",
"}",
""
].join("\n");

for (const [p, content, label] of [[welcomePath, WELCOME, 'welcome'], [joinPath, JOIN, 'join']]) {
  if (!fs.existsSync(p + '.v3bak')) { fs.copyFileSync(p, p + '.v3bak'); console.log('  .  backup -> app/' + label + '/page.tsx.v3bak'); }
  fs.writeFileSync(p, content, 'utf8');
  console.log('  +  app/' + label + '/page.tsx rewritten in v4 (logic unchanged)');
}

const MARK = '/* === V4 WELCOME + JOIN STYLES === */';
const CSS = [
MARK,
"/* shared ambient + badge + divider */",
".v4home .amb{position:absolute;inset:0;pointer-events:none;overflow:hidden;}",
".v4home .amb-glow{position:absolute;top:50%;left:50%;transform:translate(-50%,-60%);width:800px;height:600px;background:radial-gradient(ellipse at center,var(--v4-aSoft) 0%,transparent 70%);}",
".v4home .amb-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(180,126,14,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(180,126,14,.04) 1px,transparent 1px);background-size:96px 96px;}",
".v4home .amb-line{position:absolute;top:0;left:50%;transform:translateX(-50%);width:60%;height:2px;background:linear-gradient(90deg,transparent,var(--v4-a),transparent);opacity:.4;}",
".v4home .vbadge{display:inline-flex;align-items:center;gap:8px;border:1px solid var(--v4-aSoft2);background:var(--v4-aSoft);border-radius:999px;padding:7px 15px;}",
".v4home .vbadge-dot{width:7px;height:7px;border-radius:50%;background:var(--v4-a);box-shadow:0 0 6px var(--v4-a);}",
".v4home .vbadge-txt{font-size:10px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:var(--v4-aDeep);}",
".v4home .vor{display:flex;align-items:center;gap:12px;}",
".v4home .vor-line{flex:1;height:1px;background:var(--v4-line);}",
".v4home .vor-txt{font-size:9px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:var(--v4-tx40);}",
"/* welcome */",
".v4home.wc-main{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;position:relative;overflow:hidden;}",
".v4home .wc-in{position:relative;z-index:1;text-align:center;max-width:580px;padding:0 40px;}",
".v4home .wc-h1{font-size:clamp(40px,7vw,76px);font-weight:600;letter-spacing:-.02em;line-height:.98;margin:28px 0 18px;}",
".v4home .wc-sub{font-size:15px;color:var(--v4-tx60);line-height:1.7;max-width:420px;margin:0 auto 44px;}",
".v4home .wc-opts{display:grid;grid-template-columns:1fr 1fr;gap:14px;max-width:500px;margin:0 auto 28px;}",
".v4home .wc-opt{background:var(--v4-card);border:1px solid var(--v4-line);border-radius:16px;padding:30px 24px;text-align:left;cursor:pointer;transition:.25s;height:100%;}",
".v4home .wc-opt:hover{border-color:var(--v4-a);background:var(--v4-aSoft);transform:translateY(-2px);}",
".v4home .wc-opt-ic{font-size:30px;margin-bottom:14px;}",
".v4home .wc-opt-h{font-size:19px;font-weight:600;letter-spacing:-.01em;margin-bottom:8px;}",
".v4home .wc-opt-p{font-size:12.5px;color:var(--v4-tx60);line-height:1.6;}",
".v4home .wc-explore{font-size:12px;font-weight:600;letter-spacing:.06em;color:var(--v4-tx40);text-decoration:none;transition:color .2s;}",
".v4home .wc-explore:hover{color:var(--v4-aDeep);}",
"/* join */",
".v4home.jn-main{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;position:relative;overflow:hidden;}",
".v4home .jn-in{position:relative;z-index:1;width:100%;max-width:480px;padding:90px 40px;}",
".v4home .jn-head{text-align:center;margin-bottom:36px;}",
".v4home .jn-h1{font-size:clamp(44px,8vw,76px);font-weight:600;letter-spacing:-.02em;line-height:.95;margin:18px 0 14px;}",
".v4home .jn-sub{font-size:13.5px;color:var(--v4-tx60);line-height:1.7;}",
".v4home .jn-card{border:1px solid var(--v4-line);background:var(--v4-card);border-radius:16px;padding:24px;}",
".v4home .jn-card-l{font-size:10px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-aDeep);margin-bottom:8px;}",
".v4home .jn-card-p{font-size:12.5px;color:var(--v4-tx60);margin-bottom:16px;line-height:1.6;}",
".v4home .jn-connect{display:flex;justify-content:center;}",
".v4home .jn-browse{font-size:11px;font-weight:600;letter-spacing:.06em;color:var(--v4-tx40);text-decoration:none;}",
".v4home .jn-browse:hover{color:var(--v4-aDeep);}",
".v4home .jn-circle{border:1px solid var(--v4-line2);background:var(--v4-card);border-radius:18px;padding:24px;}",
".v4home .jn-circle-l{font-size:9.5px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:var(--v4-tx40);margin-bottom:4px;}",
".v4home .jn-circle-h{font-size:22px;font-weight:600;letter-spacing:-.01em;}",
".v4home .jn-circle-top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px;}",
".v4home .jn-p{font-size:12.5px;color:var(--v4-tx60);line-height:1.7;margin-bottom:18px;}",
".v4home .jn-p strong,.v4home .jn-circle strong{color:var(--v4-ink);font-weight:600;}",
".v4home .jn-err{font-size:12px;color:#C0392B;border:1px solid rgba(192,57,43,.3);background:rgba(192,57,43,.08);border-radius:10px;padding:9px 13px;margin-bottom:12px;}",
".v4home .jn-ok{font-size:11px;color:#3F7A47;border:1px solid rgba(123,176,130,.4);background:rgba(123,176,130,.10);border-radius:10px;padding:9px 13px;margin-bottom:12px;word-break:break-all;}",
".v4home .jn-spin{text-align:center;padding:28px 0;}",
".v4home .jn-spin-p{font-size:12.5px;color:var(--v4-tx60);margin-top:14px;}",
".v4home .jn-link-btn{background:transparent;border:none;font-size:11px;font-weight:500;color:var(--v4-tx40);cursor:pointer;padding:8px 0;}",
".v4home .jn-link-btn:hover{color:var(--v4-ink);}",
".v4home .jn-link-btn:disabled{cursor:not-allowed;}",
".v4home .jn-link-row{display:flex;justify-content:space-between;}",
".v4home .jn-wallet{border:1px solid var(--v4-aSoft2);background:var(--v4-aSoft);border-radius:14px;padding:18px;margin-bottom:16px;}",
".v4home .jn-wallet-l{font-size:9.5px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-tx40);margin-bottom:6px;}",
".v4home .jn-addr-row{display:flex;align-items:center;gap:8px;margin-bottom:14px;}",
".v4home .jn-addr{font-size:12px;color:var(--v4-aDeep);flex:1;word-break:break-all;font-weight:500;}",
".v4home .jn-copy{font-size:9px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;border:1px solid var(--v4-line2);color:var(--v4-tx60);padding:5px 10px;border-radius:999px;background:transparent;cursor:pointer;flex-shrink:0;white-space:nowrap;}",
".v4home .jn-copy.done{color:#3F7A47;border-color:rgba(123,176,130,.5);}",
".v4home .jn-bal-row{display:flex;justify-content:space-between;align-items:flex-end;}",
".v4home .jn-bal{font-size:30px;font-weight:700;letter-spacing:-.02em;color:var(--v4-aDeep);line-height:1;}",
".v4home .jn-otp-input{letter-spacing:.3em;font-size:22px;text-align:center;}",
".v4home .jn-cta{width:100%;justify-content:center;padding:13px;font-size:14px;margin-bottom:10px;}",
".v4home .jn-logout{font-size:9px;font-weight:600;letter-spacing:.06em;padding:6px 12px;border-radius:999px;border:1px solid var(--v4-line2);background:transparent;color:#C0392B;cursor:pointer;flex-shrink:0;}",
".v4home .jn-logout:hover{background:#C0392B;color:#fff;border-color:#C0392B;}",
".v4home .jn-btn-row{display:flex;gap:8px;margin-bottom:12px;}",
".v4home .jn-sm{font-size:10px;padding:9px;justify-content:center;}",
"@media(max-width:520px){.v4home .wc-opts{grid-template-columns:1fr;}}",
""
].join("\n");

let css = fs.readFileSync(cssPath, 'utf8');
const i = css.indexOf(MARK);
if (i !== -1) { css = css.slice(0, i).replace(/\s+$/, '') + '\n\n'; }
css = css.replace(/\s+$/, '') + '\n\n' + CSS;
fs.writeFileSync(cssPath, css, 'utf8');
console.log('  +  v4 welcome + join styles appended to globals.css');
console.log('\n  Done. npm run build -> npm run dev -> open /welcome and /join. Then git push.\n');
