/* ============================================================
   batch22_storeedit.js  —  Vendra v4, Batch 22 (manage store)
   Drop in project root (C:\Users\kvngs\VENDRA), then run:
       node batch22_storeedit.js
   ------------------------------------------------------------
   - rewrites app/store/edit/page.tsx in the v4 light look
   - reuses ob-* form styles (Batch 18) + pf-del button (Batch 14)
   - adds self-contained se-* styles (tabs, banner, category grid,
     product rows, product-image uploader)
   - keeps ALL logic: tab + searchParams sync, getStoreByWallet
     load + redirect to /store/create, handleSave (updateStore +
     banner upload), handleAddProduct (uploadImage + saveProduct),
     handleDeleteProduct, showAdd toggle, deletingId, CATS/TYPES
   Backs up the page once. Idempotent CSS.
   NOTE: requires ob-* styles from batch18_onboarding.js.
   ============================================================ */
const fs = require('fs');
const path = require('path');
const root = process.cwd();
const pagePath = path.join(root, 'app', 'store', 'edit', 'page.tsx');
const cssPath = path.join(root, 'app', 'globals.css');
if (!fs.existsSync(pagePath)) { console.error('\n  x  app/store/edit/page.tsx not found. Run from project root.\n'); process.exit(1); }
if (!fs.existsSync(cssPath)) { console.error('\n  x  app/globals.css not found.\n'); process.exit(1); }
if (!fs.readFileSync(cssPath, 'utf8').includes('V4 ONBOARDING STYLES')) {
  console.warn('  !  Warning: onboarding (ob-*) styles not found. Run node batch18_onboarding.js first, or the form will be unstyled.');
}

const PAGE = [
"'use client';",
"import Nav from '../../Nav';",
"import { useState, useEffect, useRef, Suspense } from 'react';",
"import { useAccount } from 'wagmi';",
"import { useRouter, useSearchParams } from 'next/navigation';",
"import { getStoreByWallet, updateStore, saveProduct, deleteProduct, uploadImage } from '../../lib/supabase';",
"import Link from 'next/link';",
"",
"const CATS = [{ icon: '\uD83D\uDC57', name: 'Fashion' }, { icon: '\uD83D\uDCBE', name: 'Digital' }, { icon: '\uD83C\uDFA8', name: 'Art' }, { icon: '\uD83D\uDEE0', name: 'Services' }, { icon: '\uD83C\uDF71', name: 'Food' }, { icon: '\uD83D\uDCF1', name: 'Tech' }, { icon: '\uD83C\uDFB5', name: 'Music' }, { icon: '\u2728', name: 'Other' }];",
"const TYPES = ['Physical', 'Digital', 'Service'];",
"",
"function EditStoreContent() {",
"  const { address } = useAccount();",
"  const router = useRouter();",
"  const searchParams = useSearchParams();",
"  const bannerRef = useRef<HTMLInputElement>(null);",
"  const imgRef = useRef<HTMLInputElement>(null);",
"  const [store, setStore] = useState<any>(null);",
"  const [loading, setLoading] = useState(true);",
"  const [saving, setSaving] = useState(false);",
"  const [error, setError] = useState('');",
"  const [success, setSuccess] = useState('');",
"  const [tab, setTab] = useState<'details'|'products'>('details');",
"  const [form, setForm] = useState({ name: '', tagline: '', description: '', xHandle: '', category: 'Fashion' });",
"  const [bannerFile, setBannerFile] = useState<File|null>(null);",
"  const [bannerPreview, setBannerPreview] = useState('');",
"  const [newProd, setNewProd] = useState({ name: '', description: '', price: '', type: 'Physical' });",
"  const [prodFile, setProdFile] = useState<File|null>(null);",
"  const [prodPreview, setProdPreview] = useState('');",
"  const [adding, setAdding] = useState(false);",
"  const [deletingId, setDeletingId] = useState('');",
"  const [showAdd, setShowAdd] = useState(false);",
"",
"  useEffect(() => { if (searchParams.get('tab') === 'products') setTab('products'); }, [searchParams]);",
"  useEffect(() => {",
"    if (!address) return;",
"    getStoreByWallet(address).then(s => {",
"      if (!s) { router.push('/store/create'); return; }",
"      setStore(s);",
"      setForm({ name: s.name || '', tagline: s.tagline || '', description: s.description || '', xHandle: s.x_handle || '', category: s.category || 'Fashion' });",
"      setBannerPreview(s.banner_url || '');",
"      setLoading(false);",
"    });",
"  }, [address, router]);",
"",
"  const handleSave = async () => {",
"    if (!form.name) { setError('Store name required'); return; }",
"    setSaving(true); setError(''); setSuccess('');",
"    try {",
"      let bannerUrl = store.banner_url || '';",
"      if (bannerFile && address) bannerUrl = await uploadImage('banners/' + address, bannerFile);",
"      await updateStore(store.id, { name: form.name, tagline: form.tagline, description: form.description, category: form.category, x_handle: form.xHandle, banner_url: bannerUrl });",
"      setSuccess('Store updated!'); setTimeout(() => setSuccess(''), 2500);",
"    } catch { setError('Something went wrong.'); } finally { setSaving(false); }",
"  };",
"",
"  const handleAddProduct = async () => {",
"    if (!newProd.name || !newProd.price) { setError('Name and price required'); return; }",
"    setAdding(true); setError('');",
"    try {",
"      let imageUrl = '';",
"      if (prodFile && address) imageUrl = await uploadImage('products/' + store.id + '/' + Date.now(), prodFile);",
"      const p = await saveProduct({ store_id: store.id, name: newProd.name, description: newProd.description, price: Number(newProd.price), type: newProd.type, image_url: imageUrl });",
"      setStore({ ...store, products: [...(store.products || []), p] });",
"      setNewProd({ name: '', description: '', price: '', type: 'Physical' }); setProdFile(null); setProdPreview(''); setShowAdd(false);",
"    } catch { setError('Failed to add product.'); } finally { setAdding(false); }",
"  };",
"",
"  const handleDeleteProduct = async (id: string) => {",
"    setDeletingId(id);",
"    try { await deleteProduct(id); setStore({ ...store, products: store.products.filter((p:any) => p.id !== id) }); }",
"    catch { setError('Failed to delete.'); } finally { setDeletingId(''); }",
"  };",
"",
"  if (loading) return <main className='v4home' style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Nav theme='v4' /><div className='v4spinner' /></main>;",
"",
"  return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}>",
"      <Nav theme='v4' />",
"      <div className='ob-wrap' style={{ maxWidth: 720 }}>",
"        <p className='eyebrow'>Manage store</p>",
"        <h1 className='ob-title' style={{ fontSize: 'clamp(30px,5vw,48px)', marginBottom: 6 }}>{store?.name}</h1>",
"        <div className='se-meta'>{store?.products?.length || 0} products \u00b7 {store?.category} \u00b7 Arc Testnet</div>",
"        <div className='se-actions'>",
"          <a href={'/store/' + store?.slug} target='_blank' rel='noopener noreferrer' className='v4btn v4btn-amber se-sm'>View storefront \u2197</a>",
"          <Link href='/profile' className='v4btn v4btn-ghost se-sm'>\u2190 Profile</Link>",
"        </div>",
"        <div className='se-tabs'>",
"          <button onClick={() => setTab('details')} className={'se-tab' + (tab === 'details' ? ' on' : '')}>Store details</button>",
"          <button onClick={() => setTab('products')} className={'se-tab' + (tab === 'products' ? ' on' : '')}>Products ({store?.products?.length || 0})</button>",
"        </div>",
"",
"        {tab === 'details' && (",
"          <>",
"            <div className='ob-card'>",
"              <div className='ob-card-head'>Store banner</div>",
"              <div className='ob-card-body'>",
"                <input ref={bannerRef} type='file' accept='image/*' onChange={e => { const f = e.target.files?.[0]; if (!f) return; setBannerFile(f); setBannerPreview(URL.createObjectURL(f)); }} style={{ display: 'none' }} />",
"                {bannerPreview",
"                  ? <div className='se-banner-prev'><img src={bannerPreview} alt='banner' /><button onClick={() => bannerRef.current?.click()} className='se-banner-change'>Change</button></div>",
"                  : <div onClick={() => bannerRef.current?.click()} className='se-banner-zone'><div className='se-banner-ic'>\uD83D\uDDBC\uFE0F</div><div className='se-banner-label'>Click to upload banner</div></div>}",
"              </div>",
"            </div>",
"            <div className='ob-card'>",
"              <div className='ob-card-head'>Store info</div>",
"              <div className='ob-card-body'>",
"                <div className='ob-field'><label className='ob-label'>Store name *</label><input className='ob-input' value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div>",
"                <div className='ob-field'><label className='ob-label'>Tagline</label><input className='ob-input' placeholder='One line about what you sell' value={form.tagline} onChange={e => setForm({ ...form, tagline: e.target.value })} /></div>",
"                <div className='ob-field'><label className='ob-label'>Description</label><textarea className='ob-textarea' value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></div>",
"                <div className='ob-field last'><label className='ob-label'>X (Twitter) handle</label><input className='ob-input' placeholder='@yourhandle' value={form.xHandle} onChange={e => setForm({ ...form, xHandle: e.target.value })} /></div>",
"              </div>",
"            </div>",
"            <div className='ob-card'>",
"              <div className='ob-card-head'>Category</div>",
"              <div className='se-cats'>",
"                {CATS.map(c => <div key={c.name} onClick={() => setForm({ ...form, category: c.name })} className={'se-cat' + (form.category === c.name ? ' sel' : '')}><div className='se-cat-ic'>{c.icon}</div><div className='se-cat-name'>{c.name}</div></div>)}",
"              </div>",
"            </div>",
"            {error && <div className='ob-error'>{error}</div>}",
"            {success && <div className='ob-success'>{success}</div>}",
"            <button onClick={handleSave} disabled={saving} className='v4btn v4btn-amber ob-cta'>{saving ? 'Saving\u2026' : 'Save changes \u2192'}</button>",
"          </>",
"        )}",
"",
"        {tab === 'products' && (",
"          <>",
"            <div className='se-prodhead'>",
"              <div className='se-prodhead-c'>{store?.products?.length || 0} products listed</div>",
"              <button onClick={() => { setShowAdd(!showAdd); setError(''); }} className={'v4btn se-sm ' + (showAdd ? 'v4btn-ghost' : 'v4btn-amber')}>{showAdd ? 'Cancel' : '+ Add product'}</button>",
"            </div>",
"            {showAdd && (",
"              <div className='se-addcard'>",
"                <div className='se-addhead'>New product</div>",
"                <div className='ob-card-body'>",
"                  <div className='ob-field'><label className='ob-label'>Product image</label>",
"                    <input ref={imgRef} type='file' accept='image/*' onChange={e => { const f = e.target.files?.[0]; if (!f) return; setProdFile(f); setProdPreview(URL.createObjectURL(f)); }} style={{ display: 'none' }} />",
"                    {prodPreview",
"                      ? <div className='se-prodimg-prev'><img src={prodPreview} alt='product' /><button onClick={() => imgRef.current?.click()} className='se-prodimg-change'>Change</button></div>",
"                      : <div onClick={() => imgRef.current?.click()} className='se-prodimg-zone'><div className='se-prodimg-ic'>\uD83D\uDCF7</div><div className='se-prodimg-cap'>Add photo</div></div>}",
"                  </div>",
"                  <div className='ob-field'><label className='ob-label'>Product name *</label><input className='ob-input' placeholder='e.g. Gold Ring' value={newProd.name} onChange={e => setNewProd({ ...newProd, name: e.target.value })} /></div>",
"                  <div className='ob-field'><label className='ob-label'>Description</label><input className='ob-input' placeholder='What is this product?' value={newProd.description} onChange={e => setNewProd({ ...newProd, description: e.target.value })} /></div>",
"                  <div className='ob-field' style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>",
"                    <div><label className='ob-label'>Price (USDC) *</label><input className='ob-input' type='number' placeholder='e.g. 25' value={newProd.price} onChange={e => setNewProd({ ...newProd, price: e.target.value })} /></div>",
"                    <div><label className='ob-label'>Type</label><select className='ob-input' value={newProd.type} onChange={e => setNewProd({ ...newProd, type: e.target.value })}>{TYPES.map(t => <option key={t} value={t}>{t}</option>)}</select></div>",
"                  </div>",
"                  {error && <div className='ob-error' style={{ marginBottom: 12 }}>{error}</div>}",
"                  <button onClick={handleAddProduct} disabled={adding} className='v4btn v4btn-amber ob-cta'>{adding ? 'Adding\u2026' : 'Add product \u2192'}</button>",
"                </div>",
"              </div>)}",
"            <div className='se-prods'>",
"              {!store?.products?.length",
"                ? <div className='se-prods-empty'>No products yet \u2014 add your first one above.</div>",
"                : store.products.map((p:any) => (",
"                  <div key={p.id} className='se-prod'>",
"                    {p.image_url ? <img src={p.image_url} alt={p.name} className='se-prod-img' /> : <div className='se-prod-box'>\uD83D\uDCE6</div>}",
"                    <div style={{ flex: 1, minWidth: 0 }}><div className='se-prod-name'>{p.name}</div><div className='se-prod-meta'>{p.type} \u00b7 ${p.price} USDC</div></div>",
"                    <button onClick={() => handleDeleteProduct(p.id)} disabled={deletingId === p.id} className='pf-del'>{deletingId === p.id ? '\u2026' : 'Remove'}</button>",
"                  </div>))}",
"            </div>",
"          </>",
"        )}",
"      </div>",
"    </main>",
"  );",
"}",
"",
"export default function EditStore() {",
"  return <Suspense><EditStoreContent /></Suspense>;",
"}",
""
].join("\n");

if (!fs.existsSync(pagePath + '.v3bak')) { fs.copyFileSync(pagePath, pagePath + '.v3bak'); console.log('  .  backup -> app/store/edit/page.tsx.v3bak'); }
fs.writeFileSync(pagePath, PAGE, 'utf8');
console.log('  +  app/store/edit/page.tsx rewritten in v4 (logic unchanged)');

const MARK = '/* === V4 STORE-EDIT STYLES === */';
const CSS = [
MARK,
".v4home .se-meta{font-size:11px;color:var(--v4-tx40);letter-spacing:.04em;margin-bottom:24px;}",
".v4home .se-actions{display:flex;gap:10px;margin-bottom:30px;flex-wrap:wrap;}",
".v4home .se-sm{font-size:11px;padding:8px 16px;}",
".v4home .se-tabs{display:flex;border-bottom:1px solid var(--v4-line);margin-bottom:30px;gap:4px;}",
".v4home .se-tab{font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;padding:12px 20px;background:transparent;border:none;border-bottom:2px solid transparent;color:var(--v4-tx40);cursor:pointer;transition:.2s;margin-bottom:-1px;}",
".v4home .se-tab.on{border-bottom-color:var(--v4-a);color:var(--v4-aDeep);}",
".v4home .se-tab:hover{color:var(--v4-ink);}",
".v4home .se-banner-zone{height:130px;border:1px dashed var(--v4-line2);border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;cursor:pointer;background:var(--v4-paper2);transition:border-color .25s;}",
".v4home .se-banner-zone:hover{border-color:var(--v4-a);}",
".v4home .se-banner-ic{font-size:26px;}",
".v4home .se-banner-label{font-size:12px;font-weight:600;color:var(--v4-tx);}",
".v4home .se-banner-prev{position:relative;border-radius:12px;overflow:hidden;}",
".v4home .se-banner-prev img{width:100%;height:150px;object-fit:cover;display:block;}",
".v4home .se-banner-change{position:absolute;bottom:10px;right:10px;font-size:10px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:#fff;border:1px solid rgba(255,255,255,.4);padding:5px 11px;border-radius:999px;background:rgba(21,19,13,.6);cursor:pointer;backdrop-filter:blur(4px);}",
".v4home .se-cats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:18px;}",
".v4home .se-cat{padding:14px 8px;text-align:center;cursor:pointer;border:1px solid var(--v4-line);border-radius:12px;background:var(--v4-paper);transition:.2s;}",
".v4home .se-cat:hover{border-color:var(--v4-line2);}",
".v4home .se-cat.sel{border-color:var(--v4-a);background:var(--v4-aSoft);}",
".v4home .se-cat-ic{font-size:18px;margin-bottom:5px;}",
".v4home .se-cat-name{font-size:9.5px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .se-cat.sel .se-cat-name{color:var(--v4-aDeep);}",
".v4home select.ob-input{cursor:pointer;-webkit-appearance:none;appearance:none;background-image:linear-gradient(45deg,transparent 50%,var(--v4-tx40) 50%),linear-gradient(135deg,var(--v4-tx40) 50%,transparent 50%);background-position:calc(100% - 18px) 19px,calc(100% - 13px) 19px;background-size:5px 5px,5px 5px;background-repeat:no-repeat;}",
".v4home select.ob-input option{background:var(--v4-paper);color:var(--v4-tx);}",
".v4home .se-addcard{border:1px solid var(--v4-aSoft2);background:var(--v4-aSoft);border-radius:16px;overflow:hidden;margin-bottom:20px;}",
".v4home .se-addhead{font-size:11px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:var(--v4-aDeep);padding:14px 20px;border-bottom:1px solid var(--v4-aSoft2);}",
".v4home .se-prodhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;gap:12px;}",
".v4home .se-prodhead-c{font-size:11px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .se-prodimg-zone{width:100px;height:100px;border:1px dashed var(--v4-line2);border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;cursor:pointer;background:var(--v4-paper);transition:border-color .2s;}",
".v4home .se-prodimg-zone:hover{border-color:var(--v4-a);}",
".v4home .se-prodimg-ic{font-size:22px;}",
".v4home .se-prodimg-cap{font-size:9px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .se-prodimg-prev{position:relative;display:inline-block;border-radius:12px;overflow:hidden;}",
".v4home .se-prodimg-prev img{width:100px;height:100px;object-fit:cover;display:block;}",
".v4home .se-prodimg-change{position:absolute;bottom:4px;right:4px;font-size:8px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:#fff;border:none;padding:4px 8px;border-radius:999px;background:rgba(21,19,13,.65);cursor:pointer;backdrop-filter:blur(4px);}",
".v4home .se-prods{border:1px solid var(--v4-line);border-radius:16px;overflow:hidden;background:var(--v4-card);}",
".v4home .se-prod{display:flex;align-items:center;gap:16px;padding:16px 20px;border-bottom:1px solid var(--v4-line);}",
".v4home .se-prod:last-child{border-bottom:none;}",
".v4home .se-prod-img{width:48px;height:48px;object-fit:cover;border-radius:10px;flex-shrink:0;border:1px solid var(--v4-line);}",
".v4home .se-prod-box{width:48px;height:48px;border-radius:10px;flex-shrink:0;border:1px solid var(--v4-line);background:var(--v4-paper2);display:flex;align-items:center;justify-content:center;font-size:22px;}",
".v4home .se-prod-name{font-size:15px;font-weight:600;letter-spacing:-.01em;margin-bottom:2px;}",
".v4home .se-prod-meta{font-size:10px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .se-prods-empty{padding:32px;text-align:center;font-size:13px;color:var(--v4-tx40);}",
"@media(max-width:560px){.v4home .se-cats{grid-template-columns:repeat(2,1fr);}}",
""
].join("\n");

let css = fs.readFileSync(cssPath, 'utf8');
const i = css.indexOf(MARK);
if (i !== -1) { css = css.slice(0, i).replace(/\s+$/, '') + '\n\n'; }
css = css.replace(/\s+$/, '') + '\n\n' + CSS;
fs.writeFileSync(cssPath, css, 'utf8');
console.log('  +  v4 store-edit styles appended to globals.css');
console.log('\n  Done. npm run build -> npm run dev -> open /store/edit. Then git push.\n');
