/* ============================================================
   batch14_profile.js  —  Vendra v4, Batch 14 (profile page)
   Drop in project root (C:\Users\kvngs\VENDRA), then run:
       node batch14_profile.js
   ------------------------------------------------------------
   - rewrites app/profile/page.tsx in the v4 light look
   - keeps ALL logic untouched: Promise.all profile/store/orders
     load, seller/buyer view toggle, handleDeleteStore + modal,
     derived totals (revenue/spent), order links to /orders/[id]
   - appends v4 profile styles (pf-*) to globals.css (idempotent)
   Backs up the page once.
   ============================================================ */
const fs = require('fs');
const path = require('path');
const root = process.cwd();
const pagePath = path.join(root, 'app', 'profile', 'page.tsx');
const cssPath = path.join(root, 'app', 'globals.css');
if (!fs.existsSync(pagePath)) { console.error('\n  x  app/profile/page.tsx not found. Run from project root.\n'); process.exit(1); }
if (!fs.existsSync(cssPath)) { console.error('\n  x  app/globals.css not found.\n'); process.exit(1); }

const PAGE = [
"'use client';",
"import Nav from '../Nav';",
"import Link from 'next/link';",
"import { useAccount } from 'wagmi';",
"import { useState, useEffect } from 'react';",
"import { getAllProfiles, getOrdersByBuyer, getOrdersBySeller, getStoreByWallet, deleteStore } from '../lib/supabase';",
"import { useRouter } from 'next/navigation';",
"",
"export default function Profile() {",
"  const { address, isConnected } = useAccount();",
"  const router = useRouter();",
"  const [sellerProfile, setSellerProfile] = useState<any>(null);",
"  const [buyerProfile, setBuyerProfile] = useState<any>(null);",
"  const [store, setStore] = useState<any>(null);",
"  const [buyerOrders, setBuyerOrders] = useState<any[]>([]);",
"  const [sellerOrders, setSellerOrders] = useState<any[]>([]);",
"  const [view, setView] = useState<'seller'|'buyer'>('seller');",
"  const [loading, setLoading] = useState(true);",
"  const [deleting, setDeleting] = useState(false);",
"  const [showDelete, setShowDelete] = useState(false);",
"",
"  useEffect(() => {",
"    if (!isConnected || !address) { router.push('/'); return; }",
"    Promise.all([getAllProfiles(address), getStoreByWallet(address), getOrdersByBuyer(address), getOrdersBySeller(address)]).then(([all, s, bo, so]) => {",
"      const sp = all.find((p:any) => p.role === 'seller') || null;",
"      const bp = all.find((p:any) => p.role === 'buyer') || null;",
"      setSellerProfile(sp); setBuyerProfile(bp); setStore(s); setBuyerOrders(bo); setSellerOrders(so);",
"      if (sp) setView('seller'); else if (bp) setView('buyer');",
"      setLoading(false);",
"    });",
"  }, [address, isConnected, router]);",
"",
"  const handleDeleteStore = async () => {",
"    if (!store) return; setDeleting(true);",
"    try { await deleteStore(store.id); setStore(null); setShowDelete(false); }",
"    catch (e) { console.error(e); } finally { setDeleting(false); }",
"  };",
"",
"  const isSeller = !!sellerProfile, isBuyer = !!buyerProfile;",
"  const active = view === 'seller' ? sellerProfile : buyerProfile;",
"  const initials = active?.display_name?.slice(0,2).toUpperCase() || address?.slice(2,4).toUpperCase() || 'VN';",
"  const totalRevenue = sellerOrders.reduce((s,o) => s + Number(o.amount), 0);",
"  const totalSpent = buyerOrders.reduce((s,o) => s + Number(o.amount), 0);",
"",
"  if (loading) return <main className='v4home' style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Nav theme='v4' /><div className='v4spinner' /></main>;",
"",
"  if (!isSeller && !isBuyer) return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}><Nav theme='v4' />",
"      <div style={{ minHeight: '70vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '24px' }}>",
"        <h1 className='pf-name' style={{ fontSize: 'clamp(32px,5vw,52px)' }}>No profile <span className='v4amber'>found</span></h1>",
"        <p className='lede' style={{ margin: '12px 0 28px' }}>Complete onboarding to join Vendra.</p>",
"        <Link href='/onboarding' className='v4btn v4btn-amber'>Get started</Link>",
"      </div>",
"    </main>",
"  );",
"",
"  return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}>",
"      <Nav theme='v4' />",
"      {showDelete && <div className='pf-modal-bg'><div className='pf-modal'><div className='pf-modal-title'>Delete store?</div><div className='pf-modal-body'>This will permanently delete <strong style={{ color: 'var(--v4-ink)' }}>{store?.name}</strong> and all its products. This cannot be undone.</div><div style={{ display: 'flex', gap: 12 }}><button onClick={handleDeleteStore} disabled={deleting} className='pf-del-solid'>{deleting ? 'Deleting\u2026' : 'Yes, delete'}</button><button onClick={() => setShowDelete(false)} className='v4btn v4btn-ghost'>Cancel</button></div></div></div>}",
"",
"      <div className='pf-hero'>",
"        <div className='pf-hero-in'>",
"          <div className='pf-avatar'>{active?.avatar_url ? <img src={active.avatar_url} alt='avatar' /> : initials}</div>",
"          <div style={{ flex: 1, minWidth: 0 }}>",
"            <div className='pf-name'>{active?.display_name || 'Vendra user'}{view === 'seller' && store && <span className='pf-owner'>owner \u00b7 {store.name}</span>}</div>",
"            {active?.bio && <div className='pf-bio'>{active.bio}</div>}",
"            {active?.x_handle && <a href={'https://x.com/' + active.x_handle.replace('@','')} target='_blank' rel='noopener noreferrer' className='pf-x'>\uD835\uDD4F {active.x_handle.startsWith('@') ? active.x_handle : '@' + active.x_handle} \u2197</a>}",
"            <div className='pf-addr'>{address ? address.slice(0,6) + '...' + address.slice(-4) : ''} \u00b7 Arc Testnet</div>",
"            <div className='pf-badges'>",
"              {isSeller && <div className='pf-badge amber'>Seller</div>}",
"              {isBuyer && <div className='pf-badge'>Buyer</div>}",
"              <div className='pf-badge'>ERC-8004 Identity</div>",
"            </div>",
"          </div>",
"          <div className='pf-actions'>",
"            {isSeller && isBuyer && <div className='pf-toggle'><button onClick={() => setView('seller')} className={view === 'seller' ? 'on' : ''}>Seller</button><button onClick={() => setView('buyer')} className={view === 'buyer' ? 'on' : ''}>Buyer</button></div>}",
"            {!isSeller && <Link href='/onboarding?role=seller' className='v4btn v4btn-amber'>+ Seller profile</Link>}",
"            {!isBuyer && <Link href='/onboarding?role=buyer' className='v4btn v4btn-ink'>+ Buyer profile</Link>}",
"            <Link href={'/edit-profile?role=' + view} className='v4btn v4btn-ghost'>Edit profile</Link>",
"          </div>",
"        </div>",
"      </div>",
"",
"      {view === 'seller' && isSeller && (",
"        <div className='pf-wrap'>",
"          <div className='pf-stats s4'>",
"            {[{ val: '$' + totalRevenue.toFixed(2), label: 'Total revenue', amber: true }, { val: String(sellerOrders.length), label: 'Orders' }, { val: String(store?.products?.length || 0), label: 'Products' }, { val: '0%', label: 'Platform fee', amber: true }].map(s => (",
"              <div key={s.label} className='pf-stat'><div className={'pf-stat-v' + ((s as any).amber ? ' amber' : '')}>{s.val}</div><div className='pf-stat-l'>{s.label}</div></div>",
"            ))}",
"          </div>",
"          <div className='pf-grid'>",
"            <div>",
"              <div className='eyebrow' style={{ marginBottom: 14 }}>Your store</div>",
"              <div className='pf-card'>",
"                {store ? (",
"                  <div className='pf-store-pad'>",
"                    {store.banner_url && <div className='pf-store-banner'><img src={store.banner_url} alt='banner' /></div>}",
"                    <div className='pf-store-name'>{store.name}</div>",
"                    <div className='pf-store-tag'>{store.tagline}</div>",
"                    <div className='pf-store-meta'>{store.category} \u00b7 {store.products?.length || 0} products \u00b7 Arc Testnet</div>",
"                    <div className='pf-store-btns'>",
"                      <Link href={'/store/' + store.slug} className='v4btn v4btn-amber'>View storefront</Link>",
"                      <Link href='/store/edit?tab=products' className='v4btn v4btn-ghost'>+ Add products</Link>",
"                      <Link href='/store/edit' className='v4btn v4btn-ghost'>Edit store</Link>",
"                      <button onClick={() => setShowDelete(true)} className='pf-del'>Delete</button>",
"                    </div>",
"                  </div>",
"                ) : (",
"                  <div className='pf-empty'><div className='pf-empty-h'>No store yet</div><Link href='/store/create' className='v4btn v4btn-amber'>Create store</Link></div>",
"                )}",
"              </div>",
"            </div>",
"            <div className='pf-bal'>",
"              <div className='pf-bal-l'>Store balance</div>",
"              <div className='pf-bal-v'>${totalRevenue.toFixed(2)}</div>",
"              <div className='pf-bal-u'>USDC \u00b7 Arc Testnet</div>",
"              <div className='pf-recent-h'>Recent sales</div>",
"              {sellerOrders.slice(0,3).length === 0 ? <div className='pf-recent-empty'>No sales yet</div>",
"              : sellerOrders.slice(0,3).map((o:any) => (",
"                <div key={o.id} className='pf-recent-row'><div className='pf-recent-ic'>\uD83D\uDCE6</div><div style={{ flex: 1, minWidth: 0 }}><div className='pf-recent-name'>{o.product_name}</div><div className='pf-recent-date'>{new Date(o.created_at).toLocaleDateString()}</div></div><div className='pf-recent-amt'>+{Number(o.amount).toFixed(0)}</div></div>",
"              ))}",
"            </div>",
"          </div>",
"          <div className='eyebrow' style={{ marginBottom: 14 }}>All sales</div>",
"          <div className='pf-orders'>",
"            {sellerOrders.length === 0 ? <div className='pf-orders-empty'>No sales yet</div>",
"            : sellerOrders.map((o:any) => (",
"              <div key={o.id} className='pf-order'><div className='pf-order-ic'>\uD83D\uDCE6</div><div style={{ flex: 1, minWidth: 0 }}><div className='pf-order-name'>{o.product_name}</div><div className='pf-order-meta'>{new Date(o.created_at).toLocaleDateString()}{o.tx_hash ? ' \u00b7 ' + o.tx_hash.slice(0,14) + '...' : ''}</div></div><div className='pf-order-amt'>${Number(o.amount).toFixed(2)}</div></div>",
"            ))}",
"          </div>",
"        </div>",
"      )}",
"",
"      {view === 'buyer' && isBuyer && (",
"        <div className='pf-wrap'>",
"          <div className='pf-stats s3'>",
"            {[{ val: '$' + totalSpent.toFixed(2), label: 'Total spent' }, { val: String(buyerOrders.length), label: 'Orders' }, { val: 'Arc Testnet', label: 'Network' }].map(s => (",
"              <div key={s.label} className='pf-stat'><div className='pf-stat-v'>{s.val}</div><div className='pf-stat-l'>{s.label}</div></div>",
"            ))}",
"          </div>",
"          <div className='eyebrow' style={{ marginBottom: 14 }}>Order history</div>",
"          <div className='pf-orders' style={{ marginBottom: 28 }}>",
"            {buyerOrders.length === 0 ? <div className='pf-orders-empty'>No orders yet \u2014 <Link href='/marketplace' style={{ color: 'var(--v4-aDeep)' }}>explore the marketplace</Link></div>",
"            : buyerOrders.map((o:any) => (",
"              <Link key={o.id} href={'/orders/' + o.id} className='pf-order'><div className='pf-order-ic'>\uD83D\uDCE6</div><div style={{ flex: 1, minWidth: 0 }}><div className='pf-order-name'>{o.product_name}</div><div className='pf-order-meta'>{new Date(o.created_at).toLocaleDateString()} \u00b7 click to view \u2192</div></div><div className='pf-order-amt'>${Number(o.amount).toFixed(2)}</div></Link>",
"            ))}",
"          </div>",
"          <Link href='/marketplace' className='v4btn v4btn-amber'>Browse marketplace \u2192</Link>",
"        </div>",
"      )}",
"",
"      <footer className='pf-foot'><div className='pf-foot-brand'>Vendra</div><div className='pf-foot-copy'>ERC-8183 Escrow \u00b7 ERC-8004 Identity \u00b7 Arc Testnet</div><div className='pf-foot-links'><Link href='/marketplace'>Marketplace</Link><Link href='/store/create'>Sell</Link></div></footer>",
"    </main>",
"  );",
"}",
""
].join("\n");

if (!fs.existsSync(pagePath + '.v3bak')) { fs.copyFileSync(pagePath, pagePath + '.v3bak'); console.log('  .  backup -> app/profile/page.tsx.v3bak'); }
fs.writeFileSync(pagePath, PAGE, 'utf8');
console.log('  +  app/profile/page.tsx rewritten in v4 (logic unchanged)');

const MARK = '/* === V4 PROFILE STYLES === */';
const CSS = [
MARK,
".v4home .pf-hero{border-bottom:1px solid var(--v4-line);padding:104px 40px 40px;background:var(--v4-paper2);}",
".v4home .pf-hero-in{max-width:1160px;margin:0 auto;display:flex;align-items:flex-start;gap:28px;flex-wrap:wrap;}",
".v4home .pf-avatar{width:84px;height:84px;border-radius:50%;flex-shrink:0;overflow:hidden;border:1px solid var(--v4-line2);display:flex;align-items:center;justify-content:center;font-size:26px;font-weight:600;color:#fff;background:linear-gradient(135deg,var(--v4-a),var(--v4-aDeep));}",
".v4home .pf-avatar img{width:100%;height:100%;object-fit:cover;}",
".v4home .pf-name{font-size:clamp(28px,4vw,44px);font-weight:600;letter-spacing:-.02em;line-height:1;margin-bottom:10px;}",
".v4home .pf-owner{font-size:12px;font-weight:500;color:var(--v4-tx40);margin-left:14px;letter-spacing:.02em;}",
".v4home .pf-bio{font-size:14px;color:var(--v4-tx60);margin-bottom:8px;line-height:1.6;max-width:560px;}",
".v4home .pf-x{font-size:12px;color:var(--v4-aDeep);text-decoration:none;display:inline-block;margin-bottom:8px;font-weight:600;}",
".v4home .pf-x:hover{text-decoration:underline;}",
".v4home .pf-addr{font-size:11px;color:var(--v4-tx40);letter-spacing:.04em;margin-bottom:16px;}",
".v4home .pf-badges{display:flex;gap:8px;flex-wrap:wrap;}",
".v4home .pf-badge{font-size:10px;letter-spacing:.1em;text-transform:uppercase;padding:5px 12px;border-radius:999px;border:1px solid var(--v4-line2);color:var(--v4-tx60);font-weight:600;}",
".v4home .pf-badge.amber{border-color:var(--v4-aSoft2);color:var(--v4-aDeep);background:var(--v4-aSoft);}",
".v4home .pf-actions{display:flex;flex-direction:column;gap:10px;align-items:flex-end;flex-shrink:0;margin-left:auto;}",
".v4home .pf-actions .v4btn{padding:8px 16px;font-size:11px;}",
".v4home .pf-toggle{display:flex;border:1px solid var(--v4-line2);border-radius:999px;overflow:hidden;padding:3px;}",
".v4home .pf-toggle button{font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;padding:7px 16px;border:none;cursor:pointer;background:transparent;color:var(--v4-tx40);border-radius:999px;transition:.2s;}",
".v4home .pf-toggle button.on{background:var(--v4-ink);color:var(--v4-paper);}",
".v4home .pf-wrap{max-width:1160px;margin:0 auto;padding:40px 40px 72px;}",
".v4home .pf-stats{display:grid;gap:14px;margin-bottom:28px;}",
".v4home .pf-stats.s4{grid-template-columns:repeat(4,1fr);}",
".v4home .pf-stats.s3{grid-template-columns:repeat(3,1fr);}",
".v4home .pf-stat{background:var(--v4-card);border:1px solid var(--v4-line);border-radius:14px;padding:20px 22px;}",
".v4home .pf-stat-v{font-size:26px;font-weight:700;letter-spacing:-.02em;line-height:1;}",
".v4home .pf-stat-v.amber{color:var(--v4-aDeep);}",
".v4home .pf-stat-l{font-size:10.5px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:var(--v4-tx40);margin-top:8px;}",
".v4home .pf-grid{display:grid;grid-template-columns:1fr 320px;gap:22px;margin-bottom:36px;align-items:start;}",
".v4home .pf-card{background:var(--v4-card);border:1px solid var(--v4-line);border-radius:16px;overflow:hidden;}",
".v4home .pf-store-pad{padding:26px;}",
".v4home .pf-store-btns .v4btn{padding:9px 16px;font-size:11px;}",
".v4home .pf-store-banner{margin-bottom:18px;border-radius:12px;overflow:hidden;height:120px;}",
".v4home .pf-store-banner img{width:100%;height:100%;object-fit:cover;}",
".v4home .pf-store-name{font-size:26px;font-weight:600;letter-spacing:-.01em;margin-bottom:6px;}",
".v4home .pf-store-tag{font-size:13px;color:var(--v4-tx60);margin-bottom:16px;line-height:1.55;}",
".v4home .pf-store-meta{font-size:11px;color:var(--v4-tx40);letter-spacing:.04em;margin-bottom:22px;}",
".v4home .pf-store-btns{display:flex;gap:10px;flex-wrap:wrap;align-items:center;}",
".v4home .pf-empty{padding:40px;text-align:center;}",
".v4home .pf-empty-h{font-size:20px;font-weight:600;margin-bottom:14px;}",
".v4home .pf-bal{background:linear-gradient(160deg,var(--v4-aSoft),var(--v4-card));border:1px solid var(--v4-aSoft2);border-radius:16px;padding:24px;}",
".v4home .pf-bal-l{font-size:10px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:var(--v4-tx40);margin-bottom:6px;}",
".v4home .pf-bal-v{font-size:34px;font-weight:700;letter-spacing:-.02em;line-height:1;color:var(--v4-aDeep);}",
".v4home .pf-bal-u{font-size:11px;color:var(--v4-tx40);margin-top:4px;margin-bottom:16px;}",
".v4home .pf-recent-h{font-size:10px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-tx40);margin-bottom:12px;border-top:1px solid var(--v4-line);padding-top:14px;}",
".v4home .pf-recent-row{display:flex;align-items:center;gap:10px;margin-bottom:10px;}",
".v4home .pf-recent-ic{width:32px;height:32px;border-radius:8px;background:var(--v4-aSoft);border:1px solid var(--v4-aSoft2);display:flex;align-items:center;justify-content:center;font-size:14px;flex-shrink:0;}",
".v4home .pf-recent-name{font-size:12px;font-weight:500;color:var(--v4-tx);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}",
".v4home .pf-recent-date{font-size:10px;color:var(--v4-tx40);}",
".v4home .pf-recent-amt{font-size:13px;font-weight:700;color:var(--v4-aDeep);flex-shrink:0;}",
".v4home .pf-recent-empty{font-size:12px;color:var(--v4-tx40);text-align:center;padding:10px 0;}",
".v4home .pf-orders{border:1px solid var(--v4-line);border-radius:16px;overflow:hidden;background:var(--v4-card);}",
".v4home .pf-order{display:flex;align-items:center;gap:16px;padding:16px 22px;border-bottom:1px solid var(--v4-line);text-decoration:none;color:inherit;transition:background .15s;}",
".v4home .pf-order:last-child{border-bottom:none;}",
".v4home a.pf-order:hover{background:var(--v4-paper2);}",
".v4home .pf-order-ic{font-size:18px;flex-shrink:0;}",
".v4home .pf-order-name{font-size:15px;font-weight:600;letter-spacing:-.01em;}",
".v4home .pf-order-meta{font-size:11px;color:var(--v4-tx40);margin-top:3px;}",
".v4home .pf-order-amt{font-size:16px;font-weight:700;flex-shrink:0;}",
".v4home .pf-orders-empty{padding:32px;text-align:center;font-size:13px;color:var(--v4-tx40);}",
".v4home .pf-modal-bg{position:fixed;inset:0;background:rgba(21,19,13,.5);backdrop-filter:blur(6px);z-index:200;display:flex;align-items:center;justify-content:center;padding:24px;}",
".v4home .pf-modal{background:var(--v4-paper);border:1px solid var(--v4-line2);border-radius:18px;padding:28px;max-width:420px;width:100%;box-shadow:0 24px 64px rgba(21,19,13,.22);}",
".v4home .pf-modal-title{font-size:22px;font-weight:600;letter-spacing:-.01em;margin-bottom:10px;}",
".v4home .pf-modal-body{font-size:14px;color:var(--v4-tx60);line-height:1.6;margin-bottom:22px;}",
".v4home .pf-del{display:inline-flex;align-items:center;justify-content:center;font-size:11px;font-weight:600;letter-spacing:.04em;padding:9px 16px;border-radius:999px;border:1px solid var(--v4-line2);background:transparent;color:#C0392B;cursor:pointer;transition:.2s;}",
".v4home .pf-del:hover{background:#C0392B;border-color:#C0392B;color:#fff;}",
".v4home .pf-del-solid{display:inline-flex;align-items:center;justify-content:center;font-size:12px;font-weight:600;padding:11px 20px;border-radius:999px;border:none;background:#C0392B;color:#fff;cursor:pointer;transition:.2s;}",
".v4home .pf-del-solid:hover{background:#A93226;}",
".v4home .pf-del-solid:disabled{opacity:.6;cursor:default;}",
".v4home .pf-foot{border-top:1px solid var(--v4-line);padding:40px;text-align:center;}",
".v4home .pf-foot-brand{font-size:15px;font-weight:600;letter-spacing:.22em;text-transform:uppercase;color:var(--v4-tx60);}",
".v4home .pf-foot-copy{font-size:11px;color:var(--v4-tx40);margin:10px 0;}",
".v4home .pf-foot-links{display:flex;gap:18px;justify-content:center;}",
".v4home .pf-foot-links a{font-size:12px;color:var(--v4-tx60);text-decoration:none;}",
".v4home .pf-foot-links a:hover{color:var(--v4-ink);}",
"@media(max-width:900px){.v4home .pf-grid{grid-template-columns:1fr;}}",
"@media(max-width:760px){.v4home .pf-stats.s4{grid-template-columns:repeat(2,1fr);}.v4home .pf-stats.s3{grid-template-columns:1fr;}.v4home .pf-hero,.v4home .pf-wrap{padding-left:24px;padding-right:24px;}.v4home .pf-actions{align-items:flex-start;margin-left:0;width:100%;}}",
""
].join("\n");

let css = fs.readFileSync(cssPath, 'utf8');
const i = css.indexOf(MARK);
if (i !== -1) { css = css.slice(0, i).replace(/\s+$/, '') + '\n\n'; }
css = css.replace(/\s+$/, '') + '\n\n' + CSS;
fs.writeFileSync(cssPath, css, 'utf8');
console.log('  +  v4 profile styles appended to globals.css');
console.log('\n  Done. npm run build -> npm run dev -> open /profile. Then git push.\n');
