/* ============================================================
   batch8_pdp.js  —  Vendra v4, Batch 8 (product detail page)
   Drop in project root (C:\Users\kvngs\VENDRA), then run:
       node batch8_pdp.js
   ------------------------------------------------------------
   - CREATES  app/store/[slug]/[id]/page.tsx  (the PDP: zoomable
     image, specs, escrow refund policy, qty stepper, Add to cart,
     Buy now, and a "More from this store" grid)
   - REWRITES app/store/[slug]/page.tsx       (product cards now link
     to the PDP; clear "Add to cart" + "Buy" buttons)
   - REWRITES app/marketplace/page.tsx        (cards link to the PDP)
   - appends PDP + card-link styles to globals.css (idempotent)
   Needs the v3 seed (weight/dimensions/condition columns) for specs.
   Backups kept once.
   ============================================================ */
const fs = require('fs');
const path = require('path');
const root = process.cwd();
const pdpDir = path.join(root, 'app', 'store', '[slug]', '[id]');
const pdpPath = path.join(pdpDir, 'page.tsx');
const storePath = path.join(root, 'app', 'store', '[slug]', 'page.tsx');
const mktPath = path.join(root, 'app', 'marketplace', 'page.tsx');
const cssPath = path.join(root, 'app', 'globals.css');
for (const [p, label] of [[storePath, 'app/store/[slug]/page.tsx'], [mktPath, 'app/marketplace/page.tsx'], [cssPath, 'app/globals.css']]) {
  if (!fs.existsSync(p)) { console.error('\n  x  ' + label + ' not found. Run from project root.\n'); process.exit(1); }
}

/* ---------- 1) PDP ---------- */
const PDP = [
"'use client';",
"import Nav from '../../../Nav';",
"import Link from 'next/link';",
"import { useParams } from 'next/navigation';",
"import { useState, useEffect } from 'react';",
"import { getStoreBySlug } from '../../../lib/supabase';",
"import { useCart } from '../../../lib/cart';",
"",
"export default function ProductPage() {",
"  const params = useParams();",
"  const slug = Array.isArray(params.slug) ? params.slug[0] : (params.slug as string);",
"  const pid = Array.isArray(params.id) ? params.id[0] : (params.id as string);",
"  const [store, setStore] = useState<any>(null);",
"  const [loading, setLoading] = useState(true);",
"  const [qty, setQty] = useState(1);",
"  const [added, setAdded] = useState(false);",
"  const [zoom, setZoom] = useState({ on: false, x: 50, y: 50 });",
"  const { items, addItem, updateQuantity, openCart } = useCart();",
"",
"  useEffect(() => {",
"    let active = true;",
"    setLoading(true);",
"    getStoreBySlug(slug)",
"      .then(db => { if (active) { setStore(db); setLoading(false); } })",
"      .catch(() => { if (active) setLoading(false); });",
"    return () => { active = false; };",
"  }, [slug]);",
"",
"  if (loading) return (<main className='v4home'><Nav theme='v4' /><div style={{ minHeight: '70vh', display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 68 }}><div className='v4spinner' /></div></main>);",
"",
"  const product = store && (store.products || []).find((p: any) => String(p.id) === String(pid));",
"  if (!store || !product) return (<main className='v4home'><Nav theme='v4' /><div style={{ minHeight: '70vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 18, paddingTop: 68 }}><div style={{ fontSize: 30, fontWeight: 600 }}>Product not found</div><Link href='/marketplace'><button className='v4btn v4btn-ink'>Back to marketplace</button></Link></div></main>);",
"",
"  const cartId = store.slug + '-' + product.id;",
"  const others = (store.products || []).filter((p: any) => String(p.id) !== String(pid));",
"  const xHandle = store.x_handle ? (store.x_handle.startsWith('@') ? store.x_handle : '@' + store.x_handle) : null;",
"",
"  const addToCart = () => {",
"    const existing = items.find(i => i.id === cartId);",
"    if (!existing) addItem({ id: cartId, storeSlug: store.slug, storeName: store.name, sellerWallet: store.owner_wallet, productName: product.name, price: product.price, image: product.image_url || '' });",
"    updateQuantity(cartId, (existing ? existing.quantity : 0) + qty);",
"    openCart();",
"    setAdded(true); setTimeout(() => setAdded(false), 1800);",
"  };",
"",
"  const checkoutHref = '/checkout?store=' + store.slug + '&product=' + encodeURIComponent(product.name) + '&price=' + product.price + '&seller=' + store.owner_wallet + '&qty=' + qty;",
"",
"  return (",
"    <main className='v4home'>",
"      <Nav theme='v4' />",
"      <div className='pdp-wrap'>",
"        <Link href={'/store/' + store.slug} className='pdp-back'>{'\u2190 '}{store.name}</Link>",
"        <div className='pdp-grid'>",
"          <div className='pdp-media'>",
"            {product.image_url",
"              ? <div className='pdp-img' onMouseMove={(e) => { const r = e.currentTarget.getBoundingClientRect(); setZoom({ on: true, x: ((e.clientX - r.left) / r.width) * 100, y: ((e.clientY - r.top) / r.height) * 100 }); }} onMouseLeave={() => setZoom({ on: false, x: 50, y: 50 })}>",
"                  <img src={product.image_url} alt={product.name} style={{ transformOrigin: zoom.x + '% ' + zoom.y + '%', transform: zoom.on ? 'scale(2)' : 'scale(1)' }} onError={(e) => { const d = e.currentTarget.parentElement; if (d) { (d as HTMLElement).style.background = 'linear-gradient(150deg,#2c2c34,#16161a)'; e.currentTarget.style.display = 'none'; } }} />",
"                </div>",
"              : <div className='pdp-img pdp-img-ph' style={{ background: 'linear-gradient(150deg,#2c2c34,#16161a)' }}><span>{product.name}</span></div>}",
"            {product.image_url && <div className='pdp-zoomhint'>Hover image to zoom</div>}",
"          </div>",
"          <div className='pdp-info'>",
"            <div className='pdp-cat'>{store.category}{xHandle ? ' \u00b7 ' + xHandle : ''}</div>",
"            <h1 className='pdp-title'>{product.name}</h1>",
"            <div className='pdp-price'>{product.price}<span className='u'>USDC</span></div>",
"            {product.description && <p className='pdp-desc'>{product.description}</p>}",
"            <div className='pdp-specs'>",
"              {product.dimensions && <div className='spec-row'><span>Size</span><b>{product.dimensions}</b></div>}",
"              {product.weight && <div className='spec-row'><span>Weight</span><b>{product.weight}</b></div>}",
"              {product.condition && <div className='spec-row'><span>Condition</span><b>{product.condition}</b></div>}",
"              <div className='spec-row'><span>Type</span><b>{product.type}</b></div>",
"            </div>",
"            <div className='pdp-policy'><b>Buyer protection.</b> Every order is held in Vendra escrow (ERC-8183) until you confirm it arrived as described. If it does not, you are refunded in full \u2014 settlement is instant in USDC on Arc.</div>",
"            <div className='pdp-buybar'>",
"              <div className='pdp-qty'>",
"                <button className='qty-btn' onClick={() => setQty(q => Math.max(1, q - 1))} aria-label='Decrease quantity'>{'\u2212'}</button>",
"                <span className='qty-val'>{qty}</span>",
"                <button className='qty-btn' onClick={() => setQty(q => q + 1)} aria-label='Increase quantity'>+</button>",
"              </div>",
"              <button className={'v4btn v4btn-ghost pdp-add' + (added ? ' is-added' : '')} onClick={addToCart}>{added ? 'Added \u2713' : 'Add to cart'}</button>",
"              <Link href={checkoutHref} className='v4btn v4btn-amber pdp-buy'>Buy now</Link>",
"            </div>",
"          </div>",
"        </div>",
"",
"        {others.length > 0 && (",
"          <div className='pdp-more'>",
"            <h2 className='pdp-more-h'>More from {store.name}</h2>",
"            <div className='v4grid' style={{ marginTop: 22 }}>",
"              {others.map((p: any) => (",
"                <Link key={p.id} href={'/store/' + store.slug + '/' + p.id} className='pcard'>",
"                  <div className='pc-img'>",
"                    <span className='pc-badge'>{p.type}</span>",
"                    <img src={p.image_url} alt={p.name} loading='lazy' onError={(e) => { const d = e.currentTarget.parentElement; if (d) { d.classList.add('grad'); (d as HTMLElement).style.background = 'linear-gradient(150deg,#2c2c34,#16161a)'; } }} />",
"                    <span className='ph-name'>{p.name}</span>",
"                  </div>",
"                  <div className='pc-body'>",
"                    <div className='pc-name'>{p.name}</div>",
"                    <div className='pc-seller'>{store.name}</div>",
"                    <div className='pc-foot'><div className='pc-price'>{p.price}<span className='u'>USDC</span></div><span className='pc-buy'>View</span></div>",
"                  </div>",
"                </Link>",
"              ))}",
"            </div>",
"          </div>",
"        )}",
"      </div>",
"      <footer className='v4foot'>",
"        <div className='foot-wrap'>",
"          <div className='foot-brand'>",
"            <div className='v4brandrow'><span className='v4emblem'><span>V</span></span><span className='fb-name'>Vendra</span></div>",
"            <p>The Web3-native marketplace. Sell anything, keep everything, get paid instantly in USDC. Powered by Arc.</p>",
"          </div>",
"          <div className='foot-col'><h4>Marketplace</h4><Link href='/marketplace'>Browse</Link><Link href='/marketplace'>Categories</Link><Link href='/marketplace'>Top sellers</Link></div>",
"          <div className='foot-col'><h4>Sell</h4><Link href='/store/create'>Open a store</Link><Link href='/store/create'>Escrow and payouts</Link><Link href='/profile'>Reputation</Link></div>",
"          <div className='foot-col'><h4>Company</h4><Link href='/marketplace'>About</Link><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'>Faucet</a><a href='https://docs.arc.io/' target='_blank' rel='noopener noreferrer'>Docs</a></div>",
"        </div>",
"        <div className='foot-bot'><span>{'\u00a9'} 2026 Vendra {'\u00b7'} Commerce Unchained</span><span>Live on Arc Testnet {'\u00b7'} USDC native</span></div>",
"      </footer>",
"    </main>",
"  );",
"}",
""
].join("\n");

/* ---------- 2) store page (cards -> PDP, clear buttons) ---------- */
const STORE = [
"'use client';",
"import Nav from '../../Nav';",
"import Link from 'next/link';",
"import { useParams } from 'next/navigation';",
"import { useState, useEffect } from 'react';",
"import { getStoreBySlug } from '../../lib/supabase';",
"import { useCart } from '../../lib/cart';",
"",
"export default function StorePage() {",
"  const params = useParams();",
"  const storeSlug = Array.isArray(params.slug) ? params.slug[0] : (params.slug as string);",
"  const [store, setStore] = useState<any>(null);",
"  const [loading, setLoading] = useState(true);",
"  const [addedIds, setAddedIds] = useState<Record<string,boolean>>({});",
"  const { addItem } = useCart();",
"",
"  useEffect(() => {",
"    let active = true;",
"    setLoading(true);",
"    getStoreBySlug(storeSlug)",
"      .then(db => { if (active) { setStore(db); setLoading(false); } })",
"      .catch(() => { if (active) setLoading(false); });",
"    return () => { active = false; };",
"  }, [storeSlug]);",
"",
"  const handleAddToCart = (product: any) => {",
"    if (!store) return;",
"    addItem({ id: store.slug + '-' + product.id, storeSlug: store.slug, storeName: store.name, sellerWallet: store.owner_wallet, productName: product.name, price: product.price, image: product.image_url || '' });",
"    setAddedIds(prev => ({ ...prev, [product.id]: true }));",
"    setTimeout(() => setAddedIds(prev => ({ ...prev, [product.id]: false })), 2000);",
"  };",
"",
"  if (loading) return (<main className='v4home'><Nav theme='v4' /><div style={{ minHeight: '70vh', display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 68 }}><div className='v4spinner' /></div></main>);",
"  if (!store) return (<main className='v4home'><Nav theme='v4' /><div style={{ minHeight: '70vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 18, paddingTop: 68 }}><div style={{ fontSize: 30, fontWeight: 600 }}>Store not found</div><Link href='/marketplace'><button className='v4btn v4btn-ink'>Back to marketplace</button></Link></div></main>);",
"",
"  const products: any[] = store.products || [];",
"  const xHandle = store.x_handle ? (store.x_handle.startsWith('@') ? store.x_handle : '@' + store.x_handle) : null;",
"",
"  return (",
"    <main className='v4home'>",
"      <Nav theme='v4' />",
"      {store.banner_url",
"        ? <div className='v4st-banner'><img src={store.banner_url} alt='' /></div>",
"        : <div style={{ height: 68 }} />}",
"      <section className='v4st-head'>",
"        <div className='v4st-head-inner'>",
"          <div className='v4st-emblem'>{store.name?.slice(0,2).toUpperCase()}</div>",
"          <div className='v4st-info'>",
"            <div className='v4st-cat'>{store.category}{' \u00b7 Arc Testnet \u00b7 ERC-8004 Verified'}</div>",
"            <h1 className='v4st-title'>{store.name}</h1>",
"            {store.tagline && <div className='v4st-tag'>{store.tagline}</div>}",
"            {xHandle && <a className='v4st-x' href={'https://x.com/' + xHandle.replace('@','')} target='_blank' rel='noopener noreferrer'>{'\uD835\uDD4F '}{xHandle}{' \u2197'}</a>}",
"            {store.description && <div className='v4st-desc'>{store.description}</div>}",
"          </div>",
"        </div>",
"      </section>",
"      <section className='v4st-body'>",
"        <div className='v4st-count'>{products.length}{' product'}{products.length !== 1 ? 's' : ''}</div>",
"        {products.length === 0",
"          ? <div className='v4empty' style={{ marginTop: 24 }}><h3>No products yet</h3><p>This store has not listed anything.</p></div>",
"          : <div className='v4grid' style={{ marginTop: 24 }}>",
"              {products.map((product: any) => {",
"                const pdp = '/store/' + store.slug + '/' + product.id;",
"                const checkoutHref = '/checkout?store=' + store.slug + '&product=' + encodeURIComponent(product.name) + '&price=' + product.price + '&seller=' + store.owner_wallet + '&qty=1';",
"                return (",
"                  <div key={product.id} className='pcard'>",
"                    <Link href={pdp} className='pc-imglink'>",
"                      <div className='pc-img'>",
"                        <span className='pc-badge'>{product.type}</span>",
"                        <img src={product.image_url} alt={product.name} loading='lazy' onError={(e) => { const d = e.currentTarget.parentElement; if (d) { d.classList.add('grad'); (d as HTMLElement).style.background = 'linear-gradient(150deg,#2c2c34,#16161a)'; } }} />",
"                        <span className='ph-name'>{product.name}</span>",
"                      </div>",
"                    </Link>",
"                    <div className='pc-body'>",
"                      <Link href={pdp} className='pc-namelink'><div className='pc-name'>{product.name}</div></Link>",
"                      {product.description && <div className='pc-desc'>{product.description}</div>}",
"                      <div className='pc-foot'>",
"                        <div className='pc-price'>{product.price}<span className='u'>USDC</span></div>",
"                        <Link href={checkoutHref}><button className='pc-buynow'>Buy</button></Link>",
"                      </div>",
"                      <button className={'pc-addcart' + (addedIds[product.id] ? ' added' : '')} onClick={() => handleAddToCart(product)}>{addedIds[product.id] ? 'Added \u2713' : 'Add to cart'}</button>",
"                    </div>",
"                  </div>",
"                );",
"              })}",
"            </div>}",
"      </section>",
"      <footer className='v4foot'>",
"        <div className='foot-wrap'>",
"          <div className='foot-brand'>",
"            <div className='v4brandrow'><span className='v4emblem'><span>V</span></span><span className='fb-name'>Vendra</span></div>",
"            <p>The Web3-native marketplace. Sell anything, keep everything, get paid instantly in USDC. Powered by Arc.</p>",
"          </div>",
"          <div className='foot-col'><h4>Marketplace</h4><Link href='/marketplace'>Browse</Link><Link href='/marketplace'>Categories</Link><Link href='/marketplace'>Top sellers</Link></div>",
"          <div className='foot-col'><h4>Sell</h4><Link href='/store/create'>Open a store</Link><Link href='/store/create'>Escrow and payouts</Link><Link href='/profile'>Reputation</Link></div>",
"          <div className='foot-col'><h4>Company</h4><Link href='/marketplace'>About</Link><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'>Faucet</a><a href='https://docs.arc.io/' target='_blank' rel='noopener noreferrer'>Docs</a></div>",
"        </div>",
"        <div className='foot-bot'><span>{'\u00a9'} 2026 Vendra {'\u00b7'} Commerce Unchained</span><span>Live on Arc Testnet {'\u00b7'} USDC native</span></div>",
"      </footer>",
"    </main>",
"  );",
"}",
""
].join("\n");

/* ---------- 3) marketplace (cards -> PDP) ---------- */
const MKT = [
"'use client';",
"import Nav from '../Nav';",
"import Link from 'next/link';",
"import { useState, useEffect } from 'react';",
"import { getStores } from '../lib/supabase';",
"",
"export default function Marketplace() {",
"  const [stores, setStores] = useState<any[]>([]);",
"  const [loading, setLoading] = useState(true);",
"  const [cat, setCat] = useState('All');",
"  const [search, setSearch] = useState('');",
"",
"  useEffect(() => {",
"    getStores().then(s => { setStores(s || []); setLoading(false); }).catch(() => setLoading(false));",
"  }, []);",
"",
"  const items = stores.flatMap((s: any) => (s.products || []).map((p: any) => ({",
"    id: p.id, name: p.name, price: p.price, image: p.image_url || '',",
"    cat: s.category || 'Other', storeSlug: s.slug, storeName: s.name,",
"  })));",
"  const CATS = ['All', ...Array.from(new Set(items.map(i => i.cat)))];",
"  const filtered = items.filter(i =>",
"    (cat === 'All' || i.cat === cat) &&",
"    ((i.name || '').toLowerCase().includes(search.toLowerCase()) ||",
"     (i.storeName || '').toLowerCase().includes(search.toLowerCase()))",
"  );",
"",
"  return (",
"    <main className='v4home'>",
"      <Nav theme='v4' />",
"      <section className='v4mkt-head'>",
"        <div className='v4mkt-head-inner'>",
"          <p className='eyebrow'>Arc Testnet {'\u00b7'} Live listings</p>",
"          <h1>The <span className='v4amber'>Marketplace</span></h1>",
"          <p className='lede'>Every listing on Vendra {'\u2014'} zero platform fees, instant USDC settlement, and escrow on every order.</p>",
"          <input className='v4search' value={search} onChange={e => setSearch(e.target.value)} placeholder='Search listings\u2026' />",
"        </div>",
"      </section>",
"      <section className='v4mkt-body'>",
"        <div className='chips'>",
"          {CATS.map(c => (<span key={c} className={'chip' + (cat === c ? ' active' : '')} onClick={() => setCat(c)}>{c}</span>))}",
"        </div>",
"        {loading ? (",
"          <div style={{ padding: '72px 0', display: 'flex', justifyContent: 'center' }}><div className='v4spinner' /></div>",
"        ) : filtered.length === 0 ? (",
"          <div className='v4empty'><h3>No listings yet</h3><p>Open a store and your products show up here instantly.</p></div>",
"        ) : (",
"          <div className='v4grid' style={{ marginTop: 32 }}>",
"            {filtered.map(i => (",
"              <Link key={i.storeSlug + '-' + i.id} href={'/store/' + i.storeSlug + '/' + i.id} className='pcard'>",
"                <div className='pc-img'>",
"                  <span className='pc-badge'>{i.cat}</span>",
"                  <img src={i.image} alt={i.name} loading='lazy' onError={(e) => { const d = e.currentTarget.parentElement; if (d) { d.classList.add('grad'); (d as HTMLElement).style.background = 'linear-gradient(150deg,#2c2c34,#16161a)'; } }} />",
"                  <span className='ph-name'>{i.name}</span>",
"                </div>",
"                <div className='pc-body'>",
"                  <div className='pc-name'>{i.name}</div>",
"                  <div className='pc-seller'>{i.storeName}</div>",
"                  <div className='pc-foot'><div className='pc-price'>{i.price}<span className='u'>USDC</span></div><span className='pc-buy'>View</span></div>",
"                </div>",
"              </Link>",
"            ))}",
"          </div>",
"        )}",
"      </section>",
"      <footer className='v4foot'>",
"        <div className='foot-wrap'>",
"          <div className='foot-brand'>",
"            <div className='v4brandrow'><span className='v4emblem'><span>V</span></span><span className='fb-name'>Vendra</span></div>",
"            <p>The Web3-native marketplace. Sell anything, keep everything, get paid instantly in USDC. Powered by Arc.</p>",
"          </div>",
"          <div className='foot-col'><h4>Marketplace</h4><Link href='/marketplace'>Browse</Link><Link href='/marketplace'>Categories</Link><Link href='/marketplace'>Top sellers</Link></div>",
"          <div className='foot-col'><h4>Sell</h4><Link href='/store/create'>Open a store</Link><Link href='/store/create'>Escrow and payouts</Link><Link href='/profile'>Reputation</Link></div>",
"          <div className='foot-col'><h4>Company</h4><Link href='/marketplace'>About</Link><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'>Faucet</a><a href='https://docs.arc.io/' target='_blank' rel='noopener noreferrer'>Docs</a></div>",
"        </div>",
"        <div className='foot-bot'><span>{'\u00a9'} 2026 Vendra {'\u00b7'} Commerce Unchained</span><span>Live on Arc Testnet {'\u00b7'} USDC native</span></div>",
"      </footer>",
"    </main>",
"  );",
"}",
""
].join("\n");

if (!fs.existsSync(pdpDir)) fs.mkdirSync(pdpDir, { recursive: true });
fs.writeFileSync(pdpPath, PDP, 'utf8');
console.log('  +  app/store/[slug]/[id]/page.tsx created (product detail page)');

if (!fs.existsSync(storePath + '.v3bak')) fs.copyFileSync(storePath, storePath + '.v3bak');
fs.writeFileSync(storePath, STORE, 'utf8');
console.log('  +  app/store/[slug]/page.tsx rewritten (cards link to PDP, Add to cart + Buy)');

if (!fs.existsSync(mktPath + '.v3bak')) fs.copyFileSync(mktPath, mktPath + '.v3bak');
fs.writeFileSync(mktPath, MKT, 'utf8');
console.log('  +  app/marketplace/page.tsx rewritten (cards link to PDP)');

/* ---------- 4) CSS ---------- */
const MARK = '/* === V4 PRODUCT DETAIL + CARD LINKS === */';
const CSS = [
MARK,
".v4home .pdp-wrap{max-width:1100px;margin:0 auto;padding:calc(68px + clamp(24px,4vw,40px)) clamp(20px,4vw,48px) clamp(64px,8vw,96px);}",
".v4home .pdp-back{display:inline-block;font-size:13px;font-weight:600;color:var(--v4-tx60);text-decoration:none;margin-bottom:20px;}",
".v4home .pdp-back:hover{color:var(--v4-ink);}",
".v4home .pdp-grid{display:grid;grid-template-columns:1fr 1fr;gap:clamp(24px,4vw,56px);align-items:start;}",
".v4home .pdp-media{position:sticky;top:88px;}",
".v4home .pdp-img{position:relative;aspect-ratio:1/1;border-radius:18px;overflow:hidden;border:1px solid var(--v4-line);background:var(--v4-paper2);cursor:zoom-in;}",
".v4home .pdp-img img{width:100%;height:100%;object-fit:cover;transition:transform .15s ease-out;}",
".v4home .pdp-img-ph{display:flex;align-items:flex-end;padding:22px;cursor:default;}",
".v4home .pdp-img-ph span{color:#fff;font-size:22px;font-weight:600;}",
".v4home .pdp-zoomhint{font-size:11px;color:var(--v4-tx40);margin-top:10px;text-align:center;letter-spacing:.04em;}",
".v4home .pdp-info{padding-top:4px;}",
".v4home .pdp-cat{font-size:11px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-aDeep);margin-bottom:10px;}",
".v4home .pdp-title{font-size:clamp(26px,3.6vw,40px);font-weight:600;letter-spacing:-.02em;line-height:1.05;}",
".v4home .pdp-price{font-size:28px;font-weight:700;letter-spacing:-.02em;margin-top:14px;}",
".v4home .pdp-price .u{font-size:14px;color:var(--v4-tx40);font-weight:500;margin-left:5px;}",
".v4home .pdp-desc{font-size:15px;color:var(--v4-tx60);line-height:1.7;margin-top:18px;}",
".v4home .pdp-specs{margin-top:22px;border-top:1px solid var(--v4-line);}",
".v4home .spec-row{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid var(--v4-line);font-size:13.5px;}",
".v4home .spec-row span{color:var(--v4-tx40);}",
".v4home .spec-row b{font-weight:600;color:var(--v4-tx);}",
".v4home .pdp-policy{margin-top:20px;background:var(--v4-aSoft);border:1px solid var(--v4-aSoft2);border-radius:14px;padding:16px 18px;font-size:13px;color:var(--v4-tx60);line-height:1.6;}",
".v4home .pdp-policy b{color:var(--v4-tx);}",
".v4home .pdp-buybar{display:flex;align-items:center;gap:10px;margin-top:24px;flex-wrap:wrap;}",
".v4home .pdp-qty{display:flex;align-items:center;border:1px solid var(--v4-line2);border-radius:999px;overflow:hidden;}",
".v4home .qty-btn{width:38px;height:42px;background:transparent;border:none;font-size:18px;color:var(--v4-tx);cursor:pointer;transition:background .2s;}",
".v4home .qty-btn:hover{background:var(--v4-paper2);}",
".v4home .qty-val{min-width:34px;text-align:center;font-weight:600;font-size:15px;}",
".v4home .pdp-add{padding-top:11px;padding-bottom:11px;}",
".v4home .pdp-add.is-added{border-color:var(--v4-a);color:var(--v4-aDeep);}",
".v4home .pdp-buy{text-decoration:none;}",
".v4home .pdp-more{margin-top:clamp(48px,7vw,80px);}",
".v4home .pdp-more-h{font-size:22px;font-weight:600;letter-spacing:-.01em;}",
"@media(max-width:820px){.v4home .pdp-grid{grid-template-columns:1fr;}.v4home .pdp-media{position:static;}}",
".v4home .pc-imglink,.v4home .pc-namelink{display:block;text-decoration:none;color:inherit;}",
".v4home .v4st-body .pcard{cursor:default;}",
".v4home .pc-addcart{margin-top:12px;width:100%;border:1px solid var(--v4-line2);background:transparent;color:var(--v4-tx);font-family:'General Sans',sans-serif;font-weight:600;font-size:13px;padding:10px;border-radius:999px;cursor:pointer;transition:.25s;}",
".v4home .pc-addcart:hover{border-color:var(--v4-ink);}",
".v4home .pc-addcart.added{border-color:var(--v4-a);color:var(--v4-aDeep);}",
""
].join("\n");

let css = fs.readFileSync(cssPath, 'utf8');
const i = css.indexOf(MARK);
if (i !== -1) { css = css.slice(0, i).replace(/\s+$/, '') + '\n\n'; }
css = css.replace(/\s+$/, '') + '\n\n' + CSS;
fs.writeFileSync(cssPath, css, 'utf8');
console.log('  +  PDP + card-link styles appended to globals.css');
console.log('\n  Done. npm run build -> npm run dev -> open /marketplace, click a product. Then git push.\n');
