/* ============================================================
   batch16_order_images.js  —  Vendra v4, Batch 16
   Drop in project root (C:\Users\kvngs\VENDRA), then run:
       node batch16_order_images.js
   ------------------------------------------------------------
   Adds real product thumbnails (box only as fallback):
     - app/profile/page.tsx        buyer history + seller recent/all sales
     - app/orders/[id]/page.tsx    product image at top of the receipt
   Images are resolved from getStores() by matching order -> product
   (seller_wallet + product name, with a name-only fallback). Broken
   image files fall back to the box via onError. No schema change.
   Keeps ALL existing logic. Appends thumbnail CSS (idempotent).
   These files already have .v3bak backups from batches 14/15.
   ============================================================ */
const fs = require('fs');
const path = require('path');
const root = process.cwd();
const profilePath = path.join(root, 'app', 'profile', 'page.tsx');
const orderPath = path.join(root, 'app', 'orders', '[id]', 'page.tsx');
const cssPath = path.join(root, 'app', 'globals.css');
for (const [p, label] of [[profilePath, 'app/profile/page.tsx'], [orderPath, 'app/orders/[id]/page.tsx'], [cssPath, 'app/globals.css']]) {
  if (!fs.existsSync(p)) { console.error('\n  x  ' + label + ' not found. Run from project root.\n'); process.exit(1); }
}

/* ---------- profile/page.tsx (full rewrite, batch14 + image resolver) ---------- */
const PROFILE = [
"'use client';",
"import Nav from '../Nav';",
"import Link from 'next/link';",
"import { useAccount } from 'wagmi';",
"import { useState, useEffect } from 'react';",
"import { getAllProfiles, getOrdersByBuyer, getOrdersBySeller, getStoreByWallet, deleteStore, getStores } from '../lib/supabase';",
"import { useRouter } from 'next/navigation';",
"",
"export default function Profile() {",
"  const { address, isConnected } = useAccount();",
"  const router = useRouter();",
"  const [sellerProfile, setSellerProfile] = useState<any>(null);",
"  const [buyerProfile, setBuyerProfile] = useState<any>(null);",
"  const [store, setStore] = useState<any>(null);",
"  const [buyerOrders, setBuyerOrders] = useState<any[]>([]);",
"  const [sellerOrders, setSellerOrders] = useState<any[]>([]);",
"  const [stores, setStores] = useState<any[]>([]);",
"  const [view, setView] = useState<'seller'|'buyer'>('seller');",
"  const [loading, setLoading] = useState(true);",
"  const [deleting, setDeleting] = useState(false);",
"  const [showDelete, setShowDelete] = useState(false);",
"",
"  useEffect(() => {",
"    if (!isConnected || !address) { router.push('/'); return; }",
"    Promise.all([getAllProfiles(address), getStoreByWallet(address), getOrdersByBuyer(address), getOrdersBySeller(address), getStores()]).then(([all, s, bo, so, st]) => {",
"      const sp = all.find((p:any) => p.role === 'seller') || null;",
"      const bp = all.find((p:any) => p.role === 'buyer') || null;",
"      setSellerProfile(sp); setBuyerProfile(bp); setStore(s); setBuyerOrders(bo); setSellerOrders(so); setStores(st || []);",
"      if (sp) setView('seller'); else if (bp) setView('buyer');",
"      setLoading(false);",
"    });",
"  }, [address, isConnected, router]);",
"",
"  const handleDeleteStore = async () => {",
"    if (!store) return; setDeleting(true);",
"    try { await deleteStore(store.id); setStore(null); setShowDelete(false); }",
"    catch (e) { console.error(e); } finally { setDeleting(false); }",
"  };",
"",
"  const isSeller = !!sellerProfile, isBuyer = !!buyerProfile;",
"  const active = view === 'seller' ? sellerProfile : buyerProfile;",
"  const initials = active?.display_name?.slice(0,2).toUpperCase() || address?.slice(2,4).toUpperCase() || 'VN';",
"  const totalRevenue = sellerOrders.reduce((s,o) => s + Number(o.amount), 0);",
"  const totalSpent = buyerOrders.reduce((s,o) => s + Number(o.amount), 0);",
"",
"  // resolve an order back to its product image (seller+name, then name-only)",
"  const stripQty = (n:string) => (n || '').replace(/\\s+x\\d+$/i, '');",
"  const imgExact: Record<string,string> = {};",
"  const imgName: Record<string,string> = {};",
"  stores.forEach((s:any) => (s.products || []).forEach((p:any) => {",
"    if (p?.image_url) { imgExact[s.owner_wallet + '|' + p.name] = p.image_url; if (!imgName[p.name]) imgName[p.name] = p.image_url; }",
"  }));",
"  const imgFor = (o:any) => imgExact[o.seller_wallet + '|' + stripQty(o.product_name)] || imgName[stripQty(o.product_name)] || null;",
"  const Thumb = ({ o, sm }: { o:any; sm?:boolean }) => (",
"    <span className={'pf-thumb-wrap' + (sm ? ' sm' : '')}><span className='pf-thumb-box'>\uD83D\uDCE6</span>{imgFor(o) && <img src={imgFor(o)} alt='' className='pf-thumb-img' onError={(e) => { e.currentTarget.style.display = 'none'; }} />}</span>",
"  );",
"",
"  if (loading) return <main className='v4home' style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Nav theme='v4' /><div className='v4spinner' /></main>;",
"",
"  if (!isSeller && !isBuyer) return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}><Nav theme='v4' />",
"      <div style={{ minHeight: '70vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '24px' }}>",
"        <h1 className='pf-name' style={{ fontSize: 'clamp(32px,5vw,52px)' }}>No profile <span className='v4amber'>found</span></h1>",
"        <p className='lede' style={{ margin: '12px 0 28px' }}>Complete onboarding to join Vendra.</p>",
"        <Link href='/onboarding' className='v4btn v4btn-amber'>Get started</Link>",
"      </div>",
"    </main>",
"  );",
"",
"  return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}>",
"      <Nav theme='v4' />",
"      {showDelete && <div className='pf-modal-bg'><div className='pf-modal'><div className='pf-modal-title'>Delete store?</div><div className='pf-modal-body'>This will permanently delete <strong style={{ color: 'var(--v4-ink)' }}>{store?.name}</strong> and all its products. This cannot be undone.</div><div style={{ display: 'flex', gap: 12 }}><button onClick={handleDeleteStore} disabled={deleting} className='pf-del-solid'>{deleting ? 'Deleting\u2026' : 'Yes, delete'}</button><button onClick={() => setShowDelete(false)} className='v4btn v4btn-ghost'>Cancel</button></div></div></div>}",
"",
"      <div className='pf-hero'>",
"        <div className='pf-hero-in'>",
"          <div className='pf-avatar'>{active?.avatar_url ? <img src={active.avatar_url} alt='avatar' /> : initials}</div>",
"          <div style={{ flex: 1, minWidth: 0 }}>",
"            <div className='pf-name'>{active?.display_name || 'Vendra user'}{view === 'seller' && store && <span className='pf-owner'>owner \u00b7 {store.name}</span>}</div>",
"            {active?.bio && <div className='pf-bio'>{active.bio}</div>}",
"            {active?.x_handle && <a href={'https://x.com/' + active.x_handle.replace('@','')} target='_blank' rel='noopener noreferrer' className='pf-x'>\uD835\uDD4F {active.x_handle.startsWith('@') ? active.x_handle : '@' + active.x_handle} \u2197</a>}",
"            <div className='pf-addr'>{address ? address.slice(0,6) + '...' + address.slice(-4) : ''} \u00b7 Arc Testnet</div>",
"            <div className='pf-badges'>",
"              {isSeller && <div className='pf-badge amber'>Seller</div>}",
"              {isBuyer && <div className='pf-badge'>Buyer</div>}",
"              <div className='pf-badge'>ERC-8004 Identity</div>",
"            </div>",
"          </div>",
"          <div className='pf-actions'>",
"            {isSeller && isBuyer && <div className='pf-toggle'><button onClick={() => setView('seller')} className={view === 'seller' ? 'on' : ''}>Seller</button><button onClick={() => setView('buyer')} className={view === 'buyer' ? 'on' : ''}>Buyer</button></div>}",
"            {!isSeller && <Link href='/onboarding?role=seller' className='v4btn v4btn-amber'>+ Seller profile</Link>}",
"            {!isBuyer && <Link href='/onboarding?role=buyer' className='v4btn v4btn-ink'>+ Buyer profile</Link>}",
"            <Link href={'/edit-profile?role=' + view} className='v4btn v4btn-ghost'>Edit profile</Link>",
"          </div>",
"        </div>",
"      </div>",
"",
"      {view === 'seller' && isSeller && (",
"        <div className='pf-wrap'>",
"          <div className='pf-stats s4'>",
"            {[{ val: '$' + totalRevenue.toFixed(2), label: 'Total revenue', amber: true }, { val: String(sellerOrders.length), label: 'Orders' }, { val: String(store?.products?.length || 0), label: 'Products' }, { val: '0%', label: 'Platform fee', amber: true }].map(s => (",
"              <div key={s.label} className='pf-stat'><div className={'pf-stat-v' + ((s as any).amber ? ' amber' : '')}>{s.val}</div><div className='pf-stat-l'>{s.label}</div></div>",
"            ))}",
"          </div>",
"          <div className='pf-grid'>",
"            <div>",
"              <div className='eyebrow' style={{ marginBottom: 14 }}>Your store</div>",
"              <div className='pf-card'>",
"                {store ? (",
"                  <div className='pf-store-pad'>",
"                    {store.banner_url && <div className='pf-store-banner'><img src={store.banner_url} alt='banner' /></div>}",
"                    <div className='pf-store-name'>{store.name}</div>",
"                    <div className='pf-store-tag'>{store.tagline}</div>",
"                    <div className='pf-store-meta'>{store.category} \u00b7 {store.products?.length || 0} products \u00b7 Arc Testnet</div>",
"                    <div className='pf-store-btns'>",
"                      <Link href={'/store/' + store.slug} className='v4btn v4btn-amber'>View storefront</Link>",
"                      <Link href='/store/edit?tab=products' className='v4btn v4btn-ghost'>+ Add products</Link>",
"                      <Link href='/store/edit' className='v4btn v4btn-ghost'>Edit store</Link>",
"                      <button onClick={() => setShowDelete(true)} className='pf-del'>Delete</button>",
"                    </div>",
"                  </div>",
"                ) : (",
"                  <div className='pf-empty'><div className='pf-empty-h'>No store yet</div><Link href='/store/create' className='v4btn v4btn-amber'>Create store</Link></div>",
"                )}",
"              </div>",
"            </div>",
"            <div className='pf-bal'>",
"              <div className='pf-bal-l'>Store balance</div>",
"              <div className='pf-bal-v'>${totalRevenue.toFixed(2)}</div>",
"              <div className='pf-bal-u'>USDC \u00b7 Arc Testnet</div>",
"              <div className='pf-recent-h'>Recent sales</div>",
"              {sellerOrders.slice(0,3).length === 0 ? <div className='pf-recent-empty'>No sales yet</div>",
"              : sellerOrders.slice(0,3).map((o:any) => (",
"                <div key={o.id} className='pf-recent-row'><Thumb o={o} sm /><div style={{ flex: 1, minWidth: 0 }}><div className='pf-recent-name'>{o.product_name}</div><div className='pf-recent-date'>{new Date(o.created_at).toLocaleDateString()}</div></div><div className='pf-recent-amt'>+{Number(o.amount).toFixed(0)}</div></div>",
"              ))}",
"            </div>",
"          </div>",
"          <div className='eyebrow' style={{ marginBottom: 14 }}>All sales</div>",
"          <div className='pf-orders'>",
"            {sellerOrders.length === 0 ? <div className='pf-orders-empty'>No sales yet</div>",
"            : sellerOrders.map((o:any) => (",
"              <div key={o.id} className='pf-order'><Thumb o={o} /><div style={{ flex: 1, minWidth: 0 }}><div className='pf-order-name'>{o.product_name}</div><div className='pf-order-meta'>{new Date(o.created_at).toLocaleDateString()}{o.tx_hash ? ' \u00b7 ' + o.tx_hash.slice(0,14) + '...' : ''}</div></div><div className='pf-order-amt'>${Number(o.amount).toFixed(2)}</div></div>",
"            ))}",
"          </div>",
"        </div>",
"      )}",
"",
"      {view === 'buyer' && isBuyer && (",
"        <div className='pf-wrap'>",
"          <div className='pf-stats s3'>",
"            {[{ val: '$' + totalSpent.toFixed(2), label: 'Total spent' }, { val: String(buyerOrders.length), label: 'Orders' }, { val: 'Arc Testnet', label: 'Network' }].map(s => (",
"              <div key={s.label} className='pf-stat'><div className='pf-stat-v'>{s.val}</div><div className='pf-stat-l'>{s.label}</div></div>",
"            ))}",
"          </div>",
"          <div className='eyebrow' style={{ marginBottom: 14 }}>Order history</div>",
"          <div className='pf-orders' style={{ marginBottom: 28 }}>",
"            {buyerOrders.length === 0 ? <div className='pf-orders-empty'>No orders yet \u2014 <Link href='/marketplace' style={{ color: 'var(--v4-aDeep)' }}>explore the marketplace</Link></div>",
"            : buyerOrders.map((o:any) => (",
"              <Link key={o.id} href={'/orders/' + o.id} className='pf-order'><Thumb o={o} /><div style={{ flex: 1, minWidth: 0 }}><div className='pf-order-name'>{o.product_name}</div><div className='pf-order-meta'>{new Date(o.created_at).toLocaleDateString()} \u00b7 click to view \u2192</div></div><div className='pf-order-amt'>${Number(o.amount).toFixed(2)}</div></Link>",
"            ))}",
"          </div>",
"          <Link href='/marketplace' className='v4btn v4btn-amber'>Browse marketplace \u2192</Link>",
"        </div>",
"      )}",
"",
"      <footer className='pf-foot'><div className='pf-foot-brand'>Vendra</div><div className='pf-foot-copy'>ERC-8183 Escrow \u00b7 ERC-8004 Identity \u00b7 Arc Testnet</div><div className='pf-foot-links'><Link href='/marketplace'>Marketplace</Link><Link href='/store/create'>Sell</Link></div></footer>",
"    </main>",
"  );",
"}",
""
].join("\n");

/* ---------- orders/[id]/page.tsx (full rewrite, batch15 + product image) ---------- */
const ORDER = [
"'use client';",
"import Nav from '../../Nav';",
"import Link from 'next/link';",
"import { useParams } from 'next/navigation';",
"import { useState, useEffect } from 'react';",
"import { supabase, getStores } from '../../lib/supabase';",
"import ArcEscrowStatus from '../../components/ArcEscrowStatus';",
"",
"export default function OrderPage() {",
"  const params = useParams();",
"  const id = params.id as string;",
"  const [order, setOrder] = useState<any>(null);",
"  const [escrow, setEscrow] = useState<any>(null);",
"  const [productImg, setProductImg] = useState<string | null>(null);",
"  const [loading, setLoading] = useState(true);",
"",
"  useEffect(() => {",
"    const load = async () => {",
"      const { data: o } = await supabase.from('orders').select('*').eq('id', id).single();",
"      setOrder(o);",
"      if (o) {",
"        const { data: e } = await supabase.from('escrow_jobs').select('*').eq('order_id', id).single();",
"        setEscrow(e);",
"        try {",
"          const stores = await getStores();",
"          const base = (o.product_name || '').replace(/\\s+x\\d+$/i, '');",
"          let exact: string | null = null, nameOnly: string | null = null;",
"          (stores || []).forEach((s:any) => (s.products || []).forEach((p:any) => {",
"            if (p?.image_url && p.name === base) { if (s.owner_wallet === o.seller_wallet && !exact) exact = p.image_url; if (!nameOnly) nameOnly = p.image_url; }",
"          }));",
"          setProductImg(exact || nameOnly);",
"        } catch { /* keep box fallback */ }",
"      }",
"      setLoading(false);",
"    };",
"    load();",
"  }, [id]);",
"",
"  if (loading) return <main className='v4home' style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Nav theme='v4' /><div className='v4spinner' /></main>;",
"",
"  if (!order) return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}><Nav theme='v4' />",
"      <div style={{ minHeight: '70vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '24px' }}>",
"        <h1 className='ord-title'>Order not <span className='v4amber'>found</span></h1>",
"        <Link href='/profile' className='v4btn v4btn-amber'>Back to profile</Link>",
"      </div>",
"    </main>",
"  );",
"",
"  const explorerUrl = 'https://testnet.arcscan.app/tx/' + order.tx_hash;",
"",
"  return (",
"    <main className='v4home' style={{ minHeight: '100vh' }}>",
"      <Nav theme='v4' />",
"      <div className='ord-wrap'>",
"        <p className='eyebrow'>Order receipt</p>",
"        <h1 className='ord-title'>Order <span className='v4amber'>details</span></h1>",
"        <div className='ord-status'><span className='ord-status-dot' />{order.status || 'Confirmed'}</div>",
"        <div className='ord-card'>",
"          <div className='ord-card-top'>",
"            <div className='ord-imgwrap'><div className='ord-imgbox'>\uD83D\uDCE6</div>{productImg && <img src={productImg} alt={order.product_name} className='ord-imgimg' onError={(e) => { e.currentTarget.style.display = 'none'; }} />}</div>",
"            <div className='ord-pname'>{order.product_name}</div>",
"            <div className='ord-amt'>${Number(order.amount).toFixed(2)} USDC</div>",
"          </div>",
"          <div className='ord-rows'>",
"            {[['Date', new Date(order.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })], ['Time', new Date(order.created_at).toLocaleTimeString()], ['Buyer', order.buyer_wallet ? order.buyer_wallet.slice(0,8) + '...' + order.buyer_wallet.slice(-6) : ''], ['Seller', order.seller_wallet ? order.seller_wallet.slice(0,8) + '...' + order.seller_wallet.slice(-6) : ''], ['Network', 'Arc Testnet'], ['Status', order.status || 'Confirmed']].map(([label, val]) => (",
"              <div key={String(label)} className='ord-row'><span className='ord-row-l'>{label}</span><span className='ord-row-v'>{val}</span></div>",
"            ))}",
"          </div>",
"        </div>",
"        <div style={{ margin: '16px 0' }}>",
"          <ArcEscrowStatus orderId={id} status={escrow?.status || 'locked'} amount={Number(order.amount)} createdAt={order.created_at} />",
"        </div>",
"        {order.tx_hash && (",
"          <a href={explorerUrl} target='_blank' rel='noopener noreferrer' className='ord-tx'>",
"            <div className='ord-tx-l'>Transaction hash \u00b7 Arc Testnet</div>",
"            <div className='ord-tx-h'>{order.tx_hash}</div>",
"            <div className='ord-tx-v'>View on Arc Explorer \u2197</div>",
"          </a>)}",
"        <div className='ord-btns'>",
"          <Link href='/profile' className='v4btn v4btn-amber'>View all orders</Link>",
"          <Link href='/marketplace' className='v4btn v4btn-ghost'>Keep shopping</Link>",
"        </div>",
"      </div>",
"      <footer className='ord-foot'><div className='ord-foot-brand'>Vendra</div><div className='ord-foot-copy'>ERC-8183 Escrow \u00b7 Arc Testnet</div><div className='ord-foot-links'><Link href='/marketplace'>Marketplace</Link></div></footer>",
"    </main>",
"  );",
"}",
""
].join("\n");

fs.writeFileSync(profilePath, PROFILE, 'utf8');
console.log('  +  app/profile/page.tsx updated (product thumbnails)');
fs.writeFileSync(orderPath, ORDER, 'utf8');
console.log('  +  app/orders/[id]/page.tsx updated (product image on receipt)');

const MARK = '/* === V4 ORDER THUMBNAILS === */';
const CSS = [
MARK,
".v4home .pf-thumb-wrap{position:relative;width:44px;height:44px;flex-shrink:0;}",
".v4home .pf-thumb-wrap.sm{width:32px;height:32px;}",
".v4home .pf-thumb-box{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:var(--v4-paper2);border:1px solid var(--v4-line);border-radius:9px;font-size:18px;}",
".v4home .pf-thumb-wrap.sm .pf-thumb-box{font-size:14px;border-radius:7px;}",
".v4home .pf-thumb-img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;border:1px solid var(--v4-line);border-radius:9px;}",
".v4home .pf-thumb-wrap.sm .pf-thumb-img{border-radius:7px;}",
".v4home .ord-imgwrap{position:relative;width:120px;height:120px;margin:0 auto 14px;}",
".v4home .ord-imgbox{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:42px;background:var(--v4-card);border:1px solid var(--v4-line);border-radius:16px;}",
".v4home .ord-imgimg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;border:1px solid var(--v4-line);border-radius:16px;}",
""
].join("\n");

let css = fs.readFileSync(cssPath, 'utf8');
const i = css.indexOf(MARK);
if (i !== -1) { css = css.slice(0, i).replace(/\s+$/, '') + '\n\n'; }
css = css.replace(/\s+$/, '') + '\n\n' + CSS;
fs.writeFileSync(cssPath, css, 'utf8');
console.log('  +  v4 thumbnail styles appended to globals.css');
console.log('\n  Done. npm run build -> npm run dev -> check /profile + open the order. Then git push.\n');
