/* ============================================================
   batch24_nav_wallet.js  —  Vendra v4, Batch 24 (nav + wallet)
   Drop in project root (C:\Users\kvngs\VENDRA), then run:
       node batch24_nav_wallet.js
   ------------------------------------------------------------
   Migrates the nav/wallet surface to v4 light:
     - app/Nav.tsx                          (3 modals only; nav bar kept verbatim)
     - app/components/CircleWalletDashboard.tsx
     - app/components/CircleBalanceWidget.tsx
     - app/components/AppKitWidget.tsx
   Keeps ALL logic/handlers/API calls. Reuses pf-modal / jn-* /
   ob-* / v4btn / v4-cart-x / v4spinner (already in globals) and
   adds nv-* + cw-* styles. Requires Batches 14, 18, 23 styles.
   Backs up each file once. Idempotent CSS.
   ============================================================ */
const fs = require('fs');
const path = require('path');
const root = process.cwd();
const navPath = path.join(root, 'app', 'Nav.tsx');
const dashPath = path.join(root, 'app', 'components', 'CircleWalletDashboard.tsx');
const cbwPath = path.join(root, 'app', 'components', 'CircleBalanceWidget.tsx');
const akwPath = path.join(root, 'app', 'components', 'AppKitWidget.tsx');
const cssPath = path.join(root, 'app', 'globals.css');
for (const [p, label] of [[navPath, 'app/Nav.tsx'], [dashPath, 'CircleWalletDashboard.tsx'], [cbwPath, 'CircleBalanceWidget.tsx'], [akwPath, 'AppKitWidget.tsx'], [cssPath, 'app/globals.css']]) {
  if (!fs.existsSync(p)) { console.error('\n  x  ' + label + ' not found. Run from project root.\n'); process.exit(1); }
}
const g = fs.readFileSync(cssPath, 'utf8');
for (const need of ['V4 ONBOARDING STYLES', 'V4 WELCOME + JOIN STYLES', 'V4 PROFILE STYLES']) {
  if (!g.includes(need)) console.warn('  !  Warning: "' + need + '" not in globals.css. Run earlier batches first (14/18/23) or styles will be missing.');
}

/* ---------------- Nav.tsx ---------------- */
const NAV = [
"'use client';",
"import Link from 'next/link';",
"import { ConnectButton } from '@rainbow-me/rainbowkit';",
"import { useAccount } from 'wagmi';",
"import { useState, useEffect } from 'react';",
"import CartButton from './components/CartButton';",
"import CartDrawer from './components/CartDrawer';",
"import AppKitWidget from './components/AppKitWidget';",
"import CircleWalletDashboard from './components/CircleWalletDashboard';",
"import CircleBalanceWidget from './components/CircleBalanceWidget';",
"",
"type CircleStep = 'email'|'otp'|'checking'|'found'|'notfound'|'creating'|'done';",
"type CircleWallet = { address: string; walletId: string; email: string };",
"const STORAGE_KEY = 'vendra_circle_wallet';",
"",
"export default function Nav({ theme = 'v3' }: { theme?: 'v3' | 'v4' }) {",
"  const { isConnected } = useAccount();",
"  const [showLogin, setShowLogin] = useState(false);",
"  const [showCircle, setShowCircle] = useState(false);",
"  const [showDashboard, setShowDashboard] = useState(false);",
"  const [step, setStep] = useState<CircleStep>('email');",
"  const [email, setEmail] = useState('');",
"  const [otp, setOtp] = useState('');",
"  const [circleWallet, setCircleWallet] = useState<CircleWallet|null>(null);",
"  const [balance, setBalance] = useState('0');",
"  const [error, setError] = useState('');",
"  const [loading, setLoading] = useState(false);",
"  const [resendTimer, setResendTimer] = useState(0);",
"  const [mounted, setMounted] = useState(false);",
"",
"  useEffect(() => {",
"    setMounted(true);",
"    try {",
"      const saved = sessionStorage.getItem(STORAGE_KEY);",
"      if (saved) { const w = JSON.parse(saved); setCircleWallet(w); fetchBalance(w.walletId); }",
"    } catch {}",
"  }, []);",
"",
"  useEffect(() => {",
"    if (resendTimer > 0) { const t = setTimeout(() => setResendTimer(r => r - 1), 1000); return () => clearTimeout(t); }",
"  }, [resendTimer]);",
"",
"  const saveWallet = (w: CircleWallet) => { setCircleWallet(w); try { sessionStorage.setItem(STORAGE_KEY, JSON.stringify(w)); } catch {} };",
"  const logout = () => { setCircleWallet(null); try { sessionStorage.removeItem(STORAGE_KEY); } catch {} setShowDashboard(false); setShowCircle(false); };",
"  const closeAll = () => { setShowLogin(false); setShowCircle(false); setShowDashboard(false); setStep('email'); setError(''); setOtp(''); };",
"  const shortAddr = (addr: string) => addr ? addr.slice(0,6) + '...' + addr.slice(-4) : '';",
"",
"  const fetchBalance = async (walletId: string) => {",
"    try {",
"      const res = await fetch('/api/circle/balance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ walletId }) });",
"      const data = await res.json();",
"      setBalance(data.balance || '0');",
"    } catch {}",
"  };",
"",
"  const handleSendOtp = async () => {",
"    if (!email) { setError('Enter your email'); return; }",
"    setLoading(true); setError('');",
"    try {",
"      const res = await fetch('/api/circle/send-otp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      setStep('otp'); setResendTimer(60);",
"    } catch (e:any) { setError(e.message || 'Failed to send code'); }",
"    finally { setLoading(false); }",
"  };",
"",
"  const handleVerifyOtp = async () => {",
"    if (!otp || otp.length !== 6) { setError('Enter the 6-digit code'); return; }",
"    setLoading(true); setError(''); setStep('checking');",
"    try {",
"      const vRes = await fetch('/api/circle/verify-otp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, otp }) });",
"      const vData = await vRes.json();",
"      if (vData.error) throw new Error(vData.error);",
"      const res = await fetch('/api/circle/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      if (data.found) { const w = { address: data.address, walletId: data.walletId, email }; saveWallet(w); await fetchBalance(data.walletId); setStep('found'); }",
"      else { setStep('notfound'); }",
"    } catch (e:any) { setError(e.message || 'Verification failed'); setStep('otp'); }",
"    finally { setLoading(false); }",
"  };",
"",
"  const handleCreate = async () => {",
"    setStep('creating'); setError('');",
"    try {",
"      const res = await fetch('/api/circle/create-wallet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      const w = { address: data.address, walletId: data.walletId, email }; saveWallet(w); await fetchBalance(data.walletId); setStep('done');",
"    } catch (e:any) { setError(e.message || 'Failed'); setStep('notfound'); }",
"  };",
"",
"  return (",
"    <>",
"      <CartDrawer/>",
"",
"      {/* Login Modal */}",
"      {showLogin && !showCircle && (",
"        <div className='pf-modal-bg' onClick={closeAll}>",
"          <div className='pf-modal nv-modal' style={{ maxWidth: 400 }} onClick={e => e.stopPropagation()}>",
"            <div className='nv-mhead'>",
"              <div className='pf-modal-title'>Log in</div>",
"              <button onClick={closeAll} className='v4-cart-x' aria-label='Close'>\u2715</button>",
"            </div>",
"            <p className='jn-sub' style={{ marginBottom: 18, textAlign: 'left' }}>Choose how you want to connect to Vendra.</p>",
"            <div className='jn-card' style={{ marginBottom: 12 }}>",
"              <div className='jn-card-l'>\uD83E\uDD8A Web3 wallet</div>",
"              <div className='jn-card-p'>MetaMask, Coinbase, WalletConnect or any EVM wallet.</div>",
"              <div className='jn-connect'><ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} /></div>",
"            </div>",
"            <div className='vor' style={{ marginBottom: 12 }}><div className='vor-line' /><span className='vor-txt'>or</span><div className='vor-line' /></div>",
"            <div className='jn-card'>",
"              <div className='jn-card-l'>\u2B55 Circle wallet</div>",
"              <div className='jn-card-p'>No crypto experience needed. Verify your email to access your USDC wallet.</div>",
"              <button onClick={() => { setShowLogin(false); setShowCircle(true); }} className='v4btn v4btn-ink' style={{ width: '100%', justifyContent: 'center' }}>Log in with Circle wallet \u2192</button>",
"            </div>",
"          </div>",
"        </div>)}",
"",
"      {/* Circle Auth Modal */}",
"      {showCircle && (",
"        <div className='pf-modal-bg' onClick={closeAll}>",
"          <div className='pf-modal nv-modal' style={{ maxWidth: 440 }} onClick={e => e.stopPropagation()}>",
"            <div className='nv-mhead'>",
"              <div>",
"                <div className='jn-circle-l'>Circle \u00b7 USDC Wallet</div>",
"                <div className='jn-circle-h'>",
"                  {step === 'email' && 'Log in with Circle'}{step === 'otp' && 'Enter your code'}{step === 'checking' && 'Verifying\u2026'}{step === 'notfound' && 'Create wallet'}{step === 'creating' && 'Creating wallet\u2026'}{(step === 'found' || step === 'done') && 'Welcome back \u2713'}",
"                </div>",
"              </div>",
"              <button onClick={closeAll} className='v4-cart-x' aria-label='Close'>\u2715</button>",
"            </div>",
"            {step === 'email' && (<>",
"              <p className='jn-p'>Enter your email. We\u2019ll send a verification code to confirm it\u2019s you.</p>",
"              <div className='ob-field'><label className='ob-label'>Email address</label><input className='ob-input' type='email' placeholder='you@example.com' value={email} onChange={e => setEmail(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSendOtp()} autoFocus /></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              <button onClick={handleSendOtp} disabled={loading} className='v4btn v4btn-amber jn-cta'>{loading ? 'Sending code\u2026' : 'Send verification code \u2192'}</button>",
"              <button onClick={() => { setShowCircle(false); setShowLogin(true); }} className='jn-link-btn' style={{ width: '100%' }}>\u2190 Back to options</button>",
"            </>)}",
"            {step === 'otp' && (<>",
"              <p className='jn-p'>Code sent to <strong>{email}</strong>. Check inbox and spam.</p>",
"              <div style={{ fontSize: 11, color: 'var(--v4-tx40)', marginBottom: 18 }}>Expires in 10 minutes.</div>",
"              <div className='ob-field'><label className='ob-label'>6-digit code</label><input className='ob-input jn-otp-input' type='text' inputMode='numeric' maxLength={6} placeholder='000000' value={otp} onChange={e => setOtp(e.target.value.replace(/\\D/g, ''))} onKeyDown={e => e.key === 'Enter' && handleVerifyOtp()} autoFocus /></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              <button onClick={handleVerifyOtp} disabled={loading || otp.length !== 6} className='v4btn v4btn-amber jn-cta'>{loading ? 'Verifying\u2026' : 'Verify & continue \u2192'}</button>",
"              <div className='jn-link-row'>",
"                <button onClick={() => { setStep('email'); setOtp(''); setError(''); }} className='jn-link-btn'>\u2190 Change email</button>",
"                <button onClick={resendTimer === 0 ? handleSendOtp : undefined} disabled={resendTimer > 0} className='jn-link-btn' style={resendTimer === 0 ? { color: 'var(--v4-aDeep)' } : undefined}>{resendTimer > 0 ? `Resend in ${resendTimer}s` : 'Resend code'}</button>",
"              </div>",
"            </>)}",
"            {step === 'checking' && <div className='jn-spin'><div className='v4spinner' style={{ margin: '0 auto' }} /><div className='jn-spin-p'>Verifying\u2026</div></div>}",
"            {step === 'notfound' && (<>",
"              <div style={{ border: '1px solid var(--v4-line)', borderRadius: 10, padding: 14, marginBottom: 18, background: 'var(--v4-paper2)' }}><div style={{ fontSize: 12.5, color: 'var(--v4-tx60)', lineHeight: 1.7 }}>No wallet found for <strong>{email}</strong>. Create one?</div></div>",
"              {error && <div className='jn-err'>{error}</div>}",
"              <button onClick={handleCreate} className='v4btn v4btn-amber jn-cta'>Create new Circle wallet \u2192</button>",
"              <button onClick={() => setStep('email')} className='jn-link-btn' style={{ width: '100%' }}>\u2190 Try a different email</button>",
"            </>)}",
"            {step === 'creating' && <div className='jn-spin'><div className='v4spinner' style={{ margin: '0 auto' }} /><div className='jn-spin-p'>Creating wallet\u2026</div></div>}",
"            {(step === 'found' || step === 'done') && circleWallet && (",
"              <CircleWalletDashboard wallet={circleWallet} balance={balance} onLogout={() => { logout(); closeAll(); }} onClose={closeAll} />",
"            )}",
"          </div>",
"        </div>)}",
"",
"      {/* Circle Dashboard Modal */}",
"      {showDashboard && circleWallet && (",
"        <div className='pf-modal-bg' onClick={closeAll}>",
"          <div className='pf-modal nv-modal' style={{ maxWidth: 440 }} onClick={e => e.stopPropagation()}>",
"            <div className='nv-mhead'>",
"              <div><div className='jn-circle-l'>Circle \u00b7 USDC Wallet</div><div className='jn-circle-h' style={{ fontSize: 18 }}>{circleWallet.email}</div></div>",
"              <button onClick={closeAll} className='v4-cart-x' aria-label='Close'>\u2715</button>",
"            </div>",
"            <CircleWalletDashboard wallet={circleWallet} balance={balance} onLogout={() => { logout(); closeAll(); }} onClose={closeAll} />",
"          </div>",
"        </div>)}",
"",
"      <nav className={theme === 'v4' ? 'v-nav v4nav' : 'v-nav'}>",
"        <Link href='/' className='v-logo'><div className='v-logo-emblem'><span className='v-logo-v'>V</span></div><span className='v-logo-name'>Vendra</span></Link>",
"        <div className='v-nav-links'><Link href='/marketplace'>Marketplace</Link><Link href='/store/create'>Sell</Link>{isConnected&&<Link href='/profile'>Profile</Link>}</div>",
"        <div className='v-nav-right'>",
"          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{textDecoration:'none'}}><button className='btn-faucet'>\uD83D\uDCA7 Faucet</button></a>",
"          <CartButton/>",
"          {isConnected && <AppKitWidget />}",
"          {!isConnected && mounted && circleWallet && <CircleBalanceWidget wallet={circleWallet} />}",
"          {isConnected",
"            ? <ConnectButton accountStatus='address' chainStatus='none' showBalance={false}/>",
"            : mounted && circleWallet",
"              ? <button onClick={()=>{setShowDashboard(true);fetchBalance(circleWallet.walletId);}} className='btn-nav-amber' style={{display:'flex',alignItems:'center',gap:6}}>",
"                  <span>\u2B55</span><span>{shortAddr(circleWallet.address)}</span>",
"                </button>",
"              : <button onClick={()=>setShowLogin(true)} className='btn-nav-amber'>Log In</button>}",
"        </div>",
"      </nav>",
"    </>",
"  );",
"}",
""
].join("\n");

/* ---------------- CircleWalletDashboard.tsx ---------------- */
const DASH = [
"'use client';",
"import { useState, useCallback } from 'react';",
"",
"interface Props {",
"  wallet: { address: string; walletId: string; email: string };",
"  balance: string;",
"  onLogout: () => void;",
"  onClose: () => void;",
"}",
"",
"export default function CircleWalletDashboard({ wallet, balance, onLogout, onClose }: Props) {",
"  const [copied, setCopied] = useState(false);",
"  const [to, setTo] = useState('');",
"  const [amount, setAmount] = useState('');",
"  const [sending, setSending] = useState(false);",
"  const [sendResult, setSendResult] = useState('');",
"  const [error, setError] = useState('');",
"",
"  const handleCopy = useCallback(() => {",
"    navigator.clipboard.writeText(wallet.address);",
"    setCopied(true); setTimeout(() => setCopied(false), 2000);",
"  }, [wallet.address]);",
"",
"  const handleSend = async () => {",
"    if (!to || !amount) { setError('Fill in all fields'); return; }",
"    if (!to.startsWith('0x') || to.length !== 42) { setError('Invalid address'); return; }",
"    setSending(true); setSendResult(''); setError('');",
"    try {",
"      const res = await fetch('/api/circle/send', {",
"        method: 'POST',",
"        headers: { 'Content-Type': 'application/json' },",
"        body: JSON.stringify({ walletId: wallet.walletId, walletAddress: wallet.address, toAddress: to, amount }),",
"      });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      setSendResult('Sent! TX: ' + (data.txId || '').slice(0, 20) + '...');",
"      setTo(''); setAmount('');",
"    } catch (e:any) { setError(e.message || 'Send failed'); }",
"    finally { setSending(false); }",
"  };",
"",
"  return (",
"    <div>",
"      <div className='jn-wallet'>",
"        <div className='jn-wallet-l'>Circle wallet \u00b7 Arc Testnet</div>",
"        <div className='jn-addr-row'><div className='jn-addr'>{wallet.address}</div><button onClick={handleCopy} className={'jn-copy' + (copied ? ' done' : '')}>{copied ? '\u2713 Copied' : 'Copy'}</button></div>",
"        <div className='jn-bal-row'>",
"          <div><div className='jn-wallet-l' style={{ marginBottom: 2 }}>USDC balance</div><div className='jn-bal'>${parseFloat(balance || '0').toFixed(2)}</div></div>",
"          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ fontSize: 10, padding: '8px 12px' }}>Get USDC \u2197</a>",
"        </div>",
"      </div>",
"      <div className='ob-field'><label className='ob-label'>Send to address</label><input className='ob-input' placeholder='0x...' value={to} onChange={e => setTo(e.target.value)} autoComplete='off' /></div>",
"      <div className='ob-field'><label className='ob-label'>Amount (USDC)</label><input className='ob-input' type='number' placeholder='e.g. 5.00' value={amount} onChange={e => setAmount(e.target.value)} /></div>",
"      {error && <div className='jn-err'>{error}</div>}",
"      {sendResult && <div className='jn-ok'>{sendResult}</div>}",
"      <button onClick={handleSend} disabled={sending} className='v4btn v4btn-amber jn-cta'>{sending ? 'Sending\u2026' : 'Send USDC on Arc \u2192'}</button>",
"      <div className='jn-btn-row'>",
"        <a href={`https://testnet.arcscan.app/address/${wallet.address}`} target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost jn-sm' style={{ flex: 1 }}>Arc Explorer \u2197</a>",
"        <button onClick={onLogout} className='jn-logout' style={{ flex: 1 }}>Log out</button>",
"      </div>",
"    </div>",
"  );",
"}",
""
].join("\n");

/* ---------------- shared widget body builder (Circle = circle pill, AppKit = arc pill) ---------------- */
function widgetFile(opts) {
  // opts: { name, imports, pillIcon, balVar, addrExpr, fetchName, headLabel, depositText, bridgeText, walletScope }
  return opts;
}

/* ---------------- CircleBalanceWidget.tsx ---------------- */
const CBW = [
"'use client';",
"import { useState, useEffect } from 'react';",
"",
"type Tab = 'balance'|'deposit'|'bridge';",
"const CHAINS = [",
"  { id: 'Ethereum_Sepolia', label: 'Ethereum', logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png' },",
"  { id: 'Base_Sepolia', label: 'Base', logo: 'https://cryptologos.cc/logos/base-logo.png' },",
"  { id: 'Arbitrum_Sepolia', label: 'Arbitrum', logo: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png' },",
"  { id: 'Polygon_Amoy', label: 'Polygon', logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png' },",
"  { id: 'Solana_Devnet', label: 'Solana', logo: 'https://cryptologos.cc/logos/solana-sol-logo.png' },",
"];",
"const AMOUNTS = ['1','5','10','50'];",
"",
"interface Props { wallet: { address: string; walletId: string; email: string }; }",
"",
"export default function CircleBalanceWidget({ wallet }: Props) {",
"  const [open, setOpen] = useState(false);",
"  const [tab, setTab] = useState<Tab>('balance');",
"  const [balance, setBalance] = useState('0.00');",
"  const [copied, setCopied] = useState(false);",
"  const [fromChain, setFromChain] = useState('Ethereum_Sepolia');",
"  const [bridgeAmount, setBridgeAmount] = useState('10');",
"  const [bridgeLoading, setBridgeLoading] = useState(false);",
"  const [bridgeResult, setBridgeResult] = useState('');",
"  const [bridgeError, setBridgeError] = useState('');",
"",
"  useEffect(() => { fetchBalance(); }, [wallet.walletId]);",
"",
"  const fetchBalance = async () => {",
"    try {",
"      const res = await fetch('/api/circle/balance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ walletId: wallet.walletId }) });",
"      const data = await res.json();",
"      setBalance(parseFloat(data.balance || '0').toFixed(2));",
"    } catch {}",
"  };",
"",
"  const handleCopy = () => { navigator.clipboard.writeText(wallet.address); setCopied(true); setTimeout(() => setCopied(false), 2000); };",
"",
"  const handleBridge = async () => {",
"    if (!bridgeAmount) { setBridgeError('Enter an amount'); return; }",
"    setBridgeLoading(true); setBridgeError(''); setBridgeResult('');",
"    try {",
"      const res = await fetch('/api/circle/bridge', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fromChain, toChain: 'Arc_Testnet', amount: bridgeAmount, walletAddress: wallet.address, walletId: wallet.walletId }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      setBridgeResult('Bridge initiated! USDC is on its way to Arc Testnet.');",
"    } catch (e:any) { setBridgeError(e?.message || 'Bridge failed.'); }",
"    finally { setBridgeLoading(false); }",
"  };",
"",
"  const selectedChain = CHAINS.find(c => c.id === fromChain) || CHAINS[0];",
"  const tabs: {id:Tab;label:string}[] = [{ id: 'balance', label: 'Balance' }, { id: 'deposit', label: 'Deposit' }, { id: 'bridge', label: 'Bridge' }];",
"",
"  return (",
"    <div className='cw'>",
"      <button onClick={() => { setOpen(!open); if (!open) fetchBalance(); }} className='cw-pill'>",
"        <span>\u2B55</span><span className='cw-pill-amt'>${balance}</span><span className='cw-pill-u'>USDC</span><span className='cw-pill-ar' style={{ transform: open ? 'rotate(180deg)' : 'rotate(0)' }}>\u25BC</span>",
"      </button>",
"      {open && (<>",
"        <div onClick={() => setOpen(false)} className='cw-scrim' />",
"        <div className='cw-pop'>",
"          <div className='cw-pop-head'><div className='cw-pop-l'>Circle Wallet \u00b7 USDC</div><button onClick={() => setOpen(false)} className='cw-pop-x'>\u2715</button></div>",
"          <div className='cw-tabs'>{tabs.map(t => <button key={t.id} onClick={() => { setTab(t.id); setBridgeError(''); setBridgeResult(''); }} className={'cw-tab' + (tab === t.id ? ' on' : '')}>{t.label}</button>)}</div>",
"          <div className='cw-body'>",
"            {tab === 'balance' && (",
"              <div style={{ textAlign: 'center' }}>",
"                <div className='cw-bal-l'>Circle Wallet \u00b7 USDC Balance</div>",
"                <div className='cw-bal'>${balance}</div>",
"                <div className='cw-bal-sub'>USDC \u00b7 Arc Testnet</div>",
"                <div className='cw-row'><button onClick={() => setTab('deposit')} className='v4btn v4btn-amber' style={{ flex: 1, fontSize: 10, padding: 9, justifyContent: 'center' }}>Deposit \u2193</button><button onClick={() => setTab('bridge')} className='v4btn v4btn-ghost' style={{ flex: 1, fontSize: 10, padding: 9, justifyContent: 'center' }}>Bridge \uD83C\uDF09</button></div>",
"                <div className='cw-row' style={{ marginBottom: 0 }}><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ flex: 1, fontSize: 10, padding: 8, justifyContent: 'center' }}>\uD83D\uDCA7 Faucet</a><a href={`https://testnet.arcscan.app/address/${wallet.address}`} target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ flex: 1, fontSize: 10, padding: 8, justifyContent: 'center' }}>Explorer \u2197</a></div>",
"              </div>)}",
"            {tab === 'deposit' && (",
"              <div>",
"                <div className='cw-p'>Copy your Circle wallet address to receive USDC on Arc Testnet.</div>",
"                <div className='cw-addr-box'>",
"                  <div className='cw-addr-l'>Circle Wallet \u00b7 Arc Testnet</div>",
"                  <div className='cw-addr'>{wallet.address}</div>",
"                  <button onClick={handleCopy} className={'v4btn ' + (copied ? 'v4btn-amber' : 'v4btn-ink')} style={{ width: '100%', justifyContent: 'center', fontSize: 11, padding: 10 }}>{copied ? '\u2713 Address copied!' : 'Copy address'}</button>",
"                </div>",
"                <div className='cw-div'><div className='cw-div-line' /><span className='cw-div-txt'>or</span><div className='cw-div-line' /></div>",
"                <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ width: '100%', justifyContent: 'center', fontSize: 11, padding: 10 }}>\uD83D\uDCA7 Get free test USDC \u2197</a>",
"              </div>)}",
"            {tab === 'bridge' && (",
"              <div>",
"                <div className='cw-p'>Bridge USDC to your Circle wallet on Arc Testnet.</div>",
"                <div className='cw-lbl'>From chain</div>",
"                <div className='cw-chains'>{CHAINS.map(c => <button key={c.id} onClick={() => setFromChain(c.id)} className={'cw-chain' + (fromChain === c.id ? ' on' : '')}><img src={c.logo} alt={c.label} onError={e => { (e.target as HTMLImageElement).style.opacity = '0.3'; }} /><span className='cw-chain-n'>{c.label}</span></button>)}</div>",
"                <div className='cw-swap'>",
"                  <div className='cw-swap-box'><img src={selectedChain.logo} alt={selectedChain.label} onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }} /><span>{selectedChain.label}</span></div>",
"                  <span className='cw-swap-ar'>\u2192</span>",
"                  <div className='cw-swap-box dst'><span>Arc Testnet</span></div>",
"                </div>",
"                <div className='cw-lbl'>Amount (USDC)</div>",
"                <div className='cw-amts'>{AMOUNTS.map(a => <button key={a} onClick={() => setBridgeAmount(a)} className={'cw-amt' + (bridgeAmount === a ? ' on' : '')}>${a}</button>)}</div>",
"                <input className='ob-input' type='number' placeholder='Custom amount...' value={bridgeAmount} onChange={e => setBridgeAmount(e.target.value)} style={{ marginBottom: 12 }} />",
"                {bridgeError && <div className='jn-err'>{bridgeError}</div>}",
"                {bridgeResult && <div className='jn-ok'>{bridgeResult}</div>}",
"                <button onClick={handleBridge} disabled={bridgeLoading} className='v4btn v4btn-amber' style={{ width: '100%', justifyContent: 'center', fontSize: 11, padding: 11 }}>{bridgeLoading ? 'Bridging\u2026' : `Bridge $${bridgeAmount} USDC \u2192 Arc`}</button>",
"              </div>)}",
"          </div>",
"        </div>",
"      </>)}",
"    </div>",
"  );",
"}",
""
].join("\n");

/* ---------------- AppKitWidget.tsx ---------------- */
const AKW = [
"'use client';",
"import { useState, useEffect } from 'react';",
"import { useAccount } from 'wagmi';",
"",
"type Tab = 'balance'|'deposit'|'bridge';",
"const CHAINS = [",
"  { id: 'Ethereum_Sepolia', label: 'Ethereum', logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png' },",
"  { id: 'Base_Sepolia', label: 'Base', logo: 'https://cryptologos.cc/logos/base-logo.png' },",
"  { id: 'Arbitrum_Sepolia', label: 'Arbitrum', logo: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png' },",
"  { id: 'Polygon_Amoy', label: 'Polygon', logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png' },",
"  { id: 'Solana_Devnet', label: 'Solana', logo: 'https://cryptologos.cc/logos/solana-sol-logo.png' },",
"];",
"const AMOUNTS = ['1','5','10','50'];",
"",
"export default function AppKitWidget() {",
"  const { address, isConnected } = useAccount();",
"  const [open, setOpen] = useState(false);",
"  const [tab, setTab] = useState<Tab>('balance');",
"  const [mounted, setMounted] = useState(false);",
"  const [loading, setLoading] = useState(false);",
"  const [result, setResult] = useState('');",
"  const [error, setError] = useState('');",
"  const [copied, setCopied] = useState(false);",
"  const [fromChain, setFromChain] = useState('Ethereum_Sepolia');",
"  const [bridgeAmount, setBridgeAmount] = useState('10');",
"  const [usdcBalance, setUsdcBalance] = useState('0.00');",
"",
"  useEffect(() => { setMounted(true); }, []);",
"  useEffect(() => { if (mounted && isConnected && address) fetchUsdcBalance(); }, [mounted, isConnected, address]);",
"",
"  const fetchUsdcBalance = async () => {",
"    try {",
"      const res = await fetch('/api/arc/balance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ address }) });",
"      const data = await res.json();",
"      if (data.balance) setUsdcBalance(parseFloat(data.balance).toFixed(2));",
"    } catch {}",
"  };",
"",
"  const handleCopy = () => { if (!address) return; navigator.clipboard.writeText(address); setCopied(true); setTimeout(() => setCopied(false), 2000); };",
"",
"  const handleBridge = async () => {",
"    if (!bridgeAmount) { setError('Enter an amount'); return; }",
"    setLoading(true); setError(''); setResult('');",
"    try {",
"      const res = await fetch('/api/circle/bridge', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fromChain, toChain: 'Arc_Testnet', amount: bridgeAmount, walletAddress: address }) });",
"      const data = await res.json();",
"      if (data.error) throw new Error(data.error);",
"      setResult('Bridge initiated! USDC is on its way to Arc Testnet via CCTP.');",
"    } catch (e:any) { setError(e?.message || 'Bridge failed. Make sure you have USDC on the selected chain.'); }",
"    finally { setLoading(false); }",
"  };",
"",
"  if (!mounted || !isConnected) return null;",
"",
"  const selectedChain = CHAINS.find(c => c.id === fromChain) || CHAINS[0];",
"  const tabs: {id:Tab;label:string}[] = [{ id: 'balance', label: 'Balance' }, { id: 'deposit', label: 'Deposit' }, { id: 'bridge', label: 'Bridge' }];",
"",
"  return (",
"    <div className='cw'>",
"      <button onClick={() => { setOpen(!open); setError(''); setResult(''); if (!open) fetchUsdcBalance(); }} className='cw-pill'>",
"        <span>\uD83D\uDCB3</span><span className='cw-pill-amt'>${usdcBalance}</span><span className='cw-pill-u'>USDC</span><span className='cw-pill-ar' style={{ transform: open ? 'rotate(180deg)' : 'rotate(0)' }}>\u25BC</span>",
"      </button>",
"      {open && (<>",
"        <div onClick={() => setOpen(false)} className='cw-scrim' />",
"        <div className='cw-pop'>",
"          <div className='cw-pop-head'><div className='cw-pop-l'>Arc App Kit \u00b7 USDC</div><button onClick={() => setOpen(false)} className='cw-pop-x'>\u2715</button></div>",
"          <div className='cw-tabs'>{tabs.map(t => <button key={t.id} onClick={() => { setTab(t.id); setError(''); setResult(''); }} className={'cw-tab' + (tab === t.id ? ' on' : '')}>{t.label}</button>)}</div>",
"          <div className='cw-body'>",
"            {tab === 'balance' && (",
"              <div style={{ textAlign: 'center' }}>",
"                <div className='cw-bal-l'>Arc Testnet \u00b7 USDC Balance</div>",
"                <div className='cw-bal'>${usdcBalance}</div>",
"                <div className='cw-bal-sub'>USDC \u00b7 Arc Testnet</div>",
"                <div className='cw-row'><button onClick={() => setTab('deposit')} className='v4btn v4btn-amber' style={{ flex: 1, fontSize: 10, padding: 9, justifyContent: 'center' }}>Deposit \u2193</button><button onClick={() => setTab('bridge')} className='v4btn v4btn-ghost' style={{ flex: 1, fontSize: 10, padding: 9, justifyContent: 'center' }}>Bridge \uD83C\uDF09</button></div>",
"                <div className='cw-row' style={{ marginBottom: 0 }}><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ flex: 1, fontSize: 10, padding: 8, justifyContent: 'center' }}>\uD83D\uDCA7 Faucet</a><a href={`https://testnet.arcscan.app/address/${address}`} target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ flex: 1, fontSize: 10, padding: 8, justifyContent: 'center' }}>Explorer \u2197</a></div>",
"              </div>)}",
"            {tab === 'deposit' && (",
"              <div>",
"                <div className='cw-p'>Copy your Arc Testnet address to receive USDC, or get free test USDC from the faucet.</div>",
"                <div className='cw-addr-box'>",
"                  <div className='cw-addr-l'>Arc Testnet Address</div>",
"                  <div className='cw-addr'>{address}</div>",
"                  <button onClick={handleCopy} className={'v4btn ' + (copied ? 'v4btn-amber' : 'v4btn-ink')} style={{ width: '100%', justifyContent: 'center', fontSize: 11, padding: 10 }}>{copied ? '\u2713 Address copied!' : 'Copy address'}</button>",
"                </div>",
"                <div className='cw-div'><div className='cw-div-line' /><span className='cw-div-txt'>or</span><div className='cw-div-line' /></div>",
"                <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' className='v4btn v4btn-ghost' style={{ width: '100%', justifyContent: 'center', fontSize: 11, padding: 10 }}>\uD83D\uDCA7 Get free test USDC \u2197</a>",
"              </div>)}",
"            {tab === 'bridge' && (",
"              <div>",
"                <div className='cw-p'>Bridge USDC to Arc Testnet via Circle CCTP.</div>",
"                <div className='cw-lbl'>From chain</div>",
"                <div className='cw-chains'>{CHAINS.map(c => <button key={c.id} onClick={() => setFromChain(c.id)} className={'cw-chain' + (fromChain === c.id ? ' on' : '')}><img src={c.logo} alt={c.label} onError={e => { (e.target as HTMLImageElement).style.opacity = '0.3'; }} /><span className='cw-chain-n'>{c.label}</span></button>)}</div>",
"                <div className='cw-swap'>",
"                  <div className='cw-swap-box'><img src={selectedChain.logo} alt={selectedChain.label} onError={e => { (e.target as HTMLImageElement).style.display = 'none'; }} /><span>{selectedChain.label}</span></div>",
"                  <span className='cw-swap-ar'>\u2192</span>",
"                  <div className='cw-swap-box dst'><span>Arc Testnet</span></div>",
"                </div>",
"                <div className='cw-lbl'>Amount (USDC)</div>",
"                <div className='cw-amts'>{AMOUNTS.map(a => <button key={a} onClick={() => setBridgeAmount(a)} className={'cw-amt' + (bridgeAmount === a ? ' on' : '')}>${a}</button>)}</div>",
"                <input className='ob-input' type='number' placeholder='Custom amount...' value={bridgeAmount} onChange={e => setBridgeAmount(e.target.value)} style={{ marginBottom: 12 }} />",
"                {error && <div className='jn-err'>{error}</div>}",
"                {result && <div className='jn-ok'>{result}</div>}",
"                <button onClick={handleBridge} disabled={loading} className='v4btn v4btn-amber' style={{ width: '100%', justifyContent: 'center', fontSize: 11, padding: 11 }}>{loading ? 'Bridging\u2026' : `Bridge $${bridgeAmount} USDC \u2192 Arc`}</button>",
"              </div>)}",
"          </div>",
"        </div>",
"      </>)}",
"    </div>",
"  );",
"}",
""
].join("\n");

for (const [p, content, label] of [[navPath, NAV, 'app/Nav.tsx'], [dashPath, DASH, 'CircleWalletDashboard.tsx'], [cbwPath, CBW, 'CircleBalanceWidget.tsx'], [akwPath, AKW, 'AppKitWidget.tsx']]) {
  if (!fs.existsSync(p + '.v3bak')) { fs.copyFileSync(p, p + '.v3bak'); console.log('  .  backup -> ' + label + '.v3bak'); }
  fs.writeFileSync(p, content, 'utf8');
  console.log('  +  ' + label + ' rewritten in v4 (logic unchanged)');
}

const MARK = '/* === V4 NAV WALLET STYLES === */';
const CSS = [
MARK,
".v4home .nv-modal{max-height:88vh;overflow-y:auto;}",
".v4home .nv-mhead{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px;gap:12px;}",
".v4home .cw{position:relative;}",
".v4home .cw-pill{font-size:12px;font-weight:600;background:var(--v4-card);border:1px solid var(--v4-line2);color:var(--v4-tx);padding:7px 13px;border-radius:999px;cursor:pointer;display:flex;align-items:center;gap:7px;transition:.2s;}",
".v4home .cw-pill:hover{border-color:var(--v4-a);}",
".v4home .cw-pill-amt{font-weight:700;}",
".v4home .cw-pill-u{font-size:9px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .cw-pill-ar{font-size:8px;color:var(--v4-tx40);display:inline-block;transition:transform .2s;}",
".v4home .cw-scrim{position:fixed;inset:0;z-index:198;}",
".v4home .cw-pop{position:absolute;top:calc(100% + 8px);right:0;width:320px;background:var(--v4-paper);border:1px solid var(--v4-line2);border-radius:16px;z-index:199;box-shadow:0 20px 60px rgba(21,19,13,.18);overflow:hidden;}",
".v4home .cw-pop-head{padding:12px 16px;border-bottom:1px solid var(--v4-line);display:flex;justify-content:space-between;align-items:center;}",
".v4home .cw-pop-l{font-size:9px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-aDeep);}",
".v4home .cw-pop-x{background:transparent;border:none;color:var(--v4-tx40);cursor:pointer;font-size:13px;}",
".v4home .cw-pop-x:hover{color:var(--v4-ink);}",
".v4home .cw-tabs{display:flex;border-bottom:1px solid var(--v4-line);}",
".v4home .cw-tab{flex:1;font-size:9.5px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;padding:10px 4px;background:transparent;border:none;border-bottom:2px solid transparent;color:var(--v4-tx40);cursor:pointer;margin-bottom:-1px;transition:.2s;}",
".v4home .cw-tab.on{border-bottom-color:var(--v4-a);color:var(--v4-aDeep);}",
".v4home .cw-body{padding:16px;}",
".v4home .cw-bal-l{font-size:9px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-tx40);margin-bottom:4px;}",
".v4home .cw-bal{font-size:38px;font-weight:700;letter-spacing:-.02em;color:var(--v4-aDeep);line-height:1;margin-bottom:2px;}",
".v4home .cw-bal-sub{font-size:9px;color:var(--v4-tx40);margin-bottom:14px;}",
".v4home .cw-row{display:flex;gap:8px;margin-bottom:8px;}",
".v4home .cw-p{font-size:11.5px;color:var(--v4-tx60);line-height:1.7;margin-bottom:14px;}",
".v4home .cw-addr-box{border:1px solid var(--v4-line);background:var(--v4-paper2);border-radius:12px;padding:14px;margin-bottom:14px;}",
".v4home .cw-addr-l{font-size:9px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-aDeep);margin-bottom:6px;}",
".v4home .cw-addr{font-size:11px;color:var(--v4-tx60);word-break:break-all;margin-bottom:10px;}",
".v4home .cw-div{display:flex;align-items:center;gap:10px;margin-bottom:14px;}",
".v4home .cw-div-line{flex:1;height:1px;background:var(--v4-line);}",
".v4home .cw-div-txt{font-size:9px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .cw-chains{display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin-bottom:12px;}",
".v4home .cw-chain{padding:8px 2px;border:1px solid var(--v4-line);border-radius:10px;background:var(--v4-paper2);cursor:pointer;display:flex;flex-direction:column;align-items:center;gap:3px;transition:.2s;}",
".v4home .cw-chain.on{border-color:var(--v4-a);background:var(--v4-aSoft);}",
".v4home .cw-chain img{width:22px;height:22px;border-radius:50%;object-fit:cover;}",
".v4home .cw-chain-n{font-size:7px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;color:var(--v4-tx40);}",
".v4home .cw-chain.on .cw-chain-n{color:var(--v4-aDeep);}",
".v4home .cw-swap{display:flex;align-items:center;gap:8px;margin-bottom:12px;}",
".v4home .cw-swap-box{flex:1;display:flex;align-items:center;gap:6px;border:1px solid var(--v4-line);border-radius:10px;padding:8px 10px;background:var(--v4-paper2);}",
".v4home .cw-swap-box.dst{border-color:var(--v4-aSoft2);background:var(--v4-aSoft);}",
".v4home .cw-swap-box img{width:18px;height:18px;border-radius:50%;object-fit:cover;}",
".v4home .cw-swap-box span{font-size:10px;color:var(--v4-tx60);}",
".v4home .cw-swap-ar{color:var(--v4-aDeep);font-size:16px;}",
".v4home .cw-lbl{font-size:9px;font-weight:600;letter-spacing:.14em;text-transform:uppercase;color:var(--v4-tx40);margin-bottom:8px;}",
".v4home .cw-amts{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin-bottom:8px;}",
".v4home .cw-amt{font-size:14px;font-weight:700;padding:8px 4px;text-align:center;border:1px solid var(--v4-line);border-radius:10px;background:var(--v4-paper2);color:var(--v4-tx60);cursor:pointer;transition:.2s;}",
".v4home .cw-amt.on{border-color:var(--v4-a);background:var(--v4-aSoft);color:var(--v4-aDeep);}",
""
].join("\n");

let css = fs.readFileSync(cssPath, 'utf8');
const i = css.indexOf(MARK);
if (i !== -1) { css = css.slice(0, i).replace(/\s+$/, '') + '\n\n'; }
css = css.replace(/\s+$/, '') + '\n\n' + CSS;
fs.writeFileSync(cssPath, css, 'utf8');
console.log('  +  v4 nav + wallet styles appended to globals.css');
console.log('\n  Done. npm run build -> npm run dev -> click Log In + the wallet pill. Then git push.\n');
