const fs = require('fs');
let nav = fs.readFileSync('app/Nav.tsx', 'utf8');

// Show AppKitWidget only for Web3 connected users (it requires wagmi)
// For Circle wallet users, show a simple balance display instead
nav = nav.replace(
  "          {isConnected&&<AppKitWidget/>}",
  "          {isConnected && <AppKitWidget />}"
);

fs.writeFileSync('app/Nav.tsx', nav, 'utf8');
console.log('Nav updated');

// Also add a CircleBalanceDisplay component for Circle wallet users in nav
const lines = [];
lines.push("'use client';");
lines.push("import { useState, useEffect } from 'react';");
lines.push("");
lines.push("const STORAGE_KEY = 'vendra_circle_wallet';");
lines.push("");
lines.push("export default function CircleBalanceDisplay() {");
lines.push("  const [wallet, setWallet] = useState<any>(null);");
lines.push("  const [balance, setBalance] = useState('0');");
lines.push("  const [open, setOpen] = useState(false);");
lines.push("  const [mounted, setMounted] = useState(false);");
lines.push("  const [sending, setSending] = useState(false);");
lines.push("  const [sendForm, setSendForm] = useState({ to: '', amount: '' });");
lines.push("  const [sendResult, setSendResult] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [copied, setCopied] = useState(false);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    setMounted(true);");
lines.push("    try {");
lines.push("      const saved = sessionStorage.getItem(STORAGE_KEY);");
lines.push("      if (saved) {");
lines.push("        const w = JSON.parse(saved);");
lines.push("        setWallet(w);");
lines.push("        fetchBalance(w.walletId);");
lines.push("      }");
lines.push("    } catch {}");
lines.push("  }, []);");
lines.push("");
lines.push("  const fetchBalance = async (walletId: string) => {");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/balance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ walletId }) });");
lines.push("      const data = await res.json();");
lines.push("      setBalance(data.balance || '0');");
lines.push("    } catch {}");
lines.push("  };");
lines.push("");
lines.push("  const handleCopy = () => {");
lines.push("    if (!wallet) return;");
lines.push("    navigator.clipboard.writeText(wallet.address);");
lines.push("    setCopied(true);");
lines.push("    setTimeout(() => setCopied(false), 2000);");
lines.push("  };");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!sendForm.to || !sendForm.amount || !wallet) return;");
lines.push("    setSending(true); setSendResult(''); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ walletId: wallet.walletId, walletAddress: wallet.address, toAddress: sendForm.to, amount: sendForm.amount }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setSendResult('Sent! TX: ' + (data.txId || '').slice(0, 16) + '...');");
lines.push("      await fetchBalance(wallet.walletId);");
lines.push("    } catch (e: any) { setError(e.message || 'Send failed'); }");
lines.push("    finally { setSending(false); }");
lines.push("  };");
lines.push("");
lines.push("  if (!mounted || !wallet) return null;");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ position: 'relative' }}>");
lines.push("      <button onClick={() => { setOpen(!open); setError(''); setSendResult(''); }} style={{ fontFamily: \"'DM Sans',sans-serif\", fontSize: 11, fontWeight: 400, letterSpacing: '0.10em', background: 'var(--bg2)', border: '1px solid var(--b2)', color: 'var(--sl2)', padding: '8px 14px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8, transition: 'all 0.3s' }} onMouseEnter={e => (e.currentTarget.style.borderColor = 'var(--sl)')} onMouseLeave={e => (e.currentTarget.style.borderColor = 'var(--b2)')}>"); 
lines.push("        <span>⭕</span>");
lines.push("        <span style={{ fontFamily: \"'Cormorant',serif\", fontSize: 16, fontWeight: 300 }}>${balance}</span>");
lines.push("        <span style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.10em', textTransform: 'uppercase', color: 'var(--w18)' }}>USDC</span>");
lines.push("        <span style={{ fontSize: 8, color: 'var(--w18)', display: 'inline-block', transform: open ? 'rotate(180deg)' : 'rotate(0)' }}>▼</span>");
lines.push("      </button>");
lines.push("      {open && (");
lines.push("        <>");
lines.push("          <div onClick={() => setOpen(false)} style={{ position: 'fixed', inset: 0, zIndex: 98 }} />");
lines.push("          <div style={{ position: 'absolute', top: 'calc(100% + 8px)', right: 0, width: 300, background: 'var(--bg2)', border: '1px solid var(--b2)', zIndex: 99, boxShadow: '0 20px 60px rgba(0,0,0,0.6)', overflow: 'hidden' }}>");
lines.push("            <div style={{ position: 'absolute', top: 0, left: '10%', right: '10%', height: 1, background: 'linear-gradient(90deg,transparent,rgba(155,181,200,0.5),transparent)' }} />");
lines.push("            <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--b1)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>");
lines.push("              <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--sl)' }}>Circle Wallet · Arc Testnet</div>");
lines.push("              <button onClick={() => setOpen(false)} style={{ background: 'transparent', border: 'none', color: 'var(--w18)', cursor: 'pointer' }}>✕</button>");
lines.push("            </div>");
lines.push("            <div style={{ padding: 16 }}>");
lines.push("              <div style={{ textAlign: 'center', marginBottom: 16 }}>");
lines.push("                <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--w18)', marginBottom: 4 }}>USDC Balance</div>");
lines.push("                <div style={{ fontFamily: \"'Cormorant',serif\", fontSize: 44, fontWeight: 300, color: 'var(--sl2)', lineHeight: 1 }}>${balance}</div>");
lines.push("              </div>");
lines.push("              <div style={{ border: '1px solid var(--b1)', padding: '10px 12px', marginBottom: 14, background: 'var(--bg3)' }}>");
lines.push("                <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--w18)', marginBottom: 4 }}>Wallet Address</div>");
lines.push("                <div style={{ fontFamily: \"'Cormorant',serif\", fontSize: 11, fontWeight: 300, color: 'var(--sl)', wordBreak: 'break-all', marginBottom: 8 }}>{wallet.address}</div>");
lines.push("                <button onClick={handleCopy} style={{ fontFamily: \"'DM Sans',sans-serif\", fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.12em', textTransform: 'uppercase', border: '1px solid var(--b2)', color: copied ? 'var(--gr)' : 'var(--w35)', padding: '5px 10px', background: 'transparent', cursor: 'pointer', width: '100%', transition: 'all 0.3s' }}>{copied ? '✓ Copied!' : 'Copy Address'}</button>");
lines.push("              </div>");
lines.push("              <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--w18)', marginBottom: 8 }}>Send USDC</div>");
lines.push("              <div className='v-field'><label className='v-label'>Recipient</label><input className='v-input' placeholder='0x...' value={sendForm.to} onChange={e => setSendForm({ ...sendForm, to: e.target.value })} /></div>");
lines.push("              <div className='v-field'><label className='v-label'>Amount</label><input className='v-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e => setSendForm({ ...sendForm, amount: e.target.value })} /></div>");
lines.push("              {error && <div style={{ fontSize: 10, fontStyle: 'italic', color: 'var(--err)', marginBottom: 10, border: '1px solid rgba(232,112,112,0.2)', padding: '7px 10px' }}>{error}</div>}");
lines.push("              {sendResult && <div style={{ fontSize: 10, fontStyle: 'italic', color: 'var(--gr)', marginBottom: 10, border: '1px solid var(--gr3)', padding: '7px 10px', wordBreak: 'break-all' }}>{sendResult}</div>}");
lines.push("              <button onClick={handleSend} disabled={sending} className='btn-primary' style={{ width: '100%', padding: '10px', fontSize: 10, marginBottom: 8 }}>{sending ? 'Sending...' : 'Send USDC →'}</button>");
lines.push("              <div style={{ display: 'flex', gap: 8 }}>");
lines.push("                <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{ flex: 1 }}><button className='btn-ghost' style={{ width: '100%', fontSize: 9, padding: '8px' }}>Get USDC ↗</button></a>");
lines.push("                <a href={`https://testnet.arcscan.app/address/${wallet.address}`} target='_blank' rel='noopener noreferrer' style={{ flex: 1 }}><button className='btn-ghost' style={{ width: '100%', fontSize: 9, padding: '8px' }}>Explorer ↗</button></a>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </>");
lines.push("      )}");
lines.push("    </div>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/components/CircleBalanceDisplay.tsx', lines.join('\n'), 'utf8');
console.log('CircleBalanceDisplay done');
