const fs = require('fs');

// ── Shared OTP store ──────────────────────────────────────────────────────────
fs.mkdirSync('app/lib', { recursive: true });
const store = [];
store.push("// Shared OTP store — single source of truth");
store.push("declare global { var vendraOtpStore: Map<string, { otp: string; expires: number }> }");
store.push("if (!global.vendraOtpStore) global.vendraOtpStore = new Map();");
store.push("export const otpStore = global.vendraOtpStore;");
store.push("");
store.push("export function setOtp(email: string, otp: string) {");
store.push("  global.vendraOtpStore.set(email.toLowerCase().trim(), {");
store.push("    otp,");
store.push("    expires: Date.now() + 10 * 60 * 1000,");
store.push("  });");
store.push("}");
store.push("");
store.push("export function verifyOtp(email: string, otp: string): { success: boolean; error?: string } {");
store.push("  const key = email.toLowerCase().trim();");
store.push("  const stored = global.vendraOtpStore.get(key);");
store.push("  if (!stored) return { success: false, error: 'No code found. Please request a new one.' };");
store.push("  if (Date.now() > stored.expires) {");
store.push("    global.vendraOtpStore.delete(key);");
store.push("    return { success: false, error: 'Code expired. Please request a new one.' };");
store.push("  }");
store.push("  if (stored.otp !== otp.trim()) return { success: false, error: 'Incorrect code. Please try again.' };");
store.push("  global.vendraOtpStore.delete(key);");
store.push("  return { success: true };");
store.push("}");
fs.writeFileSync('app/lib/otp.ts', store.join('\n'), 'utf8');
console.log('OTP store done');

// ── Fix send-otp route ────────────────────────────────────────────────────────
fs.mkdirSync('app/api/circle/send-otp', { recursive: true });
const send = [];
send.push("import { NextRequest, NextResponse } from 'next/server';");
send.push("import { Resend } from 'resend';");
send.push("import { setOtp } from '../../../lib/otp';");
send.push("");
send.push("const resend = new Resend(process.env.RESEND_API_KEY);");
send.push("");
send.push("export async function POST(req: NextRequest) {");
send.push("  try {");
send.push("    const { email } = await req.json();");
send.push("    if (!email) return NextResponse.json({ error: 'Email required' }, { status: 400 });");
send.push("    const otp = Math.floor(100000 + Math.random() * 900000).toString();");
send.push("    setOtp(email, otp);");
send.push("    await resend.emails.send({");
send.push("      from: 'Vendra <noreply@vendramarket.xyz>',");
send.push("      to: email,");
send.push("      subject: 'Your Vendra Login Code — ' + otp,");
send.push("      html: `<div style='font-family:Georgia,serif;max-width:480px;margin:0 auto;background:#0C0E1A;color:#fff8eb;padding:40px;'><div style='font-size:24px;font-weight:300;letter-spacing:0.22em;text-transform:uppercase;margin-bottom:8px;'>Vendra</div><div style='height:1px;background:linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent);margin-bottom:32px;'></div><div style='font-size:14px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.55);margin-bottom:24px;line-height:1.7;'>Your one-time login code for Vendra. Expires in 10 minutes.</div><div style='background:rgba(212,176,90,0.08);border:1px solid rgba(212,176,90,0.3);padding:24px;text-align:center;margin-bottom:24px;'><div style='font-size:11px;font-weight:300;font-style:italic;letter-spacing:0.18em;text-transform:uppercase;color:rgba(255,248,235,0.42);margin-bottom:8px;'>Your Login Code</div><div style='font-size:48px;font-weight:300;letter-spacing:0.2em;color:#EAC96E;'>${otp}</div></div><div style='font-size:11px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.35);line-height:1.7;'>If you didn't request this, ignore this email. Never share this code.</div><div style='height:1px;background:rgba(255,255,255,0.06);margin:24px 0;'></div><div style='font-size:10px;color:rgba(255,248,235,0.25);'>Vendra · Arc Testnet · USDC</div></div>`");
send.push("    });");
send.push("    return NextResponse.json({ success: true });");
send.push("  } catch (e: any) {");
send.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
send.push("  }");
send.push("}");
fs.writeFileSync('app/api/circle/send-otp/route.ts', send.join('\n'), 'utf8');
console.log('send-otp done');

// ── Fix verify-otp route ──────────────────────────────────────────────────────
fs.mkdirSync('app/api/circle/verify-otp', { recursive: true });
const verify = [];
verify.push("import { NextRequest, NextResponse } from 'next/server';");
verify.push("import { verifyOtp } from '../../../lib/otp';");
verify.push("");
verify.push("export async function POST(req: NextRequest) {");
verify.push("  try {");
verify.push("    const { email, otp } = await req.json();");
verify.push("    if (!email || !otp) return NextResponse.json({ error: 'Email and code required' }, { status: 400 });");
verify.push("    const result = verifyOtp(email, otp);");
verify.push("    if (!result.success) return NextResponse.json({ error: result.error }, { status: 400 });");
verify.push("    return NextResponse.json({ success: true, verified: true });");
verify.push("  } catch (e: any) {");
verify.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
verify.push("  }");
verify.push("}");
fs.writeFileSync('app/api/circle/verify-otp/route.ts', verify.join('\n'), 'utf8');
console.log('verify-otp done');

console.log('\nAll OTP files fixed!');
