const fs = require('fs');
const send = [];
send.push("import { NextRequest, NextResponse } from 'next/server';");
send.push("import { initiateDeveloperControlledWalletsClient } from '@circle-fin/developer-controlled-wallets';");
send.push("");
send.push("export async function POST(req: NextRequest) {");
send.push("  try {");
send.push("    const { walletId, walletAddress, toAddress, amount } = await req.json();");
send.push("    if (!walletId || !toAddress || !amount) return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });");
send.push("    if (!toAddress.startsWith('0x') || toAddress.length !== 42) return NextResponse.json({ error: 'Invalid recipient address' }, { status: 400 });");
send.push("    const numAmount = parseFloat(amount);");
send.push("    if (isNaN(numAmount) || numAmount <= 0) return NextResponse.json({ error: 'Invalid amount' }, { status: 400 });");
send.push("    const client = initiateDeveloperControlledWalletsClient({");
send.push("      apiKey: process.env.CIRCLE_API_KEY!,");
send.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
send.push("    });");
send.push("    const tx = (await client.createTransaction({");
send.push("      walletId,");
send.push("      blockchain: 'ARC-TESTNET' as any,");
send.push("      destinationAddress: toAddress,");
send.push("      amount: [numAmount.toFixed(6)],");
send.push("      tokenAddress: '0x3600000000000000000000000000000000000000',");
send.push("      fee: { type: 'level', config: { feeLevel: 'MEDIUM' } },");
send.push("    } as any)).data;");
send.push("    return NextResponse.json({ txId: tx?.id, state: tx?.state, success: true });");
send.push("  } catch (e: any) {");
send.push("    console.error('Send error:', e.message);");
send.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
send.push("  }");
send.push("}");
fs.writeFileSync('app/api/circle/send/route.ts', send.join('\n'), 'utf8');
console.log('Send route fixed');
