const fs = require('fs');

// Fix the send route — Circle API parameter issues
const send = [];
send.push("import { NextRequest, NextResponse } from 'next/server';");
send.push("import { initiateDeveloperControlledWalletsClient } from '@circle-fin/developer-controlled-wallets';");
send.push("");
send.push("export async function POST(req: NextRequest) {");
send.push("  try {");
send.push("    const { walletId, walletAddress, toAddress, amount } = await req.json();");
send.push("    if (!walletId || !walletAddress || !toAddress || !amount) {");
send.push("      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });");
send.push("    }");
send.push("    if (!toAddress.startsWith('0x') || toAddress.length !== 42) {");
send.push("      return NextResponse.json({ error: 'Invalid recipient address' }, { status: 400 });");
send.push("    }");
send.push("    const numAmount = parseFloat(amount);");
send.push("    if (isNaN(numAmount) || numAmount <= 0) {");
send.push("      return NextResponse.json({ error: 'Invalid amount' }, { status: 400 });");
send.push("    }");
send.push("    const client = initiateDeveloperControlledWalletsClient({");
send.push("      apiKey: process.env.CIRCLE_API_KEY!,");
send.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
send.push("    });");
send.push("    // Send native USDC on Arc Testnet");
send.push("    const tx = (await client.createTransaction({");
send.push("      walletId,");
send.push("      blockchain: 'ARC-TESTNET' as any,");
send.push("      destinationAddress: toAddress,");
send.push("      nativeAmount: numAmount.toFixed(6),");
send.push("      fee: { type: 'level', config: { feeLevel: 'MEDIUM' } },");
send.push("    })).data;");
send.push("    return NextResponse.json({ txId: tx?.id, state: tx?.state, success: true });");
send.push("  } catch (e: any) {");
send.push("    console.error('Send error:', e.message);");
send.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
send.push("  }");
send.push("}");
fs.writeFileSync('app/api/circle/send/route.ts', send.join('\n'), 'utf8');
console.log('Send route fixed');

// Fix balance route — use native balance for Arc USDC
const balance = [];
balance.push("import { NextRequest, NextResponse } from 'next/server';");
balance.push("import { initiateDeveloperControlledWalletsClient } from '@circle-fin/developer-controlled-wallets';");
balance.push("");
balance.push("export async function POST(req: NextRequest) {");
balance.push("  try {");
balance.push("    const { walletId } = await req.json();");
balance.push("    if (!walletId) return NextResponse.json({ error: 'walletId required' }, { status: 400 });");
balance.push("    const client = initiateDeveloperControlledWalletsClient({");
balance.push("      apiKey: process.env.CIRCLE_API_KEY!,");
balance.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
balance.push("    });");
balance.push("    const balances = (await client.getWalletTokenBalance({ id: walletId })).data?.tokenBalances || [];");
balance.push("    // Arc USDC is the native token — find it");
balance.push("    const usdc = balances.find((b: any) =>");
balance.push("      b.token?.symbol === 'USDC' ||");
balance.push("      b.token?.symbol === 'ARC' ||");
balance.push("      b.token?.isNative === true");
balance.push("    );");
balance.push("    const bal = usdc?.amount || '0';");
balance.push("    return NextResponse.json({ balance: bal, balances, raw: balances });");
balance.push("  } catch (e: any) {");
balance.push("    console.error('Balance error:', e.message);");
balance.push("    return NextResponse.json({ error: e.message, balance: '0' }, { status: 500 });");
balance.push("  }");
balance.push("}");
fs.writeFileSync('app/api/circle/balance/route.ts', balance.join('\n'), 'utf8');
console.log('Balance route fixed');

console.log('\nAll fixes done!');
