const fs = require('fs');

// Completely rewrite AppKitWidget to fix bridge not showing
// The issue is it imports from @circle-fin/adapter-viem-v2 at top level
// which causes issues. Use dynamic import instead.
const lines = [];
lines.push("'use client';");
lines.push("import { useState, useEffect } from 'react';");
lines.push("import { useAccount, useWalletClient } from 'wagmi';");
lines.push("");
lines.push("type Tab = 'balance'|'deposit'|'bridge';");
lines.push("const CHAINS = [");
lines.push("  { id:'Ethereum_Sepolia', label:'Ethereum', logo:'https://cryptologos.cc/logos/ethereum-eth-logo.png' },");
lines.push("  { id:'Base_Sepolia', label:'Base', logo:'https://cryptologos.cc/logos/base-logo.png' },");
lines.push("  { id:'Arbitrum_Sepolia', label:'Arbitrum', logo:'https://cryptologos.cc/logos/arbitrum-arb-logo.png' },");
lines.push("  { id:'Polygon_Amoy', label:'Polygon', logo:'https://cryptologos.cc/logos/polygon-matic-logo.png' },");
lines.push("  { id:'Solana_Devnet', label:'Solana', logo:'https://cryptologos.cc/logos/solana-sol-logo.png' },");
lines.push("];");
lines.push("const AMOUNTS = ['1','5','10','50'];");
lines.push("const ARC_USDC = '0x3600000000000000000000000000000000000000' as `0x${string}`;");
lines.push("");
lines.push("export default function AppKitWidget() {");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const { data: walletClient } = useWalletClient();");
lines.push("  const [open, setOpen] = useState(false);");
lines.push("  const [tab, setTab] = useState<Tab>('balance');");
lines.push("  const [mounted, setMounted] = useState(false);");
lines.push("  const [loading, setLoading] = useState(false);");
lines.push("  const [result, setResult] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [copied, setCopied] = useState(false);");
lines.push("  const [fromChain, setFromChain] = useState('Ethereum_Sepolia');");
lines.push("  const [bridgeAmount, setBridgeAmount] = useState('10');");
lines.push("  const [usdcBalance, setUsdcBalance] = useState('0.00');");
lines.push("");
lines.push("  useEffect(() => { setMounted(true); }, []);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    if (mounted && isConnected && address) fetchUsdcBalance();");
lines.push("  }, [mounted, isConnected, address]);");
lines.push("");
lines.push("  const fetchUsdcBalance = async () => {");
lines.push("    try {");
lines.push("      const res = await fetch('/api/arc/balance', {");
lines.push("        method: 'POST',");
lines.push("        headers: { 'Content-Type': 'application/json' },");
lines.push("        body: JSON.stringify({ address }),");
lines.push("      });");
lines.push("      const data = await res.json();");
lines.push("      if (data.balance) setUsdcBalance(parseFloat(data.balance).toFixed(2));");
lines.push("    } catch {}");
lines.push("  };");
lines.push("");
lines.push("  const handleCopy = () => {");
lines.push("    if (!address) return;");
lines.push("    navigator.clipboard.writeText(address);");
lines.push("    setCopied(true); setTimeout(() => setCopied(false), 2000);");
lines.push("  };");
lines.push("");
lines.push("  const handleBridge = async () => {");
lines.push("    if (!bridgeAmount) { setError('Enter an amount'); return; }");
lines.push("    if (!walletClient) { setError('Wallet not connected'); return; }");
lines.push("    setLoading(true); setError(''); setResult('');");
lines.push("    try {");
lines.push("      const { ViemAdapter } = await import('@circle-fin/adapter-viem-v2');");
lines.push("      const { AppKit } = await import('@circle-fin/app-kit');");
lines.push("      const adapter = new ViemAdapter({ walletClient } as any);");
lines.push("      const kit = new AppKit();");
lines.push("      await (kit as any).bridge({");
lines.push("        from: { adapter, chain: fromChain },");
lines.push("        to: { adapter, chain: 'Arc_Testnet' },");
lines.push("        amount: bridgeAmount,");
lines.push("        token: 'USDC',");
lines.push("      });");
lines.push("      setResult('Bridge initiated! USDC is on its way to Arc Testnet.');");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message || 'Bridge failed. Make sure you have USDC on the selected chain.');");
lines.push("    } finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  if (!mounted || !isConnected) return null;");
lines.push("");
lines.push("  const selectedChain = CHAINS.find(c => c.id === fromChain) || CHAINS[0];");
lines.push("  const tabs: {id:Tab;label:string}[] = [{ id:'balance', label:'Balance' },{ id:'deposit', label:'Deposit' },{ id:'bridge', label:'Bridge' }];");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ position:'relative' }}>");
lines.push("      <button onClick={() => { setOpen(!open); setError(''); setResult(''); if(!open) fetchUsdcBalance(); }} style={{ fontFamily:\"'DM Sans',sans-serif\", fontSize:11, fontWeight:400, background:'var(--bg2)', border:'1px solid var(--b2)', color:'var(--a2)', padding:'8px 14px', cursor:'pointer', display:'flex', alignItems:'center', gap:8, transition:'all 0.3s' }} onMouseEnter={e=>(e.currentTarget.style.borderColor='var(--a)')} onMouseLeave={e=>(e.currentTarget.style.borderColor='var(--b2)')}>"); 
lines.push("        <span style={{fontSize:'0.8rem'}}>💳</span>");
lines.push("        <span style={{fontFamily:\"'Cormorant',serif\",fontSize:16,fontWeight:300}}>${usdcBalance}</span>");
lines.push("        <span style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.10em',textTransform:'uppercase',color:'var(--w18)'}}>USDC</span>");
lines.push("        <span style={{fontSize:8,color:'var(--w18)',display:'inline-block',transform:open?'rotate(180deg)':'rotate(0)'}}>▼</span>");
lines.push("      </button>");
lines.push("      {open && (");
lines.push("        <>");
lines.push("          <div onClick={()=>setOpen(false)} style={{position:'fixed',inset:0,zIndex:98}}/>");
lines.push("          <div style={{position:'absolute',top:'calc(100% + 8px)',right:0,width:320,background:'var(--bg2)',border:'1px solid var(--b2)',zIndex:99,boxShadow:'0 20px 60px rgba(0,0,0,0.6)',overflow:'hidden'}}>");
lines.push("            <div style={{position:'absolute',top:0,left:'10%',right:'10%',height:1,background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.5),transparent)'}}/>");
lines.push("            <div style={{padding:'12px 16px',borderBottom:'1px solid var(--b1)',display:'flex',justifyContent:'space-between',alignItems:'center'}}>");
lines.push("              <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--a)'}}>Arc App Kit · USDC</div>");
lines.push("              <button onClick={()=>setOpen(false)} style={{background:'transparent',border:'none',color:'var(--w18)',cursor:'pointer'}}>✕</button>");
lines.push("            </div>");
lines.push("            <div style={{display:'flex',borderBottom:'1px solid var(--b1)'}}>");
lines.push("              {tabs.map(t=><button key={t.id} onClick={()=>{setTab(t.id);setError('');setResult('');}} style={{flex:1,fontFamily:\"'DM Sans',sans-serif\",fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.12em',textTransform:'uppercase',padding:'10px 4px',background:'transparent',border:'none',borderBottom:tab===t.id?'1px solid var(--a)':'1px solid transparent',color:tab===t.id?'var(--a)':'var(--w18)',cursor:'pointer',transition:'all 0.2s'}}>{t.label}</button>)}");
lines.push("            </div>");
lines.push("            <div style={{padding:16}}>");
lines.push("              {tab==='balance' && (");
lines.push("                <div style={{textAlign:'center'}}>");
lines.push("                  <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--w18)',marginBottom:4}}>Arc Testnet · USDC Balance</div>");
lines.push("                  <div style={{fontFamily:\"'Cormorant',serif\",fontSize:40,fontWeight:300,color:'var(--a2)',lineHeight:1,marginBottom:2}}>${usdcBalance}</div>");
lines.push("                  <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',color:'var(--w18)',marginBottom:14}}>USDC · Arc Testnet</div>");
lines.push("                  <div style={{display:'flex',gap:8,marginBottom:8}}>");
lines.push("                    <button onClick={()=>setTab('deposit')} className='btn-primary' style={{flex:1,fontSize:9,padding:'9px'}}>Deposit ↓</button>");
lines.push("                    <button onClick={()=>setTab('bridge')} className='btn-ghost' style={{flex:1,fontSize:9,padding:'9px'}}>Bridge 🌉</button>");
lines.push("                  </div>");
lines.push("                  <div style={{display:'flex',gap:8}}>");
lines.push("                    <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{flex:1}}><button className='btn-ghost' style={{width:'100%',fontSize:9,padding:'8px'}}>💧 Faucet</button></a>");
lines.push("                    <a href={`https://testnet.arcscan.app/address/${address}`} target='_blank' rel='noopener noreferrer' style={{flex:1}}><button className='btn-ghost' style={{width:'100%',fontSize:9,padding:'8px'}}>Explorer ↗</button></a>");
lines.push("                  </div>");
lines.push("                </div>)}");
lines.push("              {tab==='deposit' && (");
lines.push("                <div>");
lines.push("                  <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.7,marginBottom:14}}>Copy your Arc Testnet address to receive USDC, or get free test USDC from the faucet.</div>");
lines.push("                  <div style={{border:'1px solid var(--b1)',background:'var(--bg3)',padding:'14px',marginBottom:14}}>");
lines.push("                    <div style={{display:'flex',alignItems:'center',gap:8,marginBottom:8}}>");
lines.push("                      <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--a)'}}>Arc Testnet Address</div>");
lines.push("                    </div>");
lines.push("                    <div style={{fontFamily:\"'Cormorant',serif\",fontSize:11,fontWeight:300,color:'var(--w60)',wordBreak:'break-all',marginBottom:10}}>{address}</div>");
lines.push("                    <button onClick={handleCopy} className={copied?'btn-primary':'btn-amber-ghost'} style={{width:'100%',fontSize:10,padding:'10px'}}>{copied?'✓ Address Copied!':'Copy Address'}</button>");
lines.push("                  </div>");
lines.push("                  <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:14}}><div style={{flex:1,height:1,background:'var(--b1)'}}/><span style={{fontSize:9,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.12em',textTransform:'uppercase'}}>or</span><div style={{flex:1,height:1,background:'var(--b1)'}}/></div>");
lines.push("                  <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-ghost' style={{width:'100%',fontSize:10,padding:'10px'}}>💧 Get Free Test USDC ↗</button></a>");
lines.push("                </div>)}");
lines.push("              {tab==='bridge' && (");
lines.push("                <div>");
lines.push("                  <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.7,marginBottom:12}}>Bridge USDC to Arc Testnet via Circle CCTP.</div>");
lines.push("                  <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--w18)',marginBottom:8}}>From Chain</div>");
lines.push("                  <div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:4,marginBottom:12}}>");
lines.push("                    {CHAINS.map(c=><button key={c.id} onClick={()=>setFromChain(c.id)} style={{padding:'8px 2px',textAlign:'center',background:fromChain===c.id?'rgba(212,176,90,0.12)':'var(--bg3)',border:fromChain===c.id?'1px solid var(--a)':'1px solid var(--b1)',cursor:'pointer',transition:'all 0.2s',display:'flex',flexDirection:'column',alignItems:'center',gap:3}}>");
lines.push("                      <img src={c.logo} alt={c.label} style={{width:22,height:22,borderRadius:'50%',objectFit:'cover',border:'1px solid var(--b1)'}} onError={e=>{(e.target as HTMLImageElement).style.opacity='0.3';}}/>");
lines.push("                      <span style={{fontFamily:\"'DM Sans',sans-serif\",fontSize:7,fontWeight:300,letterSpacing:'0.06em',textTransform:'uppercase',color:fromChain===c.id?'var(--a)':'var(--w18)'}}>{c.label}</span>");
lines.push("                    </button>)}");
lines.push("                  </div>");
lines.push("                  <div style={{display:'flex',alignItems:'center',gap:8,marginBottom:12}}>");
lines.push("                    <div style={{flex:1,display:'flex',alignItems:'center',gap:6,border:'1px solid var(--b1)',padding:'8px 10px',background:'var(--bg3)'}}>");
lines.push("                      <img src={selectedChain.logo} alt={selectedChain.label} style={{width:18,height:18,borderRadius:'50%',objectFit:'cover'}} onError={e=>{(e.target as HTMLImageElement).style.display='none';}}/>");
lines.push("                      <span style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w60)'}}>{selectedChain.label}</span>");
lines.push("                    </div>");
lines.push("                    <span style={{color:'var(--a)',fontSize:'1.1rem'}}>→</span>");
lines.push("                    <div style={{flex:1,display:'flex',alignItems:'center',gap:6,border:'1px solid rgba(212,176,90,0.3)',padding:'8px 10px',background:'rgba(212,176,90,0.06)'}}>");
lines.push("                      <span style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--a2)'}}>Arc Testnet</span>");
lines.push("                    </div>");
lines.push("                  </div>");
lines.push("                  <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--w18)',marginBottom:8}}>Amount (USDC)</div>");
lines.push("                  <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:4,marginBottom:8}}>");
lines.push("                    {AMOUNTS.map(a=><button key={a} onClick={()=>setBridgeAmount(a)} style={{fontFamily:\"'Cormorant',serif\",fontSize:14,fontWeight:300,padding:'8px 4px',textAlign:'center',background:bridgeAmount===a?'rgba(212,176,90,0.12)':'var(--bg3)',border:bridgeAmount===a?'1px solid var(--a)':'1px solid var(--b1)',color:bridgeAmount===a?'var(--a2)':'var(--w35)',cursor:'pointer',transition:'all 0.2s'}}>${a}</button>)}");
lines.push("                  </div>");
lines.push("                  <input className='v-input' type='number' placeholder='Custom amount...' value={bridgeAmount} onChange={e=>setBridgeAmount(e.target.value)} style={{marginBottom:12}}/>");
lines.push("                  {error&&<div style={{fontSize:10,fontStyle:'italic',color:'var(--err)',marginBottom:10,border:'1px solid rgba(232,112,112,0.2)',padding:'7px 10px'}}>{error}</div>}");
lines.push("                  {result&&<div style={{fontSize:10,fontStyle:'italic',color:'var(--gr)',marginBottom:10,border:'1px solid var(--gr3)',padding:'7px 10px'}}>{result}</div>}");
lines.push("                  <button onClick={handleBridge} disabled={loading} className='btn-primary' style={{width:'100%',padding:'11px',fontSize:10}}>{loading?'Bridging...':`Bridge $${bridgeAmount} USDC → Arc`}</button>");
lines.push("                </div>)}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </>");
lines.push("      )}");
lines.push("    </div>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/components/AppKitWidget.tsx', lines.join('\n'), 'utf8');
console.log('AppKitWidget final done');
