const fs = require('fs');

// Fix cart checkout page
fs.mkdirSync('app/cart/checkout', { recursive: true });

const checkout = [];
checkout.push("'use client';");
checkout.push("import Nav from '../../Nav';");
checkout.push("import { useState } from 'react';");
checkout.push("import { useCart } from '../../lib/cart';");
checkout.push("import { useAccount, useSendTransaction } from 'wagmi';");
checkout.push("import { parseUnits } from 'viem';");
checkout.push("import { saveOrder } from '../../lib/supabase';");
checkout.push("import { useRouter } from 'next/navigation';");
checkout.push("import Link from 'next/link';");
checkout.push("");
checkout.push("export default function CartCheckout() {");
checkout.push("  const { items, clearCart, total } = useCart();");
checkout.push("  const { address, isConnected } = useAccount();");
checkout.push("  const { sendTransactionAsync } = useSendTransaction();");
checkout.push("  const router = useRouter();");
checkout.push("  const [step, setStep] = useState('review');");
checkout.push("  const [currentSeller, setCurrentSeller] = useState('');");
checkout.push("  const [currentItem, setCurrentItem] = useState(0);");
checkout.push("  const [totalItems, setTotalItems] = useState(0);");
checkout.push("  const [txHashes, setTxHashes] = useState([]);");
checkout.push("  const [error, setError] = useState('');");
checkout.push("");
checkout.push("  const groupedBySeller = items.reduce((acc, item) => {");
checkout.push("    if (!acc[item.storeSlug]) acc[item.storeSlug] = [];");
checkout.push("    acc[item.storeSlug].push(item);");
checkout.push("    return acc;");
checkout.push("  }, {});");
checkout.push("");
checkout.push("  const handleCheckout = async () => {");
checkout.push("    if (!isConnected || !address) { router.push('/join'); return; }");
checkout.push("    if (items.length === 0) return;");
checkout.push("    setStep('paying');");
checkout.push("    const hashes = [];");
checkout.push("    const sellers = Object.entries(groupedBySeller);");
checkout.push("    setTotalItems(sellers.length);");
checkout.push("    try {");
checkout.push("      for (let i = 0; i < sellers.length; i++) {");
checkout.push("        const [slug, storeItems] = sellers[i];");
checkout.push("        setCurrentSeller(storeItems[0].storeName);");
checkout.push("        setCurrentItem(i + 1);");
checkout.push("        const sellerWallet = storeItems[0].sellerWallet;");
checkout.push("        const storeTotal = storeItems.reduce((sum, item) => sum + item.price * item.quantity, 0);");
checkout.push("        const hash = await sendTransactionAsync({");
checkout.push("          to: sellerWallet,");
checkout.push("          value: parseUnits(storeTotal.toString(), 18),");
checkout.push("        });");
checkout.push("        hashes.push(hash);");
checkout.push("        for (const item of storeItems) {");
checkout.push("          await saveOrder({");
checkout.push("            buyer_wallet: address,");
checkout.push("            seller_wallet: sellerWallet,");
checkout.push("            product_name: item.productName + (item.quantity > 1 ? ' x' + item.quantity : ''),");
checkout.push("            amount: item.price * item.quantity,");
checkout.push("            tx_hash: hash,");
checkout.push("          });");
checkout.push("        }");
checkout.push("      }");
checkout.push("      setTxHashes(hashes);");
checkout.push("      clearCart();");
checkout.push("      setStep('success');");
checkout.push("    } catch (e) {");
checkout.push("      const msg = e?.message || '';");
checkout.push("      setError(msg.includes('rejected') ? 'Transaction rejected in wallet' : 'Transaction failed');");
checkout.push("      setStep('error');");
checkout.push("    }");
checkout.push("  };");
checkout.push("");
checkout.push("  if (items.length === 0 && step === 'review') return (");
checkout.push("    <main style={{ minHeight: '100vh', background: 'var(--bg)' }}>");
checkout.push("      <Nav />");
checkout.push("      <div style={{ maxWidth: 560, margin: '0 auto', padding: '7rem 2rem 4rem', textAlign: 'center' }}>");
checkout.push("        <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>{'🛒'}</div>");
checkout.push("        <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '2rem', marginBottom: '1rem' }}>Cart is Empty</div>");
checkout.push("        <Link href='/marketplace'><button className='btn-3d-purple' style={{ padding: '0.75rem 2rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.7rem', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Browse Marketplace</button></Link>");
checkout.push("      </div>");
checkout.push("    </main>");
checkout.push("  );");
checkout.push("");
checkout.push("  return (");
checkout.push("    <main style={{ minHeight: '100vh', background: 'var(--bg)' }}>");
checkout.push("      <Nav />");
checkout.push("      <div style={{ maxWidth: 560, margin: '0 auto', padding: '7rem 2rem 4rem' }}>");
checkout.push("        {step === 'review' && (");
checkout.push("          <>"); 
checkout.push("            <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--accent)', letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: '0.5rem' }}>Checkout</div>");
checkout.push("            <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '2.5rem', letterSpacing: '0.02em', marginBottom: '2rem' }}>ORDER SUMMARY</div>");
checkout.push("            {Object.entries(groupedBySeller).map(([slug, storeItems]) => {");
checkout.push("              const storeTotal = storeItems.reduce((sum, item) => sum + item.price * item.quantity, 0);");
checkout.push("              return (");
checkout.push("                <div key={slug} style={{ border: '1px solid var(--border)', marginBottom: '1rem', overflow: 'hidden' }}>");
checkout.push("                  <div style={{ padding: '0.75rem 1.25rem', background: 'var(--bg3)', borderBottom: '1px solid var(--border)', fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--accent)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>{'🏪 '}{storeItems[0].storeName}</div>");
checkout.push("                  {storeItems.map(item => (");
checkout.push("                    <div key={item.id} style={{ display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)' }}>");
checkout.push("                      {item.image ? <img src={item.image} alt={item.productName} style={{ width: 48, height: 48, objectFit: 'cover', flexShrink: 0 }} /> : <div style={{ width: 48, height: 48, background: 'linear-gradient(135deg,var(--accent),#7c3aed)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', flexShrink: 0 }}>{'📦'}</div>}");
checkout.push("                      <div style={{ flex: 1 }}>");
checkout.push("                        <div style={{ fontWeight: 500, fontSize: '0.9rem' }}>{item.productName}</div>");
checkout.push("                        <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.55rem', color: 'var(--muted)', marginTop: '0.2rem' }}>{'Qty: '}{item.quantity}{' · $'}{item.price}{' each'}</div>");
checkout.push("                      </div>");
checkout.push("                      <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1rem', color: 'var(--accent2)' }}>{'$'}{(item.price * item.quantity).toFixed(2)}</div>");
checkout.push("                    </div>");
checkout.push("                  ))}");
checkout.push("                  <div style={{ padding: '0.75rem 1.25rem', display: 'flex', justifyContent: 'space-between', background: 'var(--bg2)' }}>");
checkout.push("                    <span style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--muted)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>Store total</span>");
checkout.push("                    <span style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1rem', color: 'var(--accent2)' }}>{'$'}{storeTotal.toFixed(2)}{' USDC'}</span>");
checkout.push("                  </div>");
checkout.push("                </div>");
checkout.push("              );");
checkout.push("            })}");
checkout.push("            <div style={{ border: '1px solid var(--border)', padding: '1.25rem', marginBottom: '1.5rem', background: 'var(--bg2)' }}>");
checkout.push("              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>");
checkout.push("                <span style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.65rem', color: 'var(--muted)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>Grand Total</span>");
checkout.push("                <span style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '2rem', color: 'var(--accent2)' }}>{'$'}{total().toFixed(2)}{' USDC'}</span>");
checkout.push("              </div>");
checkout.push("              {Object.keys(groupedBySeller).length > 1 && <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.58rem', color: 'var(--muted)', marginTop: '0.5rem', letterSpacing: '0.06em' }}>{'⚡ '}{Object.keys(groupedBySeller).length}{' separate wallet approvals required'}</div>}");
checkout.push("            </div>");
checkout.push("            <button onClick={handleCheckout} className='btn-3d-accent' style={{ width: '100%', padding: '1rem', fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1.2rem', letterSpacing: '0.15em' }}>{'Pay $'}{total().toFixed(2)}{' USDC →'}</button>");
checkout.push("            <div style={{ textAlign: 'center', marginTop: '1rem' }}><Link href='/marketplace' style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--muted)', letterSpacing: '0.08em', textDecoration: 'none' }}>← Continue Shopping</Link></div>");
checkout.push("          </>");
checkout.push("        )}");
checkout.push("        {step === 'paying' && (");
checkout.push("          <div style={{ textAlign: 'center', padding: '4rem 2rem' }}>");
checkout.push("            <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '2.5rem', marginBottom: '1rem' }}>Processing Payment</div>");
checkout.push("            <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.65rem', color: 'var(--accent)', letterSpacing: '0.08em', marginBottom: '0.5rem', textTransform: 'uppercase' }}>{'Store '}{currentItem}{' of '}{totalItems}</div>");
checkout.push("            <div style={{ fontSize: '0.9rem', color: 'var(--muted)', fontWeight: 300, marginBottom: '2rem' }}>{'Approve payment to '}{currentSeller}{' in your wallet'}</div>");
checkout.push("            <div style={{ width: 48, height: 48, border: '3px solid var(--border)', borderTop: '3px solid var(--accent)', borderRadius: '50%', margin: '0 auto', animation: 'spin 1s linear infinite' }} />");
checkout.push("            <style>{'@keyframes spin { to { transform: rotate(360deg); } }'}</style>");
checkout.push("          </div>");
checkout.push("        )}");
checkout.push("        {step === 'success' && (");
checkout.push("          <div style={{ textAlign: 'center', padding: '3rem 1.5rem' }}>");
checkout.push("            <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '5rem', color: 'var(--accent)', lineHeight: 1 }}>{'✓'}</div>");
checkout.push("            <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '2.5rem', letterSpacing: '0.02em', marginBottom: '0.75rem' }}>All Payments Confirmed!</div>");
checkout.push("            <div style={{ fontSize: '0.9rem', color: 'var(--muted)', fontWeight: 300, marginBottom: '2rem' }}>{txHashes.length}{' transaction'}{txHashes.length > 1 ? 's' : ''}{' confirmed on Arc Testnet'}</div>");
checkout.push("            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', maxWidth: 300, margin: '0 auto' }}>");
checkout.push("              <Link href='/profile'><button className='btn-3d-purple' style={{ width: '100%', padding: '0.85rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.65rem', letterSpacing: '0.1em', textTransform: 'uppercase' }}>View Orders</button></Link>");
checkout.push("              <Link href='/marketplace'><button className='btn-3d-ghost' style={{ width: '100%', padding: '0.85rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.65rem', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Keep Shopping</button></Link>");
checkout.push("            </div>");
checkout.push("          </div>");
checkout.push("        )}");
checkout.push("        {step === 'error' && (");
checkout.push("          <div style={{ textAlign: 'center', padding: '3rem 1.5rem' }}>");
checkout.push("            <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '3rem', color: '#e84040' }}>{'✕'}</div>");
checkout.push("            <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1.8rem', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Transaction Failed</div>");
checkout.push("            <div style={{ fontSize: '0.85rem', color: 'var(--muted)', marginBottom: '1.5rem', fontWeight: 300 }}>{error}</div>");
checkout.push("            <button onClick={() => setStep('review')} className='btn-3d-accent' style={{ padding: '0.75rem 2rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.7rem', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Try Again</button>");
checkout.push("          </div>");
checkout.push("        )}");
checkout.push("      </div>");
checkout.push("    </main>");
checkout.push("  );");
checkout.push("}");

fs.writeFileSync('app/cart/checkout/page.tsx', checkout.join('\n'), 'utf8');
console.log('Cart checkout done:', fs.existsSync('app/cart/checkout/page.tsx'));

// Fix store slug page
const slug = [];
slug.push("'use client';");
slug.push("import Nav from '../../Nav';");
slug.push("import Link from 'next/link';");
slug.push("import { useParams } from 'next/navigation';");
slug.push("import { useState, useEffect } from 'react';");
slug.push("import { getStoreBySlug } from '../../lib/supabase';");
slug.push("import { useCart } from '../../lib/cart';");
slug.push("");
slug.push("const sampleStores = {");
slug.push("  'nour-atelier': { name: 'Nour Atelier', slug: 'nour-atelier', category: 'Fashion', tagline: 'Handcrafted jewellery from the Middle East', description: 'Each piece is handcrafted using traditional techniques.', owner_wallet: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', x_handle: '@nour_atelier', banner_url: '', products: [{ id: '1', name: 'Gold Crescent Ring', price: 45, type: 'Physical', description: 'Sterling silver with gold plating', image_url: '' }, { id: '2', name: 'Lapis Lazuli Earrings', price: 62, type: 'Physical', description: 'Genuine lapis lazuli stones', image_url: '' }, { id: '3', name: 'Silver Khamsa Pendant', price: 38, type: 'Physical', description: 'Traditional Khamsa hand symbol', image_url: '' }, { id: '4', name: 'Lookbook PDF', price: 8, type: 'Digital', description: 'Full season lookbook', image_url: '' }] },");
slug.push("  'bytedrop': { name: 'ByteDrop', slug: 'bytedrop', category: 'Digital', tagline: 'Premium UI kits and Figma assets', description: 'Professional design assets for modern products.', owner_wallet: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC', x_handle: '@bytedrop', banner_url: '', products: [{ id: '1', name: 'Dashboard UI Kit', price: 49, type: 'Digital', description: 'Complete dashboard component library', image_url: '' }, { id: '2', name: 'Icon Pack Pro', price: 19, type: 'Digital', description: '500+ custom icons', image_url: '' }, { id: '3', name: 'Landing Page Templates', price: 35, type: 'Digital', description: '12 conversion-optimized templates', image_url: '' }] },");
slug.push("  'solar-prints': { name: 'Solar Prints', slug: 'solar-prints', category: 'Art', tagline: 'Limited edition art prints worldwide', description: 'Gallery-quality prints from independent artists.', owner_wallet: '0x90F79bf6EB2c4f870365E785982E1f101E93b906', x_handle: '@solarprints', banner_url: '', products: [{ id: '1', name: 'Desert Bloom Print', price: 55, type: 'Physical', description: 'A2 giclée print', image_url: '' }, { id: '2', name: 'Neon City Poster', price: 40, type: 'Physical', description: 'A1 format signed', image_url: '' }] },");
slug.push("  'kode-studio': { name: 'Kode Studio', slug: 'kode-studio', category: 'Services', tagline: 'Custom dev work and automation', description: 'We build custom tools, bots, and web apps.', owner_wallet: '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65', x_handle: '@kodestudio', banner_url: '', products: [{ id: '1', name: 'Landing Page Build', price: 299, type: 'Service', description: 'Custom Next.js landing page', image_url: '' }, { id: '2', name: 'Bot Development', price: 199, type: 'Service', description: 'Telegram or Discord bot', image_url: '' }] },");
slug.push("  'umami-box': { name: 'Umami Box', slug: 'umami-box', category: 'Food', tagline: 'Artisan Japanese food kits', description: 'Curated Japanese pantry essentials.', owner_wallet: '0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc', x_handle: '@umamibox', banner_url: '', products: [{ id: '1', name: 'Ramen Kit Deluxe', price: 28, type: 'Physical', description: 'Everything for authentic ramen', image_url: '' }, { id: '2', name: 'Matcha Collection', price: 35, type: 'Physical', description: 'Ceremonial grade matcha set', image_url: '' }] },");
slug.push("  'soundvault': { name: 'SoundVault', slug: 'soundvault', category: 'Music', tagline: 'Exclusive beats and sample packs', description: 'Professional-grade audio for creators.', owner_wallet: '0x976EA74026E726554dB657fA54763abd0C3a0aa9', x_handle: '@soundvault', banner_url: '', products: [{ id: '1', name: 'Lo-Fi Essentials Pack', price: 25, type: 'Digital', description: '50 lo-fi samples', image_url: '' }, { id: '2', name: 'Trap Drums Vol.2', price: 20, type: 'Digital', description: '200 one-shot drum samples', image_url: '' }, { id: '3', name: 'Custom Beat License', price: 150, type: 'Digital', description: 'Exclusive rights to one beat', image_url: '' }] },");
slug.push("};");
slug.push("");
slug.push("export default function StorePage() {");
slug.push("  const params = useParams();");
slug.push("  const storeSlug = params.slug as string;");
slug.push("  const [store, setStore] = useState<any>(null);");
slug.push("  const [loading, setLoading] = useState(true);");
slug.push("  const [addedIds, setAddedIds] = useState<Record<string, boolean>>({});");
slug.push("  const { addItem } = useCart();");
slug.push("");
slug.push("  useEffect(() => {");
slug.push("    const load = async () => {");
slug.push("      if (sampleStores[storeSlug]) { setStore(sampleStores[storeSlug]); setLoading(false); return; }");
slug.push("      const dbStore = await getStoreBySlug(storeSlug);");
slug.push("      setStore(dbStore);");
slug.push("      setLoading(false);");
slug.push("    };");
slug.push("    load();");
slug.push("  }, [storeSlug]);");
slug.push("");
slug.push("  const handleAddToCart = (product: any) => {");
slug.push("    addItem({");
slug.push("      id: store.slug + '-' + product.id,");
slug.push("      storeSlug: store.slug,");
slug.push("      storeName: store.name,");
slug.push("      sellerWallet: store.owner_wallet,");
slug.push("      productName: product.name,");
slug.push("      price: product.price,");
slug.push("      image: product.image_url || '',");
slug.push("    });");
slug.push("    setAddedIds(prev => ({ ...prev, [product.id]: true }));");
slug.push("    setTimeout(() => setAddedIds(prev => ({ ...prev, [product.id]: false })), 2000);");
slug.push("  };");
slug.push("");
slug.push("  if (loading) return (<main style={{ minHeight: '100vh', background: 'var(--bg)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Nav /><div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.7rem', color: 'var(--muted)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Loading store...</div></main>);");
slug.push("");
slug.push("  if (!store) return (<main style={{ minHeight: '100vh', background: 'var(--bg)', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}><Nav /><div style={{ textAlign: 'center' }}><div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '3rem', marginBottom: '1rem' }}>Store Not Found</div><Link href='/marketplace'><button className='btn-3d-accent' style={{ padding: '0.75rem 2rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.7rem', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Back to Marketplace</button></Link></div></main>);");
slug.push("");
slug.push("  const products = store.products || [];");
slug.push("  const xHandle = store.x_handle ? (store.x_handle.startsWith('@') ? store.x_handle : '@' + store.x_handle) : null;");
slug.push("");
slug.push("  return (");
slug.push("    <main style={{ minHeight: '100vh', background: 'var(--bg)' }}>");
slug.push("      <Nav />");
slug.push("      {store.banner_url ? (<div style={{ width: '100%', height: 300, overflow: 'hidden', position: 'relative', marginTop: '4rem' }}><img src={store.banner_url} alt='store banner' style={{ width: '100%', height: '100%', objectFit: 'cover' }} /><div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to bottom, transparent 30%, rgba(10,6,18,0.85) 100%)' }} /></div>) : (<div style={{ height: '4rem' }} />)}");
slug.push("      <div style={{ borderBottom: '1px solid var(--border)', background: store.banner_url ? 'transparent' : 'radial-gradient(ellipse at 70% 50%, rgba(201,77,122,0.12), transparent 60%)' }}>");
slug.push("        <div style={{ maxWidth: 900, margin: '0 auto', padding: store.banner_url ? '2rem 2.5rem 2.5rem' : '4rem 2.5rem 2.5rem' }}>");
slug.push("          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '1.5rem', flexWrap: 'wrap' }}>");
slug.push("            <div style={{ width: 72, height: 72, borderRadius: '50%', background: 'linear-gradient(135deg, var(--accent), #7c3aed)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1.4rem', flexShrink: 0, border: '2px solid var(--border2)' }}>{store.name?.slice(0, 2).toUpperCase()}</div>");
slug.push("            <div style={{ flex: 1 }}>");
slug.push("              <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--accent)', letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: '0.4rem' }}>{store.category}{' · Arc Testnet'}</div>");
slug.push("              <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: 'clamp(2rem,5vw,3.5rem)', letterSpacing: '0.02em', lineHeight: 0.95, marginBottom: '0.5rem' }}>{store.name}</div>");
slug.push("              {store.tagline && <div style={{ fontSize: '0.95rem', color: 'var(--muted)', fontWeight: 300, marginBottom: '0.5rem' }}>{store.tagline}</div>}");
slug.push("              {xHandle && <a href={'https://x.com/' + xHandle.replace('@', '')} target='_blank' rel='noopener noreferrer' style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--accent)', textDecoration: 'none', marginBottom: '0.5rem' }}>{'𝕏 '}{xHandle}{' ↗'}</a>}");
slug.push("              {store.description && <div style={{ fontSize: '0.875rem', color: 'var(--muted)', fontWeight: 300, maxWidth: 500, lineHeight: 1.7, marginTop: '0.5rem' }}>{store.description}</div>}");
slug.push("            </div>");
slug.push("          </div>");
slug.push("        </div>");
slug.push("      </div>");
slug.push("      <div style={{ maxWidth: 900, margin: '0 auto', padding: '3rem 2.5rem 4rem' }}>");
slug.push("        <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', color: 'var(--muted)', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '2rem' }}>{products.length}{' product'}{products.length !== 1 ? 's' : ''}</div>");
slug.push("        {products.length === 0 ? (<div style={{ textAlign: 'center', padding: '4rem', border: '1px solid var(--border)' }}><div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '2rem', marginBottom: '0.5rem' }}>No Products Yet</div><div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.65rem', color: 'var(--muted)', letterSpacing: '0.08em' }}>This store has not listed any products yet</div></div>) : (");
slug.push("          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: '1px', background: 'var(--border)' }}>");
slug.push("            {products.map((product: any) => (");
slug.push("              <div key={product.id} style={{ background: 'var(--bg)', transition: 'background 0.2s' }} onMouseEnter={e => (e.currentTarget.style.background = 'var(--bg2)')} onMouseLeave={e => (e.currentTarget.style.background = 'var(--bg)')}>"); 
slug.push("                {product.image_url ? (<div style={{ width: '100%', height: 220, overflow: 'hidden' }}><img src={product.image_url} alt={product.name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /></div>) : (<div style={{ width: '100%', height: 160, background: 'radial-gradient(ellipse at 50% 50%, rgba(124,58,237,0.2), rgba(10,6,18,0.8))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '3rem' }}>{'📦'}</div>)}");
slug.push("                <div style={{ padding: '1.25rem' }}>");
slug.push("                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.75rem' }}>");
slug.push("                    <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1.3rem', letterSpacing: '0.04em', flex: 1, paddingRight: '1rem' }}>{product.name}</div>");
slug.push("                    <div style={{ fontFamily: \"'Space Mono', monospace\", fontSize: '0.55rem', letterSpacing: '0.08em', textTransform: 'uppercase', padding: '0.2rem 0.5rem', border: '1px solid var(--border)', color: 'var(--muted)', flexShrink: 0 }}>{product.type}</div>");
slug.push("                  </div>");
slug.push("                  {product.description && <div style={{ fontSize: '0.85rem', color: 'var(--muted)', fontWeight: 300, lineHeight: 1.6, marginBottom: '1.25rem' }}>{product.description}</div>}");
slug.push("                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '0.5rem' }}>");
slug.push("                    <div style={{ fontFamily: \"'Bebas Neue', sans-serif\", fontSize: '1.8rem', color: 'var(--accent2)' }}>{'$'}{product.price}{' USDC'}</div>");
slug.push("                    <div style={{ display: 'flex', gap: '0.5rem' }}>");
slug.push("                      <button onClick={() => handleAddToCart(product)} className={addedIds[product.id] ? 'btn-3d-purple' : 'btn-3d-dark'} style={{ padding: '0.5rem 0.75rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', letterSpacing: '0.06em', textTransform: 'uppercase' }}>{addedIds[product.id] ? '✓ Added' : '+ Cart'}</button>");
slug.push("                      <Link href={'/checkout?store=' + store.slug + '&product=' + encodeURIComponent(product.name) + '&price=' + product.price}><button className='btn-3d-accent' style={{ padding: '0.5rem 0.75rem', fontFamily: \"'Space Mono', monospace\", fontSize: '0.6rem', letterSpacing: '0.06em', textTransform: 'uppercase' }}>Buy Now</button></Link>");
slug.push("                    </div>");
slug.push("                  </div>");
slug.push("                </div>");
slug.push("              </div>");
slug.push("            ))}");
slug.push("          </div>");
slug.push("        )}");
slug.push("      </div>");
slug.push("    </main>");
slug.push("  );");
slug.push("}");

fs.writeFileSync('app/store/[slug]/page.tsx', slug.join('\n'), 'utf8');
console.log('Store page done:', fs.existsSync('app/store/[slug]/page.tsx'));
console.log('All files fixed!');