const fs = require('fs');
fs.mkdirSync('app/api/arc/balance', { recursive: true });
const lines = [];
lines.push("import { NextRequest, NextResponse } from 'next/server';");
lines.push("import { createPublicClient, http, formatUnits } from 'viem';");
lines.push("");
lines.push("const arcTestnet = {");
lines.push("  id: 5042002,");
lines.push("  name: 'Arc Testnet',");
lines.push("  nativeCurrency: { name: 'USD Coin', symbol: 'USDC', decimals: 18 },");
lines.push("  rpcUrls: { default: { http: ['https://rpc.testnet.arc.network'] } },");
lines.push("};");
lines.push("");
lines.push("const ARC_USDC = '0x3600000000000000000000000000000000000000' as `0x${string}`;");
lines.push("");
lines.push("const ERC20_ABI = [{");
lines.push("  name: 'balanceOf',");
lines.push("  type: 'function',");
lines.push("  stateMutability: 'view',");
lines.push("  inputs: [{ name: 'account', type: 'address' }],");
lines.push("  outputs: [{ name: '', type: 'uint256' }],");
lines.push("}] as const;");
lines.push("");
lines.push("export async function POST(req: NextRequest) {");
lines.push("  try {");
lines.push("    const { address } = await req.json();");
lines.push("    if (!address) return NextResponse.json({ balance: '0' });");
lines.push("    const client = createPublicClient({ chain: arcTestnet as any, transport: http() });");
lines.push("    // Try native balance first (USDC is native on Arc)");
lines.push("    const native = await client.getBalance({ address: address as `0x${string}` });");
lines.push("    const nativeBalance = formatUnits(native, 18);");
lines.push("    if (parseFloat(nativeBalance) > 0) return NextResponse.json({ balance: parseFloat(nativeBalance).toFixed(4) });");
lines.push("    // Try ERC20 balance");
lines.push("    const erc20 = await client.readContract({ address: ARC_USDC, abi: ERC20_ABI, functionName: 'balanceOf', args: [address as `0x${string}`] });");
lines.push("    const erc20Balance = formatUnits(erc20 as bigint, 18);");
lines.push("    return NextResponse.json({ balance: parseFloat(erc20Balance).toFixed(4) });");
lines.push("  } catch (e: any) {");
lines.push("    return NextResponse.json({ balance: '0', error: e.message });");
lines.push("  }");
lines.push("}");
fs.writeFileSync('app/api/arc/balance/route.ts', lines.join('\n'), 'utf8');
console.log('Arc balance API done:', fs.existsSync('app/api/arc/balance/route.ts'));
