const fs = require('fs');
fs.mkdirSync('app/components', { recursive: true });

const lines = [];
lines.push("'use client';");
lines.push("import { useState, useEffect } from 'react';");
lines.push("import { useAccount, useWalletClient } from 'wagmi';");
lines.push("import { createViemAdapter } from '@circle-fin/adapter-viem-v2';");
lines.push("import { AppKit } from '@circle-fin/app-kit';");
lines.push("");
lines.push("type Tab = 'balance'|'bridge'|'send';");
lines.push("");
lines.push("export default function CircleAppKitPanel() {");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const { data: walletClient } = useWalletClient();");
lines.push("  const [tab, setTab] = useState<Tab>('balance');");
lines.push("  const [mounted, setMounted] = useState(false);");
lines.push("  const [loading, setLoading] = useState(false);");
lines.push("  const [result, setResult] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [bridgeForm, setBridgeForm] = useState({ amount:'', fromChain:'Ethereum_Sepolia', toChain:'Arc_Testnet' });");
lines.push("  const [sendForm, setSendForm] = useState({ amount:'', to:'' });");
lines.push("");
lines.push("  useEffect(() => setMounted(true), []);");
lines.push("  if (!mounted || !isConnected) return null;");
lines.push("");
lines.push("  const getKit = () => {");
lines.push("    if (!walletClient) throw new Error('Wallet not connected');");
lines.push("    const adapter = createViemAdapter({ walletClient });");
lines.push("    return { kit: new AppKit(), adapter };");
lines.push("  };");
lines.push("");
lines.push("  const handleBridge = async () => {");
lines.push("    if (!bridgeForm.amount) { setError('Enter an amount'); return; }");
lines.push("    setLoading(true); setError(''); setResult('');");
lines.push("    try {");
lines.push("      const { kit, adapter } = getKit();");
lines.push("      const res = await kit.bridge({");
lines.push("        from: { adapter, chain: bridgeForm.fromChain as any },");
lines.push("        to: { adapter, chain: bridgeForm.toChain as any },");
lines.push("        amount: bridgeForm.amount,");
lines.push("        token: 'USDC',");
lines.push("      });");
lines.push("      setResult('Bridge initiated! Tx: ' + JSON.stringify(res).slice(0,80));");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message||'Bridge failed');");
lines.push("    } finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!sendForm.amount || !sendForm.to) { setError('Fill in all fields'); return; }");
lines.push("    setLoading(true); setError(''); setResult('');");
lines.push("    try {");
lines.push("      const { kit, adapter } = getKit();");
lines.push("      const res = await kit.send({");
lines.push("        from: { adapter, chain: 'Arc_Testnet' as any },");
lines.push("        to: { address: sendForm.to as `0x${string}`, chain: 'Arc_Testnet' as any },");
lines.push("        amount: sendForm.amount,");
lines.push("        token: 'USDC',");
lines.push("      });");
lines.push("      setResult('Sent! Tx: ' + JSON.stringify(res).slice(0,80));");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message||'Send failed');");
lines.push("    } finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const CHAINS = ['Arc_Testnet','Ethereum_Sepolia','Solana_Devnet'];");
lines.push("  const tabs: { id: Tab; label: string; icon: string }[] = [");
lines.push("    { id:'balance', label:'Unified Balance', icon:'💳' },");
lines.push("    { id:'bridge', label:'Bridge USDC', icon:'🌉' },");
lines.push("    { id:'send', label:'Send USDC', icon:'✈️' },");
lines.push("  ];");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ border:'1px solid rgba(212,176,90,0.2)', background:'linear-gradient(145deg,rgba(212,176,90,0.05),var(--bg2))', position:'relative', overflow:'hidden' }}>");
lines.push("      <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.5),transparent)' }} />");
lines.push("      {/* Header */}");
lines.push("      <div style={{ padding:'16px 20px', borderBottom:'1px solid var(--b1)', display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("        <div>");
lines.push("          <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--a)', marginBottom:2 }}>Circle · App Kit</div>");
lines.push("          <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:18, fontWeight:300, color:'var(--w85)' }}>USDC Wallet</div>");
lines.push("        </div>");
lines.push("        <div style={{ display:'flex', alignItems:'center', gap:6, border:'1px solid var(--gr3)', background:'var(--gr2)', padding:'4px 10px' }}>");
lines.push("          <div style={{ width:5, height:5, borderRadius:'50%', background:'var(--gr)', boxShadow:'0 0 6px var(--gr)' }} />");
lines.push("          <span style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.12em', textTransform:'uppercase', color:'var(--gr)' }}>Arc Testnet</span>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      {/* Tabs */}");
lines.push("      <div style={{ display:'flex', borderBottom:'1px solid var(--b1)' }}>");
lines.push("        {tabs.map(t => (");
lines.push("          <button key={t.id} onClick={() => { setTab(t.id); setError(''); setResult(''); }} style={{ flex:1, fontFamily:\"'DM Sans',sans-serif\", fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.12em', textTransform:'uppercase', padding:'10px 8px', background:'transparent', border:'none', borderBottom: tab===t.id ? '1px solid var(--a)' : '1px solid transparent', color: tab===t.id ? 'var(--a)' : 'var(--w18)', cursor:'pointer', transition:'all 0.2s' }}>");
lines.push("            {t.icon}{' '}{t.label}");
lines.push("          </button>))}");
lines.push("      </div>");
lines.push("      <div style={{ padding:'20px' }}>");
lines.push("        {/* BALANCE TAB */}");
lines.push("        {tab==='balance' && (");
lines.push("          <div>");
lines.push("            <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--w18)', marginBottom:4 }}>Connected Wallet</div>");
lines.push("            <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:14, fontWeight:300, color:'var(--a2)', marginBottom:16, wordBreak:'break-all' }}>{address}</div>");
lines.push("            <div style={{ borderTop:'1px solid var(--b1)', paddingTop:14, marginBottom:14 }}>");
lines.push("              {[{chain:'Arc Testnet',note:'Active · Native USDC'},{chain:'Ethereum Sepolia',note:'Bridge via CCTP'},{chain:'Solana Devnet',note:'Bridge via CCTP'}].map(c => (");
lines.push("                <div key={c.chain} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'8px 0', borderBottom:'1px solid rgba(255,255,255,0.04)' }}>");
lines.push("                  <div>");
lines.push("                    <div style={{ fontSize:11, fontWeight:300, color:'var(--w60)', fontStyle:'italic' }}>{c.chain}</div>");
lines.push("                    <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.08em' }}>{c.note}</div>");
lines.push("                  </div>");
lines.push("                  <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:16, fontWeight:300, color:'var(--w18)' }}>— USDC</div>");
lines.push("                </div>))}");
lines.push("            </div>");
lines.push("            <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:12 }}>Unified Balance lets you hold USDC across chains and spend on Vendra without manually bridging. Powered by Circle Gateway + CCTP.</div>");
lines.push("            <a href='https://docs.arc.io/app-kit/unified-balance' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{ width:'100%', fontSize:9, padding:'8px' }}>Read Unified Balance Docs ↗</button></a>");
lines.push("          </div>)}");
lines.push("        {/* BRIDGE TAB */}");
lines.push("        {tab==='bridge' && (");
lines.push("          <div>");
lines.push("            <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:16 }}>Bridge USDC from any supported chain to Arc Testnet via Circle CCTP.</div>");
lines.push("            <div className='v-field'>");
lines.push("              <label className='v-label'>Amount (USDC)</label>");
lines.push("              <input className='v-input' type='number' placeholder='e.g. 10.00' value={bridgeForm.amount} onChange={e => setBridgeForm({...bridgeForm, amount:e.target.value})} />");
lines.push("            </div>");
lines.push("            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12, marginBottom:16 }}>");
lines.push("              <div>");
lines.push("                <label className='v-label'>From Chain</label>");
lines.push("                <select className='v-input' value={bridgeForm.fromChain} onChange={e => setBridgeForm({...bridgeForm, fromChain:e.target.value})} style={{ cursor:'pointer' }}>");
lines.push("                  {CHAINS.filter(c => c !== 'Arc_Testnet').map(c => <option key={c} value={c} style={{ background:'var(--bg2)' }}>{c.replace('_',' ')}</option>)}");
lines.push("                </select>");
lines.push("              </div>");
lines.push("              <div>");
lines.push("                <label className='v-label'>To Chain</label>");
lines.push("                <select className='v-input' value={bridgeForm.toChain} onChange={e => setBridgeForm({...bridgeForm, toChain:e.target.value})} style={{ cursor:'pointer' }}>");
lines.push("                  {CHAINS.map(c => <option key={c} value={c} style={{ background:'var(--bg2)' }}>{c.replace('_',' ')}</option>)}");
lines.push("                </select>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {error && <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("            {result && <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'8px 12px', wordBreak:'break-all' }}>{result}</div>}");
lines.push("            <button onClick={handleBridge} disabled={loading} className='btn-primary' style={{ width:'100%', padding:'12px', fontSize:10 }}>{loading ? 'Bridging...' : 'Bridge USDC via CCTP →'}</button>");
lines.push("          </div>)}");
lines.push("        {/* SEND TAB */}");
lines.push("        {tab==='send' && (");
lines.push("          <div>");
lines.push("            <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:16 }}>Send USDC to any address on Arc Testnet.</div>");
lines.push("            <div className='v-field'>");
lines.push("              <label className='v-label'>Recipient Address</label>");
lines.push("              <input className='v-input' type='text' placeholder='0x...' value={sendForm.to} onChange={e => setSendForm({...sendForm, to:e.target.value})} />");
lines.push("            </div>");
lines.push("            <div className='v-field'>");
lines.push("              <label className='v-label'>Amount (USDC)</label>");
lines.push("              <input className='v-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e => setSendForm({...sendForm, amount:e.target.value})} />");
lines.push("            </div>");
lines.push("            {error && <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("            {result && <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'8px 12px', wordBreak:'break-all' }}>{result}</div>}");
lines.push("            <button onClick={handleSend} disabled={loading} className='btn-primary' style={{ width:'100%', padding:'12px', fontSize:10 }}>{loading ? 'Sending...' : 'Send USDC on Arc →'}</button>");
lines.push("          </div>)}");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("}");

fs.writeFileSync('app/components/CircleAppKitPanel.tsx', lines.join('\n'), 'utf8');
console.log('CircleAppKitPanel done:', fs.existsSync('app/components/CircleAppKitPanel.tsx'));
