const fs = require('fs');
fs.mkdirSync('app/components', { recursive: true });

// ── AppKitWidget — Deposit + Bridge + Balance in nav ─────────────────────────
const lines = [];
lines.push("'use client';");
lines.push("import { useState, useEffect, useCallback } from 'react';");
lines.push("import { useAccount, useConnectorClient, useBalance } from 'wagmi';");
lines.push("import { formatUnits } from 'viem';");
lines.push("");
lines.push("type Tab = 'balance'|'deposit'|'bridge';");
lines.push("");
lines.push("const CHAINS = ['Arc_Testnet','Ethereum_Sepolia','Base_Sepolia','Polygon_Amoy','Arbitrum_Sepolia'];");
lines.push("const ARC_USDC = '0x3600000000000000000000000000000000000000' as `0x${string}`;");
lines.push("");
lines.push("export default function AppKitWidget() {");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const { data: client } = useConnectorClient();");
lines.push("  const { data: usdcBalance } = useBalance({ address, token: ARC_USDC });");
lines.push("  const [open, setOpen] = useState(false);");
lines.push("  const [tab, setTab] = useState<Tab>('balance');");
lines.push("  const [mounted, setMounted] = useState(false);");
lines.push("  const [loading, setLoading] = useState(false);");
lines.push("  const [result, setResult] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [bridgeForm, setBridgeForm] = useState({ from:'Ethereum_Sepolia', to:'Arc_Testnet', amount:'' });");
lines.push("  const [depositForm, setDepositForm] = useState({ from:'Ethereum_Sepolia', amount:'' });");
lines.push("");
lines.push("  useEffect(() => setMounted(true), []);");
lines.push("  if (!mounted || !isConnected) return null;");
lines.push("");
lines.push("  const balance = usdcBalance ? Number(formatUnits(usdcBalance.value, usdcBalance.decimals)).toFixed(2) : '—';");
lines.push("");
lines.push("  const getAdapter = async () => {");
lines.push("    const { createAdapterFromProvider } = await import('@circle-fin/adapter-viem-v2');");
lines.push("    const provider = (client as any)?.transport?.value?.provider;");
lines.push("    if (!provider) throw new Error('No provider found — make sure your wallet is connected');");
lines.push("    return createAdapterFromProvider({ provider });");
lines.push("  };");
lines.push("");
lines.push("  const handleBridge = async () => {");
lines.push("    if (!bridgeForm.amount) { setError('Enter an amount'); return; }");
lines.push("    setLoading(true); setError(''); setResult('');");
lines.push("    try {");
lines.push("      const { AppKit } = await import('@circle-fin/app-kit');");
lines.push("      const adapter = await getAdapter();");
lines.push("      const kit = new AppKit();");
lines.push("      const res = await kit.bridge({");
lines.push("        from: { adapter, chain: bridgeForm.from as any },");
lines.push("        to: { adapter, chain: bridgeForm.to as any },");
lines.push("        amount: bridgeForm.amount,");
lines.push("        token: 'USDC',");
lines.push("      });");
lines.push("      setResult('Bridge initiated! ' + JSON.stringify(res).slice(0,60) + '...');");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message?.includes('provider') ? 'Wallet provider not accessible. Try reconnecting.' : e?.message || 'Bridge failed');");
lines.push("    } finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const handleDeposit = async () => {");
lines.push("    if (!depositForm.amount) { setError('Enter an amount'); return; }");
lines.push("    setLoading(true); setError(''); setResult('');");
lines.push("    try {");
lines.push("      const { AppKit } = await import('@circle-fin/app-kit');");
lines.push("      const adapter = await getAdapter();");
lines.push("      const kit = new AppKit();");
lines.push("      const res = await kit.unifiedBalance.deposit({");
lines.push("        from: { adapter, chain: depositForm.from as any },");
lines.push("        amount: depositForm.amount,");
lines.push("        token: 'USDC',");
lines.push("      });");
lines.push("      setResult('Deposit initiated! ' + JSON.stringify(res).slice(0,60) + '...');");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message?.includes('provider') ? 'Wallet provider not accessible. Try reconnecting.' : e?.message || 'Deposit failed');");
lines.push("    } finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const tabs: {id:Tab;label:string;icon:string}[] = [");
lines.push("    { id:'balance', label:'Balance', icon:'💳' },");
lines.push("    { id:'deposit', label:'Deposit', icon:'⬇️' },");
lines.push("    { id:'bridge', label:'Bridge', icon:'🌉' },");
lines.push("  ];");
lines.push("");
lines.push("  return (");
lines.push("    <div style={{ position:'relative' }}>");
lines.push("      {/* Trigger button */}");
lines.push("      <button onClick={() => { setOpen(!open); setError(''); setResult(''); }} style={{ fontFamily:\"'DM Sans',sans-serif\", fontSize:11, fontWeight:400, letterSpacing:'0.10em', background:'var(--bg2)', border:'1px solid var(--b2)', color:'var(--a2)', padding:'8px 14px', cursor:'pointer', display:'flex', alignItems:'center', gap:8, transition:'all 0.3s', borderRadius:0 }} onMouseEnter={e=>(e.currentTarget.style.borderColor='var(--a)')} onMouseLeave={e=>(e.currentTarget.style.borderColor='var(--b2)')}>"); 
lines.push("        <span style={{ fontSize:'0.8rem' }}>💳</span>");
lines.push("        <span style={{ fontFamily:\"'Cormorant',serif\", fontSize:16, fontWeight:300 }}>${balance}</span>");
lines.push("        <span style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.10em', textTransform:'uppercase', color:'var(--w18)' }}>USDC</span>");
lines.push("        <span style={{ fontSize:8, color:'var(--w18)', transition:'transform 0.2s', display:'inline-block', transform: open ? 'rotate(180deg)' : 'rotate(0deg)' }}>▼</span>");
lines.push("      </button>");
lines.push("      {/* Dropdown panel */}");
lines.push("      {open && (");
lines.push("        <>");
lines.push("          <div onClick={() => setOpen(false)} style={{ position:'fixed', inset:0, zIndex:98 }} />");
lines.push("          <div style={{ position:'absolute', top:'calc(100% + 8px)', right:0, width:340, background:'var(--bg2)', border:'1px solid var(--b2)', zIndex:99, boxShadow:'0 20px 60px rgba(0,0,0,0.6)', overflow:'hidden' }}>");
lines.push("            <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.5),transparent)' }} />");
lines.push("            {/* Header */}");
lines.push("            <div style={{ padding:'14px 16px', borderBottom:'1px solid var(--b1)', display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("              <div>");
lines.push("                <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--a)', marginBottom:2 }}>Arc App Kit · USDC Wallet</div>");
lines.push("                <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:13, fontWeight:300, color:'var(--w35)', wordBreak:'break-all' }}>{address?.slice(0,8)}...{address?.slice(-6)}</div>");
lines.push("              </div>");
lines.push("              <button onClick={() => setOpen(false)} style={{ background:'transparent', border:'none', color:'var(--w18)', cursor:'pointer', fontSize:'0.9rem', padding:4 }}>✕</button>");
lines.push("            </div>");
lines.push("            {/* Tabs */}");
lines.push("            <div style={{ display:'flex', borderBottom:'1px solid var(--b1)' }}>");
lines.push("              {tabs.map(t => (");
lines.push("                <button key={t.id} onClick={() => { setTab(t.id); setError(''); setResult(''); }} style={{ flex:1, fontFamily:\"'DM Sans',sans-serif\", fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.12em', textTransform:'uppercase', padding:'10px 4px', background:'transparent', border:'none', borderBottom: tab===t.id ? '1px solid var(--a)' : '1px solid transparent', color: tab===t.id ? 'var(--a)' : 'var(--w18)', cursor:'pointer', transition:'all 0.2s' }}>");
lines.push("                  {t.icon}{' '}{t.label}");
lines.push("                </button>))}");
lines.push("            </div>");
lines.push("            <div style={{ padding:16 }}>");
lines.push("              {/* BALANCE */}");
lines.push("              {tab==='balance' && (");
lines.push("                <div>");
lines.push("                  <div style={{ textAlign:'center', padding:'12px 0 20px' }}>");
lines.push("                    <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--w18)', marginBottom:4 }}>Arc Testnet · USDC Balance</div>");
lines.push("                    <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:48, fontWeight:300, color:'var(--a2)', lineHeight:1 }}>${balance}</div>");
lines.push("                    <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.08em', marginTop:4 }}>USDC · Arc Testnet</div>");
lines.push("                  </div>");
lines.push("                  <div style={{ display:'flex', gap:8 }}>");
lines.push("                    <button onClick={() => setTab('deposit')} className='btn-primary' style={{ flex:1, fontSize:9, padding:'10px' }}>Deposit ↓</button>");
lines.push("                    <button onClick={() => setTab('bridge')} className='btn-ghost' style={{ flex:1, fontSize:9, padding:'10px' }}>Bridge 🌉</button>");
lines.push("                  </div>");
lines.push("                  <a href={`https://testnet.arcscan.app/address/${address}`} target='_blank' rel='noopener noreferrer' style={{ display:'block', textAlign:'center', marginTop:10, fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.10em', textDecoration:'none' }}>View on Arc Explorer ↗</a>");
lines.push("                </div>)}");
lines.push("              {/* DEPOSIT */}");
lines.push("              {tab==='deposit' && (");
lines.push("                <div>");
lines.push("                  <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:14 }}>Deposit USDC into your Arc Testnet Unified Balance from any supported chain.</div>");
lines.push("                  <div className='v-field'><label className='v-label'>From Chain</label>");
lines.push("                    <select className='v-input' value={depositForm.from} onChange={e => setDepositForm({...depositForm, from:e.target.value})} style={{ cursor:'pointer' }}>");
lines.push("                      {CHAINS.filter(c => c!=='Arc_Testnet').map(c => <option key={c} value={c} style={{ background:'var(--bg2)' }}>{c.replace(/_/g,' ')}</option>)}");
lines.push("                    </select>");
lines.push("                  </div>");
lines.push("                  <div className='v-field'><label className='v-label'>Amount (USDC)</label><input className='v-input' type='number' placeholder='e.g. 10.00' value={depositForm.amount} onChange={e => setDepositForm({...depositForm, amount:e.target.value})} /></div>");
lines.push("                  {error && <div style={{ fontSize:10, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'7px 10px' }}>{error}</div>}");
lines.push("                  {result && <div style={{ fontSize:10, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'7px 10px', wordBreak:'break-all' }}>{result}</div>}");
lines.push("                  <button onClick={handleDeposit} disabled={loading} className='btn-primary' style={{ width:'100%', padding:'11px', fontSize:10 }}>{loading ? 'Processing...' : 'Deposit USDC →'}</button>");
lines.push("                  <div style={{ textAlign:'center', marginTop:10 }}><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{ fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.10em', textDecoration:'none' }}>Need test USDC? Faucet ↗</a></div>");
lines.push("                </div>)}");
lines.push("              {/* BRIDGE */}");
lines.push("              {tab==='bridge' && (");
lines.push("                <div>");
lines.push("                  <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:14 }}>Bridge USDC cross-chain via Circle CCTP. Fast, secure, non-custodial.</div>");
lines.push("                  <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:0 }}>");
lines.push("                    <div><label className='v-label'>From</label><select className='v-input' value={bridgeForm.from} onChange={e => setBridgeForm({...bridgeForm, from:e.target.value})} style={{ cursor:'pointer' }}>{CHAINS.map(c => <option key={c} value={c} style={{ background:'var(--bg2)' }}>{c.replace(/_/g,' ')}</option>)}</select></div>");
lines.push("                    <div><label className='v-label'>To</label><select className='v-input' value={bridgeForm.to} onChange={e => setBridgeForm({...bridgeForm, to:e.target.value})} style={{ cursor:'pointer' }}>{CHAINS.map(c => <option key={c} value={c} style={{ background:'var(--bg2)' }}>{c.replace(/_/g,' ')}</option>)}</select></div>");
lines.push("                  </div>");
lines.push("                  <div className='v-field' style={{ marginTop:10 }}><label className='v-label'>Amount (USDC)</label><input className='v-input' type='number' placeholder='e.g. 10.00' value={bridgeForm.amount} onChange={e => setBridgeForm({...bridgeForm, amount:e.target.value})} /></div>");
lines.push("                  {error && <div style={{ fontSize:10, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'7px 10px' }}>{error}</div>}");
lines.push("                  {result && <div style={{ fontSize:10, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'7px 10px', wordBreak:'break-all' }}>{result}</div>}");
lines.push("                  <button onClick={handleBridge} disabled={loading} className='btn-primary' style={{ width:'100%', padding:'11px', fontSize:10 }}>{loading ? 'Bridging...' : 'Bridge USDC via CCTP →'}</button>");
lines.push("                  <a href='https://docs.arc.io/app-kit/bridge' target='_blank' rel='noopener noreferrer' style={{ display:'block', textAlign:'center', marginTop:10, fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.10em', textDecoration:'none' }}>Bridge Kit Docs ↗</a>");
lines.push("                </div>)}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </>");
lines.push("      )}");
lines.push("    </div>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/components/AppKitWidget.tsx', lines.join('\n'), 'utf8');
console.log('AppKitWidget done:', fs.existsSync('app/components/AppKitWidget.tsx'));
