const fs = require('fs');
fs.mkdirSync('app/components', { recursive: true });

// ── ArcUnifiedBalance component ─────────────────────────────────────────────
const ub = [];
ub.push("'use client';");
ub.push("import { useState, useEffect } from 'react';");
ub.push("import { useAccount } from 'wagmi';");
ub.push("");
ub.push("export default function ArcUnifiedBalance() {");
ub.push("  const { address, isConnected } = useAccount();");
ub.push("  const [open, setOpen] = useState(false);");
ub.push("  const [mounted, setMounted] = useState(false);");
ub.push("  useEffect(() => setMounted(true), []);");
ub.push("  if (!mounted || !isConnected) return null;");
ub.push("  const chains = [");
ub.push("    { name: 'Arc Testnet', bal: '—', native: true },");
ub.push("    { name: 'Ethereum Sepolia', bal: '—', native: false },");
ub.push("    { name: 'Solana Devnet', bal: '—', native: false },");
ub.push("  ];");
ub.push("  return (");
ub.push("    <div style={{ border: '1px solid rgba(212,176,90,0.2)', background: 'linear-gradient(145deg,rgba(212,176,90,0.06),rgba(12,14,26,0.9))', position: 'relative', overflow: 'hidden' }}>");
ub.push("      <div style={{ position: 'absolute', top: 0, left: '10%', right: '10%', height: 1, background: 'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
ub.push("      <div style={{ padding: '20px 24px' }}>");
ub.push("        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>");
ub.push("          <div>");
ub.push("            <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--w18)', marginBottom: 4 }}>Arc App Kit · Unified Balance</div>");
ub.push("            <div style={{ fontFamily: \"'Cormorant',serif\", fontSize: 28, fontWeight: 300, color: 'var(--a2)', lineHeight: 1 }}>Multi-Chain USDC</div>");
ub.push("          </div>");
ub.push("          <div style={{ display: 'flex', alignItems: 'center', gap: 6, border: '1px solid var(--gr3)', background: 'var(--gr2)', padding: '4px 10px' }}>");
ub.push("            <div style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--gr)', boxShadow: '0 0 6px var(--gr)' }} />");
ub.push("            <span style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--gr)' }}>Live</span>");
ub.push("          </div>");
ub.push("        </div>");
ub.push("        <div style={{ fontSize: 11, fontWeight: 300, fontStyle: 'italic', color: 'var(--w35)', lineHeight: 1.7, marginBottom: 16 }}>Hold USDC on any chain. Spend directly on Vendra — no manual bridging required. Powered by CCTP.</div>");
ub.push("        <div style={{ borderTop: '1px solid var(--b1)', paddingTop: 14, marginBottom: 14 }}>");
ub.push("          {chains.map(c => (");
ub.push("            <div key={c.name} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>");
ub.push("              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>");
ub.push("                {c.native && <div style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--gr)', boxShadow: '0 0 4px var(--gr)' }} />}");
ub.push("                <span style={{ fontSize: 11, fontWeight: 300, color: c.native ? 'var(--w60)' : 'var(--w35)', fontStyle: 'italic', letterSpacing: '0.04em' }}>{c.name}{c.native ? ' (Active)' : ''}</span>");
ub.push("              </div>");
ub.push("              <span style={{ fontFamily: \"'Cormorant',serif\", fontSize: 14, fontWeight: 300, color: 'var(--w18)' }}>{c.bal} USDC</span>");
ub.push("            </div>))}");
ub.push("        </div>");
ub.push("        <div style={{ display: 'flex', gap: 8 }}>");
ub.push("          <a href='https://docs.arc.io/app-kit/unified-balance.md' target='_blank' rel='noopener noreferrer' style={{ flex: 1 }}><button className='btn-amber-ghost' style={{ width: '100%', fontSize: 9, padding: '8px' }}>Unified Balance ↗</button></a>");
ub.push("          <a href='https://docs.arc.io/app-kit/bridge.md' target='_blank' rel='noopener noreferrer' style={{ flex: 1 }}><button className='btn-ghost' style={{ width: '100%', fontSize: 9, padding: '8px' }}>Bridge USDC ↗</button></a>");
ub.push("        </div>");
ub.push("      </div>");
ub.push("    </div>");
ub.push("  );");
ub.push("}");
fs.writeFileSync('app/components/ArcUnifiedBalance.tsx', ub.join('\n'), 'utf8');
console.log('ArcUnifiedBalance done');

// ── ArcEscrowStatus component ────────────────────────────────────────────────
const es = [];
es.push("'use client';");
es.push("import { useState } from 'react';");
es.push("");
es.push("interface Props { orderId?: string; status?: string; amount?: number; createdAt?: string; }");
es.push("");
es.push("export default function ArcEscrowStatus({ orderId, status='locked', amount=0, createdAt }: Props) {");
es.push("  const releaseDate = createdAt ? new Date(new Date(createdAt).getTime() + 48*60*60*1000) : null;");
es.push("  const isReleased = status === 'released';");
es.push("  return (");
es.push("    <div style={{ border: `1px solid ${isReleased ? 'var(--gr3)' : 'rgba(212,176,90,0.2)'}`, background: isReleased ? 'var(--gr2)' : 'rgba(212,176,90,0.04)', position: 'relative', overflow: 'hidden' }}>");
es.push("      <div style={{ position: 'absolute', top: 0, left: '10%', right: '10%', height: 1, background: `linear-gradient(90deg,transparent,${isReleased ? 'rgba(143,196,152,0.4)' : 'rgba(212,176,90,0.3)'},transparent)` }} />");
es.push("      <div style={{ padding: '16px 20px' }}>");
es.push("        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>");
es.push("          <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--w18)' }}>ERC-8183 Escrow</div>");
es.push("          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>");
es.push("            <div style={{ width: 5, height: 5, borderRadius: '50%', background: isReleased ? 'var(--gr)' : 'var(--a2)', boxShadow: `0 0 6px ${isReleased ? 'var(--gr)' : 'var(--a2)'}` }} />");
es.push("            <span style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.12em', textTransform: 'uppercase', color: isReleased ? 'var(--gr)' : 'var(--a)' }}>{isReleased ? 'Released' : 'Locked'}</span>");
es.push("          </div>");
es.push("        </div>");
es.push("        <div style={{ fontFamily: \"'Cormorant',serif\", fontSize: 22, fontWeight: 300, color: isReleased ? 'var(--gr)' : 'var(--a2)', marginBottom: 4 }}>{'$'}{amount.toFixed(2)}{' USDC'}</div>");
es.push("        <div style={{ fontSize: 11, fontWeight: 300, fontStyle: 'italic', color: 'var(--w35)', lineHeight: 1.6 }}>");
es.push("          {isReleased ? 'Funds released to seller.' : releaseDate ? `Releases ${releaseDate.toLocaleDateString('en-US',{month:'short',day:'numeric'})} if no dispute raised.` : 'Protected by smart contract escrow.'}");
es.push("        </div>");
es.push("      </div>");
es.push("    </div>");
es.push("  );");
es.push("}");
fs.writeFileSync('app/components/ArcEscrowStatus.tsx', es.join('\n'), 'utf8');
console.log('ArcEscrowStatus done');

// ── ArcIdentityBadge component ───────────────────────────────────────────────
const ib = [];
ib.push("'use client';");
ib.push("");
ib.push("interface Props { score?: string | number; totalSales?: number; verified?: boolean; }");
ib.push("");
ib.push("export default function ArcIdentityBadge({ score='—', totalSales=0, verified=false }: Props) {");
ib.push("  return (");
ib.push("    <div style={{ border: '1px solid var(--b1)', background: 'var(--bg2)', padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 16 }}>");
ib.push("      <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>");
ib.push("        <div style={{ width: 5, height: 5, borderRadius: '50%', background: verified ? 'var(--gr)' : 'var(--w18)', boxShadow: verified ? '0 0 6px var(--gr)' : 'none' }} />");
ib.push("        <span style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.16em', textTransform: 'uppercase', color: verified ? 'var(--gr)' : 'var(--w18)' }}>ERC-8004</span>");
ib.push("      </div>");
ib.push("      <div style={{ flex: 1 }}>");
ib.push("        <div style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--w18)', marginBottom: 2 }}>Onchain Identity · Trust Score</div>");
ib.push("        <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>");
ib.push("          <span style={{ fontFamily: \"'Cormorant',serif\", fontSize: 22, fontWeight: 300, color: 'var(--a2)', lineHeight: 1 }}>{score}</span>");
ib.push("          <span style={{ fontSize: 10, fontWeight: 300, fontStyle: 'italic', color: 'var(--w18)' }}>from {totalSales} sale{totalSales !== 1 ? 's' : ''}</span>");
ib.push("        </div>");
ib.push("      </div>");
ib.push("      <a href='https://docs.arc.io/arc/tutorials/create-your-first-erc-8183-job.md' target='_blank' rel='noopener noreferrer' style={{ textDecoration: 'none', flexShrink: 0 }}>");
ib.push("        <button className='btn-ghost' style={{ fontSize: 9, padding: '6px 12px' }}>Docs ↗</button>");
ib.push("      </a>");
ib.push("    </div>");
ib.push("  );");
ib.push("}");
fs.writeFileSync('app/components/ArcIdentityBadge.tsx', ib.join('\n'), 'utf8');
console.log('ArcIdentityBadge done');

// ── ArcAgenticBanner component ───────────────────────────────────────────────
const ab = [];
ab.push("'use client';");
ab.push("import Link from 'next/link';");
ab.push("");
ab.push("export default function ArcAgenticBanner() {");
ab.push("  return (");
ab.push("    <div style={{ background: 'linear-gradient(135deg,rgba(212,176,90,0.06),rgba(155,181,200,0.04),var(--bg2))', border: '1px solid rgba(212,176,90,0.15)', padding: '28px 32px', position: 'relative', overflow: 'hidden' }}>");
ab.push("      <div style={{ position: 'absolute', top: 0, left: '10%', right: '10%', height: 1, background: 'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
ab.push("      <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 24, alignItems: 'center' }}>");
ab.push("        <div>");
ab.push("          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>");
ab.push("            <div style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--gr)', boxShadow: '0 0 6px var(--gr)' }} />");
ab.push("            <span style={{ fontSize: 9, fontWeight: 300, fontStyle: 'italic', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--w18)' }}>Arc Agentic Economy</span>");
ab.push("          </div>");
ab.push("          <div style={{ fontFamily: \"'Cormorant',serif\", fontSize: 20, fontWeight: 300, color: 'var(--w85)', marginBottom: 6, lineHeight: 1.2 }}>Vendra is a flagship proof-of-concept for Arc's agentic economy thesis</div>");
ab.push("          <div style={{ fontSize: 12, fontWeight: 300, fontStyle: 'italic', color: 'var(--w35)', lineHeight: 1.7 }}>Arc was built for AI agents that transact thousands of times in rapid succession. USDC gas means predictable costs. Sub-second finality means instant outcomes. Vendra demonstrates this at the application layer.</div>");
ab.push("        </div>");
ab.push("        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, flexShrink: 0 }}>");
ab.push("          <a href='https://www.arc.io/blog/how-arc-supports-the-agentic-economy-arc-blueprints' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{ fontSize: 9, padding: '8px 16px', whiteSpace: 'nowrap' }}>Arc Blog ↗</button></a>");
ab.push("          <a href='https://docs.arc.io/build/agentic-economy.md' target='_blank' rel='noopener noreferrer'><button className='btn-ghost' style={{ fontSize: 9, padding: '8px 16px', whiteSpace: 'nowrap' }}>Arc Docs ↗</button></a>");
ab.push("        </div>");
ab.push("      </div>");
ab.push("    </div>");
ab.push("  );");
ab.push("}");
fs.writeFileSync('app/components/ArcAgenticBanner.tsx', ab.join('\n'), 'utf8');
console.log('ArcAgenticBanner done');

console.log('\nAll Arc integration components done!');
console.log('Files created:');
console.log('  app/components/ArcUnifiedBalance.tsx');
console.log('  app/components/ArcEscrowStatus.tsx');
console.log('  app/components/ArcIdentityBadge.tsx');
console.log('  app/components/ArcAgenticBanner.tsx');
