const fs = require('fs');

fs.mkdirSync('app/api/circle/create-wallet', { recursive: true });
fs.mkdirSync('app/api/circle/balance', { recursive: true });
fs.mkdirSync('app/api/circle/send', { recursive: true });
fs.mkdirSync('app/api/circle/login', { recursive: true });

// ── Login / Get wallet by email ──────────────────────────────────────────────
const login = [];
login.push("import { NextRequest, NextResponse } from 'next/server';");
login.push("import { initiateDeveloperControlledWalletsClient } from '@circle-fin/developer-controlled-wallets';");
login.push("");
login.push("export async function POST(req: NextRequest) {");
login.push("  try {");
login.push("    const { email } = await req.json();");
login.push("    if (!email) return NextResponse.json({ error: 'Email required' }, { status: 400 });");
login.push("    const client = initiateDeveloperControlledWalletsClient({");
login.push("      apiKey: process.env.CIRCLE_API_KEY!,");
login.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
login.push("    });");
login.push("    // Search for existing wallet by refId (email)");
login.push("    const wallets = (await client.listWallets({ refId: email })).data?.wallets;");
login.push("    if (wallets && wallets.length > 0) {");
login.push("      const wallet = wallets[0];");
login.push("      return NextResponse.json({ found: true, walletId: wallet.id, address: wallet.address });");
login.push("    }");
login.push("    return NextResponse.json({ found: false });");
login.push("  } catch (e: any) {");
login.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
login.push("  }");
login.push("}");
fs.writeFileSync('app/api/circle/login/route.ts', login.join('\n'), 'utf8');
console.log('login route done');

// ── Create Wallet ────────────────────────────────────────────────────────────
const create = [];
create.push("import { NextRequest, NextResponse } from 'next/server';");
create.push("import { initiateDeveloperControlledWalletsClient } from '@circle-fin/developer-controlled-wallets';");
create.push("");
create.push("export async function POST(req: NextRequest) {");
create.push("  try {");
create.push("    const { email } = await req.json();");
create.push("    if (!email) return NextResponse.json({ error: 'Email required' }, { status: 400 });");
create.push("    const client = initiateDeveloperControlledWalletsClient({");
create.push("      apiKey: process.env.CIRCLE_API_KEY!,");
create.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
create.push("    });");
create.push("    const wallet = (await client.createWallets({");
create.push("      walletSetId: process.env.CIRCLE_WALLET_SET_ID!,");
create.push("      blockchains: ['ARC-TESTNET'],");
create.push("      count: 1,");
create.push("      accountType: 'EOA',");
create.push("      metadata: [{ name: email, refId: email }],");
create.push("    })).data?.wallets?.[0];");
create.push("    if (!wallet) return NextResponse.json({ error: 'Wallet creation failed' }, { status: 500 });");
create.push("    return NextResponse.json({ walletId: wallet.id, address: wallet.address });");
create.push("  } catch (e: any) {");
create.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
create.push("  }");
create.push("}");
fs.writeFileSync('app/api/circle/create-wallet/route.ts', create.join('\n'), 'utf8');
console.log('create-wallet route done');

// ── Balance ──────────────────────────────────────────────────────────────────
const balance = [];
balance.push("import { NextRequest, NextResponse } from 'next/server';");
balance.push("import { initiateDeveloperControlledWalletsClient } from '@circle-fin/developer-controlled-wallets';");
balance.push("");
balance.push("export async function POST(req: NextRequest) {");
balance.push("  try {");
balance.push("    const { walletId } = await req.json();");
balance.push("    const client = initiateDeveloperControlledWalletsClient({");
balance.push("      apiKey: process.env.CIRCLE_API_KEY!,");
balance.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
balance.push("    });");
balance.push("    const balances = (await client.getWalletTokenBalance({ id: walletId })).data?.tokenBalances;");
balance.push("    const usdc = balances?.find((b: any) => b.token?.symbol === 'USDC');");
balance.push("    return NextResponse.json({ balance: usdc?.amount || '0' });");
balance.push("  } catch (e: any) {");
balance.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
balance.push("  }");
balance.push("}");
fs.writeFileSync('app/api/circle/balance/route.ts', balance.join('\n'), 'utf8');
console.log('balance route done');

// ── Send ─────────────────────────────────────────────────────────────────────
const send = [];
send.push("import { NextRequest, NextResponse } from 'next/server';");
send.push("import { initiateDeveloperControlledWalletsClient, type TokenBlockchain } from '@circle-fin/developer-controlled-wallets';");
send.push("");
send.push("const ARC_USDC = '0x3600000000000000000000000000000000000000';");
send.push("");
send.push("export async function POST(req: NextRequest) {");
send.push("  try {");
send.push("    const { walletId, walletAddress, toAddress, amount } = await req.json();");
send.push("    if (!walletId || !walletAddress || !toAddress || !amount) return NextResponse.json({ error: 'Missing fields' }, { status: 400 });");
send.push("    const client = initiateDeveloperControlledWalletsClient({");
send.push("      apiKey: process.env.CIRCLE_API_KEY!,");
send.push("      entitySecret: process.env.CIRCLE_ENTITY_SECRET!,");
send.push("    });");
send.push("    const tx = (await client.createTransaction({");
send.push("      blockchain: 'ARC-TESTNET' as TokenBlockchain,");
send.push("      walletId,");
send.push("      walletAddress,");
send.push("      destinationAddress: toAddress,");
send.push("      amount: [amount.toString()],");
send.push("      tokenAddress: ARC_USDC,");
send.push("      fee: { type: 'level', config: { feeLevel: 'MEDIUM' } },");
send.push("    })).data;");
send.push("    return NextResponse.json({ txId: tx?.id, state: tx?.state });");
send.push("  } catch (e: any) {");
send.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
send.push("  }");
send.push("}");
fs.writeFileSync('app/api/circle/send/route.ts', send.join('\n'), 'utf8');
console.log('send route done');
console.log('\nAll Circle API routes done!');
