const fs = require('fs');
fs.mkdirSync('app/components', { recursive: true });

const btn = [];
btn.push("'use client';");
btn.push("import { useCart } from '../lib/cart';");
btn.push("export default function CartButton() {");
btn.push("  const { toggleCart, count } = useCart();");
btn.push("  const n = count();");
btn.push("  return (");
btn.push("    <button onClick={toggleCart} style={{ position: 'relative', background: 'transparent', border: '1px solid var(--b1)', color: 'var(--w35)', width: 38, height: 38, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1rem', transition: 'border-color 0.35s', flexShrink: 0 }} onMouseEnter={e => (e.currentTarget.style.borderColor = 'var(--a)')} onMouseLeave={e => (e.currentTarget.style.borderColor = 'var(--b1)')}>{'🛒'}{n > 0 && <div style={{ position: 'absolute', top: -6, right: -6, background: 'var(--a2)', color: 'var(--bg)', width: 17, height: 17, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: \"'DM Sans',sans-serif\", fontSize: '0.55rem', fontWeight: 500, border: '2px solid var(--bg)' }}>{n > 9 ? '9+' : n}</div>}</button>");
btn.push("  );");
btn.push("}");
fs.writeFileSync('app/components/CartButton.tsx', btn.join('\n'), 'utf8');
console.log('CartButton done');

const drw = [];
drw.push("'use client';");
drw.push("import { useCart } from '../lib/cart';");
drw.push("import Link from 'next/link';");
drw.push("import { useRouter } from 'next/navigation';");
drw.push("export default function CartDrawer() {");
drw.push("  const { items, isOpen, closeCart, removeItem, updateQuantity, total, count } = useCart();");
drw.push("  const router = useRouter();");
drw.push("  const grouped = items.reduce((acc: any, item) => { if (!acc[item.storeSlug]) acc[item.storeSlug] = []; acc[item.storeSlug].push(item); return acc; }, {} as Record<string, typeof items>);");
drw.push("  const sellerCount = Object.keys(grouped).length;");
drw.push("  return (");
drw.push("    <>{isOpen && <div onClick={closeCart} style={{ position: 'fixed', inset: 0, background: 'rgba(12,14,26,0.78)', zIndex: 150, backdropFilter: 'blur(6px)' }} />}");
drw.push("      <div style={{ position: 'fixed', top: 0, right: 0, bottom: 0, width: 420, background: 'var(--bg2)', borderLeft: '1px solid var(--b1)', zIndex: 151, transform: isOpen ? 'translateX(0)' : 'translateX(100%)', transition: 'transform 0.4s var(--ease)', display: 'flex', flexDirection: 'column', boxShadow: '-8px 0 48px rgba(0,0,0,0.5)' }}>");
drw.push("        <div className='v-cart-drawer-head'><div><div className='v-cart-drawer-title'>Your Cart</div><div className='v-cart-drawer-meta'>{count()} item{count()!==1?'s':''} · {sellerCount} store{sellerCount!==1?'s':''}</div></div><button onClick={closeCart} style={{ background: 'transparent', border: '1px solid var(--b1)', color: 'var(--w35)', width: 34, height: 34, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✕</button></div>");
drw.push("        <div style={{ flex: 1, overflowY: 'auto', padding: '20px 28px' }}>");
drw.push("          {items.length === 0 ? <div style={{ textAlign: 'center', padding: '48px 16px' }}><div style={{ fontSize: '3rem', marginBottom: 16 }}>{'🛒'}</div><div style={{ fontFamily: \"'Cormorant',serif\", fontSize: 22, fontWeight: 300, color: 'var(--w85)', marginBottom: 8 }}>Cart is empty</div><div style={{ fontSize: 12, fontWeight: 300, fontStyle: 'italic', color: 'var(--w18)', letterSpacing: '0.10em', marginBottom: 28 }}>Add products from any store</div><button onClick={() => { closeCart(); router.push('/marketplace'); }} className='btn-amber-ghost'>Browse Marketplace</button></div>");
drw.push("          : Object.entries(grouped).map(([slug, storeItems]: any) => <div key={slug} style={{ marginBottom: 24 }}><div className='v-cart-store-head'>{'🏪 '}{storeItems[0].storeName}</div>{storeItems.map((item: any) => <div key={item.id} className='v-cart-item'>{item.image ? <img src={item.image} alt={item.productName} style={{ width: 52, height: 52, objectFit: 'cover', flexShrink: 0, border: '1px solid var(--b1)' }} /> : <div className='v-cart-item-img'>{'📦'}</div>}<div style={{ flex: 1, minWidth: 0 }}><div className='v-cart-item-name'>{item.productName}</div><div className='v-cart-item-price'>{'$'}{(item.price*item.quantity).toFixed(2)}{' USDC'}</div></div><div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 8, flexShrink: 0 }}><button onClick={() => removeItem(item.id)} style={{ background: 'transparent', border: 'none', color: 'var(--w18)', cursor: 'pointer' }}>✕</button><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><button onClick={() => updateQuantity(item.id, item.quantity-1)} className='v-qty-btn'>-</button><span style={{ fontFamily: \"'Cormorant',serif\", fontSize: 14, fontWeight: 300, color: 'var(--w60)', minWidth: 20, textAlign: 'center' }}>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity+1)} className='v-qty-btn'>+</button></div></div></div>)}</div>)}");
drw.push("        </div>");
drw.push("        {items.length > 0 && <div className='v-cart-footer'>{sellerCount > 1 && <div className='v-cart-warn'>{'⚡ '}{sellerCount}{' separate transactions — one per store'}</div>}<div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 16 }}><div><div className='v-cart-total-label'>Total</div><div className='v-cart-total-val'>{'$'}{total().toFixed(2)}</div></div><div style={{ fontSize: 10, fontWeight: 300, fontStyle: 'italic', color: 'var(--w18)', letterSpacing: '0.10em' }}>USDC · Arc Testnet</div></div><button onClick={() => { closeCart(); router.push('/cart/checkout'); }} className='btn-primary' style={{ width: '100%', padding: 14 }}>{'Checkout · $'}{total().toFixed(2)}{' USDC →'}</button></div>}");
drw.push("      </div></>");
drw.push("  );");
drw.push("}");
fs.writeFileSync('app/components/CartDrawer.tsx', drw.join('\n'), 'utf8');
console.log('CartDrawer done');
