const fs = require('fs');

// ── Standalone CircleWalletDashboard component ───────────────────────────────
const lines = [];
lines.push("'use client';");
lines.push("import { useState, useCallback } from 'react';");
lines.push("");
lines.push("interface Props {");
lines.push("  wallet: { address: string; walletId: string; email: string };");
lines.push("  balance: string;");
lines.push("  onLogout: () => void;");
lines.push("  onClose: () => void;");
lines.push("}");
lines.push("");
lines.push("export default function CircleWalletDashboard({ wallet, balance, onLogout, onClose }: Props) {");
lines.push("  const [copied, setCopied] = useState(false);");
lines.push("  const [to, setTo] = useState('');");
lines.push("  const [amount, setAmount] = useState('');");
lines.push("  const [sending, setSending] = useState(false);");
lines.push("  const [sendResult, setSendResult] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("");
lines.push("  const handleCopy = useCallback(() => {");
lines.push("    navigator.clipboard.writeText(wallet.address);");
lines.push("    setCopied(true); setTimeout(() => setCopied(false), 2000);");
lines.push("  }, [wallet.address]);");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!to || !amount) { setError('Fill in all fields'); return; }");
lines.push("    if (!to.startsWith('0x') || to.length !== 42) { setError('Invalid address'); return; }");
lines.push("    setSending(true); setSendResult(''); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send', {");
lines.push("        method: 'POST',");
lines.push("        headers: { 'Content-Type': 'application/json' },");
lines.push("        body: JSON.stringify({ walletId: wallet.walletId, walletAddress: wallet.address, toAddress: to, amount }),");
lines.push("      });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setSendResult('Sent! TX: ' + (data.txId || '').slice(0, 20) + '...');");
lines.push("      setTo(''); setAmount('');");
lines.push("    } catch(e:any) { setError(e.message || 'Send failed'); }");
lines.push("    finally { setSending(false); }");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <div>");
lines.push("      {/* Wallet info */}");
lines.push("      <div style={{border:'1px solid rgba(212,176,90,0.2)',background:'rgba(212,176,90,0.04)',padding:'20px',marginBottom:16,position:'relative',overflow:'hidden'}}>");
lines.push("        <div style={{position:'absolute',top:0,left:'10%',right:'10%',height:1,background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)'}}/>");
lines.push("        <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--w18)',marginBottom:4}}>Circle Wallet · Arc Testnet</div>");
lines.push("        <div style={{display:'flex',alignItems:'center',gap:8,marginBottom:12}}>");
lines.push("          <div style={{fontFamily:\"'Cormorant',serif\",fontSize:11,fontWeight:300,color:'var(--a)',flex:1,wordBreak:'break-all'}}>{wallet.address}</div>");
lines.push("          <button onClick={handleCopy} style={{fontFamily:\"'DM Sans',sans-serif\",fontSize:9,letterSpacing:'0.12em',textTransform:'uppercase',border:'1px solid var(--b2)',color:copied?'var(--gr)':'var(--w35)',padding:'5px 10px',background:'transparent',cursor:'pointer',flexShrink:0,transition:'all 0.3s',whiteSpace:'nowrap'}}>{copied?'✓ Copied':'Copy'}</button>");
lines.push("        </div>");
lines.push("        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>");
lines.push("          <div>");
lines.push("            <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--w18)',marginBottom:2}}>USDC Balance</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:32,fontWeight:300,color:'var(--a2)'}}>${parseFloat(balance||'0').toFixed(2)}</div>");
lines.push("          </div>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{fontSize:9,padding:'8px 12px'}}>Get USDC ↗</button></a>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      {/* Send form */}");
lines.push("      <div style={{marginBottom:8}}>");
lines.push("        <label className='v-label'>Send to Address</label>");
lines.push("        <input className='v-input' placeholder='0x...' value={to} onChange={e => setTo(e.target.value)} autoComplete='off' />");
lines.push("      </div>");
lines.push("      <div style={{marginBottom:16}}>");
lines.push("        <label className='v-label'>Amount (USDC)</label>");
lines.push("        <input className='v-input' type='number' placeholder='e.g. 5.00' value={amount} onChange={e => setAmount(e.target.value)} />");
lines.push("      </div>");
lines.push("      {error && <div style={{fontSize:11,fontStyle:'italic',color:'var(--err)',marginBottom:10,border:'1px solid rgba(232,112,112,0.2)',padding:'8px 12px'}}>{error}</div>}");
lines.push("      {sendResult && <div style={{fontSize:10,fontStyle:'italic',color:'var(--gr)',marginBottom:10,border:'1px solid var(--gr3)',padding:'8px 12px',wordBreak:'break-all'}}>{sendResult}</div>}");
lines.push("      <button onClick={handleSend} disabled={sending} className='btn-primary' style={{width:'100%',padding:'12px',fontSize:10,marginBottom:10}}>{sending?'Sending...':'Send USDC on Arc →'}</button>");
lines.push("      <div style={{display:'flex',gap:8}}>");
lines.push("        <a href={`https://testnet.arcscan.app/address/${wallet.address}`} target='_blank' rel='noopener noreferrer' style={{flex:1}}><button className='btn-ghost' style={{width:'100%',fontSize:9,padding:'8px'}}>Arc Explorer ↗</button></a>");
lines.push("        <button onClick={onLogout} className='btn-danger' style={{flex:1,fontSize:9,padding:'8px'}}>Log Out</button>");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/components/CircleWalletDashboard.tsx', lines.join('\n'), 'utf8');
console.log('CircleWalletDashboard done:', fs.existsSync('app/components/CircleWalletDashboard.tsx'));
