const fs = require('fs');
fs.mkdirSync('app/checkout', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import Link from 'next/link';");
lines.push("import { Suspense, useState } from 'react';");
lines.push("import { useSearchParams, useRouter } from 'next/navigation';");
lines.push("import { useAccount, useSendTransaction } from 'wagmi';");
lines.push("import { parseUnits } from 'viem';");
lines.push("import { saveOrder, createEscrowJob } from '../lib/supabase';");
lines.push("");
lines.push("function CheckoutContent() {");
lines.push("  const params = useSearchParams();");
lines.push("  const router = useRouter();");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const { sendTransactionAsync } = useSendTransaction();");
lines.push("  const store = params.get('store')||'';");
lines.push("  const product = params.get('product')||'';");
lines.push("  const price = Number(params.get('price')||0);");
lines.push("  const seller = (params.get('seller')||'0x70997970C51812dc3A010C7d01b50e0d17dc79C8') as `0x${string}`;");
lines.push("  const [step, setStep] = useState<'review'|'paying'|'success'|'error'>('review');");
lines.push("  const [txHash, setTxHash] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("");
lines.push("  const handleBuy = async () => {");
lines.push("    if (!isConnected||!address) { router.push('/join'); return; }");
lines.push("    setStep('paying');");
lines.push("    try {");
lines.push("      const hash = await sendTransactionAsync({ to: seller, value: parseUnits(price.toString(),18) });");
lines.push("      const order = await saveOrder({ buyer_wallet:address, seller_wallet:seller, product_name:product, amount:price, tx_hash:hash });");
lines.push("      await createEscrowJob({ order_id:order?.id, buyer_wallet:address, seller_wallet:seller, amount:price, tx_hash:hash });");
lines.push("      setTxHash(hash); setStep('success');");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message?.includes('rejected')?'Transaction rejected in wallet':'Transaction failed — please try again');");
lines.push("      setStep('error');");
lines.push("    }");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{maxWidth:520,margin:'0 auto',padding:'120px 56px 80px'}}>");
lines.push("        {step==='review'&&(");
lines.push("          <>");
lines.push("            <div className='v-eyebrow' style={{marginBottom:16}}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Buy Now</span></div>");
lines.push("            <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,letterSpacing:'-0.01em',lineHeight:0.94,color:'var(--w)',marginBottom:32}}>Confirm Purchase</h1>");
lines.push("            <div className='v-order-card' style={{marginBottom:24}}>");
lines.push("              <div style={{padding:'28px',borderBottom:'1px solid var(--b1)'}}>");
lines.push("                <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--w18)',marginBottom:6}}>Product</div>");
lines.push("                <div style={{fontFamily:\"'Cormorant',serif\",fontSize:22,fontWeight:400,color:'var(--w85)',marginBottom:4}}>{product}</div>");
lines.push("                <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em'}}>{store}</div>");
lines.push("              </div>");
lines.push("              <div style={{padding:'20px 28px',display:'flex',justifyContent:'space-between',alignItems:'center'}}>");
lines.push("                <span style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--w18)'}}>Total</span>");
lines.push("                <span style={{fontFamily:\"'Cormorant',serif\",fontSize:32,fontWeight:300,color:'var(--a2)'}}>{'$'}{price}{' USDC'}</span>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            <div style={{border:'1px solid var(--b1)',padding:'14px 18px',marginBottom:24,display:'flex',alignItems:'center',gap:10}}>");
lines.push("              <div className='v-arc-badge-dot'/>");
lines.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.7}}>Funds held in ERC-8183 escrow until delivery confirmed. 48-hour dispute window.</div>");
lines.push("            </div>");
lines.push("            <button onClick={handleBuy} className='btn-primary' style={{width:'100%',padding:'18px',fontSize:12}}>{'Pay $'}{price}{' USDC on Arc →'}</button>");
lines.push("            <div style={{textAlign:'center',marginTop:16}}><Link href={'/store/'+store} style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',textDecoration:'none'}}>← Back to Store</Link></div>");
lines.push("          </>");
lines.push("        )}");
lines.push("        {step==='paying'&&(");
lines.push("          <div style={{textAlign:'center',padding:'4rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,color:'var(--w)',marginBottom:16}}>Processing</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:32}}>Approve the payment in your wallet</div>");
lines.push("            <div className='v-spinner' style={{margin:'0 auto'}}/>");
lines.push("          </div>)}");
lines.push("        {step==='success'&&(");
lines.push("          <div style={{textAlign:'center',padding:'3rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'5rem',fontWeight:300,color:'var(--a2)',lineHeight:1,marginBottom:16}}>✓</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,color:'var(--w)',marginBottom:12}}>Payment Confirmed</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.8,marginBottom:8}}>Transaction confirmed on Arc Testnet</div>");
lines.push("            <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em',marginBottom:8}}>ERC-8183 escrow active · Release in 48 hours</div>");
lines.push("            {txHash&&<div style={{fontSize:10,fontWeight:300,color:'var(--a)',letterSpacing:'0.06em',wordBreak:'break-all',marginBottom:32,padding:'10px 16px',border:'1px solid var(--b1)',background:'var(--bg2)'}}>{txHash}</div>}");
lines.push("            <div style={{display:'flex',flexDirection:'column',gap:12,maxWidth:260,margin:'0 auto'}}>");
lines.push("              <Link href='/profile'><button className='btn-primary' style={{width:'100%',padding:'14px',fontSize:10}}>View My Orders</button></Link>");
lines.push("              <Link href='/marketplace'><button className='btn-ghost' style={{width:'100%',padding:'14px',fontSize:10}}>Keep Shopping</button></Link>");
lines.push("            </div>");
lines.push("          </div>)}");
lines.push("        {step==='error'&&(");
lines.push("          <div style={{textAlign:'center',padding:'3rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'4rem',fontWeight:300,color:'var(--err)',lineHeight:1,marginBottom:16}}>✕</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(24px,4vw,36px)',fontWeight:300,color:'var(--w)',marginBottom:8}}>Transaction Failed</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.75,marginBottom:28}}>{error}</div>");
lines.push("            <button onClick={()=>setStep('review')} className='btn-amber-ghost'>Try Again</button>");
lines.push("          </div>)}");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
lines.push("");
lines.push("export default function Checkout() {");
lines.push("  return <Suspense><CheckoutContent /></Suspense>;");
lines.push("}");
fs.writeFileSync('app/checkout/page.tsx', lines.join('\n'), 'utf8');
console.log('Checkout done:', fs.existsSync('app/checkout/page.tsx'));
