const fs = require('fs');
fs.mkdirSync('app/cart/checkout', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../../Nav';");
lines.push("import { useState } from 'react';");
lines.push("import { useCart } from '../../lib/cart';");
lines.push("import { useAccount, useSendTransaction } from 'wagmi';");
lines.push("import { parseUnits } from 'viem';");
lines.push("import { saveOrder, createEscrowJob, upsertSellerReputation } from '../../lib/supabase';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("export default function CartCheckout() {");
lines.push("  const { items, clearCart, total } = useCart();");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const { sendTransactionAsync } = useSendTransaction();");
lines.push("  const router = useRouter();");
lines.push("  const [step, setStep] = useState<'review'|'paying'|'success'|'error'>('review');");
lines.push("  const [currentSeller, setCurrentSeller] = useState('');");
lines.push("  const [currentItem, setCurrentItem] = useState(0);");
lines.push("  const [totalItems, setTotalItems] = useState(0);");
lines.push("  const [txHashes, setTxHashes] = useState<string[]>([]);");
lines.push("  const [error, setError] = useState('');");
lines.push("");
lines.push("  const grouped: Record<string,typeof items> = items.reduce((acc:any,item)=>{ if(!acc[item.storeSlug])acc[item.storeSlug]=[]; acc[item.storeSlug].push(item); return acc; },{});");
lines.push("");
lines.push("  const handleCheckout = async () => {");
lines.push("    if (!isConnected||!address) { router.push('/join'); return; }");
lines.push("    if (items.length===0) return;");
lines.push("    setStep('paying');");
lines.push("    const hashes: string[] = [];");
lines.push("    const sellers = Object.entries(grouped);");
lines.push("    setTotalItems(sellers.length);");
lines.push("    try {");
lines.push("      for (let i=0;i<sellers.length;i++) {");
lines.push("        const [,storeItems] = sellers[i];");
lines.push("        setCurrentSeller(storeItems[0].storeName);");
lines.push("        setCurrentItem(i+1);");
lines.push("        const sellerWallet = storeItems[0].sellerWallet as `0x${string}`;");
lines.push("        const storeTotal = storeItems.reduce((s,item)=>s+item.price*item.quantity,0);");
lines.push("        const hash = await sendTransactionAsync({ to:sellerWallet, value:parseUnits(storeTotal.toString(),18) });");
lines.push("        hashes.push(hash);");
lines.push("        for (const item of storeItems) {");
lines.push("          const order = await saveOrder({ buyer_wallet:address, seller_wallet:sellerWallet, product_name:item.productName+(item.quantity>1?' x'+item.quantity:''), amount:item.price*item.quantity, tx_hash:hash });");
lines.push("          await createEscrowJob({ order_id:order?.id, buyer_wallet:address, seller_wallet:sellerWallet, amount:item.price*item.quantity, tx_hash:hash });");
lines.push("        }");
lines.push("        await upsertSellerReputation(sellerWallet,{total_sales:storeItems.length});");
lines.push("      }");
lines.push("      setTxHashes(hashes); clearCart(); setStep('success');");
lines.push("    } catch(e:any) {");
lines.push("      setError(e?.message?.includes('rejected')?'Transaction rejected in wallet':'Transaction failed — please try again');");
lines.push("      setStep('error');");
lines.push("    }");
lines.push("  };");
lines.push("");
lines.push("  if (items.length===0&&step==='review') return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}><Nav />");
lines.push("    <div style={{maxWidth:520,margin:'0 auto',padding:'120px 56px 80px',textAlign:'center'}}>");
lines.push("      <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'3rem',fontWeight:300,color:'var(--w)',marginBottom:16}}>{'🛒'}</div>");
lines.push("      <div style={{fontFamily:\"'Cormorant',serif\",fontSize:28,fontWeight:300,color:'var(--w)',marginBottom:24}}>Cart is Empty</div>");
lines.push("      <Link href='/marketplace'><button className='btn-primary'>Browse Marketplace</button></Link>");
lines.push("    </div></main>");
lines.push("  );");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{maxWidth:580,margin:'0 auto',padding:'120px 56px 80px'}}>");
lines.push("        {step==='review'&&(");
lines.push("          <>");
lines.push("            <div className='v-eyebrow' style={{marginBottom:16}}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Checkout</span></div>");
lines.push("            <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,letterSpacing:'-0.01em',lineHeight:0.94,color:'var(--w)',marginBottom:40}}>Order Summary</h1>");
lines.push("            {Object.entries(grouped).map(([slug,storeItems])=>{");
lines.push("              const storeTotal = storeItems.reduce((s,item)=>s+item.price*item.quantity,0);");
lines.push("              return (");
lines.push("                <div key={slug} style={{border:'1px solid var(--b1)',marginBottom:16,overflow:'hidden'}}>");
lines.push("                  <div className='v-block-head' style={{color:'var(--a)'}}>{'🏪 '}{storeItems[0].storeName}</div>");
lines.push("                  {storeItems.map(item=>(");
lines.push("                    <div key={item.id} style={{display:'flex',alignItems:'center',gap:16,padding:'16px 20px',borderBottom:'1px solid var(--b1)'}}>");
lines.push("                      {item.image?<img src={item.image} alt={item.productName} style={{width:48,height:48,objectFit:'cover',flexShrink:0,border:'1px solid var(--b1)'}}/>:<div style={{width:48,height:48,background:'var(--s1)',border:'1px solid var(--b1)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'1.2rem',flexShrink:0}}>{'📦'}</div>}");
lines.push("                      <div style={{flex:1}}><div style={{fontFamily:\"'Cormorant',serif\",fontSize:16,fontWeight:300,color:'var(--w85)',marginBottom:4}}>{item.productName}</div><div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em'}}>{'Qty: '}{item.quantity}{' · $'}{item.price}{' each'}</div></div>");
lines.push("                      <div style={{fontFamily:\"'Cormorant',serif\",fontSize:18,fontWeight:300,color:'var(--a2)'}}>{'$'}{(item.price*item.quantity).toFixed(2)}</div>");
lines.push("                    </div>))}");
lines.push("                  <div style={{padding:'12px 20px',display:'flex',justifyContent:'space-between',background:'var(--bg2)'}}>");
lines.push("                    <span style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--w18)'}}>Store total</span>");
lines.push("                    <span style={{fontFamily:\"'Cormorant',serif\",fontSize:16,fontWeight:300,color:'var(--a2)'}}>{'$'}{storeTotal.toFixed(2)}{' USDC'}</span>");
lines.push("                  </div>");
lines.push("                </div>);");
lines.push("            })}");
lines.push("            <div style={{border:'1px solid var(--b2)',padding:'24px',marginBottom:20,background:'var(--bg2)',position:'relative',overflow:'hidden'}}>");
lines.push("              <div style={{position:'absolute',top:0,left:'20%',right:'20%',height:1,background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)'}}/>"); 
lines.push("              <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end'}}>");
lines.push("                <div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--w18)',marginBottom:4}}>Grand Total</div><div style={{fontFamily:\"'Cormorant',serif\",fontSize:40,fontWeight:300,color:'var(--a2)',lineHeight:1}}>{'$'}{total().toFixed(2)}</div></div>");
lines.push("                <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em'}}>USDC · Arc Testnet</div>");
lines.push("              </div>");
lines.push("              {Object.keys(grouped).length>1&&<div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',marginTop:12,borderTop:'1px solid var(--b1)',paddingTop:12,letterSpacing:'0.08em'}}>{'⚡ '}{Object.keys(grouped).length}{' separate wallet approvals — one per store'}</div>}");
lines.push("            </div>");
lines.push("            <div style={{border:'1px solid var(--b1)',padding:'14px 18px',marginBottom:24,display:'flex',alignItems:'center',gap:10}}>");
lines.push("              <div className='v-arc-badge-dot'/>");
lines.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.7}}>Funds locked in ERC-8183 escrow until delivery confirmed. 48-hour dispute window.</div>");
lines.push("            </div>");
lines.push("            <button onClick={handleCheckout} className='btn-primary' style={{width:'100%',padding:'18px',fontSize:12}}>{'Pay $'}{total().toFixed(2)}{' USDC on Arc →'}</button>");
lines.push("            <div style={{textAlign:'center',marginTop:16}}><Link href='/marketplace' style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',textDecoration:'none'}}>← Continue Shopping</Link></div>");
lines.push("          </>");
lines.push("        )}");
lines.push("        {step==='paying'&&(");
lines.push("          <div style={{textAlign:'center',padding:'4rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,color:'var(--w)',marginBottom:16}}>Processing Payment</div>");
lines.push("            <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--a)',letterSpacing:'0.16em',textTransform:'uppercase',marginBottom:8}}>{'Store '}{currentItem}{' of '}{totalItems}</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:32}}>{'Approve payment to '}{currentSeller}{' in your wallet'}</div>");
lines.push("            <div className='v-spinner' style={{margin:'0 auto'}}/>");
lines.push("          </div>)}");
lines.push("        {step==='success'&&(");
lines.push("          <div style={{textAlign:'center',padding:'3rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'5rem',fontWeight:300,color:'var(--a2)',lineHeight:1,marginBottom:16}}>✓</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,color:'var(--w)',marginBottom:12}}>All Payments Confirmed</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.8,marginBottom:8}}>{txHashes.length}{' transaction'}{txHashes.length>1?'s':''}{' confirmed on Arc Testnet'}</div>");
lines.push("            <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em',marginBottom:36}}>ERC-8183 escrow active · Funds release in 48 hours</div>");
lines.push("            <div style={{display:'flex',flexDirection:'column',gap:12,maxWidth:260,margin:'0 auto'}}>");
lines.push("              <Link href='/profile'><button className='btn-primary' style={{width:'100%',padding:'14px',fontSize:10}}>View My Orders</button></Link>");
lines.push("              <Link href='/marketplace'><button className='btn-ghost' style={{width:'100%',padding:'14px',fontSize:10}}>Keep Shopping</button></Link>");
lines.push("            </div>");
lines.push("          </div>)}");
lines.push("        {step==='error'&&(");
lines.push("          <div style={{textAlign:'center',padding:'3rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'4rem',fontWeight:300,color:'var(--err)',lineHeight:1,marginBottom:16}}>✕</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(24px,4vw,36px)',fontWeight:300,color:'var(--w)',marginBottom:8}}>Transaction Failed</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.75,marginBottom:28}}>{error}</div>");
lines.push("            <button onClick={()=>setStep('review')} className='btn-amber-ghost'>Try Again</button>");
lines.push("          </div>)}");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/cart/checkout/page.tsx', lines.join('\n'), 'utf8');
console.log('Cart checkout done:', fs.existsSync('app/cart/checkout/page.tsx'));
