const fs = require('fs');
fs.mkdirSync('app/edit-profile', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import { useState, useEffect, useRef, Suspense } from 'react';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useRouter, useSearchParams } from 'next/navigation';");
lines.push("import { getProfile, saveProfile, uploadAvatar } from '../lib/supabase';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("function EditProfileContent() {");
lines.push("  const { address } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const params = useSearchParams();");
lines.push("  const role = (params.get('role')||'buyer') as 'buyer'|'seller';");
lines.push("  const avatarRef = useRef<HTMLInputElement>(null);");
lines.push("  const [form, setForm] = useState({ display_name:'', bio:'', x_handle:'' });");
lines.push("  const [avatarFile, setAvatarFile] = useState<File|null>(null);");
lines.push("  const [avatarPreview, setAvatarPreview] = useState('');");
lines.push("  const [loading, setLoading] = useState(true);");
lines.push("  const [saving, setSaving] = useState(false);");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [success, setSuccess] = useState('');");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    if (!address) return;");
lines.push("    getProfile(address, role).then(p => {");
lines.push("      if (p) { setForm({ display_name:p.display_name||'', bio:p.bio||'', x_handle:p.x_handle||'' }); setAvatarPreview(p.avatar_url||''); }");
lines.push("      setLoading(false);");
lines.push("    });");
lines.push("  }, [address, role]);");
lines.push("");
lines.push("  const handleSave = async () => {");
lines.push("    if (!address) return;");
lines.push("    if (!form.display_name) { setError('Display name required'); return; }");
lines.push("    setSaving(true); setError(''); setSuccess('');");
lines.push("    try {");
lines.push("      let avatar_url = avatarPreview;");
lines.push("      if (avatarFile) avatar_url = await uploadAvatar(address, avatarFile);");
lines.push("      await saveProfile({ wallet_address:address, role, display_name:form.display_name, bio:form.bio, avatar_url, x_handle:form.x_handle });");
lines.push("      setSuccess('Profile updated!'); setTimeout(()=>setSuccess(''),2500);");
lines.push("    } catch(e:any) { setError(e?.message||'Something went wrong'); }");
lines.push("    finally { setSaving(false); }");
lines.push("  };");
lines.push("");
lines.push("  if (loading) return <main style={{minHeight:'100vh',background:'var(--bg)',display:'flex',alignItems:'center',justifyContent:'center'}}><Nav /><div className='v-spinner'/></main>;");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{maxWidth:560,margin:'0 auto',padding:'120px 56px 80px'}}>");
lines.push("        <div className='v-eyebrow' style={{marginBottom:16}}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Edit {role==='seller'?'Seller':'Buyer'} Profile</span></div>");
lines.push("        <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,letterSpacing:'-0.01em',lineHeight:0.94,color:'var(--w)',marginBottom:32}}>Update your<br/><em style={{fontStyle:'italic',background:'linear-gradient(120deg,var(--a),var(--a2))',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text'}}>profile</em></h1>");
lines.push("        <div style={{marginBottom:28,display:'flex',alignItems:'center',gap:20}}>");
lines.push("          <div onClick={()=>avatarRef.current?.click()} style={{width:72,height:72,borderRadius:'50%',border:'1px dashed var(--b2)',display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',overflow:'hidden',transition:'border-color 0.35s',background:'var(--bg2)',flexShrink:0}} onMouseEnter={e=>(e.currentTarget.style.borderColor='var(--a)')} onMouseLeave={e=>(e.currentTarget.style.borderColor='var(--b2)')}>"); 
lines.push("            {avatarPreview?<img src={avatarPreview} alt='avatar' style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<div style={{textAlign:'center'}}><div style={{fontSize:'1.5rem'}}>{'📷'}</div><div style={{fontSize:8,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',marginTop:4}}>Change</div></div>}");
lines.push("          </div>");
lines.push("          <input ref={avatarRef} type='file' accept='image/*' onChange={e=>{const f=e.target.files?.[0];if(!f)return;setAvatarFile(f);setAvatarPreview(URL.createObjectURL(f));}} style={{display:'none'}}/>");
lines.push("          <div style={{flex:1}}><div style={{fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.6}}>Click to change your profile photo.</div></div>");
lines.push("        </div>");
lines.push("        <div style={{border:'1px solid var(--b1)',marginBottom:24}}>");
lines.push("          <div className='v-block-head'>Profile Info</div>");
lines.push("          <div style={{padding:20}}>");
lines.push("            <div className='v-field'><label className='v-label'>Display name *</label><input className='v-input' value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></div>");
lines.push("            <div className='v-field'><label className='v-label'>Bio</label><textarea className='v-textarea' value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/></div>");
lines.push("            <div className='v-field' style={{marginBottom:0}}><label className='v-label'>X (Twitter) handle</label><input className='v-input' placeholder='@yourhandle' value={form.x_handle} onChange={e=>setForm({...form,x_handle:e.target.value})}/></div>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("        {error&&<div style={{border:'1px solid rgba(232,112,112,0.3)',background:'rgba(232,112,112,0.08)',padding:'10px 16px',fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--err)',marginBottom:16}}>{error}</div>}");
lines.push("        {success&&<div style={{border:'1px solid rgba(143,196,152,0.3)',background:'rgba(143,196,152,0.08)',padding:'10px 16px',fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--gr)',marginBottom:16}}>{success}</div>}");
lines.push("        <button onClick={handleSave} disabled={saving} className='btn-primary' style={{width:'100%',padding:'18px',fontSize:12}}>{saving?'Saving...':'Save Changes →'}</button>");
lines.push("        <div style={{textAlign:'center',marginTop:16}}><Link href='/profile' style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',textDecoration:'none'}}>← Back to Profile</Link></div>");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
lines.push("");
lines.push("export default function EditProfile() {");
lines.push("  return <Suspense><EditProfileContent /></Suspense>;");
lines.push("}");
fs.writeFileSync('app/edit-profile/page.tsx', lines.join('\n'), 'utf8');
console.log('Edit profile done:', fs.existsSync('app/edit-profile/page.tsx'));
