const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Nav from './Nav';");
lines.push("import Link from 'next/link';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import { useState } from 'react';");
lines.push("import { getAllProfiles, getStoreByWallet } from './lib/supabase';");
lines.push("");
lines.push("const TICKS = ['Arc Testnet|0% Platform Fees','USDC Native|Sub-Second Settlement','ERC-8183|Escrow Protection','ERC-8004|Onchain Identity','Commerce Unchained|No Middlemen','Global Reach|Borderless Payments'];");
lines.push("const STRIP = [");
lines.push("  { slug:'nour-atelier', cat:'Fashion', name:'Nour Atelier', price:'From $38 USDC', bg:'linear-gradient(145deg,#1a1508,#3d2e14,#1a1508)' },");
lines.push("  { slug:'bytedrop', cat:'Digital', name:'ByteDrop', price:'From $19 USDC', bg:'linear-gradient(145deg,#080f1a,#142035,#080f1a)' },");
lines.push("  { slug:'solar-prints', cat:'Art', name:'Solar Prints', price:'From $40 USDC', bg:'linear-gradient(145deg,#0f0810,#261630,#0f0810)' },");
lines.push("  { slug:'soundvault', cat:'Music', name:'SoundVault', price:'From $20 USDC', bg:'linear-gradient(145deg,#050d08,#122018,#050d08)' },");
lines.push("];");
lines.push("const FEATURED = [");
lines.push("  { slug:'nour-atelier', name:'Gold Crescent Ring', seller:'Nour Atelier', price:45, cat:'Fashion', glow:'a', bg:'linear-gradient(145deg,#1e1608,#3d2e14)' },");
lines.push("  { slug:'bytedrop', name:'Dashboard UI Kit', seller:'ByteDrop', price:49, cat:'Digital', glow:'s', bg:'linear-gradient(145deg,#060d18,#142035)' },");
lines.push("  { slug:'solar-prints', name:'Desert Bloom Print', seller:'Solar Prints', price:55, cat:'Art', glow:'a', bg:'linear-gradient(145deg,#100810,#261630)' },");
lines.push("  { slug:'soundvault', name:'Lo-Fi Essentials', seller:'SoundVault', price:25, cat:'Music', glow:'s', bg:'linear-gradient(145deg,#040c08,#122018)' },");
lines.push("];");
lines.push("const SELLERS = [");
lines.push("  { rank:'I', init:'N', name:'Nour Atelier', meta:'Fashion · 12 products · 48 sales', score:'9.8' },");
lines.push("  { rank:'II', init:'B', name:'ByteDrop', meta:'Digital · 8 products · 31 sales', score:'9.6' },");
lines.push("  { rank:'III', init:'S', name:'Solar Prints', meta:'Art · 24 products · 27 sales', score:'9.4' },");
lines.push("  { rank:'IV', init:'K', name:'Kode Studio', meta:'Services · 6 products · 19 sales', score:'9.2' },");
lines.push("  { rank:'V', init:'U', name:'Umami Box', meta:'Food · 4 products · 14 sales', score:'9.0' },");
lines.push("];");
lines.push("");
lines.push("export default function Home() {");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const [loading, setLoading] = useState(false);");
lines.push("");
lines.push("  const handleGetStarted = async () => {");
lines.push("    if (!isConnected) { router.push('/join'); return; }");
lines.push("    setLoading(true);");
lines.push("    try {");
lines.push("      const [profiles, store] = await Promise.all([getAllProfiles(address!), getStoreByWallet(address!)]);");
lines.push("      const hasSeller = profiles.some((p:any) => p.role==='seller');");
lines.push("      const hasBuyer = profiles.some((p:any) => p.role==='buyer');");
lines.push("      if (hasSeller && hasBuyer) router.push('/welcome');");
lines.push("      else if (hasSeller || hasBuyer) router.push('/profile');");
lines.push("      else router.push('/onboarding');");
lines.push("    } catch { router.push('/onboarding'); }");
lines.push("    finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const Footer = () => (");
lines.push("    <footer className='v-footer'>");
lines.push("      <div style={{ opacity:0.5, display:'flex', alignItems:'center', gap:10 }}>");
lines.push("        <div className='v-logo-emblem' style={{ width:24, height:24 }}><span className='v-logo-v' style={{ fontSize:11 }}>V</span></div>");
lines.push("        <span style={{ fontFamily:\"'Cormorant',serif\", fontSize:15, fontWeight:300, letterSpacing:'0.22em', textTransform:'uppercase', color:'var(--w85)' }}>Vendra</span>");
lines.push("      </div>");
lines.push("      <div className='v-footer-copy'>© 2026 Vendra · Built on Arc Testnet · Powered by USDC · 0% Fees</div>");
lines.push("      <div className='v-footer-links'><Link href='/marketplace'>Marketplace</Link><Link href='/store/create'>Sellers</Link><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'>Faucet</a></div>");
lines.push("    </footer>");
lines.push("  );");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)' }}>");
lines.push("      <Nav />");
lines.push("");
lines.push("      {/* HERO */}");
lines.push("      <section className='v-hero'>");
lines.push("        <div className='v-atm'>");
lines.push("          <div className='v-orb-a'/><div className='v-orb-sl-l'/><div className='v-orb-sl-r'/>");
lines.push("          <div className='v-grid-overlay'/><div className='v-hairline'/>");
lines.push("        </div>");
lines.push("        <div style={{ position:'relative', zIndex:1, width:'100%', maxWidth:1000 }}>");
lines.push("          <div className='v-arc-badge' style={{ marginBottom:40 }}>");
lines.push("            <div className='v-arc-badge-dot'/>");
lines.push("            <span className='v-arc-badge-text'>Live on Arc Testnet · Powered by USDC</span>");
lines.push("          </div>");
lines.push("          <div className='v-hero-eyebrow'>");
lines.push("            <div className='v-eyebrow-line'/>");
lines.push("            <span style={{ fontFamily:\"'DM Sans',sans-serif\", fontSize:10, fontWeight:300, fontStyle:'italic', letterSpacing:'0.22em', textTransform:'uppercase', color:'var(--a)' }}>Commerce Unchained</span>");
lines.push("            <div className='v-eyebrow-line'/>");
lines.push("          </div>");
lines.push("          <h1 className='v-hero-h1'>");
lines.push("            <span className='v-h1-line1'>The marketplace</span>");
lines.push("            <span className='v-h1-line2'>everyone deserves</span>");
lines.push("            <span className='v-h1-line3'>Commerce Unchained</span>");
lines.push("          </h1>");
lines.push("          <p className='v-hero-sub'>Launch your store in minutes. Sell anything. Get paid instantly in USDC — with 0% platform fees and fraud protection baked into the protocol.</p>");
lines.push("          <div className='v-hero-actions'>");
lines.push("            <button className='btn-primary' onClick={handleGetStarted} disabled={loading}>{loading?'Loading...':isConnected?'Open Your Store':'Get Started'}</button>");
lines.push("            <Link href='/marketplace'><button className='btn-ghost'>Explore Marketplace</button></Link>");
lines.push("          </div>");
lines.push("          <div className='v-stats-bar'>");
lines.push("            <div className='v-stat'><div className='v-stat-val amber'>0%</div><div className='v-stat-label'>Platform Fees</div></div>");
lines.push("            <div className='v-stat'><div className='v-stat-val'>&lt;2s</div><div className='v-stat-label'>Settlement</div></div>");
lines.push("            <div className='v-stat'><div className='v-stat-val'>USDC</div><div className='v-stat-label'>Native Currency</div></div>");
lines.push("            <div className='v-stat'><div className='v-stat-val amber'>∞</div><div className='v-stat-label'>Global Reach</div></div>");
lines.push("          </div>");
lines.push("          <div className='v-showcase-card'>");
lines.push("            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:20 }}>");
lines.push("              <div><div className='v-sc-label'>Store Balance</div><div className='v-sc-bal'>$2,847.50</div><div className='v-sc-network'>USDC · Arc Testnet · 0x3a9f...6ef4</div></div>");
lines.push("              <div className='v-sc-badge'>Settled</div>");
lines.push("            </div>");
lines.push("            <div className='v-sc-divider'/>");
lines.push("            <div className='v-sc-label' style={{ marginBottom:12 }}>Recent Transactions</div>");
lines.push("            {[{icon:'💍',dot:'a',name:'Gold Crescent Ring — Nour Atelier',sub:'Apr 12 · 0x4a7f...8f1a · Settled in 1.2s',amt:'+$45.00'},{icon:'🎵',dot:'s',name:'Lo-Fi Essentials — SoundVault',sub:'Apr 12 · 0x9f2a...cc33 · Settled in 0.9s',amt:'+$25.00'},{icon:'🎨',dot:'a',name:'Desert Bloom Print — Solar Prints',sub:'Apr 11 · 0x7c3f...2e91 · Settled in 1.4s',amt:'+$55.00'}].map(tx=>(");
lines.push("              <div key={tx.name} className='v-sc-row'>");
lines.push("                <div className='v-sc-row-l'><div className={'v-sc-dot v-sc-dot-'+tx.dot}>{tx.icon}</div><div><div className='v-sc-tx-name'>{tx.name}</div><div className='v-sc-tx-sub'>{tx.sub}</div></div></div>");
lines.push("                <div className='v-sc-amount'>{tx.amt}</div>");
lines.push("              </div>))}");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </section>");
lines.push("");
lines.push("      {/* TICKER */}");
lines.push("      <div className='v-ticker-wrap'>");
lines.push("        <div className='v-ticker-track'>");
lines.push("          {[...TICKS,...TICKS].map((t,i)=>{ const [a,b]=t.split('|'); return <div key={i} className='v-ticker-item'><span>{a}</span><div className='v-ticker-dot'/>{b}<div className='v-ticker-dot'/></div>; })}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* IMAGE STRIP */}");
lines.push("      <div className='v-strip-section'>");
lines.push("        <div className='v-strip-ghost'><span className='v-strip-ghost-text'>Vendra</span></div>");
lines.push("        <div className='v-strip-grid'>");
lines.push("          {STRIP.map(s=>(");
lines.push("            <Link key={s.slug} href={'/store/'+s.slug} style={{ display:'block' }}>");
lines.push("              <div className='v-strip-col'>");
lines.push("                <div className='v-strip-col-bg' style={{ background:s.bg }}/>");
lines.push("                <div className='v-strip-col-inner'>");
lines.push("                  <div className='v-strip-col-cat'>{s.cat}</div>");
lines.push("                  <div className='v-strip-col-name'>{s.name}</div>");
lines.push("                  <div className='v-strip-col-price'>{s.price}</div>");
lines.push("                </div>");
lines.push("              </div>");
lines.push("            </Link>))}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* FEATURED PRODUCTS */}");
lines.push("      <div style={{ background:'var(--bg2)', padding:'1px 0' }}>");
lines.push("        <div className='v-section'>");
lines.push("          <div className='v-eyebrow'><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Live Listings</span></div>");
lines.push("          <div className='v-section-head'>");
lines.push("            <h2 className='v-section-title'>Featured <em>products</em></h2>");
lines.push("            <Link href='/marketplace' className='v-view-all'>View all <span>→</span></Link>");
lines.push("          </div>");
lines.push("          <div className='v-product-grid'>");
lines.push("            {FEATURED.map(p=>(");
lines.push("              <Link key={p.slug+p.name} href={'/store/'+p.slug} style={{ textDecoration:'none' }}>");
lines.push("                <div className='v-pcard'>");
lines.push("                  <div className='v-pcard-img'>");
lines.push("                    <div className='v-pcard-img-fill' style={{ background:p.bg }}/>");
lines.push("                    <div className='v-pcard-overlay'/>");
lines.push("                    <div className={'v-pcard-hover-glow v-phg-'+p.glow}/>");
lines.push("                    <div className='v-pcard-cat'>{p.cat}</div>");
lines.push("                    {p.glow==='a'&&<div className='v-pcard-verified'>Verified</div>}");
lines.push("                  </div>");
lines.push("                  <div className='v-pcard-body'>");
lines.push("                    <div className='v-pcard-name'>{p.name}</div>");
lines.push("                    <div className='v-pcard-seller'>{p.seller} · Arc Testnet</div>");
lines.push("                    <div className='v-pcard-foot'>");
lines.push("                      <div className='v-pcard-price'>{'$'}{p.price}{' USDC'}</div>");
lines.push("                      <button className='v-pcard-buy'>Buy Now</button>");
lines.push("                    </div>");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("              </Link>))}");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* WHY VENDRA BENTO */}");
lines.push("      <div style={{ background:'var(--bg)' }}>");
lines.push("        <div className='v-section'>");
lines.push("          <div className='v-eyebrow'><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Why Vendra</span></div>");
lines.push("          <div className='v-section-head'><h2 className='v-section-title'>Built differently.<br/><em>By design.</em></h2></div>");
lines.push("          <div className='v-bento-grid'>");
lines.push("            <div className='v-bcard'><div className='v-bcard-num'>01 — Settlement</div><div className='v-bcard-title'>Paid in under two seconds</div><div className='v-bcard-body'>Arc's Malachite consensus engine makes every transaction final in under two seconds. Sellers get paid the moment buyers confirm.</div><div className='v-bcard-stat'>&lt;2s</div><div className='v-bcard-stat-label'>Settlement Time · Arc Testnet</div></div>");
lines.push("            <div className='v-bcard'><div className='v-bcard-num'>02 — Fees</div><div className='v-bcard-title'>Zero percent. Zero exceptions.</div><div className='v-bcard-body'>Traditional platforms take 6–20% of every sale. Vendra takes nothing. Arc's low gas costs make this viable for the first time at scale.</div><div className='v-bcard-stat'>0%</div><div className='v-bcard-stat-label'>Platform Fee · Forever</div></div>");
lines.push("            <div className='v-bcard v-bcard-wide'>");
lines.push("              <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:64, alignItems:'center' }}>");
lines.push("                <div><div className='v-bcard-num'>03 — Comparison</div><div className='v-bcard-title'>What you keep vs. what they take</div><div className='v-bcard-body'>Every platform takes a cut. eBay, Etsy, Poshmark — all charging sellers with no real alternative. Until now.</div></div>");
lines.push("                <div className='v-fee-bars'>");
lines.push("                  {[{label:'Vendra',w:'2%',cls:'amber',pct:'0%'},{label:'Facebook',w:'25%',cls:'slate',pct:'5%'},{label:'Etsy',w:'39%',cls:'slate',pct:'6.5%'},{label:'eBay',w:'65%',cls:'dim',pct:'12.9%'},{label:'Poshmark',w:'100%',cls:'dim',pct:'20%'}].map(f=>(");
lines.push("                    <div key={f.label} className='v-fee-row'>");
lines.push("                      <div className='v-fee-label' style={f.cls==='amber'?{color:'var(--a)',fontWeight:500}:{}}>{f.label}</div>");
lines.push("                      <div className='v-fee-bar-wrap'><div className={'v-fee-bar-fill '+f.cls} style={{width:f.w}}/></div>");
lines.push("                      <div className={'v-fee-pct'+(f.cls==='amber'?' amber':'')}>{f.pct}</div>");
lines.push("                    </div>))}");
lines.push("                </div>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* FRAUD / ARC INTEGRATIONS */}");
lines.push("      <div className='v-editorial'>");
lines.push("        <div className='v-editorial-bg'/><div className='v-editorial-vignette'/><div className='v-editorial-orb'/>");
lines.push("        <div className='v-editorial-inner'>");
lines.push("          <div>");
lines.push("            <div className='v-arc-pill'><div className='v-arc-badge-dot' style={{width:4,height:4}}/>Protocol-Level Protection</div>");
lines.push("            <h2 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(36px,5vw,62px)', fontWeight:300, lineHeight:0.94, letterSpacing:'-0.01em', color:'var(--w)', marginBottom:24 }}>");
lines.push("              Fraud doesn't<br/><em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>stand a chance</em>");
lines.push("            </h2>");
lines.push("            <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:16, maxWidth:400 }}>Every payment on Vendra is held in an ERC-8183 smart contract escrow until the buyer confirms delivery. No fake listings. No payment reversals. The blockchain is the guarantor.</p>");
lines.push("            <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:36, maxWidth:400 }}>Onchain identity via ERC-8004 gives every seller a permanent, unfakeable reputation score built from their entire transaction history.</p>");
lines.push("            <Link href='/store/create'><button className='btn-amber-ghost'>Launch Your Store →</button></Link>");
lines.push("          </div>");
lines.push("          <div className='v-ed-stat-card'>");
lines.push("            <div className='v-ed-kpi'><div className='v-ed-kpi-val'>$0</div><div className='v-ed-kpi-label'>Fraud losses on Vendra</div></div>");
lines.push("            <div className='v-ed-kpi'><div className='v-ed-kpi-val' style={{color:'var(--sl2)',fontSize:36}}>ERC-8183</div><div className='v-ed-kpi-label'>Escrow Smart Contracts</div></div>");
lines.push("            <div className='v-ed-divider'/>");
lines.push("            <div className='v-ed-kpi' style={{marginBottom:0}}><div className='v-ed-kpi-val' style={{fontSize:36}}>ERC-8004</div><div className='v-ed-kpi-label'>Onchain Identity & Reputation</div></div>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* TOP SELLERS */}");
lines.push("      <div style={{ background:'var(--bg2)', padding:'1px 0' }}>");
lines.push("        <div className='v-section'>");
lines.push("          <div className='v-eyebrow'><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Top Sellers</span></div>");
lines.push("          <div className='v-section-head'><h2 className='v-section-title'>The stores<br/><em>setting the standard</em></h2></div>");
lines.push("          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:64 }}>");
lines.push("            <div>");
lines.push("              <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, maxWidth:380, marginBottom:32 }}>Every seller on Vendra owns their reputation onchain. It cannot be deleted, gamed, or transferred. What they build here, they keep forever.</p>");
lines.push("              <div className='v-promo-card'>");
lines.push("                <div className='v-promo-card-title'>Launch your store today</div>");
lines.push("                <div className='v-promo-card-body'>Deploy in under two minutes. $0.50 USDC deployment fee on Arc Testnet. Your storefront, your products, your wallet.</div>");
lines.push("                <Link href='/store/create'><button className='btn-amber-ghost'>Open Your Store →</button></Link>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            <div>");
lines.push("              {SELLERS.map(s=>(");
lines.push("                <div key={s.name} className='v-seller-item'>");
lines.push("                  <div className='v-seller-rank'>{s.rank}</div>");
lines.push("                  <div className='v-seller-avatar'>{s.init}</div>");
lines.push("                  <div style={{flex:1}}><div className='v-seller-name'>{s.name}</div><div className='v-seller-meta'>{s.meta}</div></div>");
lines.push("                  <div><div className='v-seller-score'>{s.score}</div><div className='v-seller-score-label'>Trust Score</div></div>");
lines.push("                </div>))}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* CTA */}");
lines.push("      <div style={{ background:'var(--bg)', borderTop:'1px solid var(--b1)' }}>");
lines.push("        <div style={{ padding:'112px 56px', textAlign:'center', maxWidth:640, margin:'0 auto' }}>");
lines.push("          <div className='v-cta-rule'><div className='v-cta-rule-line'/><div className='v-cta-rule-text'>Commerce Unchained</div><div className='v-cta-rule-line'/></div>");
lines.push("          <h2 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(40px,6vw,78px)', fontWeight:300, lineHeight:0.94, letterSpacing:'-0.01em', color:'var(--w)', marginBottom:20 }}>");
lines.push("            The future of commerce<br/><em style={{ display:'block', fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>is already here</em>");
lines.push("          </h2>");
lines.push("          <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:44 }}>Zero fees. Instant settlement. Fraud-proof escrow. Borderless payments. Everything legacy platforms promised and never delivered.</p>");
lines.push("          <div style={{ display:'flex', alignItems:'center', justifyContent:'center', gap:16 }}>");
lines.push("            <button className='btn-primary' onClick={handleGetStarted}>{isConnected?'Launch My Store':'Get Started'}</button>");
lines.push("            <Link href='/marketplace'><button className='btn-ghost'>Explore Marketplace</button></Link>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("");
lines.push("      <Footer />");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/page.tsx', lines.join('\n'), 'utf8');
console.log('Homepage done:', fs.existsSync('app/page.tsx'));
