const fs = require('fs');

// JOIN PAGE
fs.mkdirSync('app/join', { recursive: true });
const join = [];
join.push("'use client';");
join.push("import Nav from '../Nav';");
join.push("import { useAccount } from 'wagmi';");
join.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
join.push("import { useEffect } from 'react';");
join.push("import { useRouter } from 'next/navigation';");
join.push("import Link from 'next/link';");
join.push("");
join.push("export default function Join() {");
join.push("  const { isConnected } = useAccount();");
join.push("  const router = useRouter();");
join.push("  useEffect(() => { if (isConnected) router.push('/onboarding'); }, [isConnected, router]);");
join.push("  return (");
join.push("    <main style={{minHeight:'100vh',background:'var(--bg)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',position:'relative',overflow:'hidden'}}>");
join.push("      <Nav />");
join.push("      <div style={{position:'absolute',inset:0,pointerEvents:'none'}}>");
join.push("        <div style={{position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-60%)',width:800,height:600,background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)'}}/>");
join.push("        <div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)',backgroundSize:'96px 96px'}}/>");
join.push("      </div>");
join.push("      <div style={{position:'relative',zIndex:1,textAlign:'center',maxWidth:520,padding:'0 40px'}}>");
join.push("        <div className='v-arc-badge' style={{marginBottom:32,display:'inline-flex'}}><div className='v-arc-badge-dot'/><span className='v-arc-badge-text'>Arc Testnet · Powered by USDC</span></div>");
join.push("        <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(48px,8vw,96px)',fontWeight:300,lineHeight:0.90,letterSpacing:'-0.01em',color:'var(--w)',marginBottom:24}}>");
join.push("          Connect your<br/><em style={{fontStyle:'italic',background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text'}}>wallet</em>");
join.push("        </h1>");
join.push("        <p style={{fontSize:14,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.8,marginBottom:40}}>Your wallet is your identity on Vendra. No email. No password. Just your keys.</p>");
join.push("        <div style={{display:'flex',justifyContent:'center',marginBottom:20}}>");
join.push("          <ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} />");
join.push("        </div>");
join.push("        <Link href='/marketplace' style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.12em',textDecoration:'none'}}>← Browse without connecting</Link>");
join.push("      </div>");
join.push("    </main>");
join.push("  );");
join.push("}");
fs.writeFileSync('app/join/page.tsx', join.join('\n'), 'utf8');
console.log('Join done:', fs.existsSync('app/join/page.tsx'));

// WELCOME PAGE
fs.mkdirSync('app/welcome', { recursive: true });
const welcome = [];
welcome.push("'use client';");
welcome.push("import Nav from '../Nav';");
welcome.push("import Link from 'next/link';");
welcome.push("import { useAccount } from 'wagmi';");
welcome.push("import { useRouter } from 'next/navigation';");
welcome.push("import { useEffect } from 'react';");
welcome.push("");
welcome.push("export default function Welcome() {");
welcome.push("  const { isConnected } = useAccount();");
welcome.push("  const router = useRouter();");
welcome.push("  useEffect(() => { if (!isConnected) router.push('/join'); }, [isConnected, router]);");
welcome.push("  return (");
welcome.push("    <main style={{minHeight:'100vh',background:'var(--bg)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',position:'relative',overflow:'hidden'}}>");
welcome.push("      <Nav />");
welcome.push("      <div style={{position:'absolute',inset:0,pointerEvents:'none'}}>");
welcome.push("        <div style={{position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-60%)',width:800,height:600,background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)'}}/>");
welcome.push("        <div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)',backgroundSize:'96px 96px'}}/>");
welcome.push("      </div>");
welcome.push("      <div style={{position:'relative',zIndex:1,textAlign:'center',maxWidth:560,padding:'0 40px'}}>");
welcome.push("        <div className='v-arc-badge' style={{marginBottom:32,display:'inline-flex'}}><div className='v-arc-badge-dot'/><span className='v-arc-badge-text'>Welcome back</span></div>");
welcome.push("        <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(40px,7vw,88px)',fontWeight:300,lineHeight:0.90,letterSpacing:'-0.01em',color:'var(--w)',marginBottom:24}}>");
welcome.push("          What would you<br/><em style={{fontStyle:'italic',background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text'}}>like to do?</em>");
welcome.push("        </h1>");
welcome.push("        <p style={{fontSize:14,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.8,marginBottom:48}}>You have both a buyer and seller profile. Choose your path.</p>");
welcome.push("        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'1px',background:'var(--b1)',maxWidth:400,margin:'0 auto 32px'}}>");
welcome.push("          <Link href='/marketplace' style={{textDecoration:'none'}}>");
welcome.push("            <div style={{background:'var(--bg2)',padding:'32px 20px',cursor:'pointer',transition:'background 0.2s',textAlign:'center'}} onMouseEnter={e=>(e.currentTarget.style.background='rgba(212,176,90,0.08)')} onMouseLeave={e=>(e.currentTarget.style.background='var(--bg2)')}>"); 
welcome.push("              <div style={{fontSize:'2rem',marginBottom:12}}>{'🛍️'}</div>");
welcome.push("              <div style={{fontFamily:\"'Cormorant',serif\",fontSize:20,fontWeight:300,color:'var(--w)',marginBottom:6}}>Shop</div>");
welcome.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.6}}>Browse stores & buy products</div>");
welcome.push("            </div>");
welcome.push("          </Link>");
welcome.push("          <Link href='/profile' style={{textDecoration:'none'}}>");
welcome.push("            <div style={{background:'var(--bg2)',padding:'32px 20px',cursor:'pointer',transition:'background 0.2s',textAlign:'center'}} onMouseEnter={e=>(e.currentTarget.style.background='rgba(212,176,90,0.08)')} onMouseLeave={e=>(e.currentTarget.style.background='var(--bg2)')}>"); 
welcome.push("              <div style={{fontSize:'2rem',marginBottom:12}}>{'🏪'}</div>");
welcome.push("              <div style={{fontFamily:\"'Cormorant',serif\",fontSize:20,fontWeight:300,color:'var(--w)',marginBottom:6}}>Sell</div>");
welcome.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.6}}>Manage your store & products</div>");
welcome.push("            </div>");
welcome.push("          </Link>");
welcome.push("        </div>");
welcome.push("        <Link href='/profile' style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.12em',textDecoration:'none'}}>View full profile →</Link>");
welcome.push("      </div>");
welcome.push("    </main>");
welcome.push("  );");
welcome.push("}");
fs.writeFileSync('app/welcome/page.tsx', welcome.join('\n'), 'utf8');
console.log('Welcome done:', fs.existsSync('app/welcome/page.tsx'));
