const fs = require('fs');
fs.mkdirSync('app/join', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useEffect, useState } from 'react';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("export default function Join() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const [showCircle, setShowCircle] = useState(false);");
lines.push("  const [step, setStep] = useState<'form'|'creating'|'done'>('form');");
lines.push("  const [circleEmail, setCircleEmail] = useState('');");
lines.push("  const [circleWallet, setCircleWallet] = useState<{address:string;walletId:string}|null>(null);");
lines.push("  const [circleBalance, setCircleBalance] = useState('0');");
lines.push("  const [sending, setSending] = useState(false);");
lines.push("  const [sendForm, setSendForm] = useState({ to:'', amount:'' });");
lines.push("  const [sendResult, setSendResult] = useState('');");
lines.push("  const [error, setError] = useState('');");
lines.push("");
lines.push("  useEffect(() => { if (isConnected) router.push('/onboarding'); }, [isConnected, router]);");
lines.push("");
lines.push("  const handleCreateCircleWallet = async () => {");
lines.push("    if (!circleEmail) { setError('Enter your email'); return; }");
lines.push("    setStep('creating'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/create-wallet', {");
lines.push("        method: 'POST',");
lines.push("        headers: { 'Content-Type': 'application/json' },");
lines.push("        body: JSON.stringify({ userAddress: circleEmail }),");
lines.push("      });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setCircleWallet({ address: data.address, walletId: data.walletId });");
lines.push("      // Get balance");
lines.push("      const balRes = await fetch('/api/circle/balance', {");
lines.push("        method: 'POST',");
lines.push("        headers: { 'Content-Type': 'application/json' },");
lines.push("        body: JSON.stringify({ walletId: data.walletId }),");
lines.push("      });");
lines.push("      const balData = await balRes.json();");
lines.push("      setCircleBalance(balData.balance || '0');");
lines.push("      setStep('done');");
lines.push("    } catch(e:any) {");
lines.push("      setError(e.message || 'Failed to create wallet');");
lines.push("      setStep('form');");
lines.push("    }");
lines.push("  };");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!sendForm.to || !sendForm.amount || !circleWallet) return;");
lines.push("    setSending(true); setSendResult(''); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send', {");
lines.push("        method: 'POST',");
lines.push("        headers: { 'Content-Type': 'application/json' },");
lines.push("        body: JSON.stringify({ walletId: circleWallet.walletId, walletAddress: circleWallet.address, toAddress: sendForm.to, amount: sendForm.amount }),");
lines.push("      });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setSendResult('Transaction submitted! ID: ' + data.txId);");
lines.push("    } catch(e:any) { setError(e.message || 'Send failed'); }");
lines.push("    finally { setSending(false); }");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)', position:'relative', overflow:'hidden', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center' }}>");
lines.push("      <Nav />");
lines.push("      <div style={{ position:'absolute', inset:0, pointerEvents:'none' }}>");
lines.push("        <div style={{ position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-60%)', width:800, height:600, background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)' }}/>");
lines.push("        <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)', backgroundSize:'96px 96px' }}/>");
lines.push("      </div>");
lines.push("");
lines.push("      {/* Circle Wallet Modal */}");
lines.push("      {showCircle && (");
lines.push("        <div className='v-modal-bg' onClick={() => { setShowCircle(false); setStep('form'); setCircleWallet(null); setError(''); }}>");
lines.push("          <div className='v-modal' style={{ maxWidth:480 }} onClick={e => e.stopPropagation()}>");
lines.push("            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:20 }}>");
lines.push("              <div>");
lines.push("                <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--sl)', marginBottom:6 }}>Circle · Developer Controlled Wallet</div>");
lines.push("                <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:26, fontWeight:300, color:'var(--w)', lineHeight:1.1 }}>{step==='done' ? 'Wallet Ready' : step==='creating' ? 'Creating Wallet...' : 'Create Circle Wallet'}</div>");
lines.push("              </div>");
lines.push("              <button onClick={() => { setShowCircle(false); setStep('form'); setCircleWallet(null); setError(''); }} style={{ background:'transparent', border:'1px solid var(--b1)', color:'var(--w35)', width:32, height:32, cursor:'pointer', flexShrink:0, display:'flex', alignItems:'center', justifyContent:'center' }}>✕</button>");
lines.push("            </div>");
lines.push("");
lines.push("            {step==='form' && (");
lines.push("              <>");
lines.push("                <div style={{ fontSize:13, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:24 }}>No crypto experience needed. Enter your email and we'll create a USDC wallet on Arc Testnet for you instantly.</div>");
lines.push("                <div className='v-field'>");
lines.push("                  <label className='v-label'>Your Email</label>");
lines.push("                  <input className='v-input' type='email' placeholder='you@example.com' value={circleEmail} onChange={e => setCircleEmail(e.target.value)} onKeyDown={e => e.key==='Enter' && handleCreateCircleWallet()} />");
lines.push("                </div>");
lines.push("                {error && <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--err)', marginBottom:12, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                <button onClick={handleCreateCircleWallet} className='btn-primary' style={{ width:'100%', padding:'14px', fontSize:11 }}>Create My USDC Wallet →</button>");
lines.push("                <div style={{ textAlign:'center', marginTop:12, fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', lineHeight:1.6 }}>Powered by Circle · Arc Testnet · No seed phrase required</div>");
lines.push("              </>");
lines.push("            )}");
lines.push("");
lines.push("            {step==='creating' && (");
lines.push("              <div style={{ textAlign:'center', padding:'24px 0' }}>");
lines.push("                <div className='v-spinner' style={{ margin:'0 auto 20px' }} />");
lines.push("                <div style={{ fontSize:13, fontWeight:300, fontStyle:'italic', color:'var(--w35)' }}>Creating your wallet on Arc Testnet...</div>");
lines.push("              </div>");
lines.push("            )}");
lines.push("");
lines.push("            {step==='done' && circleWallet && (");
lines.push("              <>");
lines.push("                <div style={{ border:'1px solid rgba(212,176,90,0.2)', background:'rgba(212,176,90,0.04)', padding:'20px', marginBottom:20, position:'relative', overflow:'hidden' }}>");
lines.push("                  <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
lines.push("                  <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--w18)', marginBottom:4 }}>Your Circle Wallet · Arc Testnet</div>");
lines.push("                  <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:13, fontWeight:300, color:'var(--a2)', wordBreak:'break-all', marginBottom:12 }}>{circleWallet.address}</div>");
lines.push("                  <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("                    <div>");
lines.push("                      <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--w18)', marginBottom:2 }}>USDC Balance</div>");
lines.push("                      <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:28, fontWeight:300, color:'var(--a2)' }}>${circleBalance}</div>");
lines.push("                    </div>");
lines.push("                    <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{ fontSize:9, padding:'8px 14px' }}>Get Test USDC ↗</button></a>");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("                <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', letterSpacing:'0.14em', textTransform:'uppercase', color:'var(--a)', marginBottom:12 }}>Send USDC on Arc</div>");
lines.push("                <div className='v-field'>");
lines.push("                  <label className='v-label'>Recipient Address</label>");
lines.push("                  <input className='v-input' type='text' placeholder='0x...' value={sendForm.to} onChange={e => setSendForm({...sendForm, to:e.target.value})} />");
lines.push("                </div>");
lines.push("                <div className='v-field'>");
lines.push("                  <label className='v-label'>Amount (USDC)</label>");
lines.push("                  <input className='v-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e => setSendForm({...sendForm, amount:e.target.value})} />");
lines.push("                </div>");
lines.push("                {error && <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                {sendResult && <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'8px 12px', wordBreak:'break-all' }}>{sendResult}</div>}");
lines.push("                <button onClick={handleSend} disabled={sending} className='btn-primary' style={{ width:'100%', padding:'12px', fontSize:10, marginBottom:12 }}>{sending ? 'Sending...' : 'Send USDC on Arc →'}</button>");
lines.push("                <a href={`https://testnet.arcscan.app/address/${circleWallet.address}`} target='_blank' rel='noopener noreferrer' style={{ display:'block', textAlign:'center', fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--sl)', letterSpacing:'0.10em', textDecoration:'none' }}>View on Arc Explorer ↗</a>");
lines.push("              </>");
lines.push("            )}");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("");
lines.push("      {/* Main */}");
lines.push("      <div style={{ position:'relative', zIndex:1, textAlign:'center', maxWidth:480, padding:'0 40px' }}>");
lines.push("        <div className='v-arc-badge' style={{ marginBottom:36, display:'inline-flex' }}><div className='v-arc-badge-dot'/><span className='v-arc-badge-text'>Arc Testnet · Powered by USDC</span></div>");
lines.push("        <h1 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(52px,9vw,104px)', fontWeight:300, lineHeight:0.88, letterSpacing:'-0.01em', color:'var(--w)', marginBottom:20 }}>");
lines.push("          Connect your<br/><em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>wallet</em>");
lines.push("        </h1>");
lines.push("        <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:48 }}>Your wallet is your identity on Vendra. Connect a Web3 wallet or create a Circle wallet — no crypto experience needed.</p>");
lines.push("        <div style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:12, marginBottom:28 }}>");
lines.push("          <ConnectButton label='Connect Web3 Wallet' accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("          <div style={{ display:'flex', alignItems:'center', gap:12, width:'100%', maxWidth:280 }}>");
lines.push("            <div style={{ flex:1, height:1, background:'var(--b1)' }}/>");
lines.push("            <span style={{ fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.14em', textTransform:'uppercase' }}>or</span>");
lines.push("            <div style={{ flex:1, height:1, background:'var(--b1)' }}/>");
lines.push("          </div>");
lines.push("          <button onClick={() => setShowCircle(true)} className='btn-ghost' style={{ fontSize:11, padding:'14px 36px', display:'flex', alignItems:'center', gap:10 }}>");
lines.push("            <span>⭕</span>");
lines.push("            <span>Create Circle Wallet</span>");
lines.push("          </button>");
lines.push("        </div>");
lines.push("        <Link href='/marketplace' style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.12em', textDecoration:'none' }}>Browse without connecting →</Link>");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/join/page.tsx', lines.join('\n'), 'utf8');
console.log('Join Circle done:', fs.existsSync('app/join/page.tsx'));
