const fs = require('fs');
fs.mkdirSync('app/join', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useEffect, useState } from 'react';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("type CircleStep = 'email'|'checking'|'found'|'notfound'|'creating'|'done';");
lines.push("const STORAGE_KEY = 'vendra_circle_wallet';");
lines.push("");
lines.push("export default function Join() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const [step, setStep] = useState<CircleStep>('email');");
lines.push("  const [email, setEmail] = useState('');");
lines.push("  const [circleWallet, setCircleWallet] = useState<{address:string;walletId:string;email:string}|null>(null);");
lines.push("  const [balance, setBalance] = useState('0');");
lines.push("  const [copied, setCopied] = useState(false);");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [sendForm, setSendForm] = useState({ to:'', amount:'' });");
lines.push("  const [sending, setSending] = useState(false);");
lines.push("  const [sendResult, setSendResult] = useState('');");
lines.push("  const [mode, setMode] = useState<'options'|'web3'|'circle'>('options');");
lines.push("");
lines.push("  useEffect(() => { if (isConnected) router.push('/onboarding'); }, [isConnected, router]);");
lines.push("");
lines.push("  // Check for existing Circle session");
lines.push("  useEffect(() => {");
lines.push("    try {");
lines.push("      const saved = sessionStorage.getItem(STORAGE_KEY);");
lines.push("      if (saved) {");
lines.push("        const w = JSON.parse(saved);");
lines.push("        setCircleWallet(w);");
lines.push("        fetchBalance(w.walletId);");
lines.push("        setMode('circle');");
lines.push("        setStep('found');");
lines.push("      }");
lines.push("    } catch {}");
lines.push("  }, []);");
lines.push("");
lines.push("  const saveWallet = (w: {address:string;walletId:string;email:string}) => {");
lines.push("    setCircleWallet(w);");
lines.push("    try { sessionStorage.setItem(STORAGE_KEY, JSON.stringify(w)); } catch {}");
lines.push("  };");
lines.push("");
lines.push("  const fetchBalance = async (walletId: string) => {");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/balance', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId }) });");
lines.push("      const data = await res.json();");
lines.push("      setBalance(data.balance || '0');");
lines.push("    } catch {}");
lines.push("  };");
lines.push("");
lines.push("  const handleCopy = () => {");
lines.push("    if (!circleWallet) return;");
lines.push("    navigator.clipboard.writeText(circleWallet.address);");
lines.push("    setCopied(true);");
lines.push("    setTimeout(() => setCopied(false), 2000);");
lines.push("  };");
lines.push("");
lines.push("  const handleLogin = async () => {");
lines.push("    if (!email) { setError('Enter your email'); return; }");
lines.push("    setStep('checking'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/login', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      if (data.found) {");
lines.push("        const w = { address: data.address, walletId: data.walletId, email };");
lines.push("        saveWallet(w);");
lines.push("        await fetchBalance(data.walletId);");
lines.push("        setStep('found');");
lines.push("      } else {");
lines.push("        setStep('notfound');");
lines.push("      }");
lines.push("    } catch(e:any) { setError(e.message || 'Something went wrong'); setStep('email'); }");
lines.push("  };");
lines.push("");
lines.push("  const handleCreate = async () => {");
lines.push("    setStep('creating'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/create-wallet', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      const w = { address: data.address, walletId: data.walletId, email };");
lines.push("      saveWallet(w);");
lines.push("      await fetchBalance(data.walletId);");
lines.push("      setStep('done');");
lines.push("    } catch(e:any) { setError(e.message || 'Failed'); setStep('notfound'); }");
lines.push("  };");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!sendForm.to || !sendForm.amount || !circleWallet) return;");
lines.push("    setSending(true); setSendResult(''); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId: circleWallet.walletId, walletAddress: circleWallet.address, toAddress: sendForm.to, amount: sendForm.amount }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setSendResult('Sent! TX: ' + (data.txId||'').slice(0,20) + '...');");
lines.push("      await fetchBalance(circleWallet.walletId);");
lines.push("    } catch(e:any) { setError(e.message || 'Send failed'); }");
lines.push("    finally { setSending(false); }");
lines.push("  };");
lines.push("");
lines.push("  const logout = () => {");
lines.push("    setCircleWallet(null);");
lines.push("    try { sessionStorage.removeItem(STORAGE_KEY); } catch {}");
lines.push("    setMode('options'); setStep('email'); setEmail('');");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)', position:'relative', overflow:'hidden', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center' }}>");
lines.push("      <Nav />");
lines.push("      {/* Ambient */}");
lines.push("      <div style={{ position:'absolute', inset:0, pointerEvents:'none' }}>");
lines.push("        <div style={{ position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-60%)', width:800, height:600, background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)' }}/>");
lines.push("        <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)', backgroundSize:'96px 96px' }}/>");
lines.push("      </div>");
lines.push("");
lines.push("      <div style={{ position:'relative', zIndex:1, width:'100%', maxWidth:480, padding:'80px 40px' }}>");
lines.push("        <div style={{ textAlign:'center', marginBottom:40 }}>");
lines.push("          <div className='v-arc-badge' style={{ marginBottom:24, display:'inline-flex' }}><div className='v-arc-badge-dot'/><span className='v-arc-badge-text'>Arc Testnet · Powered by USDC</span></div>");
lines.push("          <h1 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(48px,8vw,80px)', fontWeight:300, lineHeight:0.90, letterSpacing:'-0.01em', color:'var(--w)', marginBottom:16 }}>Join<br/><em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>Vendra</em></h1>");
lines.push("          <p style={{ fontSize:13, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8 }}>Connect a Web3 wallet or log in with Circle — no crypto experience needed.</p>");
lines.push("        </div>");
lines.push("");
lines.push("        {/* OPTIONS */}");
lines.push("        {mode==='options' && (");
lines.push("          <div style={{ display:'flex', flexDirection:'column', gap:12 }}>");
lines.push("            {/* Web3 */}");
lines.push("            <div style={{ border:'1px solid var(--b1)', padding:'24px', background:'var(--bg2)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.3),transparent)' }} />");
lines.push("              <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--a)', marginBottom:8 }}>🦊 Web3 Wallet</div>");
lines.push("              <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', marginBottom:16, lineHeight:1.6 }}>MetaMask, Coinbase, WalletConnect or any EVM wallet.</div>");
lines.push("              <div style={{ display:'flex', justifyContent:'center' }}><ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} /></div>");
lines.push("            </div>");
lines.push("            <div style={{ display:'flex', alignItems:'center', gap:12 }}>");
lines.push("              <div style={{ flex:1, height:1, background:'var(--b1)' }}/><span style={{ fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.14em', textTransform:'uppercase' }}>or</span><div style={{ flex:1, height:1, background:'var(--b1)' }}/>");
lines.push("            </div>");
lines.push("            {/* Circle */}");
lines.push("            <div style={{ border:'1px solid rgba(155,181,200,0.2)', padding:'24px', background:'rgba(155,181,200,0.03)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(155,181,200,0.3),transparent)' }} />");
lines.push("              <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--sl)', marginBottom:8 }}>⭕ Circle Wallet</div>");
lines.push("              <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', marginBottom:16, lineHeight:1.6 }}>No crypto experience needed. Log in with your email.</div>");
lines.push("              <button onClick={() => setMode('circle')} className='btn-slate' style={{ width:'100%', fontSize:10, padding:'12px' }}>Log In with Circle Wallet →</button>");
lines.push("            </div>");
lines.push("            <div style={{ textAlign:'center', marginTop:8 }}>");
lines.push("              <Link href='/marketplace' style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.12em', textDecoration:'none' }}>Browse without connecting →</Link>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        )}");
lines.push("");
lines.push("        {/* CIRCLE FLOW */}");
lines.push("        {mode==='circle' && (");
lines.push("          <div style={{ border:'1px solid rgba(155,181,200,0.2)', background:'rgba(155,181,200,0.03)', position:'relative', overflow:'hidden' }}>");
lines.push("            <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(155,181,200,0.4),transparent)' }} />");
lines.push("            <div style={{ padding:'24px' }}>");
lines.push("              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:20 }}>");
lines.push("                <div>");
lines.push("                  <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--sl)', marginBottom:4 }}>Circle · USDC Wallet</div>");
lines.push("                  <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:22, fontWeight:300, color:'var(--w)' }}>");
lines.push("                    {step==='email'&&'Log In with Circle'}");
lines.push("                    {step==='checking'&&'Checking...'}");
lines.push("                    {step==='notfound'&&'Create Wallet'}");
lines.push("                    {step==='creating'&&'Creating Wallet...'}");
lines.push("                    {(step==='found'||step==='done')&&'Welcome Back ✓'}");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("                {(step==='found'||step==='done') && <button onClick={logout} className='btn-danger' style={{ fontSize:9, padding:'6px 12px' }}>Log Out</button>}");
lines.push("              </div>");
lines.push("");
lines.push("              {step==='email' && (");
lines.push("                <>");
lines.push("                  <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:20 }}>Enter the email linked to your Circle wallet. New here? We'll create one for you.</div>");
lines.push("                  <div className='v-field'><label className='v-label'>Email Address</label><input className='v-input' type='email' placeholder='you@example.com' value={email} onChange={e => setEmail(e.target.value)} onKeyDown={e => e.key==='Enter' && handleLogin()} autoFocus /></div>");
lines.push("                  {error && <div style={{ fontSize:11, fontStyle:'italic', color:'var(--err)', marginBottom:12, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                  <button onClick={handleLogin} className='btn-primary' style={{ width:'100%', padding:'14px', fontSize:11, marginBottom:10 }}>Continue →</button>");
lines.push("                  <button onClick={() => setMode('options')} style={{ width:'100%', background:'transparent', border:'none', fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', cursor:'pointer', padding:'8px' }}>← Back to options</button>");
lines.push("                </>");
lines.push("              )}");
lines.push("              {step==='checking' && <div style={{ textAlign:'center', padding:'24px 0' }}><div className='v-spinner' style={{ margin:'0 auto 16px' }}/><div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)' }}>Looking up your wallet...</div></div>}");
lines.push("              {step==='notfound' && (");
lines.push("                <>");
lines.push("                  <div style={{ border:'1px solid var(--b1)', padding:'14px', marginBottom:20, background:'var(--bg3)' }}>");
lines.push("                    <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7 }}>No wallet found for <strong style={{ color:'var(--w)' }}>{email}</strong>. Would you like to create one?</div>");
lines.push("                  </div>");
lines.push("                  {error && <div style={{ fontSize:11, fontStyle:'italic', color:'var(--err)', marginBottom:12, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                  <button onClick={handleCreate} className='btn-primary' style={{ width:'100%', padding:'14px', fontSize:11, marginBottom:10 }}>Create New Circle Wallet →</button>");
lines.push("                  <button onClick={() => setStep('email')} style={{ width:'100%', background:'transparent', border:'none', fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', cursor:'pointer', padding:'8px' }}>← Try a different email</button>");
lines.push("                </>");
lines.push("              )}");
lines.push("              {step==='creating' && <div style={{ textAlign:'center', padding:'24px 0' }}><div className='v-spinner' style={{ margin:'0 auto 16px' }}/><div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)' }}>Creating your wallet on Arc Testnet...</div></div>}");
lines.push("              {(step==='found'||step==='done') && circleWallet && (");
lines.push("                <>");
lines.push("                  <div style={{ border:'1px solid rgba(212,176,90,0.2)', background:'rgba(212,176,90,0.04)', padding:'20px', marginBottom:16, position:'relative', overflow:'hidden' }}>");
lines.push("                    <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
lines.push("                    <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--w18)', marginBottom:4 }}>Circle Wallet · Arc Testnet</div>");
lines.push("                    <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:12 }}>");
lines.push("                      <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:12, fontWeight:300, color:'var(--a)', flex:1, wordBreak:'break-all' }}>{circleWallet.address}</div>");
lines.push("                      <button onClick={handleCopy} style={{ fontFamily:\"'DM Sans',sans-serif\", fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.12em', textTransform:'uppercase', border:'1px solid var(--b2)', color:copied?'var(--gr)':'var(--w35)', padding:'5px 10px', background:'transparent', cursor:'pointer', flexShrink:0, transition:'all 0.3s', whiteSpace:'nowrap' }}>{copied?'✓ Copied':'Copy'}</button>");
lines.push("                    </div>");
lines.push("                    <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("                      <div><div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.14em', textTransform:'uppercase', color:'var(--w18)', marginBottom:2 }}>USDC Balance</div><div style={{ fontFamily:\"'Cormorant',serif\", fontSize:32, fontWeight:300, color:'var(--a2)' }}>${balance}</div></div>");
lines.push("                      <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{ fontSize:9, padding:'8px 12px' }}>Get USDC ↗</button></a>");
lines.push("                    </div>");
lines.push("                  </div>");
lines.push("                  <div className='v-field'><label className='v-label'>Send to Address</label><input className='v-input' placeholder='0x...' value={sendForm.to} onChange={e => setSendForm({...sendForm, to:e.target.value})} /></div>");
lines.push("                  <div className='v-field'><label className='v-label'>Amount (USDC)</label><input className='v-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e => setSendForm({...sendForm, amount:e.target.value})} /></div>");
lines.push("                  {error && <div style={{ fontSize:11, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                  {sendResult && <div style={{ fontSize:10, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'8px 12px', wordBreak:'break-all' }}>{sendResult}</div>}");
lines.push("                  <button onClick={handleSend} disabled={sending} className='btn-primary' style={{ width:'100%', padding:'12px', fontSize:10, marginBottom:10 }}>{sending?'Sending...':'Send USDC on Arc →'}</button>");
lines.push("                  <div style={{ display:'flex', gap:8, marginBottom:12 }}>");
lines.push("                    <a href={`https://testnet.arcscan.app/address/${circleWallet.address}`} target='_blank' rel='noopener noreferrer' style={{ flex:1 }}><button className='btn-ghost' style={{ width:'100%', fontSize:9, padding:'8px' }}>Arc Explorer ↗</button></a>");
lines.push("                    <Link href='/marketplace' style={{ flex:1 }}><button className='btn-primary' style={{ width:'100%', fontSize:9, padding:'8px' }}>Explore Marketplace →</button></Link>");
lines.push("                  </div>");
lines.push("                </>");
lines.push("              )}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        )}");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/join/page.tsx', lines.join('\n'), 'utf8');
console.log('Join v5 done:', fs.existsSync('app/join/page.tsx'));
