const fs = require('fs');
fs.mkdirSync('app/join', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useEffect, useState } from 'react';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("export default function Join() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const [option, setOption] = useState<'web3'|'circle'|null>(null);");
lines.push("  useEffect(() => { if (isConnected) router.push('/onboarding'); }, [isConnected, router]);");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)', position:'relative', overflow:'hidden' }}>");
lines.push("      <Nav />");
lines.push("      {/* Ambient bg */}");
lines.push("      <div style={{ position:'absolute', inset:0, pointerEvents:'none' }}>");
lines.push("        <div style={{ position:'absolute', top:'40%', left:'50%', transform:'translate(-50%,-60%)', width:800, height:600, background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)' }}/>");
lines.push("        <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)', backgroundSize:'96px 96px' }}/>");
lines.push("      </div>");
lines.push("      <div style={{ position:'relative', zIndex:1, maxWidth:680, margin:'0 auto', padding:'120px 40px 80px', textAlign:'center' }}>");
lines.push("        <div className='v-arc-badge' style={{ marginBottom:32, display:'inline-flex' }}><div className='v-arc-badge-dot'/><span className='v-arc-badge-text'>Arc Testnet · Powered by USDC</span></div>");
lines.push("        <h1 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(40px,7vw,80px)', fontWeight:300, lineHeight:0.90, letterSpacing:'-0.01em', color:'var(--w)', marginBottom:16 }}>");
lines.push("          Join<br/><em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>Vendra</em>");
lines.push("        </h1>");
lines.push("        <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:48, maxWidth:440, margin:'0 auto 48px' }}>Buy and sell anything, get paid instantly in USDC. Choose how you want to connect.</p>");
lines.push("");
lines.push("        {/* Two options */}");
lines.push("        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1px', background:'var(--b1)', marginBottom:32 }}>");
lines.push("          {/* Web3 Wallet */}");
lines.push("          <div onClick={() => setOption('web3')} style={{ background: option==='web3' ? 'rgba(212,176,90,0.08)' : 'var(--bg2)', padding:'36px 28px', cursor:'pointer', borderBottom: option==='web3' ? '1px solid var(--a)' : '1px solid transparent', transition:'all 0.2s', textAlign:'left' }}>");
lines.push("            <div style={{ fontSize:'2rem', marginBottom:14 }}>🦊</div>");
lines.push("            <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:22, fontWeight:300, color: option==='web3' ? 'var(--a2)' : 'var(--w)', marginBottom:8 }}>Web3 Wallet</div>");
lines.push("            <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:16 }}>Connect MetaMask, Coinbase, WalletConnect or any EVM wallet. Full Web3 experience on Arc Testnet.</div>");
lines.push("            <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>");
lines.push("              {['MetaMask','Coinbase','WalletConnect','Rabby'].map(w => <span key={w} style={{ fontSize:8, fontWeight:300, fontStyle:'italic', letterSpacing:'0.12em', textTransform:'uppercase', color:'var(--w18)', border:'1px solid var(--b1)', padding:'3px 8px' }}>{w}</span>)}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("          {/* Circle Wallet */}");
lines.push("          <div onClick={() => setOption('circle')} style={{ background: option==='circle' ? 'rgba(155,181,200,0.08)' : 'var(--bg2)', padding:'36px 28px', cursor:'pointer', borderBottom: option==='circle' ? '1px solid var(--sl)' : '1px solid transparent', transition:'all 0.2s', textAlign:'left' }}>");
lines.push("            <div style={{ fontSize:'2rem', marginBottom:14 }}>⭕</div>");
lines.push("            <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:22, fontWeight:300, color: option==='circle' ? 'var(--sl2)' : 'var(--w)', marginBottom:8 }}>Circle Wallet</div>");
lines.push("            <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:16 }}>No crypto experience needed. Use Circle's App Kit to bridge USDC from any chain and pay on Vendra instantly.</div>");
lines.push("            <div style={{ display:'flex', flexWrap:'wrap', gap:6 }}>");
lines.push("              {['USDC Native','CCTP Bridge','Multi-Chain','Unified Balance'].map(w => <span key={w} style={{ fontSize:8, fontWeight:300, fontStyle:'italic', letterSpacing:'0.12em', textTransform:'uppercase', color:'var(--w18)', border:'1px solid var(--b1)', padding:'3px 8px' }}>{w}</span>)}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>");
lines.push("");
lines.push("        {/* Web3 connect */}");
lines.push("        {option==='web3' && (");
lines.push("          <div style={{ border:'1px solid var(--b1)', background:'var(--bg2)', padding:'28px', position:'relative', overflow:'hidden', marginBottom:16 }}>");
lines.push("            <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
lines.push("            <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--a)', marginBottom:16 }}>Connect your Web3 wallet</div>");
lines.push("            <div style={{ display:'flex', justifyContent:'center', marginBottom:12 }}>");
lines.push("              <ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("            </div>");
lines.push("            <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.08em' }}>Your wallet is your identity. No email or password needed.</div>");
lines.push("          </div>)}");
lines.push("");
lines.push("        {/* Circle App Kit option */}");
lines.push("        {option==='circle' && (");
lines.push("          <div style={{ border:'1px solid rgba(155,181,200,0.2)', background:'linear-gradient(145deg,rgba(155,181,200,0.05),var(--bg2))', padding:'28px', position:'relative', overflow:'hidden', marginBottom:16 }}>");
lines.push("            <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(155,181,200,0.4),transparent)' }} />");
lines.push("            <div style={{ fontSize:10, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--sl)', marginBottom:16 }}>Circle App Kit · Bridge & Pay</div>");
lines.push("            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:'1px', background:'var(--b1)', marginBottom:20 }}>");
lines.push("              {[{icon:'🌉',title:'Bridge',desc:'Move USDC from Ethereum, Solana, or any supported chain to Arc Testnet via CCTP'},{icon:'💳',title:'Unified Balance',desc:'Hold USDC anywhere, spend on Vendra without manual bridging'},{icon:'✈️',title:'Send',desc:'Transfer USDC directly to any seller wallet on Arc Testnet instantly'}].map(f => (");
lines.push("                <div key={f.title} style={{ background:'var(--bg2)', padding:'20px 16px', textAlign:'left' }}>");
lines.push("                  <div style={{ fontSize:'1.4rem', marginBottom:8 }}>{f.icon}</div>");
lines.push("                  <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:16, fontWeight:300, color:'var(--w85)', marginBottom:6 }}>{f.title}</div>");
lines.push("                  <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.65 }}>{f.desc}</div>");
lines.push("                </div>))}");
lines.push("            </div>");
lines.push("            <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:16 }}>To use Circle App Kit, you still need to connect a Web3 wallet — but the App Kit handles all the complex bridging and payment routing so you never have to think about chains.</div>");
lines.push("            <div style={{ display:'flex', justifyContent:'center', marginBottom:12 }}>");
lines.push("              <ConnectButton label='Connect & Use Circle App Kit' accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("            </div>");
lines.push("            <a href='https://docs.arc.io/app-kit' target='_blank' rel='noopener noreferrer' style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--sl)', letterSpacing:'0.10em', textDecoration:'none', display:'block', marginTop:8 }}>Learn about Circle App Kit ↗</a>");
lines.push("          </div>)}");
lines.push("");
lines.push("        {!option && (");
lines.push("          <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.08em' }}>← Select an option above to continue</div>)}");
lines.push("");
lines.push("        <div style={{ marginTop:24 }}>");
lines.push("          <Link href='/marketplace' style={{ fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.12em', textDecoration:'none' }}>Browse without connecting →</Link>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/join/page.tsx', lines.join('\n'), 'utf8');
console.log('Join v2 done:', fs.existsSync('app/join/page.tsx'));
