const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import Link from 'next/link';");
lines.push("import { useState, useEffect } from 'react';");
lines.push("import { getStores } from '../lib/supabase';");
lines.push("");
lines.push("const CATS = ['All','Fashion','Digital','Art','Services','Food','Tech','Music','Other'];");
lines.push("const SAMPLE: any[] = [");
lines.push("  { id:'s1', slug:'nour-atelier', name:'Nour Atelier', tagline:'Handcrafted jewellery from the Middle East', category:'Fashion', products:[1,2,3,4], bg:'linear-gradient(145deg,#1e1608,#3d2e14)' },");
lines.push("  { id:'s2', slug:'bytedrop', name:'ByteDrop', tagline:'Premium UI kits and Figma assets', category:'Digital', products:[1,2,3], bg:'linear-gradient(145deg,#060d18,#142035)' },");
lines.push("  { id:'s3', slug:'solar-prints', name:'Solar Prints', tagline:'Limited edition art prints worldwide', category:'Art', products:[1,2], bg:'linear-gradient(145deg,#100810,#261630)' },");
lines.push("  { id:'s4', slug:'kode-studio', name:'Kode Studio', tagline:'Custom dev work and automation', category:'Services', products:[1,2], bg:'linear-gradient(145deg,#0a1208,#162418)' },");
lines.push("  { id:'s5', slug:'umami-box', name:'Umami Box', tagline:'Artisan Japanese food kits', category:'Food', products:[1,2], bg:'linear-gradient(145deg,#180d06,#2e1a0c)' },");
lines.push("  { id:'s6', slug:'soundvault', name:'SoundVault', tagline:'Exclusive beats and sample packs', category:'Music', products:[1,2,3], bg:'linear-gradient(145deg,#050d18,#0d1a2e)' },");
lines.push("];");
lines.push("");
lines.push("export default function Marketplace() {");
lines.push("  const [stores, setStores] = useState<any[]>([]);");
lines.push("  const [cat, setCat] = useState('All');");
lines.push("  const [search, setSearch] = useState('');");
lines.push("  const [loading, setLoading] = useState(true);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    getStores().then(db => {");
lines.push("      const merged = [...SAMPLE.filter((s:any) => !db.find((d:any) => d.slug===s.slug)), ...db.map((s:any) => ({...s, bg:'linear-gradient(145deg,var(--bg2),var(--bg3))', products:s.products||[]}))];");
lines.push("      setStores(merged); setLoading(false);");
lines.push("    });");
lines.push("  }, []);");
lines.push("");
lines.push("  const filtered = stores.filter(s => (cat==='All'||s.category===cat) && (s.name.toLowerCase().includes(search.toLowerCase())||s.tagline?.toLowerCase().includes(search.toLowerCase())));");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)' }}>");
lines.push("      <Nav />");
lines.push("      <div style={{ paddingTop:72 }}>");
lines.push("        {/* Header */}");
lines.push("        <div style={{ background:'var(--bg2)', borderBottom:'1px solid var(--b1)', padding:'64px 56px 48px' }}>");
lines.push("          <div style={{ maxWidth:1200, margin:'0 auto' }}>");
lines.push("            <div className='v-eyebrow' style={{ marginBottom:16 }}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Arc Testnet · Live Stores</span></div>");
lines.push("            <h1 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(40px,6vw,72px)', fontWeight:300, letterSpacing:'-0.01em', lineHeight:0.94, color:'var(--w)', marginBottom:32 }}>");
lines.push("              The <em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>Marketplace</em>");
lines.push("            </h1>");
lines.push("            <input value={search} onChange={e=>setSearch(e.target.value)} placeholder='Search stores and products...' style={{ width:'100%', maxWidth:480, background:'transparent', border:'none', borderBottom:'1px solid var(--b2)', padding:'10px 0', color:'var(--w85)', fontFamily:\"'DM Sans',sans-serif\", fontSize:14, fontWeight:300, fontStyle:'italic', outline:'none', letterSpacing:'0.04em' }} />");
lines.push("          </div>");
lines.push("        </div>");
lines.push("        {/* Tabs */}");
lines.push("        <div style={{ borderBottom:'1px solid var(--b1)', background:'var(--bg)', overflowX:'auto' }}>");
lines.push("          <div style={{ maxWidth:1200, margin:'0 auto', padding:'0 56px', display:'flex' }}>");
lines.push("            {CATS.map(c=><button key={c} onClick={()=>setCat(c)} style={{ fontFamily:\"'DM Sans',sans-serif\", fontSize:10, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', padding:'16px 24px', background:'transparent', border:'none', borderBottom:cat===c?'1px solid var(--a)':'1px solid transparent', color:cat===c?'var(--a)':'var(--w18)', cursor:'pointer', transition:'all 0.3s', whiteSpace:'nowrap' }}>{c}</button>)}");
lines.push("          </div>");
lines.push("        </div>");
lines.push("        {/* Grid */}");
lines.push("        <div style={{ maxWidth:1200, margin:'0 auto', padding:'48px 56px 80px' }}>");
lines.push("          {loading");
lines.push("            ? <div style={{ textAlign:'center', padding:'4rem' }}><div className='v-spinner' style={{ margin:'0 auto' }}/></div>");
lines.push("            : filtered.length===0");
lines.push("              ? <div style={{ textAlign:'center', padding:'4rem', border:'1px solid var(--b1)' }}><div style={{ fontFamily:\"'Cormorant',serif\", fontSize:28, fontWeight:300, color:'var(--w)', marginBottom:8 }}>No stores found</div><div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.10em' }}>Try a different search or category</div></div>");
lines.push("              : <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'1px', background:'var(--b1)' }}>");
lines.push("                  {filtered.map(s=>(");
lines.push("                    <Link key={s.id||s.slug} href={'/store/'+s.slug} style={{ textDecoration:'none' }}>");
lines.push("                      <div className='v-store-card'>");
lines.push("                        <div className='v-store-banner' style={{ background:s.banner_url?'none':s.bg, position:'relative' }}>");
lines.push("                          {s.banner_url&&<img src={s.banner_url} alt={s.name} style={{ width:'100%', height:'100%', objectFit:'cover', filter:'brightness(0.6)' }}/>}");
lines.push("                          {!s.banner_url&&<div style={{ position:'absolute', inset:0, display:'flex', alignItems:'center', justifyContent:'center', fontFamily:\"'Cormorant',serif\", fontSize:56, fontWeight:300, fontStyle:'italic', color:'rgba(212,176,90,0.15)' }}>{s.name?.slice(0,1)}</div>}");
lines.push("                        </div>");
lines.push("                        <div className='v-store-body'>");
lines.push("                          <div className='v-store-name'>{s.name}</div>");
lines.push("                          <div className='v-store-desc'>{s.tagline}</div>");
lines.push("                          <div className='v-store-meta'><span className='v-store-cat'>{s.category}</span><span className='v-store-count'>{s.products?.length||0} products</span></div>");
lines.push("                        </div>");
lines.push("                      </div>");
lines.push("                    </Link>))}");
lines.push("                </div>}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <footer className='v-footer'>");
lines.push("        <div style={{ opacity:0.5, fontFamily:\"'Cormorant',serif\", fontSize:16, fontWeight:300, letterSpacing:'0.22em', textTransform:'uppercase', color:'var(--w85)' }}>Vendra</div>");
lines.push("        <div className='v-footer-copy'>Arc Testnet · 0% Fees · USDC Native · ERC-8183 Escrow</div>");
lines.push("        <div className='v-footer-links'><Link href='/store/create'>Open a Store</Link><a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'>Faucet</a></div>");
lines.push("      </footer>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/marketplace/page.tsx', lines.join('\n'), 'utf8');
console.log('Marketplace done:', fs.existsSync('app/marketplace/page.tsx'));
