const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Link from 'next/link';");
lines.push("import Nav from './Nav';");
lines.push("");
lines.push("export default function NotFound() {");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', position:'relative', overflow:'hidden' }}>");
lines.push("      <Nav />");
lines.push("      <div style={{ position:'absolute', inset:0, pointerEvents:'none' }}>");
lines.push("        <div style={{ position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-60%)', width:800, height:600, background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)' }}/>");
lines.push("        <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)', backgroundSize:'96px 96px' }}/>");
lines.push("      </div>");
lines.push("      <div style={{ position:'relative', zIndex:1, textAlign:'center', maxWidth:480, padding:'0 40px' }}>");
lines.push("        <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(80px,20vw,160px)', fontWeight:300, lineHeight:1, background:'linear-gradient(120deg,var(--a),var(--a2))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text', marginBottom:8 }}>404</div>");
lines.push("        <div className='v-cta-rule' style={{ marginBottom:20 }}><div className='v-cta-rule-line'/><div className='v-cta-rule-text'>Page Not Found</div><div className='v-cta-rule-line'/></div>");
lines.push("        <h1 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(28px,5vw,48px)', fontWeight:300, letterSpacing:'-0.01em', lineHeight:0.94, color:'var(--w)', marginBottom:16 }}>This page doesn't<br/><em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>exist</em></h1>");
lines.push("        <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:40 }}>The page you're looking for has moved, was deleted, or never existed. Let's get you back on track.</p>");
lines.push("        <div style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:12 }}>");
lines.push("          <Link href='/'><button className='btn-primary' style={{ fontSize:11, padding:'14px 36px' }}>Back to Homepage</button></Link>");
lines.push("          <Link href='/marketplace'><button className='btn-ghost' style={{ fontSize:11, padding:'14px 36px' }}>Browse Marketplace</button></Link>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/not-found.tsx', lines.join('\n'), 'utf8');
console.log('404 page done:', fs.existsSync('app/not-found.tsx'));
