const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Link from 'next/link';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useState, useEffect } from 'react';");
lines.push("import CartButton from './components/CartButton';");
lines.push("import CartDrawer from './components/CartDrawer';");
lines.push("import AppKitWidget from './components/AppKitWidget';");
lines.push("");
lines.push("type CircleStep = 'email'|'otp'|'checking'|'found'|'notfound'|'creating'|'done';");
lines.push("type CircleWallet = { address: string; walletId: string; email: string };");
lines.push("const STORAGE_KEY = 'vendra_circle_wallet';");
lines.push("");
lines.push("export default function Nav() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const [showLogin, setShowLogin] = useState(false);");
lines.push("  const [showCircle, setShowCircle] = useState(false);");
lines.push("  const [showDashboard, setShowDashboard] = useState(false);");
lines.push("  const [step, setStep] = useState<CircleStep>('email');");
lines.push("  const [email, setEmail] = useState('');");
lines.push("  const [otp, setOtp] = useState('');");
lines.push("  const [circleWallet, setCircleWallet] = useState<CircleWallet|null>(null);");
lines.push("  const [balance, setBalance] = useState('0');");
lines.push("  const [copied, setCopied] = useState(false);");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [loading, setLoading] = useState(false);");
lines.push("  const [sendForm, setSendForm] = useState({ to:'', amount:'' });");
lines.push("  const [sending, setSending] = useState(false);");
lines.push("  const [sendResult, setSendResult] = useState('');");
lines.push("  const [resendTimer, setResendTimer] = useState(0);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    try {");
lines.push("      const saved = sessionStorage.getItem(STORAGE_KEY);");
lines.push("      if (saved) { const w = JSON.parse(saved); setCircleWallet(w); fetchBalance(w.walletId); }");
lines.push("    } catch {}");
lines.push("  }, []);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    if (resendTimer > 0) { const t = setTimeout(() => setResendTimer(resendTimer - 1), 1000); return () => clearTimeout(t); }");
lines.push("  }, [resendTimer]);");
lines.push("");
lines.push("  const saveWallet = (w: CircleWallet) => { setCircleWallet(w); try { sessionStorage.setItem(STORAGE_KEY, JSON.stringify(w)); } catch {} };");
lines.push("  const logout = () => { setCircleWallet(null); try { sessionStorage.removeItem(STORAGE_KEY); } catch {} setShowDashboard(false); };");
lines.push("  const closeAll = () => { setShowLogin(false); setShowCircle(false); setShowDashboard(false); setStep('email'); setError(''); setOtp(''); setSendResult(''); };");
lines.push("  const shortAddr = (addr: string) => addr ? addr.slice(0,6)+'...'+addr.slice(-4) : '';");
lines.push("");
lines.push("  const fetchBalance = async (walletId: string) => {");
lines.push("    try { const res = await fetch('/api/circle/balance', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId }) }); const data = await res.json(); setBalance(data.balance || '0'); } catch {}");
lines.push("  };");
lines.push("");
lines.push("  const handleCopy = () => { if (!circleWallet) return; navigator.clipboard.writeText(circleWallet.address); setCopied(true); setTimeout(() => setCopied(false), 2000); };");
lines.push("");
lines.push("  const handleSendOtp = async () => {");
lines.push("    if (!email) { setError('Enter your email'); return; }");
lines.push("    setLoading(true); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send-otp', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setStep('otp'); setResendTimer(60);");
lines.push("    } catch(e:any) { setError(e.message || 'Failed to send code'); }");
lines.push("    finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const handleVerifyOtp = async () => {");
lines.push("    if (!otp || otp.length !== 6) { setError('Enter the 6-digit code'); return; }");
lines.push("    setLoading(true); setError(''); setStep('checking');");
lines.push("    try {");
lines.push("      const verifyRes = await fetch('/api/circle/verify-otp', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email, otp }) });");
lines.push("      const verifyData = await verifyRes.json();");
lines.push("      if (verifyData.error) throw new Error(verifyData.error);");
lines.push("      // OTP verified — now check/create wallet");
lines.push("      const res = await fetch('/api/circle/login', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      if (data.found) {");
lines.push("        const w = { address: data.address, walletId: data.walletId, email };");
lines.push("        saveWallet(w); await fetchBalance(data.walletId); setStep('found');");
lines.push("      } else { setStep('notfound'); }");
lines.push("    } catch(e:any) { setError(e.message || 'Verification failed'); setStep('otp'); }");
lines.push("    finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  const handleCreate = async () => {");
lines.push("    setStep('creating'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/create-wallet', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      const w = { address: data.address, walletId: data.walletId, email };");
lines.push("      saveWallet(w); await fetchBalance(data.walletId); setStep('done');");
lines.push("    } catch(e:any) { setError(e.message || 'Failed'); setStep('notfound'); }");
lines.push("  };");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!sendForm.to||!sendForm.amount||!circleWallet) return;");
lines.push("    setSending(true); setSendResult(''); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId:circleWallet.walletId, walletAddress:circleWallet.address, toAddress:sendForm.to, amount:sendForm.amount }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setSendResult('Sent! TX: '+(data.txId||'').slice(0,20)+'...');");
lines.push("    } catch(e:any) { setError(e.message||'Send failed'); }");
lines.push("    finally { setSending(false); }");
lines.push("  };");
lines.push("");
lines.push("  const WalletDashboard = () => (");
lines.push("    <>");
lines.push("      <div style={{border:'1px solid rgba(212,176,90,0.2)',background:'rgba(212,176,90,0.04)',padding:'20px',marginBottom:16,position:'relative',overflow:'hidden'}}>");
lines.push("        <div style={{position:'absolute',top:0,left:'10%',right:'10%',height:1,background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)'}}/>");
lines.push("        <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--w18)',marginBottom:4}}>Circle Wallet · Arc Testnet</div>");
lines.push("        <div style={{display:'flex',alignItems:'center',gap:8,marginBottom:12}}>");
lines.push("          <div style={{fontFamily:\"'Cormorant',serif\",fontSize:12,fontWeight:300,color:'var(--a)',flex:1,wordBreak:'break-all'}}>{circleWallet?.address}</div>");
lines.push("          <button onClick={handleCopy} style={{fontFamily:\"'DM Sans',sans-serif\",fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.12em',textTransform:'uppercase',border:'1px solid var(--b2)',color:copied?'var(--gr)':'var(--w35)',padding:'5px 10px',background:'transparent',cursor:'pointer',flexShrink:0,transition:'all 0.3s',whiteSpace:'nowrap'}}>{copied?'✓ Copied':'Copy'}</button>");
lines.push("        </div>");
lines.push("        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>");
lines.push("          <div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--w18)',marginBottom:2}}>USDC Balance</div><div style={{fontFamily:\"'Cormorant',serif\",fontSize:32,fontWeight:300,color:'var(--a2)'}}>${balance}</div></div>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{fontSize:9,padding:'8px 12px'}}>Get USDC ↗</button></a>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div className='v-field'><label className='v-label'>Send to Address</label><input className='v-input' placeholder='0x...' value={sendForm.to} onChange={e=>setSendForm({...sendForm,to:e.target.value})}/></div>");
lines.push("      <div className='v-field'><label className='v-label'>Amount (USDC)</label><input className='v-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e=>setSendForm({...sendForm,amount:e.target.value})}/></div>");
lines.push("      {error&&<div style={{fontSize:11,fontStyle:'italic',color:'var(--err)',marginBottom:10,border:'1px solid rgba(232,112,112,0.2)',padding:'8px 12px'}}>{error}</div>}");
lines.push("      {sendResult&&<div style={{fontSize:10,fontStyle:'italic',color:'var(--gr)',marginBottom:10,border:'1px solid var(--gr3)',padding:'8px 12px',wordBreak:'break-all'}}>{sendResult}</div>}");
lines.push("      <button onClick={handleSend} disabled={sending} className='btn-primary' style={{width:'100%',padding:'12px',fontSize:10,marginBottom:10}}>{sending?'Sending...':'Send USDC on Arc →'}</button>");
lines.push("      <div style={{display:'flex',gap:8}}>");
lines.push("        <a href={`https://testnet.arcscan.app/address/${circleWallet?.address}`} target='_blank' rel='noopener noreferrer' style={{flex:1}}><button className='btn-ghost' style={{width:'100%',fontSize:9,padding:'8px'}}>Arc Explorer ↗</button></a>");
lines.push("        <button onClick={logout} className='btn-danger' style={{flex:1,fontSize:9,padding:'8px'}}>Log Out</button>");
lines.push("      </div>");
lines.push("    </>");
lines.push("  );");
lines.push("");
lines.push("  const CircleFlow = () => (");
lines.push("    <div className='v-modal-bg' onClick={closeAll}>");
lines.push("      <div className='v-modal' style={{maxWidth:440}} onClick={e=>e.stopPropagation()}>");
lines.push("        <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:20}}>");
lines.push("          <div>");
lines.push("            <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--sl)',marginBottom:4}}>Circle · USDC Wallet</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:24,fontWeight:300,color:'var(--w)'}}>"); 
lines.push("              {step==='email'&&'Log In with Circle'}");
lines.push("              {step==='otp'&&'Enter Your Code'}");
lines.push("              {step==='checking'&&'Verifying...'}");
lines.push("              {step==='notfound'&&'Create Wallet'}");
lines.push("              {step==='creating'&&'Creating Wallet...'}");
lines.push("              {(step==='found'||step==='done')&&'Welcome Back ✓'}");
lines.push("            </div>");
lines.push("          </div>");
lines.push("          <button onClick={closeAll} style={{background:'transparent',border:'1px solid var(--b1)',color:'var(--w35)',width:32,height:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>✕</button>");
lines.push("        </div>");
lines.push("        {step==='email'&&(");
lines.push("          <>");
lines.push("            <div style={{fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.8,marginBottom:20}}>Enter your email. We'll send a verification code to confirm it's you.</div>");
lines.push("            <div className='v-field'><label className='v-label'>Email Address</label><input className='v-input' type='email' placeholder='you@example.com' value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&handleSendOtp()} autoFocus/></div>");
lines.push("            {error&&<div style={{fontSize:11,fontStyle:'italic',color:'var(--err)',marginBottom:12,border:'1px solid rgba(232,112,112,0.2)',padding:'8px 12px'}}>{error}</div>}");
lines.push("            <button onClick={handleSendOtp} disabled={loading} className='btn-primary' style={{width:'100%',padding:'14px',fontSize:11,marginBottom:10}}>{loading?'Sending code...':'Send Verification Code →'}</button>");
lines.push("            <button onClick={()=>{setShowCircle(false);setShowLogin(true);}} style={{width:'100%',background:'transparent',border:'none',fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',cursor:'pointer',padding:'8px'}}>← Back to options</button>");
lines.push("          </>");
lines.push("        )}");
lines.push("        {step==='otp'&&(");
lines.push("          <>");
lines.push("            <div style={{fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.8,marginBottom:8}}>We sent a 6-digit code to <strong style={{color:'var(--w)'}}>{email}</strong>. Enter it below.</div>");
lines.push("            <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',marginBottom:20,letterSpacing:'0.06em'}}>Check your inbox and spam folder. Code expires in 10 minutes.</div>");
lines.push("            <div className='v-field'><label className='v-label'>6-Digit Code</label><input className='v-input' type='text' inputMode='numeric' maxLength={6} placeholder='000000' value={otp} onChange={e=>setOtp(e.target.value.replace(/\\D/g,''))} onKeyDown={e=>e.key==='Enter'&&handleVerifyOtp()} autoFocus style={{letterSpacing:'0.3em',fontSize:22,textAlign:'center'}}/></div>");
lines.push("            {error&&<div style={{fontSize:11,fontStyle:'italic',color:'var(--err)',marginBottom:12,border:'1px solid rgba(232,112,112,0.2)',padding:'8px 12px'}}>{error}</div>}");
lines.push("            <button onClick={handleVerifyOtp} disabled={loading||otp.length!==6} className='btn-primary' style={{width:'100%',padding:'14px',fontSize:11,marginBottom:10}}>{loading?'Verifying...':'Verify & Continue →'}</button>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>");
lines.push("              <button onClick={()=>{setStep('email');setOtp('');setError('');}} style={{background:'transparent',border:'none',fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',cursor:'pointer',padding:'8px 0'}}>← Change email</button>");
lines.push("              <button onClick={resendTimer===0?handleSendOtp:undefined} disabled={resendTimer>0} style={{background:'transparent',border:'none',fontSize:10,fontWeight:300,fontStyle:'italic',color:resendTimer>0?'var(--w18)':'var(--a)',cursor:resendTimer>0?'not-allowed':'pointer',padding:'8px 0'}}>");
lines.push("                {resendTimer>0?`Resend in ${resendTimer}s`:'Resend code'}");
lines.push("              </button>");
lines.push("            </div>");
lines.push("          </>");
lines.push("        )}");
lines.push("        {step==='checking'&&<div style={{textAlign:'center',padding:'24px 0'}}><div className='v-spinner' style={{margin:'0 auto 16px'}}/><div style={{fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w35)'}}>Verifying your identity...</div></div>}");
lines.push("        {step==='notfound'&&(");
lines.push("          <>");
lines.push("            <div style={{border:'1px solid var(--b1)',padding:'16px',marginBottom:20,background:'var(--bg3)'}}>");
lines.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.7}}>No wallet found for <strong style={{color:'var(--w)'}}>{email}</strong>. Would you like to create one?</div>");
lines.push("            </div>");
lines.push("            {error&&<div style={{fontSize:11,fontStyle:'italic',color:'var(--err)',marginBottom:12,border:'1px solid rgba(232,112,112,0.2)',padding:'8px 12px'}}>{error}</div>}");
lines.push("            <button onClick={handleCreate} className='btn-primary' style={{width:'100%',padding:'14px',fontSize:11,marginBottom:10}}>Create New Circle Wallet →</button>");
lines.push("            <button onClick={()=>setStep('email')} style={{width:'100%',background:'transparent',border:'none',fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',cursor:'pointer',padding:'8px'}}>← Try a different email</button>");
lines.push("          </>");
lines.push("        )}");
lines.push("        {step==='creating'&&<div style={{textAlign:'center',padding:'24px 0'}}><div className='v-spinner' style={{margin:'0 auto 16px'}}/><div style={{fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w35)'}}>Creating your wallet on Arc Testnet...</div></div>}");
lines.push("        {(step==='found'||step==='done')&&circleWallet&&<WalletDashboard/>}");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("");
lines.push("  return (");
lines.push("    <>");
lines.push("      <CartDrawer/>");
lines.push("      {showLogin&&!showCircle&&(");
lines.push("        <div className='v-modal-bg' onClick={closeAll}>");
lines.push("          <div className='v-modal' style={{maxWidth:400}} onClick={e=>e.stopPropagation()}>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}>");
lines.push("              <div style={{fontFamily:\"'Cormorant',serif\",fontSize:28,fontWeight:300,color:'var(--w)'}}>Log In</div>");
lines.push("              <button onClick={closeAll} style={{background:'transparent',border:'1px solid var(--b1)',color:'var(--w35)',width:32,height:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'}}>✕</button>");
lines.push("            </div>");
lines.push("            <div style={{fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w35)',lineHeight:1.7,marginBottom:20}}>Choose how you want to connect to Vendra.</div>");
lines.push("            <div style={{border:'1px solid var(--b1)',padding:'20px',marginBottom:12,background:'var(--bg3)',position:'relative',overflow:'hidden'}}>");
lines.push("              <div style={{position:'absolute',top:0,left:'20%',right:'20%',height:1,background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.3),transparent)'}}/>");
lines.push("              <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--a)',marginBottom:8}}>🦊 Web3 Wallet</div>");
lines.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:14,lineHeight:1.6}}>MetaMask, Coinbase, WalletConnect or any EVM wallet.</div>");
lines.push("              <div style={{display:'flex',justifyContent:'center'}}><ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false}/></div>");
lines.push("            </div>");
lines.push("            <div style={{display:'flex',alignItems:'center',gap:12,marginBottom:12}}>");
lines.push("              <div style={{flex:1,height:1,background:'var(--b1)'}}/><span style={{fontSize:9,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.14em',textTransform:'uppercase'}}>or</span><div style={{flex:1,height:1,background:'var(--b1)'}}/>");
lines.push("            </div>");
lines.push("            <div style={{border:'1px solid rgba(155,181,200,0.2)',padding:'20px',background:'rgba(155,181,200,0.03)',position:'relative',overflow:'hidden'}}>");
lines.push("              <div style={{position:'absolute',top:0,left:'20%',right:'20%',height:1,background:'linear-gradient(90deg,transparent,rgba(155,181,200,0.3),transparent)'}}/>");
lines.push("              <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.16em',textTransform:'uppercase',color:'var(--sl)',marginBottom:8}}>⭕ Circle Wallet</div>");
lines.push("              <div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:14,lineHeight:1.6}}>No crypto experience needed. Verify your email to access your USDC wallet.</div>");
lines.push("              <button onClick={()=>{setShowLogin(false);setShowCircle(true);}} className='btn-slate' style={{width:'100%',fontSize:10,padding:'12px'}}>Log In with Circle Wallet →</button>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("      {showCircle&&<CircleFlow/>}");
lines.push("      {showDashboard&&circleWallet&&(");
lines.push("        <div className='v-modal-bg' onClick={closeAll}>");
lines.push("          <div className='v-modal' style={{maxWidth:440}} onClick={e=>e.stopPropagation()}>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:20}}>");
lines.push("              <div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--sl)',marginBottom:4}}>Circle · USDC Wallet</div><div style={{fontFamily:\"'Cormorant',serif\",fontSize:22,fontWeight:300,color:'var(--w)'}}>{circleWallet.email}</div></div>");
lines.push("              <button onClick={closeAll} style={{background:'transparent',border:'1px solid var(--b1)',color:'var(--w35)',width:32,height:32,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>✕</button>");
lines.push("            </div>");
lines.push("            <WalletDashboard/>");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("      <nav className='v-nav'>");
lines.push("        <Link href='/' className='v-logo'><div className='v-logo-emblem'><span className='v-logo-v'>V</span></div><span className='v-logo-name'>Vendra</span></Link>");
lines.push("        <div className='v-nav-links'>");
lines.push("          <Link href='/marketplace'>Marketplace</Link>");
lines.push("          <Link href='/store/create'>Sell</Link>");
lines.push("          {isConnected&&<Link href='/profile'>Profile</Link>}");
lines.push("        </div>");
lines.push("        <div className='v-nav-right'>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{textDecoration:'none'}}><button className='btn-faucet'>💧 Faucet</button></a>");
lines.push("          <CartButton/>");
lines.push("          {isConnected&&<AppKitWidget/>}");
lines.push("          {isConnected");
lines.push("            ?<ConnectButton accountStatus='address' chainStatus='none' showBalance={false}/>");
lines.push("            :circleWallet");
lines.push("              ?<button onClick={()=>{setShowDashboard(true);fetchBalance(circleWallet.walletId);}} className='btn-nav-amber' style={{display:'flex',alignItems:'center',gap:8}}><span>⭕</span><span>{shortAddr(circleWallet.address)}</span></button>");
lines.push("              :<button onClick={()=>setShowLogin(true)} className='btn-nav-amber'>Log In</button>}");
lines.push("        </div>");
lines.push("      </nav>");
lines.push("    </>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/Nav.tsx', lines.join('\n'), 'utf8');
console.log('Nav with OTP done:', fs.existsSync('app/Nav.tsx'));
