const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Link from 'next/link';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useState } from 'react';");
lines.push("import CartButton from './components/CartButton';");
lines.push("import CartDrawer from './components/CartDrawer';");
lines.push("");
lines.push("type CircleStep = 'email'|'checking'|'found'|'notfound'|'creating'|'done';");
lines.push("");
lines.push("export default function Nav() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const [showLogin, setShowLogin] = useState(false);");
lines.push("  const [showCircle, setShowCircle] = useState(false);");
lines.push("  const [step, setStep] = useState<CircleStep>('email');");
lines.push("  const [email, setEmail] = useState('');");
lines.push("  const [wallet, setWallet] = useState<{address:string;walletId:string}|null>(null);");
lines.push("  const [balance, setBalance] = useState('0');");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [sendForm, setSendForm] = useState({ to:'', amount:'' });");
lines.push("  const [sending, setSending] = useState(false);");
lines.push("  const [sendResult, setSendResult] = useState('');");
lines.push("");
lines.push("  const closeAll = () => { setShowLogin(false); setShowCircle(false); setStep('email'); setError(''); setSendResult(''); };");
lines.push("");
lines.push("  const fetchBalance = async (walletId: string) => {");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/balance', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId }) });");
lines.push("      const data = await res.json();");
lines.push("      setBalance(data.balance || '0');");
lines.push("    } catch {}");
lines.push("  };");
lines.push("");
lines.push("  const handleLogin = async () => {");
lines.push("    if (!email) { setError('Enter your email'); return; }");
lines.push("    setStep('checking'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/login', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      if (data.found) {");
lines.push("        setWallet({ address: data.address, walletId: data.walletId });");
lines.push("        await fetchBalance(data.walletId);");
lines.push("        setStep('found');");
lines.push("      } else {");
lines.push("        setStep('notfound');");
lines.push("      }");
lines.push("    } catch(e:any) { setError(e.message || 'Something went wrong'); setStep('email'); }");
lines.push("  };");
lines.push("");
lines.push("  const handleCreate = async () => {");
lines.push("    setStep('creating'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/create-wallet', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setWallet({ address: data.address, walletId: data.walletId });");
lines.push("      await fetchBalance(data.walletId);");
lines.push("      setStep('done');");
lines.push("    } catch(e:any) { setError(e.message || 'Failed to create wallet'); setStep('notfound'); }");
lines.push("  };");
lines.push("");
lines.push("  const handleSend = async () => {");
lines.push("    if (!sendForm.to || !sendForm.amount || !wallet) return;");
lines.push("    setSending(true); setSendResult(''); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/send', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId: wallet.walletId, walletAddress: wallet.address, toAddress: sendForm.to, amount: sendForm.amount }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setSendResult('Sent! TX: ' + data.txId?.slice(0, 20) + '...');");
lines.push("    } catch(e:any) { setError(e.message || 'Send failed'); }");
lines.push("    finally { setSending(false); }");
lines.push("  };");
lines.push("");
lines.push("  const WalletDashboard = () => (");
lines.push("    <>");
lines.push("      <div style={{ border:'1px solid rgba(212,176,90,0.2)', background:'rgba(212,176,90,0.04)', padding:'20px', marginBottom:16, position:'relative', overflow:'hidden' }}>");
lines.push("        <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
lines.push("        <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--w18)', marginBottom:4 }}>Circle Wallet · Arc Testnet</div>");
lines.push("        <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:11, fontWeight:300, color:'var(--a)', wordBreak:'break-all', marginBottom:12 }}>{wallet?.address}</div>");
lines.push("        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("          <div><div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.14em', textTransform:'uppercase', color:'var(--w18)', marginBottom:2 }}>USDC Balance</div><div style={{ fontFamily:\"'Cormorant',serif\", fontSize:32, fontWeight:300, color:'var(--a2)' }}>${balance}</div></div>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{ fontSize:9, padding:'8px 12px' }}>Get USDC ↗</button></a>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <div className='v-field'><label className='v-label'>Send to</label><input className='v-input' placeholder='0x...' value={sendForm.to} onChange={e => setSendForm({...sendForm, to:e.target.value})} /></div>");
lines.push("      <div className='v-field'><label className='v-label'>Amount USDC</label><input className='v-input' type='number' placeholder='e.g. 5.00' value={sendForm.amount} onChange={e => setSendForm({...sendForm, amount:e.target.value})} /></div>");
lines.push("      {error && <div style={{ fontSize:11, fontStyle:'italic', color:'var(--err)', marginBottom:10, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("      {sendResult && <div style={{ fontSize:10, fontStyle:'italic', color:'var(--gr)', marginBottom:10, border:'1px solid var(--gr3)', padding:'8px 12px', wordBreak:'break-all' }}>{sendResult}</div>}");
lines.push("      <button onClick={handleSend} disabled={sending} className='btn-primary' style={{ width:'100%', padding:'12px', fontSize:10, marginBottom:10 }}>{sending?'Sending...':'Send USDC on Arc →'}</button>");
lines.push("      <div style={{ display:'flex', gap:8 }}>");
lines.push("        <a href={`https://testnet.arcscan.app/address/${wallet?.address}`} target='_blank' rel='noopener noreferrer' style={{ flex:1 }}><button className='btn-ghost' style={{ width:'100%', fontSize:9, padding:'8px' }}>Arc Explorer ↗</button></a>");
lines.push("        <button onClick={closeAll} className='btn-slate' style={{ flex:1, fontSize:9, padding:'8px' }}>Close</button>");
lines.push("      </div>");
lines.push("    </>");
lines.push("  );");
lines.push("");
lines.push("  return (");
lines.push("    <>");
lines.push("      <CartDrawer />");
lines.push("");
lines.push("      {/* Login Modal */}");
lines.push("      {showLogin && !showCircle && (");
lines.push("        <div className='v-modal-bg' onClick={closeAll}>");
lines.push("          <div className='v-modal' style={{ maxWidth:400 }} onClick={e => e.stopPropagation()}>");
lines.push("            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:24 }}>");
lines.push("              <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:28, fontWeight:300, color:'var(--w)' }}>Log In</div>");
lines.push("              <button onClick={closeAll} style={{ background:'transparent', border:'1px solid var(--b1)', color:'var(--w35)', width:32, height:32, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center' }}>✕</button>");
lines.push("            </div>");
lines.push("            <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:20 }}>Choose how you want to connect to Vendra.</div>");
lines.push("            {/* Web3 */}");
lines.push("            <div style={{ border:'1px solid var(--b1)', padding:'20px', marginBottom:12, background:'var(--bg3)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.3),transparent)' }} />");
lines.push("              <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--a)', marginBottom:8 }}>🦊 Web3 Wallet</div>");
lines.push("              <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', marginBottom:14, lineHeight:1.6 }}>MetaMask, Coinbase, WalletConnect or any EVM wallet.</div>");
lines.push("              <div style={{ display:'flex', justifyContent:'center' }}><ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} /></div>");
lines.push("            </div>");
lines.push("            <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:12 }}>");
lines.push("              <div style={{ flex:1, height:1, background:'var(--b1)' }}/><span style={{ fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.14em', textTransform:'uppercase' }}>or</span><div style={{ flex:1, height:1, background:'var(--b1)' }}/>");
lines.push("            </div>");
lines.push("            {/* Circle */}");
lines.push("            <div style={{ border:'1px solid rgba(155,181,200,0.2)', padding:'20px', background:'rgba(155,181,200,0.03)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(155,181,200,0.3),transparent)' }} />");
lines.push("              <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--sl)', marginBottom:8 }}>⭕ Circle Wallet</div>");
lines.push("              <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', marginBottom:14, lineHeight:1.6 }}>No crypto experience needed. Log in with your email.</div>");
lines.push("              <button onClick={() => setShowCircle(true)} className='btn-slate' style={{ width:'100%', fontSize:10, padding:'12px' }}>Log In with Circle Wallet →</button>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("");
lines.push("      {/* Circle Modal */}");
lines.push("      {showCircle && (");
lines.push("        <div className='v-modal-bg' onClick={closeAll}>");
lines.push("          <div className='v-modal' style={{ maxWidth:440 }} onClick={e => e.stopPropagation()}>");
lines.push("            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:20 }}>");
lines.push("              <div>");
lines.push("                <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--sl)', marginBottom:4 }}>Circle · USDC Wallet</div>");
lines.push("                <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:24, fontWeight:300, color:'var(--w)' }}>");
lines.push("                  {step==='email'&&'Log In with Circle'}");
lines.push("                  {step==='checking'&&'Checking...'}");
lines.push("                  {step==='notfound'&&'Create Wallet'}");
lines.push("                  {step==='creating'&&'Creating Wallet...'}");
lines.push("                  {(step==='found'||step==='done')&&'Welcome Back'}");
lines.push("                </div>");
lines.push("              </div>");
lines.push("              <button onClick={closeAll} style={{ background:'transparent', border:'1px solid var(--b1)', color:'var(--w35)', width:32, height:32, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>✕</button>");
lines.push("            </div>");
lines.push("");
lines.push("            {/* Step: Email */}");
lines.push("            {step==='email' && (");
lines.push("              <>");
lines.push("                <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:20 }}>Enter the email linked to your Circle wallet. If you don't have one yet, we'll create one for you.</div>");
lines.push("                <div className='v-field'><label className='v-label'>Email Address</label><input className='v-input' type='email' placeholder='you@example.com' value={email} onChange={e => setEmail(e.target.value)} onKeyDown={e => e.key==='Enter' && handleLogin()} autoFocus /></div>");
lines.push("                {error && <div style={{ fontSize:11, fontStyle:'italic', color:'var(--err)', marginBottom:12, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                <button onClick={handleLogin} className='btn-primary' style={{ width:'100%', padding:'14px', fontSize:11, marginBottom:10 }}>Continue →</button>");
lines.push("                <button onClick={() => setShowCircle(false)} style={{ width:'100%', background:'transparent', border:'none', fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', cursor:'pointer', padding:'8px' }}>← Back to options</button>");
lines.push("              </>");
lines.push("            )}");
lines.push("");
lines.push("            {/* Step: Checking */}");
lines.push("            {step==='checking' && <div style={{ textAlign:'center', padding:'24px 0' }}><div className='v-spinner' style={{ margin:'0 auto 16px' }}/><div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)' }}>Looking up your wallet...</div></div>}");
lines.push("");
lines.push("            {/* Step: Not found — offer to create */}");
lines.push("            {step==='notfound' && (");
lines.push("              <>");
lines.push("                <div style={{ border:'1px solid var(--b1)', padding:'16px', marginBottom:20, background:'var(--bg3)' }}>");
lines.push("                  <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7 }}>No wallet found for <strong style={{ color:'var(--w)' }}>{email}</strong>. Would you like to create one?</div>");
lines.push("                </div>");
lines.push("                {error && <div style={{ fontSize:11, fontStyle:'italic', color:'var(--err)', marginBottom:12, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                <button onClick={handleCreate} className='btn-primary' style={{ width:'100%', padding:'14px', fontSize:11, marginBottom:10 }}>Create New Circle Wallet →</button>");
lines.push("                <button onClick={() => setStep('email')} style={{ width:'100%', background:'transparent', border:'none', fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', cursor:'pointer', padding:'8px' }}>← Try a different email</button>");
lines.push("              </>");
lines.push("            )}");
lines.push("");
lines.push("            {/* Step: Creating */}");
lines.push("            {step==='creating' && <div style={{ textAlign:'center', padding:'24px 0' }}><div className='v-spinner' style={{ margin:'0 auto 16px' }}/><div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)' }}>Creating your wallet on Arc Testnet...</div></div>}");
lines.push("");
lines.push("            {/* Step: Found or Done — show dashboard */}");
lines.push("            {(step==='found' || step==='done') && wallet && <WalletDashboard />}");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("");
lines.push("      <nav className='v-nav'>");
lines.push("        <Link href='/' className='v-logo'>");
lines.push("          <div className='v-logo-emblem'><span className='v-logo-v'>V</span></div>");
lines.push("          <span className='v-logo-name'>Vendra</span>");
lines.push("        </Link>");
lines.push("        <div className='v-nav-links'>");
lines.push("          <Link href='/marketplace'>Marketplace</Link>");
lines.push("          <Link href='/store/create'>Sell</Link>");
lines.push("          {isConnected && <Link href='/profile'>Profile</Link>}");
lines.push("        </div>");
lines.push("        <div className='v-nav-right'>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{ textDecoration:'none' }}>");
lines.push("            <button className='btn-faucet'>💧 Faucet</button>");
lines.push("          </a>");
lines.push("          <CartButton />");
lines.push("          {isConnected");
lines.push("            ? <ConnectButton accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("            : <button onClick={() => setShowLogin(true)} className='btn-nav-amber'>Log In</button>}");
lines.push("        </div>");
lines.push("      </nav>");
lines.push("    </>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/Nav.tsx', lines.join('\n'), 'utf8');
console.log('Nav v3 done:', fs.existsSync('app/Nav.tsx'));
