const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Link from 'next/link';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useState } from 'react';");
lines.push("import CartButton from './components/CartButton';");
lines.push("import CartDrawer from './components/CartDrawer';");
lines.push("");
lines.push("export default function Nav() {");
lines.push("  const { isConnected, address } = useAccount();");
lines.push("  const [showLogin, setShowLogin] = useState(false);");
lines.push("  const [showCircle, setShowCircle] = useState(false);");
lines.push("  const [step, setStep] = useState<'form'|'creating'|'done'>('form');");
lines.push("  const [email, setEmail] = useState('');");
lines.push("  const [circleWallet, setCircleWallet] = useState<{address:string;walletId:string}|null>(null);");
lines.push("  const [balance, setBalance] = useState('0');");
lines.push("  const [error, setError] = useState('');");
lines.push("");
lines.push("  const closeAll = () => { setShowLogin(false); setShowCircle(false); setStep('form'); setError(''); };");
lines.push("");
lines.push("  const handleCreateCircleWallet = async () => {");
lines.push("    if (!email) { setError('Enter your email'); return; }");
lines.push("    setStep('creating'); setError('');");
lines.push("    try {");
lines.push("      const res = await fetch('/api/circle/create-wallet', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ userAddress: email }) });");
lines.push("      const data = await res.json();");
lines.push("      if (data.error) throw new Error(data.error);");
lines.push("      setCircleWallet({ address: data.address, walletId: data.walletId });");
lines.push("      const balRes = await fetch('/api/circle/balance', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ walletId: data.walletId }) });");
lines.push("      const balData = await balRes.json();");
lines.push("      setBalance(balData.balance || '0');");
lines.push("      setStep('done');");
lines.push("    } catch(e:any) { setError(e.message || 'Failed'); setStep('form'); }");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <>");
lines.push("      <CartDrawer />");
lines.push("");
lines.push("      {/* Login Modal */}");
lines.push("      {showLogin && !showCircle && (");
lines.push("        <div className='v-modal-bg' onClick={closeAll}>");
lines.push("          <div className='v-modal' style={{ maxWidth:400 }} onClick={e => e.stopPropagation()}>");
lines.push("            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:24 }}>");
lines.push("              <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:28, fontWeight:300, color:'var(--w)' }}>Log In</div>");
lines.push("              <button onClick={closeAll} style={{ background:'transparent', border:'1px solid var(--b1)', color:'var(--w35)', width:32, height:32, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center' }}>✕</button>");
lines.push("            </div>");
lines.push("            <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7, marginBottom:24 }}>Choose how you want to connect to Vendra.</div>");
lines.push("            {/* Web3 Option */}");
lines.push("            <div style={{ border:'1px solid var(--b1)', padding:'20px', marginBottom:12, background:'var(--bg3)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.3),transparent)' }} />");
lines.push("              <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--a)', marginBottom:8 }}>🦊 Web3 Wallet</div>");
lines.push("              <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', marginBottom:16, lineHeight:1.6 }}>MetaMask, Coinbase, WalletConnect or any EVM wallet.</div>");
lines.push("              <div style={{ display:'flex', justifyContent:'center' }}>");
lines.push("                <ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {/* Divider */}");
lines.push("            <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:12 }}>");
lines.push("              <div style={{ flex:1, height:1, background:'var(--b1)' }}/>");
lines.push("              <span style={{ fontSize:9, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.14em', textTransform:'uppercase' }}>or</span>");
lines.push("              <div style={{ flex:1, height:1, background:'var(--b1)' }}/>");
lines.push("            </div>");
lines.push("            {/* Circle Option */}");
lines.push("            <div style={{ border:'1px solid rgba(155,181,200,0.2)', padding:'20px', background:'rgba(155,181,200,0.03)', position:'relative', overflow:'hidden' }}>");
lines.push("              <div style={{ position:'absolute', top:0, left:'20%', right:'20%', height:1, background:'linear-gradient(90deg,transparent,rgba(155,181,200,0.3),transparent)' }} />");
lines.push("              <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--sl)', marginBottom:8 }}>⭕ Circle Wallet</div>");
lines.push("              <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w35)', marginBottom:16, lineHeight:1.6 }}>No crypto experience needed. Create a USDC wallet with just your email.</div>");
lines.push("              <button onClick={() => setShowCircle(true)} className='btn-slate' style={{ width:'100%', fontSize:10, padding:'12px' }}>Create Circle Wallet →</button>");
lines.push("            </div>");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("");
lines.push("      {/* Circle Wallet Modal */}");
lines.push("      {showCircle && (");
lines.push("        <div className='v-modal-bg' onClick={closeAll}>");
lines.push("          <div className='v-modal' style={{ maxWidth:440 }} onClick={e => e.stopPropagation()}>");
lines.push("            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:20 }}>");
lines.push("              <div>");
lines.push("                <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.18em', textTransform:'uppercase', color:'var(--sl)', marginBottom:6 }}>Circle · Developer Controlled Wallet</div>");
lines.push("                <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:24, fontWeight:300, color:'var(--w)' }}>{step==='done'?'Wallet Ready':step==='creating'?'Creating...':'Create Circle Wallet'}</div>");
lines.push("              </div>");
lines.push("              <button onClick={closeAll} style={{ background:'transparent', border:'1px solid var(--b1)', color:'var(--w35)', width:32, height:32, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }}>✕</button>");
lines.push("            </div>");
lines.push("            {step==='form' && (");
lines.push("              <>");
lines.push("                <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:20 }}>Enter your email and we'll create a USDC wallet on Arc Testnet instantly.</div>");
lines.push("                <div className='v-field'><label className='v-label'>Email</label><input className='v-input' type='email' placeholder='you@example.com' value={email} onChange={e => setEmail(e.target.value)} onKeyDown={e => e.key==='Enter' && handleCreateCircleWallet()} /></div>");
lines.push("                {error && <div style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--err)', marginBottom:12, border:'1px solid rgba(232,112,112,0.2)', padding:'8px 12px' }}>{error}</div>}");
lines.push("                <button onClick={handleCreateCircleWallet} className='btn-primary' style={{ width:'100%', padding:'14px', fontSize:11, marginBottom:12 }}>Create My USDC Wallet →</button>");
lines.push("                <button onClick={() => setShowCircle(false)} style={{ width:'100%', background:'transparent', border:'none', fontSize:10, fontWeight:300, fontStyle:'italic', color:'var(--w18)', cursor:'pointer', padding:'8px' }}>← Back</button>");
lines.push("              </>");
lines.push("            )}");
lines.push("            {step==='creating' && <div style={{ textAlign:'center', padding:'24px 0' }}><div className='v-spinner' style={{ margin:'0 auto 16px' }}/><div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)' }}>Creating your wallet on Arc Testnet...</div></div>}");
lines.push("            {step==='done' && circleWallet && (");
lines.push("              <>");
lines.push("                <div style={{ border:'1px solid rgba(212,176,90,0.2)', background:'rgba(212,176,90,0.04)', padding:'20px', marginBottom:16, position:'relative', overflow:'hidden' }}>");
lines.push("                  <div style={{ position:'absolute', top:0, left:'10%', right:'10%', height:1, background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent)' }} />");
lines.push("                  <div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.16em', textTransform:'uppercase', color:'var(--w18)', marginBottom:4 }}>Your Circle Wallet · Arc Testnet</div>");
lines.push("                  <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:12, fontWeight:300, color:'var(--a2)', wordBreak:'break-all', marginBottom:12 }}>{circleWallet.address}</div>");
lines.push("                  <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>");
lines.push("                    <div><div style={{ fontSize:9, fontWeight:300, fontStyle:'italic', letterSpacing:'0.14em', textTransform:'uppercase', color:'var(--w18)', marginBottom:2 }}>USDC Balance</div><div style={{ fontFamily:\"'Cormorant',serif\", fontSize:28, fontWeight:300, color:'var(--a2)' }}>${balance}</div></div>");
lines.push("                    <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{ fontSize:9, padding:'8px 14px' }}>Get Test USDC ↗</button></a>");
lines.push("                  </div>");
lines.push("                </div>");
lines.push("                <div style={{ display:'flex', gap:8 }}>");
lines.push("                  <a href={`https://testnet.arcscan.app/address/${circleWallet.address}`} target='_blank' rel='noopener noreferrer' style={{ flex:1 }}><button className='btn-ghost' style={{ width:'100%', fontSize:9, padding:'10px' }}>Arc Explorer ↗</button></a>");
lines.push("                  <Link href='/marketplace' onClick={closeAll} style={{ flex:1 }}><button className='btn-primary' style={{ width:'100%', fontSize:9, padding:'10px' }}>Browse Marketplace →</button></Link>");
lines.push("                </div>");
lines.push("              </>");
lines.push("            )}");
lines.push("          </div>");
lines.push("        </div>)}");
lines.push("");
lines.push("      <nav className='v-nav'>");
lines.push("        <Link href='/' className='v-logo'>");
lines.push("          <div className='v-logo-emblem'><span className='v-logo-v'>V</span></div>");
lines.push("          <span className='v-logo-name'>Vendra</span>");
lines.push("        </Link>");
lines.push("        <div className='v-nav-links'>");
lines.push("          <Link href='/marketplace'>Marketplace</Link>");
lines.push("          <Link href='/store/create'>Sell</Link>");
lines.push("          {isConnected && <Link href='/profile'>Profile</Link>}");
lines.push("        </div>");
lines.push("        <div className='v-nav-right'>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{ textDecoration:'none' }}>");
lines.push("            <button className='btn-faucet'>💧 Faucet</button>");
lines.push("          </a>");
lines.push("          <CartButton />");
lines.push("          {isConnected");
lines.push("            ? <ConnectButton accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("            : <button onClick={() => setShowLogin(true)} className='btn-nav-amber'>Log In</button>}");
lines.push("        </div>");
lines.push("      </nav>");
lines.push("    </>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/Nav.tsx', lines.join('\n'), 'utf8');
console.log('Nav v2 done:', fs.existsSync('app/Nav.tsx'));
