const fs = require('fs');
const lines = [];
lines.push("'use client';");
lines.push("import Link from 'next/link';");
lines.push("import { ConnectButton } from '@rainbow-me/rainbowkit';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useState } from 'react';");
lines.push("import CartButton from './components/CartButton';");
lines.push("import CartDrawer from './components/CartDrawer';");
lines.push("");
lines.push("export default function Nav() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const [fHover, setFHover] = useState(false);");
lines.push("  return (");
lines.push("    <>");
lines.push("      <CartDrawer />");
lines.push("      <nav className='v-nav'>");
lines.push("        <Link href='/' className='v-logo'>");
lines.push("          <div className='v-logo-emblem'><span className='v-logo-v'>V</span></div>");
lines.push("          <span className='v-logo-name'>Vendra</span>");
lines.push("        </Link>");
lines.push("        <div className='v-nav-links'>");
lines.push("          <Link href='/marketplace'>Marketplace</Link>");
lines.push("          <Link href='/store/create'>Sell</Link>");
lines.push("          {isConnected && <Link href='/profile'>Profile</Link>}");
lines.push("        </div>");
lines.push("        <div className='v-nav-right'>");
lines.push("          <a href='https://faucet.circle.com/' target='_blank' rel='noopener noreferrer' style={{ textDecoration: 'none' }} onMouseEnter={() => setFHover(true)} onMouseLeave={() => setFHover(false)}>");
lines.push("            <button className='btn-faucet' style={{ border: fHover ? '1px solid rgba(155,181,200,0.45)' : '1px solid rgba(155,181,200,0.25)' }}>💧 Faucet</button>");
lines.push("          </a>");
lines.push("          <CartButton />");
lines.push("          <ConnectButton label='Connect Wallet' accountStatus='address' chainStatus='none' showBalance={false} />");
lines.push("        </div>");
lines.push("      </nav>");
lines.push("    </>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/Nav.tsx', lines.join('\n'), 'utf8');
console.log('Nav done');
