const fs = require('fs');
fs.mkdirSync('app/orders/[id]', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../../Nav';");
lines.push("import Link from 'next/link';");
lines.push("import { useParams } from 'next/navigation';");
lines.push("import { useState, useEffect } from 'react';");
lines.push("import { supabase } from '../../lib/supabase';");
lines.push("");
lines.push("export default function OrderPage() {");
lines.push("  const params = useParams();");
lines.push("  const id = params.id as string;");
lines.push("  const [order, setOrder] = useState<any>(null);");
lines.push("  const [loading, setLoading] = useState(true);");
lines.push("");
lines.push("  useEffect(() => {");
lines.push("    supabase.from('orders').select('*').eq('id',id).single().then(({data})=>{setOrder(data);setLoading(false);});");
lines.push("  }, [id]);");
lines.push("");
lines.push("  if (loading) return <main style={{minHeight:'100vh',background:'var(--bg)',display:'flex',alignItems:'center',justifyContent:'center'}}><Nav /><div className='v-spinner'/></main>;");
lines.push("");
lines.push("  if (!order) return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{textAlign:'center'}}>");
lines.push("        <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'3rem',fontWeight:300,color:'var(--w)',marginBottom:16}}>Order Not Found</div>");
lines.push("        <Link href='/profile'><button className='btn-primary'>Back to Profile</button></Link>");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("");
lines.push("  const explorerUrl = 'https://testnet.arcscan.app/tx/'+order.tx_hash;");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{maxWidth:560,margin:'0 auto',padding:'120px 56px 80px'}}>");
lines.push("        <div className='v-eyebrow' style={{marginBottom:16}}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Order Receipt</span></div>");
lines.push("        <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,letterSpacing:'-0.01em',lineHeight:0.94,color:'var(--w)',marginBottom:32}}>Order Details</h1>");
lines.push("        <div className='v-status-settled' style={{marginBottom:32}}><div className='v-status-dot'/>{order.status||'Confirmed'}</div>");
lines.push("        <div className='v-order-card'>");
lines.push("          <div style={{padding:'32px',background:'linear-gradient(145deg,rgba(212,176,90,0.06),rgba(12,14,26,0.8))',textAlign:'center',borderBottom:'1px solid var(--b1)'}}>");
lines.push("            <div style={{fontSize:'3.5rem',marginBottom:16}}>{'📦'}</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:24,fontWeight:400,color:'var(--w85)',marginBottom:8}}>{order.product_name}</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:40,fontWeight:300,color:'var(--a2)',lineHeight:1}}>{'$'}{Number(order.amount).toFixed(2)}{' USDC'}</div>");
lines.push("          </div>");
lines.push("          <div style={{padding:'24px'}}>");
lines.push("            {[['Date',new Date(order.created_at).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})],['Time',new Date(order.created_at).toLocaleTimeString()],['Buyer',order.buyer_wallet?order.buyer_wallet.slice(0,8)+'...'+order.buyer_wallet.slice(-6):''],['Seller',order.seller_wallet?order.seller_wallet.slice(0,8)+'...'+order.seller_wallet.slice(-6):''],['Network','Arc Testnet'],['Escrow','ERC-8183 Protected'],['Status',order.status||'Confirmed']].map(([label,val])=>(");
lines.push("              <div key={String(label)} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid var(--b1)'}}>");
lines.push("                <span style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--w18)'}}>{label}</span>");
lines.push("                <span style={{fontSize:12,fontWeight:300,color:'var(--w60)',fontFamily:\"'DM Sans',sans-serif\"}}>{val}</span>");
lines.push("              </div>))}");
lines.push("          </div>");
lines.push("        </div>");
lines.push("        {order.tx_hash&&(");
lines.push("          <a href={explorerUrl} target='_blank' rel='noopener noreferrer' style={{display:'block',border:'1px solid var(--b1)',padding:'16px 20px',marginBottom:24,textDecoration:'none',background:'var(--bg2)',transition:'border-color 0.35s'}} onMouseEnter={e=>(e.currentTarget.style.borderColor='var(--a)')} onMouseLeave={e=>(e.currentTarget.style.borderColor='var(--b1)')}>");
lines.push("            <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--w18)',marginBottom:6}}>Transaction Hash</div>");
lines.push("            <div style={{fontSize:11,fontWeight:300,color:'var(--a)',wordBreak:'break-all',fontFamily:\"'DM Sans',sans-serif\",marginBottom:6}}>{order.tx_hash}</div>");
lines.push("            <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em'}}>View on Arc Explorer ↗</div>");
lines.push("          </a>)}");
lines.push("        <div style={{display:'flex',gap:12,flexWrap:'wrap'}}>");
lines.push("          <Link href='/profile'><button className='btn-primary' style={{padding:'12px 24px',fontSize:10}}>View All Orders</button></Link>");
lines.push("          <Link href='/marketplace'><button className='btn-ghost' style={{padding:'12px 24px',fontSize:10}}>Keep Shopping</button></Link>");
lines.push("        </div>");
lines.push("      </div>");
lines.push("      <footer className='v-footer'><div style={{opacity:0.5,fontFamily:\"'Cormorant',serif\",fontSize:15,fontWeight:300,letterSpacing:'0.22em',textTransform:'uppercase',color:'var(--w85)'}}>Vendra</div><div className='v-footer-copy'>ERC-8183 Escrow · Arc Testnet</div><div className='v-footer-links'><Link href='/marketplace'>Marketplace</Link></div></footer>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/orders/[id]/page.tsx', lines.join('\n'), 'utf8');
console.log('Orders done:', fs.existsSync('app/orders/[id]/page.tsx'));
