const fs = require('fs');

// ── 1. Send OTP API Route ─────────────────────────────────────────────────────
fs.mkdirSync('app/api/circle/send-otp', { recursive: true });
const sendOtp = [];
sendOtp.push("import { NextRequest, NextResponse } from 'next/server';");
sendOtp.push("import { Resend } from 'resend';");
sendOtp.push("");
sendOtp.push("const resend = new Resend(process.env.RESEND_API_KEY);");
sendOtp.push("");
sendOtp.push("// Store OTPs in memory (resets on server restart — fine for testnet)");
sendOtp.push("const otpStore = new Map<string, { otp: string; expires: number }>();");
sendOtp.push("");
sendOtp.push("export async function POST(req: NextRequest) {");
sendOtp.push("  try {");
sendOtp.push("    const { email } = await req.json();");
sendOtp.push("    if (!email) return NextResponse.json({ error: 'Email required' }, { status: 400 });");
sendOtp.push("");
sendOtp.push("    // Generate 6-digit OTP");
sendOtp.push("    const otp = Math.floor(100000 + Math.random() * 900000).toString();");
sendOtp.push("    const expires = Date.now() + 10 * 60 * 1000; // 10 minutes");
sendOtp.push("    otpStore.set(email.toLowerCase(), { otp, expires });");
sendOtp.push("");
sendOtp.push("    // Send email via Resend");
sendOtp.push("    await resend.emails.send({");
sendOtp.push("      from: 'Vendra <onboarding@resend.dev>',");
sendOtp.push("      to: email,");
sendOtp.push("      subject: 'Your Vendra Login Code',");
sendOtp.push("      html: `");
sendOtp.push("        <div style='font-family:Georgia,serif;max-width:480px;margin:0 auto;background:#0C0E1A;color:#fff8eb;padding:40px;'>");
sendOtp.push("          <div style='font-size:24px;font-weight:300;letter-spacing:0.22em;text-transform:uppercase;margin-bottom:8px;'>Vendra</div>");
sendOtp.push("          <div style='height:1px;background:linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent);margin-bottom:32px;'></div>");
sendOtp.push("          <div style='font-size:14px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.55);margin-bottom:24px;line-height:1.7;'>Your one-time login code for Vendra. This code expires in 10 minutes.</div>");
sendOtp.push("          <div style='background:rgba(212,176,90,0.08);border:1px solid rgba(212,176,90,0.3);padding:24px;text-align:center;margin-bottom:24px;'>");
sendOtp.push("            <div style='font-size:11px;font-weight:300;font-style:italic;letter-spacing:0.18em;text-transform:uppercase;color:rgba(255,248,235,0.42);margin-bottom:8px;'>Your Login Code</div>");
sendOtp.push("            <div style='font-size:48px;font-weight:300;letter-spacing:0.2em;color:#EAC96E;'>${otp}</div>");
sendOtp.push("          </div>");
sendOtp.push("          <div style='font-size:11px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.35);line-height:1.7;'>If you didn't request this code, you can safely ignore this email. Never share this code with anyone.</div>");
sendOtp.push("          <div style='height:1px;background:rgba(255,255,255,0.06);margin:24px 0;'></div>");
sendOtp.push("          <div style='font-size:10px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.25);'>Vendra · Built on Arc Testnet · Powered by USDC</div>");
sendOtp.push("        </div>`");
sendOtp.push("    });");
sendOtp.push("");
sendOtp.push("    return NextResponse.json({ success: true });");
sendOtp.push("  } catch (e: any) {");
sendOtp.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
sendOtp.push("  }");
sendOtp.push("}");
sendOtp.push("");
sendOtp.push("// Export for use in verify route");
sendOtp.push("export { otpStore };");
fs.writeFileSync('app/api/circle/send-otp/route.ts', sendOtp.join('\n'), 'utf8');
console.log('send-otp route done');

// ── 2. Verify OTP API Route ───────────────────────────────────────────────────
fs.mkdirSync('app/api/circle/verify-otp', { recursive: true });
const verifyOtp = [];
verifyOtp.push("import { NextRequest, NextResponse } from 'next/server';");
verifyOtp.push("");
verifyOtp.push("// In-memory OTP store (shared via module cache)");
verifyOtp.push("const otpStore = new Map<string, { otp: string; expires: number }>();");
verifyOtp.push("");
verifyOtp.push("// Make store accessible globally on this server instance");
verifyOtp.push("declare global { var vendraOtpStore: Map<string, { otp: string; expires: number }> }");
verifyOtp.push("if (!global.vendraOtpStore) global.vendraOtpStore = new Map();");
verifyOtp.push("");
verifyOtp.push("export async function POST(req: NextRequest) {");
verifyOtp.push("  try {");
verifyOtp.push("    const { email, otp } = await req.json();");
verifyOtp.push("    if (!email || !otp) return NextResponse.json({ error: 'Email and OTP required' }, { status: 400 });");
verifyOtp.push("    const key = email.toLowerCase();");
verifyOtp.push("    const stored = global.vendraOtpStore.get(key);");
verifyOtp.push("    if (!stored) return NextResponse.json({ error: 'No OTP found. Please request a new code.' }, { status: 400 });");
verifyOtp.push("    if (Date.now() > stored.expires) {");
verifyOtp.push("      global.vendraOtpStore.delete(key);");
verifyOtp.push("      return NextResponse.json({ error: 'Code expired. Please request a new one.' }, { status: 400 });");
verifyOtp.push("    }");
verifyOtp.push("    if (stored.otp !== otp.trim()) return NextResponse.json({ error: 'Incorrect code. Please try again.' }, { status: 400 });");
verifyOtp.push("    global.vendraOtpStore.delete(key);");
verifyOtp.push("    return NextResponse.json({ success: true, verified: true });");
verifyOtp.push("  } catch (e: any) {");
verifyOtp.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
verifyOtp.push("  }");
verifyOtp.push("}");
fs.writeFileSync('app/api/circle/verify-otp/route.ts', verifyOtp.join('\n'), 'utf8');
console.log('verify-otp route done');

// ── 3. Update send-otp to use global store ───────────────────────────────────
const sendOtpFixed = [];
sendOtpFixed.push("import { NextRequest, NextResponse } from 'next/server';");
sendOtpFixed.push("import { Resend } from 'resend';");
sendOtpFixed.push("");
sendOtpFixed.push("const resend = new Resend(process.env.RESEND_API_KEY);");
sendOtpFixed.push("declare global { var vendraOtpStore: Map<string, { otp: string; expires: number }> }");
sendOtpFixed.push("if (!global.vendraOtpStore) global.vendraOtpStore = new Map();");
sendOtpFixed.push("");
sendOtpFixed.push("export async function POST(req: NextRequest) {");
sendOtpFixed.push("  try {");
sendOtpFixed.push("    const { email } = await req.json();");
sendOtpFixed.push("    if (!email) return NextResponse.json({ error: 'Email required' }, { status: 400 });");
sendOtpFixed.push("    const otp = Math.floor(100000 + Math.random() * 900000).toString();");
sendOtpFixed.push("    const expires = Date.now() + 10 * 60 * 1000;");
sendOtpFixed.push("    global.vendraOtpStore.set(email.toLowerCase(), { otp, expires });");
sendOtpFixed.push("    await resend.emails.send({");
sendOtpFixed.push("      from: 'Vendra <onboarding@resend.dev>',");
sendOtpFixed.push("      to: email,");
sendOtpFixed.push("      subject: 'Your Vendra Login Code — ' + otp,");
sendOtpFixed.push("      html: `<div style='font-family:Georgia,serif;max-width:480px;margin:0 auto;background:#0C0E1A;color:#fff8eb;padding:40px;'><div style='font-size:24px;font-weight:300;letter-spacing:0.22em;text-transform:uppercase;margin-bottom:8px;'>Vendra</div><div style='height:1px;background:linear-gradient(90deg,transparent,rgba(212,176,90,0.4),transparent);margin-bottom:32px;'></div><div style='font-size:14px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.55);margin-bottom:24px;line-height:1.7;'>Your one-time login code for Vendra. Expires in 10 minutes.</div><div style='background:rgba(212,176,90,0.08);border:1px solid rgba(212,176,90,0.3);padding:24px;text-align:center;margin-bottom:24px;'><div style='font-size:11px;font-weight:300;font-style:italic;letter-spacing:0.18em;text-transform:uppercase;color:rgba(255,248,235,0.42);margin-bottom:8px;'>Your Login Code</div><div style='font-size:48px;font-weight:300;letter-spacing:0.2em;color:#EAC96E;'>${otp}</div></div><div style='font-size:11px;font-weight:300;font-style:italic;color:rgba(255,248,235,0.35);line-height:1.7;'>If you didn't request this, ignore this email. Never share this code.</div><div style='height:1px;background:rgba(255,255,255,0.06);margin:24px 0;'></div><div style='font-size:10px;color:rgba(255,248,235,0.25);'>Vendra · Arc Testnet · USDC</div></div>`");
sendOtpFixed.push("    });");
sendOtpFixed.push("    return NextResponse.json({ success: true });");
sendOtpFixed.push("  } catch (e: any) {");
sendOtpFixed.push("    return NextResponse.json({ error: e.message }, { status: 500 });");
sendOtpFixed.push("  }");
sendOtpFixed.push("}");
fs.writeFileSync('app/api/circle/send-otp/route.ts', sendOtpFixed.join('\n'), 'utf8');
console.log('send-otp fixed with global store');

console.log('\nAll OTP routes done!');
