const fs = require('fs');
fs.mkdirSync('app/store/create', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../../Nav';");
lines.push("import { useState, useRef } from 'react';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import { saveStore, getStoreByWallet, uploadImage } from '../../lib/supabase';");
lines.push("import { useSendTransaction } from 'wagmi';");
lines.push("import { parseUnits } from 'viem';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("const CATS = [{icon:'👗',name:'Fashion'},{icon:'💾',name:'Digital'},{icon:'🎨',name:'Art'},{icon:'🛠',name:'Services'},{icon:'🍱',name:'Food'},{icon:'📱',name:'Tech'},{icon:'🎵',name:'Music'},{icon:'✨',name:'Other'}];");
lines.push("const FEE = 0.5;");
lines.push("const FEE_WALLET = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8' as `0x${string}`;");
lines.push("");
lines.push("export default function CreateStore() {");
lines.push("  const { address, isConnected } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const { sendTransactionAsync } = useSendTransaction();");
lines.push("  const bannerRef = useRef<HTMLInputElement>(null);");
lines.push("  const [cat, setCat] = useState('Fashion');");
lines.push("  const [form, setForm] = useState({ name:'', tagline:'', description:'', xHandle:'' });");
lines.push("  const [bannerFile, setBannerFile] = useState<File|null>(null);");
lines.push("  const [bannerPreview, setBannerPreview] = useState('');");
lines.push("  const [step, setStep] = useState<'form'|'paying'|'success'>('form');");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [deployedStore, setDeployedStore] = useState<any>(null);");
lines.push("  const [loading, setLoading] = useState(false);");
lines.push("");
lines.push("  const slug = (form.name.toLowerCase().replace(/\\s+/g,'-').replace(/[^a-z0-9-]/g,''))+(address?'-'+address.slice(2,6):'');");
lines.push("  const storeUrl = 'https://vendra-app-omega.vercel.app/store/'+slug;");
lines.push("  const tweet = 'I just deployed my store \"'+form.name+'\" on Arc Testnet!\\n\\n'+storeUrl+'\\n\\n#ArcTestnet #Web3 #Vendra';");
lines.push("");
lines.push("  const handleBanner = (e: React.ChangeEvent<HTMLInputElement>) => {");
lines.push("    const f = e.target.files?.[0]; if (!f) return;");
lines.push("    setBannerFile(f); setBannerPreview(URL.createObjectURL(f));");
lines.push("  };");
lines.push("");
lines.push("  const handleCreate = async () => {");
lines.push("    if (!address || !isConnected) { setError('Please connect your wallet'); return; }");
lines.push("    if (!form.name) { setError('Store name is required'); return; }");
lines.push("    setLoading(true); setError('');");
lines.push("    try {");
lines.push("      const existing = await getStoreByWallet(address);");
lines.push("      if (existing) { setError('You already have a store. Delete it first.'); setLoading(false); return; }");
lines.push("      setStep('paying');");
lines.push("      const hash = await sendTransactionAsync({ to: FEE_WALLET, value: parseUnits(FEE.toString(), 18) });");
lines.push("      let bannerUrl = '';");
lines.push("      if (bannerFile && address) bannerUrl = await uploadImage('banners/'+address, bannerFile);");
lines.push("      const store = await saveStore({ owner_wallet:address, name:form.name, tagline:form.tagline, description:form.description, category:cat, slug, x_handle:form.xHandle, deploy_fee_tx:hash, banner_url:bannerUrl });");
lines.push("      setDeployedStore(store); setStep('success');");
lines.push("    } catch(e:any) {");
lines.push("      setStep('form');");
lines.push("      setError(e?.message?.includes('rejected')?'Transaction rejected.':'Something went wrong. Please try again.');");
lines.push("    } finally { setLoading(false); }");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{maxWidth:640,margin:'0 auto',padding:'120px 56px 80px'}}>");
lines.push("");
lines.push("        {step==='paying'&&(");
lines.push("          <div style={{textAlign:'center',padding:'4rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,color:'var(--w)',marginBottom:16}}>Deploying Store</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:32}}>Approve the {'$'}{FEE}{' USDC deployment fee in your wallet'}</div>");
lines.push("            <div className='v-spinner' style={{margin:'0 auto'}}/>");
lines.push("          </div>)}");
lines.push("");
lines.push("        {step==='success'&&(");
lines.push("          <div style={{textAlign:'center',padding:'3rem 0'}}>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'5rem',fontWeight:300,color:'var(--a2)',lineHeight:1,marginBottom:16}}>✓</div>");
lines.push("            <div style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,color:'var(--w)',marginBottom:12}}>Store Deployed</div>");
lines.push("            <div style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:36,lineHeight:1.7}}><strong style={{color:'var(--w)'}}>{form.name}</strong>{' is now live on Arc Testnet'}</div>");
lines.push("            <div style={{display:'flex',flexDirection:'column',gap:12,maxWidth:280,margin:'0 auto'}}>");
lines.push("              <a href={'https://twitter.com/intent/tweet?text='+encodeURIComponent(tweet)} target='_blank' rel='noopener noreferrer'><button className='btn-ghost' style={{width:'100%',padding:'14px'}}>Share on 𝕏</button></a>");
lines.push("              <Link href={'/store/'+(deployedStore?.slug||slug)}><button className='btn-primary' style={{width:'100%',padding:'14px'}}>View My Store →</button></Link>");
lines.push("              <Link href='/store/edit'><button className='btn-amber-ghost' style={{width:'100%',padding:'14px'}}>Add Products →</button></Link>");
lines.push("            </div>");
lines.push("          </div>)}");
lines.push("");
lines.push("        {step==='form'&&(");
lines.push("          <>");
lines.push("            <div className='v-eyebrow' style={{marginBottom:24}}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Arc Testnet</span></div>");
lines.push("            <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(40px,6vw,72px)',fontWeight:300,letterSpacing:'-0.01em',lineHeight:0.94,color:'var(--w)',marginBottom:12}}>Launch Your<br/><em style={{fontStyle:'italic',background:'linear-gradient(120deg,var(--a),var(--a2))',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text'}}>Store</em></h1>");
lines.push("            <p style={{fontSize:13,fontWeight:300,fontStyle:'italic',color:'var(--w35)',marginBottom:8,lineHeight:1.7}}>Set up in 2 minutes. Sell globally, get paid instantly.</p>");
lines.push("            <div style={{display:'inline-flex',alignItems:'center',gap:8,border:'1px solid rgba(212,176,90,0.2)',padding:'8px 16px',marginBottom:40}}>");
lines.push("              <div className='v-arc-badge-dot'/>");
lines.push("              <span style={{fontSize:10,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--a)'}}>{'Deployment fee: $'}{FEE}{' USDC · Arc Testnet'}</span>");
lines.push("            </div>");
lines.push("            {/* Banner */}");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:28,overflow:'hidden'}}>");
lines.push("              <div className='v-block-head'>Store Banner</div>");
lines.push("              <div style={{padding:20}}>");
lines.push("                <input ref={bannerRef} type='file' accept='image/*' onChange={handleBanner} style={{display:'none'}}/>"); 
lines.push("                {bannerPreview");
lines.push("                  ? <div style={{position:'relative'}}><img src={bannerPreview} alt='banner' style={{width:'100%',height:160,objectFit:'cover',display:'block',filter:'brightness(0.7)'}}/><button onClick={()=>bannerRef.current?.click()} style={{position:'absolute',bottom:12,right:12,fontFamily:\"'DM Sans',sans-serif\",fontSize:9,fontWeight:300,letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--w35)',border:'1px solid var(--b2)',padding:'6px 12px',background:'rgba(12,14,26,0.85)',cursor:'pointer'}}>Change</button></div>");
lines.push("                  : <div onClick={()=>bannerRef.current?.click()} className='v-upload-zone' style={{height:140}}><div style={{fontSize:'2rem'}}>{'🖼️'}</div><div className='v-upload-label'>Click to upload banner</div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em'}}>Recommended: 1200×400px</div></div>}");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {/* Identity */}");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:28}}>");
lines.push("              <div className='v-block-head'>Store Identity</div>");
lines.push("              <div style={{padding:20}}>");
lines.push("                <div className='v-field'><label className='v-label'>Store name *</label><input className='v-input' type='text' placeholder='e.g. Nour Atelier' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div>");
lines.push("                <div className='v-field'><label className='v-label'>Tagline</label><input className='v-input' type='text' placeholder='One line about what you sell' value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></div>");
lines.push("                <div className='v-field'><label className='v-label'>Description</label><textarea className='v-textarea' placeholder='Tell buyers what makes your store special...' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>");
lines.push("                <div className='v-field' style={{marginBottom:0}}><label className='v-label'>X (Twitter) handle</label><input className='v-input' type='text' placeholder='@yourhandle' value={form.xHandle} onChange={e=>setForm({...form,xHandle:e.target.value})}/></div>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {/* Category */}");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:28}}>");
lines.push("              <div className='v-block-head'>Category</div>");
lines.push("              <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'1px',background:'var(--b1)'}}>");
lines.push("                {CATS.map(c=><div key={c.name} onClick={()=>setCat(c.name)} style={{padding:'16px 8px',textAlign:'center',cursor:'pointer',background:cat===c.name?'rgba(212,176,90,0.12)':'var(--bg2)',borderBottom:cat===c.name?'1px solid var(--a)':'1px solid transparent',transition:'all 0.2s'}}><div style={{fontSize:'1.2rem',marginBottom:6}}>{c.icon}</div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.12em',textTransform:'uppercase',color:cat===c.name?'var(--a)':'var(--w18)'}}>{c.name}</div></div>)}");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {/* Wallet */}");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:28}}>");
lines.push("              <div className='v-block-head'>Payment Wallet · ERC-8004 Identity</div>");
lines.push("              <div style={{padding:'16px 20px'}}>");
lines.push("                <div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.18em',textTransform:'uppercase',color:'var(--w18)',marginBottom:6}}>Receives USDC payments from buyers</div>");
lines.push("                <div style={{fontFamily:\"'Cormorant',serif\",fontSize:16,fontWeight:300,color:'var(--a2)'}}>{address?address.slice(0,6)+'...'+address.slice(-4)+' · Arc Testnet':'Connect your wallet'}</div>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {error&&<div style={{border:'1px solid rgba(232,112,112,0.3)',background:'rgba(232,112,112,0.08)',padding:'12px 16px',fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--err)',marginBottom:20}}>{error}</div>}");
lines.push("            <button onClick={handleCreate} disabled={loading} className='btn-primary' style={{width:'100%',padding:'18px',fontSize:12}}>{'Deploy Store on Arc · $'}{FEE}{' USDC →'}</button>");
lines.push("            <div style={{textAlign:'center',marginTop:16}}><Link href='/profile' style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',textDecoration:'none'}}>← Back to Profile</Link></div>");
lines.push("          </>");
lines.push("        )}");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/store/create/page.tsx', lines.join('\n'), 'utf8');
console.log('Store create done:', fs.existsSync('app/store/create/page.tsx'));
