const fs = require('fs');
fs.mkdirSync('app/store/edit', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../../Nav';");
lines.push("import { useState, useEffect, useRef, Suspense } from 'react';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useRouter, useSearchParams } from 'next/navigation';");
lines.push("import { getStoreByWallet, updateStore, saveProduct, deleteProduct, uploadImage } from '../../lib/supabase';");
lines.push("import Link from 'next/link';");
lines.push("");
lines.push("const CATS = [{icon:'👗',name:'Fashion'},{icon:'💾',name:'Digital'},{icon:'🎨',name:'Art'},{icon:'🛠',name:'Services'},{icon:'🍱',name:'Food'},{icon:'📱',name:'Tech'},{icon:'🎵',name:'Music'},{icon:'✨',name:'Other'}];");
lines.push("const TYPES = ['Physical','Digital','Service'];");
lines.push("");
lines.push("function EditStoreContent() {");
lines.push("  const { address } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  const searchParams = useSearchParams();");
lines.push("  const bannerRef = useRef<HTMLInputElement>(null);");
lines.push("  const imgRef = useRef<HTMLInputElement>(null);");
lines.push("  const [store, setStore] = useState<any>(null);");
lines.push("  const [loading, setLoading] = useState(true);");
lines.push("  const [saving, setSaving] = useState(false);");
lines.push("  const [error, setError] = useState('');");
lines.push("  const [success, setSuccess] = useState('');");
lines.push("  const [tab, setTab] = useState<'details'|'products'>('details');");
lines.push("  const [form, setForm] = useState({ name:'', tagline:'', description:'', xHandle:'', category:'Fashion' });");
lines.push("  const [bannerFile, setBannerFile] = useState<File|null>(null);");
lines.push("  const [bannerPreview, setBannerPreview] = useState('');");
lines.push("  const [newProd, setNewProd] = useState({ name:'', description:'', price:'', type:'Physical' });");
lines.push("  const [prodFile, setProdFile] = useState<File|null>(null);");
lines.push("  const [prodPreview, setProdPreview] = useState('');");
lines.push("  const [adding, setAdding] = useState(false);");
lines.push("  const [deletingId, setDeletingId] = useState('');");
lines.push("  const [showAdd, setShowAdd] = useState(false);");
lines.push("");
lines.push("  useEffect(() => { if (searchParams.get('tab')==='products') setTab('products'); }, [searchParams]);");
lines.push("  useEffect(() => {");
lines.push("    if (!address) return;");
lines.push("    getStoreByWallet(address).then(s => {");
lines.push("      if (!s) { router.push('/store/create'); return; }");
lines.push("      setStore(s);");
lines.push("      setForm({ name:s.name||'', tagline:s.tagline||'', description:s.description||'', xHandle:s.x_handle||'', category:s.category||'Fashion' });");
lines.push("      setBannerPreview(s.banner_url||'');");
lines.push("      setLoading(false);");
lines.push("    });");
lines.push("  }, [address, router]);");
lines.push("");
lines.push("  const handleSave = async () => {");
lines.push("    if (!form.name) { setError('Store name required'); return; }");
lines.push("    setSaving(true); setError(''); setSuccess('');");
lines.push("    try {");
lines.push("      let bannerUrl = store.banner_url||'';");
lines.push("      if (bannerFile && address) bannerUrl = await uploadImage('banners/'+address, bannerFile);");
lines.push("      await updateStore(store.id, { name:form.name, tagline:form.tagline, description:form.description, category:form.category, x_handle:form.xHandle, banner_url:bannerUrl });");
lines.push("      setSuccess('Store updated!'); setTimeout(()=>setSuccess(''),2500);");
lines.push("    } catch { setError('Something went wrong.'); } finally { setSaving(false); }");
lines.push("  };");
lines.push("");
lines.push("  const handleAddProduct = async () => {");
lines.push("    if (!newProd.name||!newProd.price) { setError('Name and price required'); return; }");
lines.push("    setAdding(true); setError('');");
lines.push("    try {");
lines.push("      let imageUrl = '';");
lines.push("      if (prodFile && address) imageUrl = await uploadImage('products/'+store.id+'/'+Date.now(), prodFile);");
lines.push("      const p = await saveProduct({ store_id:store.id, name:newProd.name, description:newProd.description, price:Number(newProd.price), type:newProd.type, image_url:imageUrl });");
lines.push("      setStore({...store, products:[...(store.products||[]),p]});");
lines.push("      setNewProd({name:'',description:'',price:'',type:'Physical'}); setProdFile(null); setProdPreview(''); setShowAdd(false);");
lines.push("    } catch { setError('Failed to add product.'); } finally { setAdding(false); }");
lines.push("  };");
lines.push("");
lines.push("  const handleDeleteProduct = async (id: string) => {");
lines.push("    setDeletingId(id);");
lines.push("    try { await deleteProduct(id); setStore({...store,products:store.products.filter((p:any)=>p.id!==id)}); }");
lines.push("    catch { setError('Failed to delete.'); } finally { setDeletingId(''); }");
lines.push("  };");
lines.push("");
lines.push("  if (loading) return <main style={{minHeight:'100vh',background:'var(--bg)',display:'flex',alignItems:'center',justifyContent:'center'}}><Nav /><div className='v-spinner'/></main>;");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{minHeight:'100vh',background:'var(--bg)'}}>");
lines.push("      <Nav />");
lines.push("      <div style={{maxWidth:700,margin:'0 auto',padding:'120px 56px 80px'}}>");
lines.push("        <div className='v-eyebrow' style={{marginBottom:16}}><div className='v-eyebrow-rule'/><span className='v-eyebrow-label'>Manage Store</span></div>");
lines.push("        <h1 style={{fontFamily:\"'Cormorant',serif\",fontSize:'clamp(32px,5vw,52px)',fontWeight:300,letterSpacing:'-0.01em',lineHeight:0.94,color:'var(--w)',marginBottom:8}}>{store?.name}</h1>");
lines.push("        <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',marginBottom:28}}>{store?.products?.length||0}{' products · '}{store?.category}{' · Arc Testnet'}</div>");
lines.push("        <div style={{display:'flex',gap:10,marginBottom:32}}>");
lines.push("          <a href={'/store/'+store?.slug} target='_blank' rel='noopener noreferrer'><button className='btn-amber-ghost' style={{fontSize:10,padding:'8px 16px'}}>View Storefront ↗</button></a>");
lines.push("          <Link href='/profile'><button className='btn-ghost' style={{fontSize:10,padding:'8px 16px'}}>← Profile</button></Link>");
lines.push("        </div>");
lines.push("        {/* Tabs */}");
lines.push("        <div style={{display:'flex',borderBottom:'1px solid var(--b1)',marginBottom:32}}>");
lines.push("          <button onClick={()=>setTab('details')} style={{fontFamily:\"'DM Sans',sans-serif\",fontSize:10,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',padding:'12px 24px',background:'transparent',border:'none',borderBottom:tab==='details'?'1px solid var(--a)':'1px solid transparent',color:tab==='details'?'var(--a)':'var(--w18)',cursor:'pointer',transition:'all 0.2s'}}>Store Details</button>");
lines.push("          <button onClick={()=>setTab('products')} style={{fontFamily:\"'DM Sans',sans-serif\",fontSize:10,fontWeight:300,fontStyle:'italic',letterSpacing:'0.14em',textTransform:'uppercase',padding:'12px 24px',background:'transparent',border:'none',borderBottom:tab==='products'?'1px solid var(--a)':'1px solid transparent',color:tab==='products'?'var(--a)':'var(--w18)',cursor:'pointer',transition:'all 0.2s'}}>{'Products ('}{store?.products?.length||0}{')'}</button>");
lines.push("        </div>");
lines.push("        {/* DETAILS */}");
lines.push("        {tab==='details'&&(");
lines.push("          <>");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:24}}>");
lines.push("              <div className='v-block-head'>Store Banner</div>");
lines.push("              <div style={{padding:20}}>");
lines.push("                <input ref={bannerRef} type='file' accept='image/*' onChange={e=>{const f=e.target.files?.[0];if(!f)return;setBannerFile(f);setBannerPreview(URL.createObjectURL(f));}} style={{display:'none'}}/>");
lines.push("                {bannerPreview");
lines.push("                  ?<div style={{position:'relative'}}><img src={bannerPreview} alt='banner' style={{width:'100%',height:140,objectFit:'cover',display:'block',filter:'brightness(0.65)'}}/><button onClick={()=>bannerRef.current?.click()} style={{position:'absolute',bottom:10,right:10,fontFamily:\"'DM Sans',sans-serif\",fontSize:9,fontWeight:300,letterSpacing:'0.12em',textTransform:'uppercase',color:'var(--w35)',border:'1px solid var(--b2)',padding:'5px 10px',background:'rgba(12,14,26,0.85)',cursor:'pointer'}}>Change</button></div>");
lines.push("                  :<div onClick={()=>bannerRef.current?.click()} className='v-upload-zone' style={{height:120}}><div style={{fontSize:'1.8rem'}}>{'🖼️'}</div><div className='v-upload-label'>Click to upload banner</div></div>}");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:24}}>");
lines.push("              <div className='v-block-head'>Store Info</div>");
lines.push("              <div style={{padding:20}}>");
lines.push("                <div className='v-field'><label className='v-label'>Store name *</label><input className='v-input' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div>");
lines.push("                <div className='v-field'><label className='v-label'>Tagline</label><input className='v-input' placeholder='One line about what you sell' value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></div>");
lines.push("                <div className='v-field'><label className='v-label'>Description</label><textarea className='v-textarea' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>");
lines.push("                <div className='v-field' style={{marginBottom:0}}><label className='v-label'>X (Twitter) handle</label><input className='v-input' placeholder='@yourhandle' value={form.xHandle} onChange={e=>setForm({...form,xHandle:e.target.value})}/></div>");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            <div style={{border:'1px solid var(--b1)',marginBottom:24}}>");
lines.push("              <div className='v-block-head'>Category</div>");
lines.push("              <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'1px',background:'var(--b1)'}}>");
lines.push("                {CATS.map(c=><div key={c.name} onClick={()=>setForm({...form,category:c.name})} style={{padding:'14px 8px',textAlign:'center',cursor:'pointer',background:form.category===c.name?'rgba(212,176,90,0.10)':'var(--bg2)',borderBottom:form.category===c.name?'1px solid var(--a)':'1px solid transparent',transition:'all 0.2s'}}><div style={{fontSize:'1.1rem',marginBottom:4}}>{c.icon}</div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',letterSpacing:'0.10em',textTransform:'uppercase',color:form.category===c.name?'var(--a)':'var(--w18)'}}>{c.name}</div></div>)}");
lines.push("              </div>");
lines.push("            </div>");
lines.push("            {error&&<div style={{border:'1px solid rgba(232,112,112,0.3)',background:'rgba(232,112,112,0.08)',padding:'10px 16px',fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--err)',marginBottom:16}}>{error}</div>}");
lines.push("            {success&&<div style={{border:'1px solid rgba(143,196,152,0.3)',background:'rgba(143,196,152,0.08)',padding:'10px 16px',fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--gr)',marginBottom:16}}>{success}</div>}");
lines.push("            <button onClick={handleSave} disabled={saving} className='btn-primary' style={{width:'100%',padding:'16px',fontSize:11}}>{saving?'Saving...':'Save Changes →'}</button>");
lines.push("          </>");
lines.push("        )}");
lines.push("        {/* PRODUCTS */}");
lines.push("        {tab==='products'&&(");
lines.push("          <>");
lines.push("            <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:20}}>");
lines.push("              <div style={{fontSize:10,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',textTransform:'uppercase'}}>{store?.products?.length||0}{' products listed'}</div>");
lines.push("              <button onClick={()=>{setShowAdd(!showAdd);setError('');}} className={showAdd?'btn-ghost':'btn-amber-ghost'} style={{fontSize:10,padding:'8px 16px'}}>{showAdd?'Cancel':'+ Add Product'}</button>");
lines.push("            </div>");
lines.push("            {showAdd&&(");
lines.push("              <div style={{border:'1px solid rgba(212,176,90,0.25)',marginBottom:20,background:'rgba(212,176,90,0.03)'}}>");
lines.push("                <div className='v-block-head' style={{color:'var(--a)'}}>New Product</div>");
lines.push("                <div style={{padding:20}}>");
lines.push("                  <div className='v-field'><label className='v-label'>Product Image</label>");
lines.push("                    <input ref={imgRef} type='file' accept='image/*' onChange={e=>{const f=e.target.files?.[0];if(!f)return;setProdFile(f);setProdPreview(URL.createObjectURL(f));}} style={{display:'none'}}/>");
lines.push("                    {prodPreview");
lines.push("                      ?<div style={{position:'relative',display:'inline-block'}}><img src={prodPreview} alt='product' style={{width:100,height:100,objectFit:'cover',border:'1px solid var(--b1)',display:'block'}}/><button onClick={()=>imgRef.current?.click()} style={{position:'absolute',bottom:4,right:4,fontFamily:\"'DM Sans',sans-serif\",fontSize:8,color:'var(--w35)',border:'1px solid var(--b2)',padding:'3px 8px',background:'rgba(12,14,26,0.85)',cursor:'pointer'}}>Change</button></div>");
lines.push("                      :<div onClick={()=>imgRef.current?.click()} style={{width:100,height:100,border:'1px dashed var(--b2)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',cursor:'pointer',gap:4}} onMouseEnter={e=>(e.currentTarget.style.borderColor='var(--a)')} onMouseLeave={e=>(e.currentTarget.style.borderColor='var(--b2)')}><div style={{fontSize:'1.5rem'}}>{'📷'}</div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.08em'}}>Add photo</div></div>}");
lines.push("                  </div>");
lines.push("                  <div className='v-field'><label className='v-label'>Product name *</label><input className='v-input' placeholder='e.g. Gold Ring' value={newProd.name} onChange={e=>setNewProd({...newProd,name:e.target.value})}/></div>");
lines.push("                  <div className='v-field'><label className='v-label'>Description</label><input className='v-input' placeholder='What is this product?' value={newProd.description} onChange={e=>setNewProd({...newProd,description:e.target.value})}/></div>");
lines.push("                  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:20}}>");
lines.push("                    <div><label className='v-label'>Price (USDC) *</label><input className='v-input' type='number' placeholder='e.g. 25' value={newProd.price} onChange={e=>setNewProd({...newProd,price:e.target.value})}/></div>");
lines.push("                    <div><label className='v-label'>Type</label><select className='v-input' value={newProd.type} onChange={e=>setNewProd({...newProd,type:e.target.value})} style={{cursor:'pointer'}}>{TYPES.map(t=><option key={t} value={t} style={{background:'var(--bg2)'}}>{t}</option>)}</select></div>");
lines.push("                  </div>");
lines.push("                  {error&&<div style={{fontSize:11,fontWeight:300,fontStyle:'italic',color:'var(--err)',marginBottom:12}}>{error}</div>}");
lines.push("                  <button onClick={handleAddProduct} disabled={adding} className='btn-primary' style={{width:'100%',padding:'14px',fontSize:11}}>{adding?'Adding...':'Add Product →'}</button>");
lines.push("                </div>");
lines.push("              </div>)}");
lines.push("            <div style={{border:'1px solid var(--b1)'}}>");
lines.push("              {!store?.products?.length");
lines.push("                ?<div style={{padding:'32px',textAlign:'center',fontSize:12,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em'}}>No products yet — add your first one above</div>");
lines.push("                :store.products.map((p:any)=>(");
lines.push("                  <div key={p.id} style={{display:'flex',alignItems:'center',gap:16,padding:'16px 20px',borderBottom:'1px solid var(--b1)'}}>");
lines.push("                    {p.image_url?<img src={p.image_url} alt={p.name} style={{width:48,height:48,objectFit:'cover',flexShrink:0,border:'1px solid var(--b1)'}}/>:<div style={{width:48,height:48,background:'var(--s1)',border:'1px solid var(--b1)',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,fontSize:'1.4rem'}}>{'📦'}</div>}");
lines.push("                    <div style={{flex:1}}><div style={{fontFamily:\"'Cormorant',serif\",fontSize:16,fontWeight:300,color:'var(--w85)',marginBottom:2}}>{p.name}</div><div style={{fontSize:9,fontWeight:300,fontStyle:'italic',color:'var(--w18)',letterSpacing:'0.10em',textTransform:'uppercase'}}>{p.type}{' · $'}{p.price}{' USDC'}</div></div>");
lines.push("                    <button onClick={()=>handleDeleteProduct(p.id)} disabled={deletingId===p.id} className='btn-danger' style={{fontSize:9,padding:'6px 12px',flexShrink:0}}>{deletingId===p.id?'...':'Remove'}</button>");
lines.push("                  </div>))}");
lines.push("            </div>");
lines.push("          </>");
lines.push("        )}");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
lines.push("");
lines.push("export default function EditStore() {");
lines.push("  return <Suspense><EditStoreContent /></Suspense>;");
lines.push("}");
fs.writeFileSync('app/store/edit/page.tsx', lines.join('\n'), 'utf8');
console.log('Store edit done:', fs.existsSync('app/store/edit/page.tsx'));
