const fs = require('fs');
fs.mkdirSync('app/welcome', { recursive: true });
const lines = [];
lines.push("'use client';");
lines.push("import Nav from '../Nav';");
lines.push("import Link from 'next/link';");
lines.push("import { useAccount } from 'wagmi';");
lines.push("import { useRouter } from 'next/navigation';");
lines.push("import { useEffect } from 'react';");
lines.push("");
lines.push("export default function Welcome() {");
lines.push("  const { isConnected } = useAccount();");
lines.push("  const router = useRouter();");
lines.push("  useEffect(() => { if (!isConnected) router.push('/join'); }, [isConnected, router]);");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ minHeight:'100vh', background:'var(--bg)', position:'relative', overflow:'hidden', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center' }}>");
lines.push("      <Nav />");
lines.push("      {/* Ambient */}");
lines.push("      <div style={{ position:'absolute', inset:0, pointerEvents:'none' }}>");
lines.push("        <div style={{ position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-60%)', width:800, height:600, background:'radial-gradient(ellipse at center,rgba(212,176,90,0.08) 0%,transparent 70%)' }}/>");
lines.push("        <div style={{ position:'absolute', inset:0, backgroundImage:'linear-gradient(rgba(212,176,90,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(212,176,90,0.018) 1px,transparent 1px)', backgroundSize:'96px 96px' }}/>");
lines.push("        <div style={{ position:'absolute', top:0, left:'50%', transform:'translateX(-50%)', width:'60%', height:'2px', background:'linear-gradient(90deg,transparent,rgba(212,176,90,0.3),transparent)' }}/>");
lines.push("      </div>");
lines.push("");
lines.push("      <div style={{ position:'relative', zIndex:1, textAlign:'center', maxWidth:560, padding:'0 40px' }}>");
lines.push("        {/* Badge */}");
lines.push("        <div className='v-arc-badge' style={{ marginBottom:32, display:'inline-flex' }}>");
lines.push("          <div className='v-arc-badge-dot'/>");
lines.push("          <span className='v-arc-badge-text'>Welcome back · Arc Testnet</span>");
lines.push("        </div>");
lines.push("        {/* Heading */}");
lines.push("        <h1 style={{ fontFamily:\"'Cormorant',serif\", fontSize:'clamp(44px,8vw,88px)', fontWeight:300, lineHeight:0.90, letterSpacing:'-0.01em', color:'var(--w)', marginBottom:20 }}>");
lines.push("          What would you<br/>");
lines.push("          <em style={{ fontStyle:'italic', background:'linear-gradient(120deg,var(--a),var(--a2),var(--a3))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>like to do?</em>");
lines.push("        </h1>");
lines.push("        <p style={{ fontSize:14, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.8, marginBottom:48, maxWidth:400, margin:'0 auto 48px' }}>");
lines.push("          You have both a buyer and seller profile. Your storefront and order history are ready whenever you are.");
lines.push("        </p>");
lines.push("        {/* Options */}");
lines.push("        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'1px', background:'var(--b1)', maxWidth:480, margin:'0 auto 32px' }}>");
lines.push("          {/* Seller */}");
lines.push("          <Link href='/profile' style={{ textDecoration:'none' }}>");
lines.push("            <div style={{ background:'var(--bg2)', padding:'36px 24px', cursor:'pointer', transition:'all 0.3s', textAlign:'left' }} onMouseEnter={e=>{ e.currentTarget.style.background='rgba(212,176,90,0.06)'; e.currentTarget.style.borderBottom='1px solid var(--a)'; }} onMouseLeave={e=>{ e.currentTarget.style.background='var(--bg2)'; e.currentTarget.style.borderBottom='1px solid transparent'; }}>");
lines.push("              <div style={{ fontSize:'2rem', marginBottom:14 }}>🏪</div>");
lines.push("              <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:22, fontWeight:300, color:'var(--w)', marginBottom:8, lineHeight:1.2 }}>Manage my store</div>");
lines.push("              <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7 }}>Add products, view sales, edit your storefront or launch a new store on Arc Testnet.</div>");
lines.push("            </div>");
lines.push("          </Link>");
lines.push("          {/* Buyer */}");
lines.push("          <Link href='/marketplace' style={{ textDecoration:'none' }}>");
lines.push("            <div style={{ background:'var(--bg2)', padding:'36px 24px', cursor:'pointer', transition:'all 0.3s', textAlign:'left' }} onMouseEnter={e=>{ e.currentTarget.style.background='rgba(212,176,90,0.06)'; e.currentTarget.style.borderBottom='1px solid var(--a)'; }} onMouseLeave={e=>{ e.currentTarget.style.background='var(--bg2)'; e.currentTarget.style.borderBottom='1px solid transparent'; }}>");
lines.push("              <div style={{ fontSize:'2rem', marginBottom:14 }}>🛍️</div>");
lines.push("              <div style={{ fontFamily:\"'Cormorant',serif\", fontSize:22, fontWeight:300, color:'var(--w)', marginBottom:8, lineHeight:1.2 }}>Keep shopping</div>");
lines.push("              <div style={{ fontSize:12, fontWeight:300, fontStyle:'italic', color:'var(--w35)', lineHeight:1.7 }}>Browse stores, discover new products and pay instantly in USDC on Arc.</div>");
lines.push("            </div>");
lines.push("          </Link>");
lines.push("        </div>");
lines.push("        {/* Eyebrow divider */}");
lines.push("        <div className='v-cta-rule' style={{ marginBottom:20 }}>");
lines.push("          <div className='v-cta-rule-line'/>");
lines.push("          <div className='v-cta-rule-text'>or</div>");
lines.push("          <div className='v-cta-rule-line'/>");
lines.push("        </div>");
lines.push("        <Link href='/marketplace' style={{ fontSize:11, fontWeight:300, fontStyle:'italic', color:'var(--w18)', letterSpacing:'0.12em', textDecoration:'none', transition:'color 0.3s' }} onMouseEnter={e=>(e.currentTarget.style.color='var(--a)')} onMouseLeave={e=>(e.currentTarget.style.color='var(--w18)')}>Explore Marketplace →</Link>");
lines.push("      </div>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
fs.writeFileSync('app/welcome/page.tsx', lines.join('\n'), 'utf8');
console.log('Welcome v2 done:', fs.existsSync('app/welcome/page.tsx'));
